### ISSUE TITLE
Crash on first start

### ISSUE THREAD

**Issue by konsheng** [pl3xgaming/Purpur#1000]
### Timings link

\

### Expected behavior

\

### Observed/Actual behavior

\

### Steps/models to reproduce

\

### Purpur version

\

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

---- Minecraft Crash Report ----
// // DO NOT REPORT THIS TO PAPER! REPORT TO PURPUR INSTEAD!// Don't do that.

Time: 2022/6/11 下午8:03
Description: Exception in server tick loop

java.lang.IllegalStateException: Failed to initialize server
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1138)
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 182527336 bytes (174 MiB) / 364904448 bytes (348 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 950
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1402
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2514
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34530.03
	Virtual memory used (MB): 10433.53
	Swap memory total (MB): 18208.02
	Swap memory used (MB): 187.32
	JVM Flags: 1 total; -Xmx4G
	CraftBukkit Information: 
   Running: Purpur version git-Purpur-1647 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) true
   Plugins: {}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { RUNNABLE Server thread: [java.base@17.0.3/java.lang.Thread.dumpThreads(Native Method), java.base@17.0.3/java.lang.Thread.getAllStackTraces(Thread.java:1662), org.bukkit.craftbukkit.v1_19_R1.CraftCrashReport.get(CraftCrashReport.java:33), org.bukkit.craftbukkit.v1_19_R1.CraftCrashReport.get(CraftCrashReport.java:17), net.minecraft.SystemReport.a(SystemReport.java:61), net.minecraft.CrashReport.<init>(CrashReport.java:36), net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1297), net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1238), net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307), net.minecraft.server.MinecraftServer$$Lambda$4405/0x000000080152f480.run(Unknown Source), java.base@17.0.3/java.lang.Thread.run(Thread.java:833)], WAITING Paper Async Chunk Task Thread #0: [java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:97)], RUNNABLE Reference Handler: [java.base@17.0.3/java.lang.ref.Reference.waitForReferencePendingList(Native Method), java.base@17.0.3/java.lang.ref.Reference.processPendingReferences(Reference.java:253), java.base@17.0.3/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)], WAITING Worker-Main-1: [java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.3/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463), java.base@17.0.3/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434), java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.3/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.3/java.lang.Thread.run(Thread.java:833)], WAITING Paper Async Chunk Task Thread #2: [java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:97)], TIMED_WAITING Craft Scheduler Thread - 3: [java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.3/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.3/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.3/java.lang.Thread.run(Thread.java:833)], WAITING Finalizer: [java.base@17.0.3/java.lang.Object.wait(Native Method), java.base@17.0.3/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.3/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), java.base@17.0.3/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)], WAITING Worker-Main-4: [java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.3/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463), java.base@17.0.3/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434), java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.3/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.3/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Craft Scheduler Thread - 0: [java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.3/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.3/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.3/java.lang.Thread.run(Thread.java:833)], RUNNABLE Signal Dispatcher: [], TIMED_WAITING Timer hack thread: [java.base@17.0.3/java.lang.Thread.sleep(Native Method), net.minecraft.SystemUtils$7.run(SystemUtils.java:706)], WAITING Worker-Main-2: [java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.3/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463), java.base@17.0.3/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434), java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.3/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.3/java.lang.Thread.run(Thread.java:833)], RUNNABLE DestroyJavaVM: [], WAITING Worker-Main-3: [java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.3/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463), java.base@17.0.3/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434), java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.3/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.3/java.lang.Thread.run(Thread.java:833)], WAITING Paper Async Chunk Urgent Task Thread: [java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:97)], RUNNABLE WindowsStreamPump: [org.fusesource.jansi.internal.Kernel32.WaitForSingleObject(Native Method), org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.processConsoleInput(JansiWinSysTerminal.java:138), org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:460), org.jline.terminal.impl.AbstractWindowsTerminal$$Lambda$133/0x0000000800d85b90.run(Unknown Source), java.base@17.0.3/java.lang.Thread.run(Thread.java:833)], WAITING Log4j2-AsyncAppenderEventDispatcher-1-Async: [java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.3/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463), java.base@17.0.3/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434), java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.3/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:71), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:63)], WAITING Paper Async Chunk Task Thread #1: [java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:97)], TIMED_WAITING Craft Scheduler Thread - 1: [java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.3/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.3/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.3/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Common-Cleaner: [java.base@17.0.3/java.lang.Object.wait(Native Method), java.base@17.0.3/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.3/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140), java.base@17.0.3/java.lang.Thread.run(Thread.java:833), java.base@17.0.3/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)], RUNNABLE Server console handler: [com.mojang.brigadier.context.CommandContextBuilder.<init>(CommandContextBuilder.java:28), com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:348), io.papermc.paper.console.BrigadierCommandHighlighter.highlight(BrigadierCommandHighlighter.java:29), org.jline.reader.impl.LineReaderImpl.getHighlightedBuffer(LineReaderImpl.java:4040), org.jline.reader.impl.LineReaderImpl.getDisplayedBufferWithPrompts(LineReaderImpl.java:3979), org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3848), org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3784), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:640), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468), net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158), net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141), net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:107)], TIMED_WAITING Craft Scheduler Thread - 2: [java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.3/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.3/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.3/java.lang.Thread.run(Thread.java:833)], RUNNABLE Notification Thread: [], RUNNABLE Attach Listener: [], TIMED_WAITING Watchdog Thread: [java.base@17.0.3/java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:242)], TIMED_WAITING pool-4-thread-1: [java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672), java.base@17.0.3/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@17.0.3/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.3/java.lang.Thread.run(Thread.java:833)],}
   
   Force Loaded Chunks: {}
	Server Running: true
	Player Count: 0 / 200; []
	Data Packs: vanilla, file/bukkit (incompatible)
	World Generation: ERR
	Is Modded: Definitely; Server brand changed to 'Purpur'
	Type: Dedicated Server (map_server.txt)

**Comment by BillyGalbreath** [comment]
Required fields in the issue template are _not_ optional..
