### ISSUE TITLE
player join game error

### ISSUE THREAD

**Issue by konsheng** [pl3xgaming/Purpur#1001]
### Timings link

None

### Expected behavior

None

### Observed/Actual behavior

After the error is reported, the server may be shut down, or it may not be shut down

### Steps/models to reproduce

Start the server, join the game, then the following error will be generated, no plugin installed

bat script
`@echo off
title Server 1.19
"C:\Users\Konsheng\Desktop\Server\jdk-17.0.3+7\bin\java.exe" -Xmx4G -jar purpur-1.19-1647.jar -nogui
pause`

### Purpur version

> version
[21:21:26 INFO]: Checking version, please wait...
[21:21:27 INFO]: Current: git-Purpur-1647 (MC: 1.19)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

[crash-2022-06-11_21.18.50-server.txt](https://github.com/PurpurMC/Purpur/files/8883962/crash-2022-06-11_21.18.50-server.txt)
[latest.log](https://github.com/PurpurMC/Purpur/files/8883964/latest.log)
[2022-06-11-15.log.gz](https://github.com/PurpurMC/Purpur/files/8883965/2022-06-11-15.log.gz)

**Comment by BillyGalbreath** [comment]
Known Pufferfish issue. We'll get the fix merged from upstream as soon as they fix it.
