### ISSUE TITLE
Hopper Minecarts Inventory Disappears On Chunk Unload

### ISSUE THREAD

**Issue by TheFishNextDoor** [pl3xgaming/Purpur#1008]
### Timings link

https://timings.aikar.co/?id=5defaf76b68147269afda707ea390869

### Expected behavior

The items still be in the hopper minecart inventory

### Observed/Actual behavior

Hopper Minecarts Inventory Disappears On Chunk Unload

### Steps/models to reproduce

Put items in hopper minecart, teleport away, come back.

### Purpur version

Current: git-Purpur-1668 (MC: 1.19)*
Previous: git-Purpur-1628 (MC: 1.18.2)
You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I have not yet had a chance to test this in other forks to confirm this is a purpur issue. I just use purpur and know this is a bug that is happening to me.

**Comment by akdukaan** [comment]
I can reliably reproduce this issue on a server with no plugins. Happens to both minecart with hopper and minecart with chest. Does not occur when using paper.

Reproduction steps:
1. /tp 9 99 9999
2. place rail and minecart with chest on rail
3. /tp 9 99 9
4. wait 30 seconds to ensure that the chunk is unloaded
5. /tp 9 99 9999
6. open the chest minecart and observe that it is empty

**Comment by BillyGalbreath** [comment]
> I can reliably reproduce this issue on a server with no plugins. Happens to both minecart with hopper and minecart with chest. Does not occur when using paper.
> 
> Reproduction steps:
> 
> 1. /tp 9 99 9999
> 2. place rail and minecart with chest on rail
> 3. /tp 9 99 9
> 4. wait 30 seconds to ensure that the chunk is unloaded
> 5. /tp 9 99 9999
> 6. open the chest minecart and observe that it is empty

Are you able to replicate this in our upstream, Pufferfish?

**Comment by akdukaan** [comment]
> Are you able to replicate this in our upstream, Pufferfish?

Just tested it out now, and yes. I've let Kevin know about the issue and he said he'll take a look.

**Comment by kev626** [comment]
I can confirm this is a Pufferfish issue, I will push a fix likely in the next 30 minutes.

**Comment by kev626** [comment]
Issue was caused by a botched merge that was never detected from the 1.19 update.
