### ISSUE TITLE
paper.yml not being generated when start server jar

### ISSUE THREAD

**Issue by iapchi** [pl3xgaming/Purpur#1011]
### Timings link

N/A

### Expected behavior

all missing files are generated (pufferfish, purpur, spigot, paper, bukkit, server.properties)

### Observed/Actual behavior

Seems like everything but paper.yml is being generated (pufferfish, purpur, spigot, bukkit, server.properties)

### Steps/models to reproduce

Run fresh copy of server jar using jvm.

### Purpur version

Build 1671

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

[Screenshot of fresh run](https://i.imgur.com/B0wzaLy.png)

**Comment by encode42** [comment]
This is normal. Paper changed how their config is structured in 1.19, resulting in `paper.yml` being split into multiple other files, most of which are in the `config` directory. For more info, read [Paper's forum post](https://forums.papermc.io/threads/paper-1-19.344/).
