### ISSUE TITLE
Failed to parse level-type default, defaulting to minecraft:normal

### ISSUE THREAD

**Issue by candy999** [pl3xgaming/Purpur#1018]
### Timings link

n/a

### Stack trace

```
[11:48:54 INFO]: Preparing level "chaos"
[11:48:54 WARN]: Failed to parse level-type default, defaulting to minecraft:normal
```

### Actions to reproduce (if known)

Adding ::-XX:+UseCMoveUnconditionally to JAVA startup parameters will crash map generation

Remove ::-XX:+UseCMoveUnconditionally to fix map generation and this bug
https://github.com/PurpurMC/Purpur/issues/992

### Purpur version

1.18.1 is normal
1.18.2 A certain version starts

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other
Note all JAVA startup parameters
`"zulu18.30.11-ca-jdk18.0.1-win_x64\bin\java.exe" -server -XX:-TieredCompilation -XX:CompileThreshold=100 -Xmx20G -Xms20G -XX:MetaspaceSize=256M -XX:CompressedClassSpaceSize=512M -XX:ReservedCodeCacheSize=96M -XX:+UseZGC -Xnoclassgc -XX:MaxDirectMemorySize=96M -Dio.netty.noPreferDirect=false -Dio.netty.noUnsafe=false -Dio.netty.recycler.maxCapacity.default=0 -Dio.netty.recycler.maxCapacity=0 -Djdk.nio.maxCachedBufferSize=262144 -Dio.netty.allocator.type=pooled -Dio.netty.leakDetectionLevel=disabled -Dio.netty.buffer.bytebuf.checkAccessible=false -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:UseSSE=4 -XX:+UseSSE42Intrinsics -XX:UseAVX=2 -XX:+UseNUMA -XX:+AlwaysPreTouch -XX:-DontCompileHugeMethods -XX:+ExplicitGCInvokesConcurrent -XX:-UseGCOverheadLimit -XX:+UseAES -XX:+UseAESIntrinsics -XX:+UseThreadPriorities -XX:+TrustFinalNonStaticFields -XX:ThreadPriorityPolicy=1 -XX:+UseXmmI2D -XX:+UseXmmI2F -XX:+UseXmmRegToRegMoveAll -XX:+UseNewLongLShift -XX:+UseXMMForArrayCopy -XX:+UseVectorCmov -XX:+UseCMoveUnconditionally -XX:+UseFPUForSpilling -XX:+UseFastUnorderedTimeStamps -XX:+PerfDisableSharedMem -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:HeapDumpPath=C:\Minecraft\ErrorDump\ -XX:-CreateCoredumpOnCrash -Xlog:gc+heap=debug,safepoint:.\logs\GC.log:time,uptime:filecount=10,filesize=1024K -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9011 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false --add-modules=jdk.incubator.vector -jar purpur-1.19.jar -W .\worlds nogui`

**Comment by BillyGalbreath** [comment]
So don't use that flag then. When you use that flag the JVM will use CMake instructions unconditionally, meaning it skips the tests to see if it even needs them. Let the JVM decide.
