### ISSUE TITLE
Server Crash - Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by mibby** [pl3xgaming/Purpur#1021]
### Timings link

https://timings.aikar.co/?id=90cc52627df94160bf457b2f070eaa99

### Stack trace

https://paste.gg/p/anonymous/17fcba27d66943dd83454c2b30f7c183/files/66c4841665e6465298fa37e6b9ba8827/raw

### Actions to reproduce (if known)

No idea, sorry. Was a one-off crash error that I figured I'd report upstream before updating Purpur 9 builds ahead.

### Purpur version

git-Purpur-1675 (MC: 1.19)*

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by katekerllenevich** [comment]
Are you able to reproduce on the latest version?

**Comment by mibby** [comment]
I'm not sure how it even happened so I can't say. Latest doesn't have any new commits to chunk loading or behavior. It's mostly just Spark changes and a minor API change in Bukkit/Craftbukkit (from Paper upstream merge) so the issue should still be relevant from this build the error occurred in.

**Comment by SageSphinx63920** [comment]
I had the same error some days before. Idk what I did exactly but update all plugins and purpur itself.

**Comment by BillyGalbreath** [comment]
This is caused by something that is ticking things off the main thread. It could be one of your plugins, or a bug in one of our upstreams. You'll have to do some troubleshooting to figure out which, but this is not caused by Purpur.
