### ISSUE TITLE
Tadpoles do not grow into frogs

### ISSUE THREAD

**Issue by HorusApl** [pl3xgaming/Purpur#1022]
### Spark link

n/a

### Expected behavior

After the 24000 game ticks it takes to grow, tadpoles will turn into normal frogs.

### Observed/Actual behavior

They don't grow no matter how much time has passed

### Steps/models to reproduce

Start barebones test server with no plugins, set randomTickspeed to 1000 and wait. They won't grow.

### Purpur version

[08:10:45 INFO]: Current: git-Purpur-1682 (MC: 1.19)*
Previous: git-Purpur-1631 (MC: 1.18.2)
* You are 3 version(s) behind

Have not tested latest 2 builds, but I see no other mention of this issue in other Github issues or changelogs.

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
Completely ignoring that you didn't follow instructions; Are you able to reproduce on one of our upstreams, either on a Paper or Pufferfish server?

**Comment by YouHaveTrouble** [comment]
> Spark link n/a

spark link is not optional

> Start barebones test server with no plugins, set randomTickspeed to 1000 and wait. They won't grow.

Random tick speed doesn't affect animal growth speed afaik

> You are 3 version(s) behind

**Comment by HorusApl** [comment]
Just wanted to report what I had found, feel free to close it and do nothing if what I provided wasn't adequate.

**Comment by BillyGalbreath** [comment]
Unable to reproduce. Tadpoles take 20 minutes (24000 ticks) to grow up. The random tick speed gamerule does not speed this up at all because this isn't a random tick feature.

Is slimeballs to speed it up if you want.
