### ISSUE TITLE
Spark link is not clickable in chat.

### ISSUE THREAD

**Issue by mibby** [pl3xgaming/Purpur#1023]
### Spark link

Not relevant.

### Expected behavior

Being able to click on the spark info link when trying to use timings.

### Observed/Actual behavior

Can't click on the link, have to manually type it in browser.

### Steps/models to reproduce

* ``/timings on``
* Get replacement output
* Try clicking on link

![link](https://i.imgur.com/Z9wpjau.png)

### Purpur version

git-Purpur-1684 (MC: 1.19)*

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by mibby** [comment]
Also knowing timings is probably going to be removed, is there no way to have it off by default for minimal performance implications keeping it around and allow forcing it enabled for profiling for those that prefer it? I personally find Aikar's timings much more human readable in quickly figuring out which plugin or datapack function call is at fault for diagnosing small performance issues, so it can be reported upstream.

With Spark, you really have to dig deep and try to figure out obfuscated threads if it isn't named or called from a specific plugin. Can't quickly check what is problematic imo. Maybe I'm just dumb but I can't figure out how to find datapack functions / clocks (Terralith / Incendium / Nullscape) in Spark either where it was easily findable in Timings.

![link](https://i.imgur.com/8A9pP4s.png)

**Comment by 12emin34** [comment]
The only reason Timings is gonna get removed is that it hurts performance even when it's disabled. Spark is actually more accurate too and won't blame random entities for async tasks taking too long like Timings does.

**Comment by emielderckx** [comment]
Press this button until you see sources this gives you the same kind of view as timings
![image](https://user-images.githubusercontent.com/35953244/176377872-e0bd5b70-26ba-4b99-b0ac-de905d9c23b2.png)

**Comment by mibby** [comment]
Oh! That definitely seems new since I last used Spark. Very cool.

My only concern is obfuscation from datapack functions / clocks I guess.
