### ISSUE TITLE
Purpur doesn't send Ender Dragon position to the client.

### ISSUE THREAD

**Issue by Fox2Code** [pl3xgaming/Purpur#1027]
### Spark link

https://spark.lucko.me/7Xiaif6BSX

### Expected behavior

Ender Dragon position is sent to client.

### Observed/Actual behavior

Ender Dragon position is not sent to client.

### Steps/models to reproduce

Go to the end or summon an Ender Dragon.

### Purpur version

Current: git-Purpur-1685 (MC: 1.19)*
Previous: git-Purpur-1670 (MC: 1.19)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Video of me showing the bug and visual location (Client Location) doesn't match `/tp` location (Server location) on a server with no plugins.
[PurpurEnderDragonFail.mp4.zip](https://github.com/PurpurMC/Purpur/files/9020801/PurpurEnderDragonFail.mp4.zip)

**Comment by encode42** [comment]
Try reproducing this on our upstream, [Pufferfish](https://github.com/pufferfish-gg/Pufferfish). Purpur doesn't modify packets, and especially not packets for the Ender Dragon, but Pufferfish might.

**Comment by BillyGalbreath** [comment]
I am unable to reproduce this.

**Comment by Fox2Code** [comment]
![StillDoesNotWork](https://user-images.githubusercontent.com/42963271/177034049-f228bd8a-89fc-402d-800d-70d8393cbce7.gif)
I reproduce this on a local server with no plugins, nothing.
I just downloaded latest Purpur 30 seconds ago.

**Comment by Fox2Code** [comment]
@Encode42 I was able to reproduce that on Pufferfish, I will report to them.
