### ISSUE TITLE
The Redstone does not work anymore

### ISSUE THREAD

**Issue by SundayMC** [pl3xgaming/Purpur#1028]
### Spark link

https://spark.lucko.me/M70WTgfDe

### Expected behavior

I would like the levers, buttons, torches and restone blocks to work.

### Observed/Actual behavior

The redstone works for the first 10 minutes after the server is launched and then stops working

### Steps/models to reproduce

Trying to use redstone with the same configuration as me

### Purpur version

git-Purpur-1632 (MC: 1.18.2)*
* You are running the latest version

### Agreements

- [x] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I use the following plugins: AnimaBossBar*, AuctionHouse, BetterRTP, ChestCommands, Citizens, CoreProtect, DiscordSRV, EconomyShopGUI, EpicFurnaces, Essentials, EssentialsChat, EssentialsSpawn, ExecutableItems, HolographicDisplays, InvSeePlusPlus, Iris, JoinSound*, JukeBox, LagAssist, LaggRemover, LastLoginAPI, LuckPerms, Maintenance, Multiverse-Core, Multiverse-Inventories, NoteBlockAPI, OreAnnouncer, PlaceholderAPI, PortableCraftingInvs, ProtocolLib, SCore, spark, SuperVanish, TabList, TradeSystem, Vault, VoxelSniper, WorldBorder, WorldEdit, WorldGuard

If needed, ask me for any information.

Sincerely and thank you for your help,
Sunday

**Comment by 0x7d8** [comment]
1.18.2 isnt supported anymore
