### ISSUE TITLE
Coral not generating and showing errors while pre-generating the world with Chunky.

### ISSUE THREAD

**Issue by devendrapoonia** [pl3xgaming/Purpur#1041]
### Spark link

https://spark.lucko.me/mZ3MHYYZbm

### Expected behavior

I was pre-generating the world with Chunky. World should generate normally.

### Observed/Actual behavior

After few minutes of starting pre-generation. Console spams with a lot of errors making the log file very large. I contacted Chunky's developers but they said that Coral is not generating properly and you should report this to Purpur.

### Steps/models to reproduce

Install Chunky
Pre-generate the world
There is a chance that an error will come

### Purpur version

git-Purpur-1697 (MC: 1.19)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I was pre-generating the world in Purpur's this version - git-Purpur-1697 (MC: 1.19)
logs - 
[2022-07-07-1.log](https://github.com/PurpurMC/Purpur/files/9060637/2022-07-07-1.log)

Plugins - https://cdn.discordapp.com/attachments/734228189370646658/994456145471221760/unknown.png

Crash Report - 
[crash-2022-07-07_02.17.48-server (1).txt](https://github.com/PurpurMC/Purpur/files/9060645/crash-2022-07-07_02.17.48-server.1.txt)

**Comment by encode42** [comment]
You *are not* running the latest version of Purpur available from https://purpurmc.org/downloads.

**Comment by BillyGalbreath** [comment]
There is a reason those agreement checkboxes are there. If you were in fact on the latest version available you would not be having this issue because it was fixed literally in the build right after the one you are running..

![image](https://user-images.githubusercontent.com/332527/177780890-7c40f098-631f-4a61-8b64-d402904ae754.png)
