### ISSUE TITLE
Spawner permissions do not work 

### ISSUE THREAD

**Issue by RhythmicSys** [pl3xgaming/Purpur#1045]
### Spark link

https://spark.lucko.me/Dgse2p2IDb

### Expected behavior

That a player would be able to mine/place spawners with a silk touch pickaxe when that config option is enabled, and they have the permissions for it.

### Observed/Actual behavior

Only players with OP are able to drop spawners with silk touch, and place them with the correct data, regardless if the player has the permissions or not

### Steps/models to reproduce

Video cause I'm bad at words

https://user-images.githubusercontent.com/45906780/177884294-a52a1a79-50e4-4880-9f15-455379bab64c.mp4

### Purpur version

Current: git-Purpur-1702 (MC: 1.19)*
Previous: git-Purpur-1692 (MC: 1.19)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

It also appears that you don't need the permissions at all if you're OP'd, which idk if that's a bug as well, since the docs say 
`By default all of these permissions are disabled, no matter if a user has OP. Users will need to be granted permissions using a permissions plugin such as [LuckPerms](https://luckperms.net/).`

https://user-images.githubusercontent.com/45906780/177884640-670f8e0b-715e-4f48-aa26-fed454173da6.mp4

**Comment by RhythmicSys** [comment]
![image](https://user-images.githubusercontent.com/45906780/177884872-2e84e8d8-fbb3-418d-83e7-785831b6575a.png)

okay so it seems like the initial issue is that,, I was using an incorrect permission,, I guess there's 2? Is that an issue on my end/do I need to clear something?

**Comment by BillyGalbreath** [comment]
Fixed in build 1704
