### ISSUE TITLE
Pillage tower

### ISSUE THREAD

**Issue by bluejt** [pl3xgaming/Purpur#1046]
### Spark link

purpur

### Expected behavior

Attack generated are not affected

### Observed/Actual behavior

purpur Server plunder tower generation is affected, how should be adjusted

### Steps/models to reproduce

Attack generation speed is slow

### Purpur version

Attack generation speed is slow

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I'm sorry to ask you a question in this way, but I really can't find where to ask the question. Sorry.

**Comment by BillyGalbreath** [comment]
> I'm sorry to ask you a question in this way, but I really can't find where to ask the question. Sorry.

I can't make heads from tails of this ticket. Join us on Discord for further discussion.
