### ISSUE TITLE
Bedrock Players get kicked if their enderchest rows are modified while they are in game.

### ISSUE THREAD

**Issue by Tydium** [pl3xgaming/Purpur#1053]
### Spark link

https://spark.lucko.me/PEpxfO6gj9

### Expected behavior

When pupur.enderchest.row.(4-6) is modified or enabled, bedrock players should be able to open their echest with the modified row numbers.

### Observed/Actual behavior

Instead, while a bedrock player is playing and you modified their rows between 4-6 they get kicked for "Packet processing error". When they rejoin it will act normally and give the amount of rows that the permission has.

### Steps/models to reproduce

1. Join on bedrock
2. edit the row permission of the bedrock user with your designated permissions editor (We use LuckPerms) 
3. Make sure its not purpur.enderchest.rows.1-3 and make sure you don't edit to something the bedrock player already had.
4. On bedrock open the modified echest.
5. Experience the chaos.

Video demonstration: https://youtu.be/ZWlPd_v1yLU

### Purpur version

[03:14:39 INFO]: Current: git-Purpur-1714 (MC: 1.19)*
Previous: git-Purpur-1690 (MC: 1.19)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Few things:
1. I spoke to the geyser devs already. There was no errors coming from geyser as far as I can see. They told me to come to you guys.
2. Here is an error from console of purpur. https://pastebin.com/rUEyrtvg
3.  im using Velocity. 
4. Using Floodgate (Geyser)

**Comment by BillyGalbreath** [comment]
Sorry, but we don't support protocol hacks.
