### ISSUE TITLE
Patch 0108 - Arrows Should Not Reset Despawn Counter Not Configurable

### ISSUE THREAD

**Issue by NutNutty64** [pl3xgaming/Purpur#1064]
### Spark link

https://spark.lucko.me/JCuxCSpDGr

### Expected behavior

Somewhere in the config for Purpur there should be a setting to re-enable resetting the despawn timer.

### Observed/Actual behavior

There is no config setting available.

### Steps/models to reproduce

1. Run Server

### Purpur version

[03:28:14 INFO]: Checking version, please wait...
[03:28:15 INFO]: Current: git-Purpur-1720 (MC: 1.19)*
Previous: git-Purpur-1718 (MC: 1.19)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by encode42** [comment]
Added in 3316c894deb3a9e3cb5e21c16cf914654c7b15f6
