### ISSUE TITLE
Gravity blocks aren't properly exiting the end portal

### ISSUE THREAD

**Issue by BossDaily** [pl3xgaming/Purpur#1067]
### Spark link

https://spark.lucko.me/AzMYr1hcF9

### Expected behavior

Something is up with entities coming thru the end portal. If you look you can see that they are not coming out in the middle like normal. This is causing dupers not to work.

### Observed/Actual behavior

https://cdn.discordapp.com/attachments/762750140250718220/997426244129914981/Base_Profile_2022.07.15_-_04.55.16.03.mp4 As you can see here the sand isn't coming out of the exact center

### Steps/models to reproduce

enable sand duping and go to the end platform with a sand duper running

### Purpur version

1724

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by iJamiro24** [comment]
Problem has been ongoing from version 1697 to current version 1725, all previous versions had the blocks teleporting in the middle like they should be

**Comment by BillyGalbreath** [comment]
This is caused from an [update in CraftBukkit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/991aeda1218e72e9237942071e7ea55cc77b541c). Recreate your duper on CraftBukkit and [report the issue to them](https://hub.spigotmc.org/jira/secure/Dashboard.jspa).
