### ISSUE TITLE
`Villagers- bypass-mob-griefing: true` does not allow villagers to bypass mob griefing

### ISSUE THREAD

**Issue by RhythmicSys** [pl3xgaming/Purpur#1068]
### Spark link

https://spark.lucko.me/kdDIm7Q74y

### Expected behavior

Villagers would bypass `gamerule mobGriefing false`

### Observed/Actual behavior

Villagers will not pick up items when bypass is set to true

### Steps/models to reproduce

https://user-images.githubusercontent.com/45906780/180356955-aaff7291-c6e7-4de1-8ac0-d2f2f6c1619f.mp4

### Purpur version

Current: git-Purpur-1724 (MC: 1.19)*
Previous: git-Purpur-1713 (MC: 1.19)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Creepers do successfully bypass the mobgriefing gamerule when the same config option is set on that.

**Comment by BillyGalbreath** [comment]
Because of where the pickup items check is in the code, it is not specific to any single entity. It is shared across all entities that pickup loot. Because of this, there is a separate option for this: `entities-pick-up-loot-bypass-mob-griefing`
