### ISSUE TITLE
piglins spawn without ai and do not react until you approach them

### ISSUE THREAD

**Issue by meaningg** [pl3xgaming/Purpur#1070]
### Spark link

https://spark.lucko.me/abgoyutyMe

### Expected behavior

After spawning, the pyglines go towards the turtle egg and enter the portal

### Observed/Actual behavior

After spawning, the pyglies stand and do not react to anything unless a player approaches them

https://user-images.githubusercontent.com/61989272/180454481-003705a5-7782-4ecc-8579-33695160f546.mp4

https://user-images.githubusercontent.com/61989272/180454729-1f433c9d-86f0-4900-9c43-68a6a8fb5f08.mp4

.

### Steps/models to reproduce

Build a classic gold farm in nether on the latest version of purpur 1.19

### Purpur version

Current: git-Purpur-1725 (MC: 1.19)*
Previous: git-Purpur-1718 (MC: 1.19)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by meaningg** [comment]
one more video proof https://youtu.be/mYBnNCf_gz8

**Comment by encode42** [comment]
This is expected behavior of our upstream, Pufferfish.

You can either disable DAB for a decrease in performance, or add piglins to DAB's blacklist.

More info can be found at [Pufferfish's documentation](https://docs.pufferfish.host/setup/pufferfish-fork-configuration/#dab)
