### ISSUE TITLE
Rainbow Shulker Spawning Feature Issue

### ISSUE THREAD

**Issue by LeeTheTech** [pl3xgaming/Purpur#1075]
### Spark link

https://spark.lucko.me/vLgDLUh7Po

### Expected behavior

For shulkers to spawn random colored shulkers on bullet impact. 

### Observed/Actual behavior

Just normal old shulkers.

### Steps/models to reproduce

Enable: random-color under the shulker key

### Purpur version

git-purpur-1732 1.19

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

This was working back in 1.18 but sadly not 1.19.
Gif: https://gyazo.com/a4526022f1a5844e7c9d819ecabff00e

**Comment by granny** [comment]
please update your comment with proper steps to reproduce your issue

**Comment by LeeTheTech** [comment]
> please update your comment with proper steps to reproduce your issue

I thought it was clear but ok, updated

**Comment by granny** [comment]
https://user-images.githubusercontent.com/43185817/180668593-29379238-9d04-4795-bcc2-ec3b73af6685.mp4


Works on latest for me with these config changes:
```yml
      shulker:
        spawn-from-bullet:
          require-open-lid: true
          random-color: true
```

**Comment by LeeTheTech** [comment]
> javaw_YljdzWO6NE.mp4 
> Works on latest for me with these config changes:
> 
> ```yaml
>       shulker:
>         spawn-from-bullet:
>           require-open-lid: true
>           random-color: true
> ```

oh shoot, sorry, I uninstalled all the plugns and it worked again, hmm, wonder what would prevent that...
Thanks for your time!
