### ISSUE TITLE
teleport-if-outside-border feature issue

### ISSUE THREAD

**Issue by LeeTheTech** [pl3xgaming/Purpur#1076]
### Spark link

https://spark.lucko.me/atZIGA3bI4

### Expected behavior

To teleport the player back to spawn or back in the world border when teleporting outside the world border.

### Observed/Actual behavior

When I used a ender pearl outside the border it just displayed this weird void rendering issue: https://gyazo.com/5e815cbae89ad3cd59f0c894ad87fdc4

### Steps/models to reproduce

1. Enable: teleport-if-outside-border in purpur.yml
2. Throw a ender pearl outside the world border, while not an operator

### Purpur version

git-purpur-1732 1.19

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

This worked back in 1.18 but sadly not 1.19.

**Comment by granny** [comment]
https://user-images.githubusercontent.com/43185817/180669176-67ac4d6a-1abb-4345-bd43-63445be656f6.mp4


Could not reproduce.

**Comment by LeeTheTech** [comment]
> javaw_P9eoRZ0P7j.mp4 
> Could not reproduce.

Were you not oped? It'll let you bypass as a op

**Comment by granny** [comment]
> > javaw_P9eoRZ0P7j.mp4
> > Could not reproduce.
> 
> Were you not oped? It'll let you bypass as a op

I was not op'd. You can see I attempted to run the `/op` command and got an error, as well as the `/lp` command which states I have not set any permissions.

**Comment by LeeTheTech** [comment]
> > > javaw_P9eoRZ0P7j.mp4
> > > Could not reproduce.
> > 
> > 
> > Were you not oped? It'll let you bypass as a op
> 
> I was not op'd. You can see I attempted to run the `/op` command and got an error, as well as the `/lp` command which states I have not set any permissions.

Whoops, missed that, thanks for your time!
