### ISSUE TITLE
End platform clears too many blocks when player enters dimension

### ISSUE THREAD

**Issue by Aldebaran-0** [pl3xgaming/Purpur#1079]
### Spark link

https://spark.lucko.me/ZgePRHLuDN

### Expected behavior

When player enters end portal, 3 layers of blocks above the obsidian platform in the end are cleared, and if entities enter the end portal like items, 3 layers are cleared as well.

### Observed/Actual behavior

When player enters end portal, 4 layers (1 layer too many upwards) is deleted, but when an item entity enters, 3 layers are deleted as should be.

### Steps/models to reproduce

Simply place a 4 block tall pillar on the end obsidian platform at 100,0 in the end and when a player enters the dimension all 4 blocks are gone but if an item does and you teleport to it, only 3 blocks are gone as correct vanilla behavior.

### Purpur version

Checking version, please wait...
**Current : git-Purpur-1732 (MC 1.19)**
You are running the latest version.
_Previous : git-Purpur-1711 (MC 1.19)_

### Agreements

- [x] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Spigot has been messing with teleport precision here lately. Can you test this on build 1735 (or higher if there any when you get to read this)

**Comment by Aldebaran-0** [comment]
Unfortunately the issue still persists on git-Purpur-1735

**Comment by BillyGalbreath** [comment]
Can you try on our upstreams? Pufferfish and Paper.

**Comment by Aldebaran-0** [comment]
Really sorry for wasting your time :(
I've tested a lot of stuff and managed to figure out that the issue is with multiverse and not purpur. Thank you for trying to help and sorry again for mistaking the error for a purpur bug
