### ISSUE TITLE
World deletion problem //Win 1.18.2 ok (created on win1.18.2), Linux both 1.18.2 and 1.19 wipes.

### ISSUE THREAD

**Issue by jokbon** [pl3xgaming/Purpur#1080]
### Spark link

jiojioj

### Expected behavior

purpur starts up and starts upgrading and runs server with old world

### Observed/Actual behavior

purpur wipes old world and starts new one on random seed

### Steps/models to reproduce

1.18.2 world on windows vanilla
go to linux (1.18.2 and 1.19) and it keeps on deleting (owerwriting) the world

### Purpur version

Current: git-Purpur-1730 (MC: 1.19)*
Previous: git-Purpur-1722 (MC: 1.19)
* You are 2 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Plugins: iridium skyblock, skulls, protocol lib, via version, voting, world edit, world guard, economy shop guy, essentials, papi, mineresetlite, coins, animated frames, insights, gsit, farm limiter.

**Comment by jokbon** [comment]
It shud not delete world when i change operating system :/

**Comment by jokbon** [comment]
If need world link i can provide. **Same server version and same plugins.**
On **windows** it don't **wipe old world.** On **linux** it **wipes old world and starts new one** on random seed.

**Comment by encode42** [comment]
You are **not** running the latest version of Purpur available from https://purpurmc.org/downloads.

"jiojioj" isn't a valid link either.

We can't help you if you don't give us the information required to help you.

Your issue most likely isn't related to Purpur anyways. I'm going to guess you either haven't given the user correct permissions, copied the world over incorrectly, or just haven't read your server's logs.

**Comment by jokbon** [comment]
i did no changes to server i just added startup script.sh and it deleted old world.
