### ISSUE TITLE
Pumpkin and Melon Stems not reverting

### ISSUE THREAD

**Issue by DuneSciFye** [pl3xgaming/Purpur#1083]
### Spark link

https://spark.lucko.me/EQARhZjhZN

### Expected behavior

Pumpkin and Melon stems should revert when the attached Pumpkin/Melon is broken.

### Observed/Actual behavior

One of my player's pumpkin farm has a design where once the stem has changed, an observer will detect it and crush the pumpkin. However sometimes the pumpkin stem doesn't revert back to the upright position.

![image](https://user-images.githubusercontent.com/65089425/180851329-4ea99e56-c1a5-4871-9580-e494e2e5be99.png)
![image](https://user-images.githubusercontent.com/65089425/180851336-5c64c0db-b9e0-4f68-b106-0a1895b7de18.png)
![image](https://user-images.githubusercontent.com/65089425/180851340-33a18aaa-5a14-4d22-a135-59902ead7c7c.png)

### Steps/models to reproduce

![image](https://user-images.githubusercontent.com/65089425/180852208-085adc76-2c40-41ee-aaa0-fa3071854e0b.png)
![image](https://user-images.githubusercontent.com/65089425/180852212-adb9007f-8e18-4b92-83a8-11b1b3015d72.png)
![image](https://user-images.githubusercontent.com/65089425/180852220-b733d5d3-5cc9-441b-9cb9-110fb50ddc4d.png)
Here are some pictures of the farm.

### Purpur version

Current: git-Purpur-1715 (MC: 1.19)*
Previous: git-Purpur-1632 (MC: 1.18.2)
* You are 17 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I know I'm outdated and not running the latest, but I don't think that really should affect it as its been a very long and reacurring issue on my server. Just let me know if you want me to update to latest and test.

**Comment by encode42** [comment]
~~Your version of Minecraft is **not** supported by Purpur.~~

**Comment by encode42** [comment]
I keep misreading! sorry (read the previous version instead of current)

Though you are **not** running the latest version of Purpur available from https://purpurmc.org/downloads, which is still important because this could've been fixed recently.

Are you sure this isn't client-sided? Tried on the vanilla client, no mods?

**Comment by DuneSciFye** [comment]
Yes, this was the issue with a vanilla Java account with no mods or anything, along with a bedrock user. I will be testing the latest Purpur version tonight.

**Comment by Itsyourdriver** [comment]
> I keep misreading! sorry (read the previous version instead of current)
> 
> Though you are **not** running the latest version of Purpur available from https://purpurmc.org/downloads, which is still important because this could've been fixed recently.
> 
> Are you sure this isn't client-sided? Tried on the vanilla client, no mods?

When I had this issue it was only for the other people on my server (I usually have under 5 ping, all stems update fine for me), as the farm *seemed* to be working as normal. (when testing, we found that relogging updates everything, making me believe this is a client-side issue.)

**Comment by DuneSciFye** [comment]
Odd alright, let me have them relog.

**Comment by DuneSciFye** [comment]
Here's what the players said: "I relog everyday and even after relog this issue still persists
Also if its a client side issue only i would see this technically. But everyone who come on my island can see the stems not reverting"

**Comment by BillyGalbreath** [comment]
> Here's what the players said: "I relog everyday and even after relog this issue still persists Also if its a client side issue only i would see this technically. But everyone who come on my island can see the stems not reverting"

That is not what they meant. What they meant is if you (or your player) sees a stem not updating, disconnect and reconnect to see if it fixes itself for that one time. If it does, then the stem is actually updating but there is a client desync issue we need to look into. If it doesn't, though, then that means the block really isn't updating and we need to look elsewhere in the code for the possible cause. It is vital we get the correct information from troubleshooting before we start digging through code. There's a lot of code, and knowing details like this helps is greatly narrow down our search.

**Comment by DuneSciFye** [comment]
Alright, let me have them record a video.

**Comment by Itsyourdriver** [comment]
Went in on my server running build #1721 (I am aware this is outdated, this issue is too.)

Quick video of a melon & pumpkin farm working properly. (I have under 10 ping, running on fabric with sodium, some other peformance mods.) No protocol hacks, no lag-reducing plugins, or anything of that sort.




[https://cdn.driver.fyi/r/2022-07-28_19-04-48.mp4](https://us-east-1.tixte.net/uploads/cdn.driver.fyi/2022-07-28_19-04-48.mp4) (video is too big to send via github or discord)

**Comment by DuneSciFye** [comment]
Yep, can confirm with my players after some testing that it is player sided
