### ISSUE TITLE
fps drops problem

### ISSUE THREAD

**Issue by mrpunky** [pl3xgaming/Purpur#1087]
### Spark link

https://spark.lucko.me/VNNuEblIh7

### Expected behavior

be like other places

### Observed/Actual behavior

Hi, while going through some places on my server, the fps drops from 200 300 to 70 80, so they eat fps drops, what do you recommend I do for this?

### Steps/models to reproduce

https://prnt.sc/3ms4heuaaGm3

### Purpur version

Current: git-Purpur-1732 (MC: 1.19)*
* You are 3 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Agreements

- [ ] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by 0x7d8** [comment]
That could just be alot of building in that area, I dont think thats a Purpur Problem, besides that, you arent using the newest Version, or a supported Minecraft Version, atleast I believe 1.19 isnt supported anymore, only 1.19.1 is

**Comment by mrpunky** [comment]
![image](https://user-images.githubusercontent.com/101196617/181904369-38a4b554-4ae3-4e15-8a2a-a34b020aef61.png)
The area is an empty area. I was using the same map in version 1.18.
I started to encounter such a problem when I upgraded to version 1.19.

**Comment by 0x7d8** [comment]
Yeah, I dont think Purpur causes FPS Drops, its a Server, not a Client, the max that would happen is TPS drops. FPS drops dont really come from Purpur

**Comment by mrpunky** [comment]
Got it, do you have any idea what it's from? because this is pvp zone and players are very uncomfortable

**Comment by MADS0LADEN** [comment]
By pressing F3 you can find the entity and particles counter, if that is very high the fps suffers.
Very pixel detailed blocks combined with a lot of light level changes is also heavy on fps.
