### ISSUE TITLE
Feature Request: nether wart harvestable by clerics

### ISSUE THREAD

**Issue by datsanakas** [pl3xgaming/Purpur#109]
Hi, would it be possible to add a config option that lets cleric villagers harvest nether warts like farmers harvest wheat, potatoes and carrots? I got this idea from the [carpet-extra mod](https://github.com/gnembon/carpet-extra#clericsfarmwarts) .

**Comment by BillyGalbreath** [comment]
Sounds like an easy thing. I'll see what I can do ^_^

**Comment by jpenilla** [comment]
Added in 9935466 (build 876)
