### ISSUE TITLE
Silk Spawners config doesn't work

### ISSUE THREAD

**Issue by Aldebaran-0** [pl3xgaming/Purpur#1092]
### Spark link

https://spark.lucko.me/ZgePRHLuDN

### Expected behavior

When silk touch drops spawners is enabled in purpur config, spawners used to drop properly when you broke them with a silk touch pickaxe.

### Observed/Actual behavior

As of 1.19.1 builds this does not work anymore and the spawners don't drop when broken even though the setting is enabled in config.

### Steps/models to reproduce

Try breaking a spawner with silk spawners enabled in purpur.yml on 1.19.1 using a silk touch pickaxe and nothing drops

### Purpur version

Current : git-Purpur-1749 (MC 1.19.1)
You are running the latest version.

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by Itsyourdriver** [comment]
Have you checked if you have the correct permissions? 
![image](https://user-images.githubusercontent.com/73563507/183101888-d6692ea1-ec45-4906-8880-a98da7a02640.png)

**Comment by Itsyourdriver** [comment]
> Have you checked if you have the correct permissions? ![image](https://user-images.githubusercontent.com/73563507/183101888-d6692ea1-ec45-4906-8880-a98da7a02640.png)

Current: git-Purpur-1749 (MC: 1.19.1)*

Video below of this feature working properly, I have given myself the two permissions (purpur.drop.spawners & purpur.place.spawners) using luckperms

https://user-images.githubusercontent.com/73563507/183107417-8d258e0e-97c1-4b3a-b5ed-22160540c0c6.mp4

**Comment by Aldebaran-0** [comment]
I am an operator on the server, but since it seems to work for you i will try to check if its one of the plugins im using that causes this. Thanks

**Comment by BillyGalbreath** [comment]
> I am an operator on the server, but since it seems to work for you i will try to check if its one of the plugins im using that causes this. Thanks

Operators dont get any Purpur permissions. This is by design. Op is not a rank.
