### ISSUE TITLE
Server sending bad client packet?

### ISSUE THREAD

**Issue by ogidevs** [pl3xgaming/Purpur#1104]
### Spark link

https://spark.lucko.me/sjf3d4d3mZ

### Expected behavior

I'm running the newest 1.19.2 purpur build and I'm using mcprotocollib library for creating clients, while sending a message to the chat thru client with ServerboundChatPacket it should work without any problems. (tested on normal spigot build 1.19.2)

### Observed/Actual behavior

While trying to send message to the chat thru client, chat is sent, then client gets disconnected. No error in server's console is presented, but I get this error on my side:
https://pastebin.com/tDF75fRw

### Steps/models to reproduce

https://streamable.com/hotc30

### Purpur version

[03:22:07 INFO]: Checking version, please wait...
[03:22:07 INFO]: Current: git-Purpur-1760 (MC: 1.19.2)*
Previous: git-Paper-130 (MC: 1.19.2)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by katekerllenevich** [comment]
Chat is *vastly, **vastly*** different on 1.19. Likely this is an error with your protocol library (iirc in 1.19.2 there is a separate packet for system messages)..

**Comment by katekerllenevich** [comment]
I'm stupid, ignore the previous comment. This is a Paper issue about Adventure, where adventure can't serialize the json into a component.

**Comment by ogidevs** [comment]
So what now?

**Comment by katekerllenevich** [comment]
Join our [discord](https://purpurmc.org/discord) and send the code you're using in #developers, feel free to ping me.

**Comment by ogidevs** [comment]
Thanks a bunch!
