### ISSUE TITLE
Wrong version displayed when using wrong Java version.

### ISSUE THREAD

**Issue by ghost** [pl3xgaming/Purpur#1108]
### Spark link

none

### Expected behavior

Displaying 1.19.2 as the version.

### Observed/Actual behavior

Displaying 1.18.2 as the version.

### Steps/models to reproduce

Use any version of Java under 18.
See the output.

### Purpur version

> version
[05:21:15 INFO]: Current: git-Purpur-1762 (MC: 1.19.2)*
* Error obtaining version information

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

It's not that bad of a bug but I think you should change it.

**Comment by katekerllenevich** [comment]
The only plausible issue happening here is that you are running the wrong jar file, there aren't any mentions of 1.18 in the 1.19 codebase.
