### ISSUE TITLE
Shovel duping

### ISSUE THREAD

**Issue by agoniaprivat** [pl3xgaming/Purpur#111]
**Describe the bug**
Duping shovels

**To Reproduce**
1. Place out a campfire 
2. Rightclick with an shovel to put off the fire
3. Break it with an Silktouch pickaxe and then you get a duplicated shovel

**Screenshots or Videos**
I don't think we need any

**Plugins**
Show the output of `/plugins` here.
![image](https://user-images.githubusercontent.com/50961682/101376544-0178e880-38b1-11eb-849e-5ef84475b71f.png)

**Version**
git-Purpur-876 (MC: 1.16.4)

**Comment by BillyGalbreath** [comment]
Unable to reproduce.

Can you try it without plugins? It's probably one of those doing it.
