### ISSUE TITLE
Enderman do not pick up blocks 

### ISSUE THREAD

**Issue by wlm3201** [pl3xgaming/Purpur#1115]
### Spark link

https://spark.lucko.me/F27Nw4EwMR

### Expected behavior

Endermans ramdomly pick up blocks like dirt.
![image](https://user-images.githubusercontent.com/77601125/187032332-120fe6dc-e373-4bed-a97c-39507a6e5134.png)

### Observed/Actual behavior

Endermans do not pick up blocks like dirt. Default config and no plugins, purely purpur.
![image](https://user-images.githubusercontent.com/77601125/187032237-4ca4f697-a488-4984-91a8-8fc222f18ce3.png)

![image](https://user-images.githubusercontent.com/77601125/187032177-50141b5e-f79f-4205-8f76-3a73da0a46ce.png)
in default purpur.yml and 
![image](https://user-images.githubusercontent.com/77601125/187032197-3c1e7e58-1443-4a02-b4ea-111401d3aeab.png)
 in game.

### Steps/models to reproduce

/fill ~ ~ ~ ~10 ~10 ~10 dirt. Dig a hole and spawn some enderman inside, then wait a few second.

### Purpur version

Current: git-Purpur-1768 (MC: 1.19.2)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

upstreams paper and pufferfish work normally
![Snipaste_2022-08-27_21-35-36](https://user-images.githubusercontent.com/77601125/187032701-81751d50-da57-4f73-a32f-4e4ea0698b6e.png)
![Snipaste_2022-08-27_21-29-26](https://user-images.githubusercontent.com/77601125/187032717-77a8b8f4-4da8-46d0-8aa8-a0adfabc439e.png)

**Comment by hexadecimal233** [comment]
Can reproduce
and the enderman grief toggle code is strange

-  return this.enderman.getCarriedBlock() == null ? false : (!this.enderman.level.getGameRules().getBoolean(GameRules.RULE_MOBGRIEFING) ? false : this.enderman.getRandom().nextInt(reducedTickDelay(2000)) == 0));
+  return this.enderman.getCarriedBlock() != null ? false : (!this.enderman.level.purpurConfig.endermanBypassMobGriefing && !this.enderman.level.getGameRules().getBoolean(GameRules.RULE_MOBGRIEFING) ? false : this.enderman.getRandom().nextInt(reducedTickDelay(2000)) == 0)); // Purpur
-  return this.enderman.getCarriedBlock() != null ? false : (!this.enderman.level.getGameRules().getBoolean(GameRules.RULE_MOBGRIEFING) ? false : this.enderman.getRandom().nextInt(reducedTickDelay(20)) == 0);
+  return this.enderman.getCarriedBlock() == null ? false : (!this.enderman.level.purpurConfig.endermanBypassMobGriefing && !this.enderman.level.getGameRules().getBoolean(GameRules.RULE_MOBGRIEFING) ? false : this.enderman.getRandom().nextInt(reducedTickDelay(2000)) == 0); // Purpur

Purpur totally break this i think
