### ISSUE TITLE
[Tile entity] [Block] [Bug Event] Problematic TILE Blocks

### ISSUE THREAD

**Issue by SteelsSystem** [pl3xgaming/Purpur#1116]
### Spark link

can't provide, we had to switch to paper

### Expected behavior

as title states there's problem with TILE(entity/spawner) blocks added through resource pack on Java, i've ran into so many problemss with them trying to make them apply texture, texture shoudl've correctly apply, it did on Paper fork.
it is only problem with purpur 1.19.2, issue doesn't occur on 1.18 versions and below
 https://github.com/PluginBugs/Issues-ItemsAdder/issues/1933

### Observed/Actual behavior

https://youtu.be/xdDmDfxQfx0

### Steps/models to reproduce

install purpur, 
install itemsadder, 
use resource pack and make sure the
 blocks you install are TILE type block

### Purpur version

https://github.com/PluginBugs/Issues-ItemsAdder/issues/1933

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by LoneDev6** [comment]
Is this reproducible on Paper 1.19.2 or only on Purpur 1.19.2?
You have to make sure that this issue is Purpur related. It might be caused by some internal changes on how tile data is handled I think, I'm not really familiar with what Purpur changes.

**Comment by SteelsSystem** [comment]
I had it occuring on paper as well after i tested more :(

**Comment by LoneDev6** [comment]
There is no point into opening an issue report on Purpur Github if you can reproduce it on Paper too.
Continue on: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1933
And please also try with normal Spigot.

I cannot reproduce the issue in any way, you might have a corrupted world, I don't know.
