### ISSUE TITLE
Fishing dont work

### ISSUE THREAD

**Issue by editon96** [pl3xgaming/Purpur#1118]
### Spark link

https://spark.lucko.me/P8YQq10TEy

### Expected behavior

I want to see that I can Use the fishing road like in Minecraft Survival to fish fishes.

### Observed/Actual behavior

When I use the fishing Road on water an Animation for Fishing Start was Played for an second. 
After that Second the animation for waiting on fishes and bubbels reverse and I cant fish.

### Steps/models to reproduce

1. Start Minecraft
2. Go on an Pupur Server
3. give you an fishing road
4. try to fish on water

### Purpur version

git-Purpur-1774 (MC: 1.19.2)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I use Velocity over that Pupur Server there and on the purpur Server was not any Plugins expect Spark.
Velocity Version 3.1.1 Build  102

Here an Video to show that Issue: [https://www.veed.io/view/c3eebb19-f2ed-414d-95a6-52686d022a69?sharingWidget=true](url)

**Comment by editon96** [comment]
the Video get deleted in 24 hours are written on the website I send it on discord too

**Comment by BillyGalbreath** [comment]
This was determined to be a misconfiguration. Reporter had fishing bobber's set to 15 ticks in pufferfish.yml's entity_timeouts.
