### ISSUE TITLE
Server Problem

### ISSUE THREAD

**Issue by RecanLive** [pl3xgaming/Purpur#1123]
### Spark link

none

### Stack trace

```
paste your stack trace or a paste.gg link here!
```
https://paste.gg/p/anonymous/87f2ab391c144b2dab0ad61a87b2fa1f

### Actions to reproduce (if known)

none

### Purpur version

Current: git-Purpur-1735 (MC: 1.19)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Players sometimes get stuck when they enter the gate of hell, and then the above error will appear, but the server does not restart or crash, but it will return to normal after a period of time. How can I solve this problem?

**Comment by BillyGalbreath** [comment]
You did _not_ post a Spark report.

This is _not_ a reportable bug, as stated in the report itself in all caps.

1.19 is _not_ the latest version available from our website.

We do _not_ support outdated software.

We do _not_ support offline mode servers.
