### ISSUE TITLE
How to adjust server shipping limits？

### ISSUE THREAD

**Issue by yizhixiaomifeng** [pl3xgaming/Purpur#1125]
### Spark link

I don't know what this is.

### Description of issue

When I finished using this server, I couldn't use an auxiliary module with too much packet mods.I went through any YML files in the server root folder and I barely found anything about this project, and even if there were, tweaking it was of little use.The author's work is very good, I hope that the author will have a MC version 1.18.2 or 1.19.X version of the package modification option, thank you, I am a heavy user of this project, I will always support the project.

### Purpur version

All versions.

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

~

**Comment by encode42** [comment]
I don't know what this is either. What are "shipping limits"? "auxiliary module with too much packet mods"? "package modification option"? I have no idea what any of this means.

**Comment by BillyGalbreath** [comment]
I think they are talking about the packet limiter?

https://docs.papermc.io/paper/reference/global-configuration#packet-limiter
