### ISSUE TITLE
villager.lobotomize

### ISSUE THREAD

**Issue by MrEDok** [pl3xgaming/Purpur#113]
**Describe the bug**
when villager is lobotomize they doesnt restock.

**To Reproduce**
trap villager in 1x1 area
trade till unable to trade
wait a couple minecraft day (wont restock)

**Plugins**
none

**Version**
git-Purpur-882 (MC: 1.16.4)

**Comment by Titaniumtown** [comment]
I can reproduce this issue.

**Comment by BillyGalbreath** [comment]
I have a fix I am testing right now
