### ISSUE TITLE
Plenty of zipfstmp*.tmp files in plugins directory

### ISSUE THREAD

**Issue by lospejos** [pl3xgaming/Purpur#1158]
### Spark link

no spark logs

### Expected behavior

No extra temporary files are left after server shuts down

### Observed/Actual behavior

A lot of files named `zipfstmp*.tmp` files are left after server shuts down.

### Steps/models to reproduce

Start server with plugins installed
Stop server

`zipfstmp*.tmp` files are present in `plugins` directory.

### Purpur version

purpur-1.19.2-1819

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

OS: `Windows 10`
Java: `openjdk 18.0.2 2022-07-19`

**Comment by BillyGalbreath** [comment]
This isn't something the server is doing

**Comment by DecisiveDolphin** [comment]
Having same issue. Any fix?
