### ISSUE TITLE
Some features are not working on latest release

### ISSUE THREAD

**Issue by itsBeaco** [pl3xgaming/Purpur#1165]
### Expected behavior

Some features are not working on the latest release. Currently, we have noticed the following:

1. Shift + right click mending has stopped working
2. Totems in inventory have stopped working

We updated to the latest version tonight and after the restart they have stopped working.

### Observed/Actual behavior

1. Shift + right click doesn't repair tools as expected. Tools definitely have mending
2. Player died with a totem in their inventory

### Steps/models to reproduce

![2022-10-17_20 59 09](https://user-images.githubusercontent.com/77558094/196271392-5c2a2976-5870-44d8-bda4-21a2c233f227.png)
![2022-10-17_20 59 37](https://user-images.githubusercontent.com/77558094/196271444-92a0e7c2-19a0-40e8-bf36-3dc8e4142ea6.png)

### Purpur version

git-Purpur-1804 (MC: 1.19.2)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by RhythmicSys** [comment]
These options have stopped working because as of b63fc3b8725d3319422083daee24626f280c4717
Shift mending now requires permission `purpur.mending_shift_click`
Totem in inventory now requires permission `purpur.inventory_totem`

**Comment by itsBeaco** [comment]
Ah, my apologies, I was a few versions behind before updating and didn't see the update. Thank you for letting me know!
