### ISSUE TITLE
totem-of-undying-works-in-inventory is not working

### ISSUE THREAD

**Issue by KioProject123** [pl3xgaming/Purpur#1166]
### Spark link

N/A

### Expected behavior

totem-of-undying-works-in-inventory works normally

### Observed/Actual behavior

The totem was not used when the player died

### Steps/models to reproduce

+ Set totem-of-undying-works-in-inventory: true in purpur.yml
+ Make sure you are in survival mode
+ Have Totem of undying in inventory but not equipped
+ Choose your method of dying

### Purpur version

[14:51:00 INFO]: Checking version, please wait...
[14:51:02 INFO]: Current: git-Purpur-1824 (MC: 1.19.2)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Use a clean server and only enable `totem-of-undying-works-in-inventory` option

**Comment by RhythmicSys** [comment]
This option has changed functionality because as of Build 1820, there are now additional permissions 
Totem in inventory now requires permission `purpur.inventory_totem`

**Comment by KioProject123** [comment]
oh ok, I didn't notice this update
