### ISSUE TITLE
Error plugin ServerBooster with Purpur

### ISSUE THREAD

**Issue by istarengwa** [pl3xgaming/Purpur#117]
**Describe the bug**
Hello, a little problem with the functioning of a plugin, this error only appears with purpur, the plugin works correctly with paper.
The Developer tells me that it comes from the getEntities function.

**To Reproduce**
the error is displayed each time each player connects

**Screenshots or Videos**
There are more screenshoots on the developer github error call, I put the link to you :

https://github.com/LoneDev6/Issues-ServerBooster/issues/33

**Plugins**
This just concerns the Servebooster plugin, with or without another plugin the error is the same.

**Version**
purpurclip-885 (1.16.4)

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
No

**Additional context**
I send the link of this error to the booster server developer hoping to find a solution with you =)

**Comment by Titaniumtown** [comment]
Don't use ServerBooster or any of those plugins that advertise that they'll speed up your server, like 99% (or even all) of those plugins have no effect, or even in some cases slow your server down even more.

**Comment by istarengwa** [comment]
This does not answer the question.

**Comment by Titaniumtown** [comment]
Also the issue isn't with Purpur, it's with Tuinity. So this issue shouldn't be reported here.

**Comment by jpenilla** [comment]
![](https://i.imgur.com/Vc8fYxw.png)

The reason Tuinity added an async catcher here is *specifically* to warn you about when plugins like the one mentioned here do something very wrong. This is a plugin issue, not a Purpur issue. This change made by Tuinity is one we agree with and will not be reverted.

The onus is on the plugin author here to fix their plugin if they want to be compatible with Tuinity based servers.

**Comment by istarengwa** [comment]
Thank you for this real constructive and explanatory response =)
