### ISSUE TITLE
Tps Drop

### ISSUE THREAD

**Issue by mrpunky** [pl3xgaming/Purpur#1178]
### Spark link

https://spark.lucko.me/C7dPu4EBwW

### Description of issue

I was using an old version I updated to the new version about 20 versions ago tps drops started to happen and I can't find the reason I need help

### Purpur version

![image](https://user-images.githubusercontent.com/101196617/199294069-c28fcf0b-614d-4b3f-9c51-0ee7cd252646.png)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
GitHub is for reporting bugs. Join our Discord for support questions.
