### ISSUE TITLE
Phantom fire time not working

### ISSUE THREAD

**Issue by MrEDok** [pl3xgaming/Purpur#118]
**Describe the bug**
Phantom firetime
Phantom:
        flames:
          fire-time: 8
entity doesnt catch fire they only take damage.

**To Reproduce**
ride phantom and spit fire on entity/player they will take damage but doesnt catch on fire

**Version**
Purpur version git-Purpur-905 (MC: 1.16.4)

**Comment by BillyGalbreath** [comment]
Confirmed. Seems I'm not actually using this value anywhere in my code. I'll have to see where and when it got lost at and add it back in
