### ISSUE TITLE
addPotionEffect() does not work as intended with Darkness

### ISSUE THREAD

**Issue by Brickgard** [pl3xgaming/Purpur#1181]
### Spark link

https://spark.lucko.me/YMnoyysEZl

### Expected behavior

The vanilla darkness effect, such as `/effect give @s darkness 15` grants the player the Skulk Shrieker's `DARKNESS` effect to the player for 15 seconds.

### Observed/Actual behavior

When Skript tries to do this, such as with:
```
command /heartbeat <player>:
    trigger:
        apply potion of darkness to arg 1 for 15 seconds
```
The client's screen goes entirely black, rather than apply the effect correctly.
![image](https://user-images.githubusercontent.com/59861581/199860598-54d5dfcb-d4c2-490c-a356-f9948cf8788c.png)

### Steps/models to reproduce

Create a fresh server running Purpur (tested builds 1752, 1800, and latest 1835), and place Skript 2.6.3 in the plugins folder.
Utilize this Skript to test the effect via the `/heartbeat <in-game player>` command:
[heartbeat.txt](https://github.com/PurpurMC/Purpur/files/9934008/heartbeat.txt)
(save as a skript in the `/plugins/Skript/scripts/` folder as `heartbeat.sk` to execute)

### Purpur version

Current: git-Purpur-1835 (MC: 1.19.2)*
Previous: git-Purpur-1752 (MC: 1.19.2)
* You are running the latest version

Also tested with Purpur-1800 and Purpur-1752 after initial latest tests failed.

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Tested with the same setup using Paper server setups had no issues; only upgrading from Paper to Purpur on various 1.19.2 builds is when this issue appeared.

Multiple users have confirmed the issue using vanilla, 1.19.2 clients with no mods, shaders or resource packs active.

Skript community has been made aware of the behavior and recommended this be explored here, as the issue is only able to be reproduced on a Purpur server and not native to Paper nor Skript itself.

**Comment by BillyGalbreath** [comment]
Unable to reproduce.

![image](https://user-images.githubusercontent.com/332527/199863382-9b574d01-29fe-44c1-9103-3c05d5ae7e71.png)

**Comment by Brickgard** [comment]
Thank you for the quick response and investigation.
However, as stated in the report, the vanilla command effect works and shows what is expected of Skript's effect; yet on Purpur specifically the effect does not function correctly.
The effect is confirmed to be functional within Skript as well as Paper 1.19.2 builds, yet not on Purpur 1.19.2 builds.
Please follow the Steps to Reproduce (install Skript 2.6.3 and utilize the included file as a simple execution test).
I can provide the plugin/configuration for testing, and/or provide access to a private dev test server to demonstrate this effect in action if necessary for validation.

**Comment by SageSphinx63920** [comment]
But script ≠ purpur
Maybe ask the script developer first

**Comment by Brickgard** [comment]
As stated in the report, the Skript team was made aware and the issue was investigated, but in tests Skript 2.6.3 functions as expected on all tested 1.19.2 Paper builds, but not on any 1.19.2 Purpur builds.
The functionality is confirmed to work within Skript in all tested environments except Purpur; so the issue was brought here to hopefully gain further insight.

**Comment by RhythmicSys** [comment]
We have one more upstream, pufferfish, was that tested as well?

**Comment by Brickgard** [comment]
> We have one more upstream, pufferfish, was that tested as well?

That's a good point, totally forgot Purpur forks Pufferfish; I can conduct tests of Pufferfish in a few hours.
Which "version" does Purpur fork from? [https://pufferfish.host/downloads](url)

**Comment by RhythmicSys** [comment]
> Which "version" does Purpur fork from? 

The first one, `Pufferfish` 

The other 2 are paid iirc

**Comment by Brickgard** [comment]
Perfect; I'll test this in Pufferfish builds and see where that lands.  Thanks for the guidance!

**Comment by MelnCat** [comment]
If this is fixed, could there be an option to revert back to the client blackouting? I'm currently using this to black out players intentionally

**Comment by Brickgard** [comment]
> If this is fixed, could there be an option to revert back to the client blackouting? I'm currently using this to black out players intentionally

Definitely a cool accidental feature; combining it with the blindness effect can make some interesting blackout effects in vanilla.  Otherwise, a font character that renders as a large black square placed as a title to players can fade to and hold a blackout even better, in case this bug doesn't become feature-ized.

**Comment by RhythmicSys** [comment]
I figure that once the cause is found, it can be turned into a feature xD

**Comment by Brickgard** [comment]
Just tested with Pufferfish 1.19.2 Build #42 and #38, and no issues were found.

**Comment by RhythmicSys** [comment]
interesting
I'll test when I get a chance (couple hours probably)

**Comment by RhythmicSys** [comment]
Can confirm, interestingly enough it didn't happen on my modded client

https://user-images.githubusercontent.com/45906780/200076645-067e36de-bd67-4d97-a8c7-721de2a88c46.mp4

**Comment by Brickgard** [comment]
> Can confirm, interestingly enough it didn't happen on my modded client

Perhaps something related to internal, vanilla shaders?
Something like that, a modded client like Lunar or Badlion might accidentally be "fixing" via something like Optifine
Just blindly spitballing here  :/
Thanks very much for the test/confirmation!

**Comment by RhythmicSys** [comment]
Yeah, client I'm using has sodium (and a ton of other visual mods so idk which one specifically fixed it)

**Comment by RhythmicSys** [comment]
Is visual weirdness specific to darkness? Or do other effects like night vis, and nausea have issues when run through skript?

**Comment by Brickgard** [comment]
> Is visual weirdness specific to darkness? Or do other effects like night vis, and nausea have issues when run through skript?

Considering Darkness was a new effect added alone in 1.19, that may be why this behavior is exclusive to it compared to other visual effects?

**Comment by MelnCat** [comment]
> Yeah, client I'm using has sodium (and a ton of other visual mods so idk which one specifically fixed it)

In sodium, only a single chunk is rendered while every other chunk is blacked out, along with all tile entities

**Comment by RhythmicSys** [comment]
Issue can be replicated with
```java
    @EventHandler
    public static void onPunch(PlayerInteractEvent event){
            PotionEffect darkness = new PotionEffect(PotionEffectType.DARKNESS, 100, 0);
            event.getPlayer().addPotionEffect(darkness);
    }
```
as well. Issue might benefit from a namechange, 'addPotionEffect() does not work as intended with the darkness effect' or something.

**Comment by Brickgard** [comment]
Confirmed in all tests, thank you so much for your patience and work with this! 🎉
