### ISSUE TITLE
LibsDisguises incompatibility - MetaIndex not found for GLOW_SQUID!

### ISSUE THREAD

**Issue by mibby** [pl3xgaming/Purpur#1185]
### Spark link

--

### Expected behavior

No LibsDisguises start-up error / incompatibility.

### Observed/Actual behavior

```
[11:00:44] [Server thread/ERROR]: [LibsDisguises] MetaIndex not found for GLOW_SQUID! Index: 17
[11:00:44] [Server thread/ERROR]: [LibsDisguises] Value: orange (class java.lang.String) (class net.minecraft.world.entity.GlowSquid) & GlowSquidWatcher
```

### Steps/models to reproduce

* Add LibsDisguises dev build to plugins folder.
https://ci.md-5.net/job/LibsDisguises/
* Add ProtocolLib dev build to plugins folder.
https://ci.dmulloy2.net/job/ProtocolLib/
* Start Purpur
https://purpurmc.org/downloads
* See error in startup log.

### Purpur version

git-Purpur-1838 (MC: 1.19.2)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

RE: https://github.com/libraryaddict/LibsDisguises/issues/675

Using Paper dev 263, LibsDisguises does not seem to have the start-up error.

Purpur dev 1838 (Paper 1.19.2)
LibsDisguises dev 1132
ProtocolLib dev 602

**Comment by encode42** [comment]
This is probably due to [Purpur's implementation of rainglow](https://github.com/PurpurMC/Purpur/blob/6e7a51e1032c976340a6be2eba65523048ccc72e/patches/server/0302-Implement-squid-colors-for-rainglow-fabric-mod.patch), which just adds an NBT value to glow squids. Not sure how it could mess with LibsDisguises though.

**Comment by libraryaddict** [comment]
.. I thought there must be a good reason that LD is having compatibility issues, only to see that purpur is adding custom mods.

Frankly, I'm leaving the error as is. It's supposed to report when metadata has been mapped incorrectly in Lib's Disguises. But Lib's Disguises isn't in the wrong here.

**Comment by BillyGalbreath** [comment]
We're not adding custom mods... We added a data watcher, and LD is tripping up on that for whatever reason. Which it probably shouldnt't, seeing as any project (plugin or server fork) can add more data watchers at will.

**Comment by libraryaddict** [comment]
1. Its a harmless error
2. You modded the server infar as that it wants a clientside mod to perform extra functions. Any server fork can do this yes
3. I don't think any plugin can do this, I believe what they do instead is extend off the entity to create a new class. Which I think LD has no problems with. You're modifying the base server files.

**Comment by BillyGalbreath** [comment]
Oh, well if it's just a harmless printerr I don't see what the fuss is about. I was under the impression there was an incompatibility which prevented LD from working as intended.
