### ISSUE TITLE
The anvil does not support hex color format

### ISSUE THREAD

**Issue by KioProject123** [pl3xgaming/Purpur#1196]
### Spark link

n/a

### Expected behavior

The anvil support hex color format

### Observed/Actual behavior

Recent updates result in the anvil does not support hex color format

### Steps/models to reproduce

Can restore this behavior with a simple line of code
`name = name.replaceAll("(?i)&#([0-9a-f])([0-9a-f])([0-9a-f])([0-9a-f])([0-9a-f])([0-9a-f])", "\u00a7x\u00a7$1\u00a7$2\u00a7$3\u00a7$4\u00a7$5\u00a7$6");`

### Purpur version

Current: git-Purpur-"e42555c" (MC: 1.19.2)*
I'm using my own build, but I don't know how to edit and push the patch, so I can only submit it in this way:)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Enable minimessage for hex support

**Comment by KioProject123** [comment]
> Enable minimessage for hex support

Minimessage will bypass `purpur.anvil.format` permission，there is no way to allow hex colors and prevent players from using font styles

**Comment by BillyGalbreath** [comment]
Yes, minimessage is recently incompatible with legacy color codes. The Paper team is pushing hard against legacy color codes and are actively breaking everyone's workflows because of it.
