### ISSUE TITLE
Leashed horses will cause serious performance issues

### ISSUE THREAD

**Issue by KioProject123** [pl3xgaming/Purpur#1198]
### Spark link

https://spark.lucko.me/HgEfAIJk5y

### Expected behavior

Leashed horses do not cause serious performance issues

### Observed/Actual behavior

In certain cases, Leashed horses will cause serious performance issues
Other animals probably do too, but it's not as obvious

### Steps/models to reproduce

Use the default configuration file
1. Facing west (other orientations are not acceptable)
2. Place blocks as shown in the figure below, and put the horse on the same position, and hitch it
3. View mspt performance usage
![4MTQ7) S5HR$@%~4HTIN2J7](https://user-images.githubusercontent.com/61594596/203413692-65dbf6e2-69d4-4ead-9a2c-31fe48258f33.png)
Same map file: [world.zip](https://github.com/PurpurMC/Purpur/files/10070839/world.zip)

### Purpur version

Current: git-Purpur-1848 (MC: 1.19.2)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I didn't test on Paper because it doesn't have tpsbar.

**Comment by BillyGalbreath** [comment]
> I didn't test on Paper because it doesn't have tpsbar.

They have `/tps` and `/mspt` commands that are just as efficient.

**Comment by KioProject123** [comment]
> > I didn't test on Paper because it doesn't have tpsbar.
> 
> They have `/tps` and `/mspt` commands that are just as efficient.

OK, I tested the same problem on Paper. I'll feed back to them
