### ISSUE TITLE
Llama ridable

### ISSUE THREAD

**Issue by x1p** [pl3xgaming/Purpur#12]
**Describe the feature**
A llama can be ridden. However it's mojangs logic to not be able to control/steer the llama where it's going. Wouldn't it be nice if the llama can be steered just like other ridable mobs? Then those animals would be of any use :-)

I really like Purpur. It's the best of both worlds
Keep up the good work :+1:

**Comment by BillyGalbreath** [comment]
Llama are now controllable, but they are required to be tamed and saddled (with carpet).

The trader llama has also been made mountable, but still has to go through the taming process. Being saddled with a carpet is _not_ a requirement for the trader llama since it technically always has a carpet ;)

**Comment by x1p** [comment]
Thank you.
I quickly tested it.
Without permissions and `ridable: false` the behavior is now that you get a message `You can't enter this vehicle!`. So this sort of breaks vanilla behavior.

**Comment by BillyGalbreath** [comment]
> Thank you.
> I quickly tested it.
> Without permissions and `ridable: false` the behavior is now that you get a message `You can't enter this vehicle!`. So this sort of breaks vanilla behavior, right?

Unable to reproduce. That message isn't part of Purpur, so you likely have a plugin that's doing something there

**Comment by x1p** [comment]
Ah yes, I forgot a plugin's stupid default option

**Comment by ZoruaFox** [comment]
> Ah yes, I forgot a plugin's stupid default option

Sorry to bother you, but I encountered the same problem as you did, I'm wondering which plugin caused this, thank you!

**Comment by x1p** [comment]
Oh geez, that was a looong time ago :)
If my memory serves me right, I believe it was a the plugin "IllegalStack" and the option was something about minecarts.

If you have a test server, try adding plugins one by one to see which one does it.

**Comment by ZoruaFox** [comment]
Thanks a lot!!
I eventually discovered that an anticheat plugin on my server caused this XD






---Original---
From: ***@***.***&gt;
Date: Fri, Aug 16, 2024 15:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PurpurMC/Purpur] Llama ridable (#12)




 
Oh geez, that was a looong time ago :)
 If my memory serves me right, I believe it was a the plugin "IllegalStack" and the option was something about minecarts.
 
If you have a test server, try adding plugins one by one to see which one does it.
