### ISSUE TITLE
InventoryClickEvent inconsistencies in survival player inventory

### ISSUE THREAD

**Issue by ShiftingKill** [pl3xgaming/Purpur#1214]
### Spark link

https://spark.lucko.me/ApEhezcWpU

### Expected behavior

The `PlayerInventory` clicked at a slot (like in hotbar) should be able to `setItem(slotClicked, itemStack)` and we should see an `ItemStack` (say from `onCursor()`) appear in the inventory at the slot clicked (in this case I am right clicking to drop off a custom item) in the hotbar.

### Observed/Actual behavior

The inventory clicked does not always match the inventory actually clicked and the hotbar setItem() ends up setting items in the armor slots or shield slots. But `addItem()` still adds to the player inventory and can be used.

### Steps/models to reproduce

In an InventoryClickEvent event handler put this:
```
Player player = (Player) event.getWhoClicked();
Inventory clickedInventory = event.getClickedInventory();
if (clickedInventory != null) {
    clickedInventory.setItem(event.getRawSlot(), onCursor);
    player.setItemOnCursor(clicked);
    event.setCancelled(true);
}
```
getRawSlot() and getSlot() I tested both of and they are always the same.

### Purpur version

Current: git-Purpur-1861 (MC: 1.19.3)*
Previous: git-Paper-303 (MC: 1.19.2)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Are you able to recreate this upstream?

**Comment by ShiftingKill** [comment]
Using setCurrentItem() works a charm and this may not be an issue at all. The methods `getRawSlot()` and `getSlot()` were confusing me and this may not be an issue at all. It is impossible to tell with the changing player inventory (do they have crafting table open, looking elsewhere) to use raw slot numbers and `inventory.setitem(slot, item)` and get consistent results across the wide variety of inventories the player can have open. `setCurrentItem()` flawlessly sets items at the slot clicked, and can check if they are in an armor by checking the `SlotType`. My bad.
