### ISSUE TITLE
buried_treasure, mineshaft config still exists (overlap option)

### ISSUE THREAD

**Issue by Pantera07** [pl3xgaming/Purpur#1223]
### Spark link

(Not required for this issue)

### Expected behavior

https://github.com/PaperMC/Paper/pull/8030
There are already `seed-buriedtreasure` and `seed-mineshaft` configs on spigot.yml.
![2](https://user-images.githubusercontent.com/89838384/208843510-95bb1799-409a-4efd-98c6-97d3f3fb5811.png)

### Observed/Actual behavior

There are `buried_treasure` and `mineshaft` config on purpur.yml. (overlap option)
![1](https://user-images.githubusercontent.com/89838384/208843056-e55f62aa-2ee9-4169-9a4a-3a8647756593.png)

### Steps/models to reproduce

Run purpur.

### Purpur version

[16:12:27 INFO]: Checking version, please wait...
[16:12:27 INFO]: Current: git-Purpur-1876 (MC: 1.19.3)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Cool. About time upstream added _all_ the seeds. One less patch we have to maintain now.

**Comment by encode42** [comment]
Closed by dad13788adeaffbfcd91f0a9b0f1c3765d0d93b7.
