### ISSUE TITLE
Camel speed & health bug

### ISSUE THREAD

**Issue by Pantera07** [pl3xgaming/Purpur#1224]
### Spark link

https://spark.lucko.me/D7COpDgprB

### Expected behavior

The camel speed bug doesn't happen on vanilla, spigot, paper, or pufferfish.
https://youtu.be/zGgMiQHj0SE

### Observed/Actual behavior

Camel speed bug occurs on purpur.
https://youtu.be/Id8v4f9YSP8

### Steps/models to reproduce

1. Spawns a camel with a spawn egg.
2. Hit the camel

### Purpur version

[16:12:27 INFO]: Checking version, please wait...
[16:12:27 INFO]: Current: git-Purpur-1876 (MC: 1.19.3)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by Pantera07** [comment]
Purpur breaks the camel's `max_health`, `movement_speed`.
(`jump_strength` may also be broken.)

This bug may be related to that patch.
https://github.com/PurpurMC/Purpur/blob/ver/1.19.3/patches/server/0009-Configurable-entity-base-attributes.patch

**Comment by Pantera07** [comment]
According to my tests, camels spawned by pupur have `movement_speed` 2-3 times that of camels spawned by pufferfish, and camels spawned by purpur have `max_health` not 32.0

**Comment by Pantera07** [comment]
Camels appear to have horse attributes. (NBT Corruption)
A camel with a corrupted NBT is not fixed by converting the jar to paper or pufferfish.

**Comment by encode42** [comment]
The issue is that Purpur adds these attributes in the `AbstractHorse` class, which is extended by horses, donkeys, and for some reason, camels. This should be an easy fix.

**Comment by Pantera07** [comment]
> The issue is that Purpur adds these attributes in the `AbstractHorse` class, which is extended by horses, donkeys, and for some reason, camels. This should be an easy fix.

I hope this problem will be fixed.
