### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Zoleeee** [pl3xgaming/Purpur#1226]
### Spark link

https://spark.lucko.me/syaMmWzAtt

### Stack trace

https://paste.gg/p/anonymous/faa1e2ab5c574969a0082a17e4ae302a

### Actions to reproduce (if known)

Szerver crash, but there is not crash report.  The server is hosting in apex.

### Purpur version

Current: git-Purpur-1835 (MC: 1.19.2)*
Previous: git-Paper-256 (MC: 1.19.2)
* You are 23 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by JanTuck** [comment]
Not gonna comment on the issue itself, but you did include quite a few ips and no stacktrace with that log.
