### ISSUE TITLE
Strongholds not registering on worlds generated & preloaded on 1.19.2

### ISSUE THREAD

**Issue by alfredcort** [pl3xgaming/Purpur#1227]
### Spark link

https://spark.lucko.me/3dHVRJJbkW

### Expected behavior

I expected players to be able to use functioning eye of enders & the _/locate structure stronghold_ command to work.

### Observed/Actual behavior

Eye of enders are completely non-functioning and so is the _/locate structure stronghold_ command.

My guess this is due to me having a world border, due to 1.19.3 using new stronghold generation it's not finding any 'new' strongholds, also not registering my old stronghold, therefor thinking that there are NO strongholds on the server.

I have also pre-loaded my world (20k x 20k) which means it's not possible to load any new strongholds with 1.19.3 generation.

### Steps/models to reproduce

I've tried reproducing this with the base Spigot jar and don't run into this issue. Once reproducing with Purpur I run into this issue.

Reproduction steps:
1) Pre-generate a world on 1.19.2.
2) Set a world border.
2) Upgrade to 1.19.3.

### Purpur version

<img width="654" alt="Screenshot 2022-12-22 at 22 29 48" src="https://user-images.githubusercontent.com/72607588/209229651-12efbac6-e4e6-4e6e-a65c-bb7248e3c5fa.png">

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Vanilla issue.

See comments where someone reported same thing to Paper: https://github.com/PaperMC/Paper/issues/8692

**Comment by Pantera07** [comment]
Plugin that help solve this issue:
https://www.spigotmc.org/resources/ender-eye-target-changer.82263/
