### ISSUE TITLE
Feature Request: Configureable vanilla movement checks.

### ISSUE THREAD

**Issue by gerome1812** [pl3xgaming/Purpur#123]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated with the vanilla movement checks. They are inconsistant, especially for players with higher latency or when using boats on ice/piston bolts. It is constantly spamming my console with warnings about moving too quickly/wrongly. Whitelisted server so client modification is no issue.

**Describe the solution you'd like**
I would like to be able to disable the vanilla movement checks

**Describe alternatives you've considered**
I have concidered writing a plugin to do this, although have never used nms so at this time is a bit out of my reach. I have also found [trusted-server](https://github.com/gnembon/trusted-server), a mod for fabric that accomplishes this same thing. I however do not use fabric, I use purpur.

This got denied from paper, completely understandably, so I thought it might be accepted here.

**Comment by BillyGalbreath** [comment]
In paper's ticket you mentioned you set the modifiers higher in spigot.yml? What values did you put, because setting them to 2000000 work for me
