### ISSUE TITLE
paperMC sand dupe end portal

### ISSUE THREAD

**Issue by ItsDaann** [pl3xgaming/Purpur#1238]
### Spark link

what is a spark link

### Expected behavior

wanted sand dupe to work but there is a patch

### Observed/Actual behavior

the sand fell down and doesnt go with the pistons

### Steps/models to reproduce

https://www.youtube.com/watch?v=dOQjmQO1BHc&t

### Purpur version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version

### Agreements

- [x] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [ ] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] My version of Minecraft is supported by Purpur.

**Comment by encode42** [comment]
https://purpurmc.org/docs/Configuration/#safe-teleporting
