### ISSUE TITLE
Leaves killing performance and crashing server.

### ISSUE THREAD

**Issue by jacklollz2** [pl3xgaming/Purpur#1242]
### Spark link

Spark couldn't be generated due to the crashes.

### Description of issue

A large amount of leaves are aggressively killing the performance of the server.
Setting leaves to persistent stopped the crashing.

### Purpur version

git-Purpur-1883 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

[crash-2023-01-04_14.55.13-server.txt](https://github.com/PurpurMC/Purpur/files/10353509/crash-2023-01-04_14.55.13-server.txt)
[crash-2023-01-04_14.59.46-server.txt](https://github.com/PurpurMC/Purpur/files/10353510/crash-2023-01-04_14.59.46-server.txt)
[crash-2023-01-04_15.22.06-server.txt](https://github.com/PurpurMC/Purpur/files/10353511/crash-2023-01-04_15.22.06-server.txt)
[crash-2023-01-04_15.27.14-server.txt](https://github.com/PurpurMC/Purpur/files/10353512/crash-2023-01-04_15.27.14-server.txt)
[crash-2023-01-04_15.43.36-server.txt](https://github.com/PurpurMC/Purpur/files/10353513/crash-2023-01-04_15.43.36-server.txt)
[crash-2023-01-04_16.16.34-server.txt](https://github.com/PurpurMC/Purpur/files/10353514/crash-2023-01-04_16.16.34-server.txt)
[crash-2023-01-04_16.35.15-server.txt](https://github.com/PurpurMC/Purpur/files/10353515/crash-2023-01-04_16.35.15-server.txt)
[crash-2023-01-04_16.43.05-server.txt](https://github.com/PurpurMC/Purpur/files/10353516/crash-2023-01-04_16.43.05-server.txt)
[crash-2023-01-04_16.54.47-server.txt](https://github.com/PurpurMC/Purpur/files/10353517/crash-2023-01-04_16.54.47-server.txt)
Purpur 1884 tested as well, same results.

**Comment by Slackadays** [comment]
That's a lot of plugins, have you tried a binary search of all the plugins to make sure it's one of them and not Purpur?

**Comment by jacklollz2** [comment]
> That's a lot of plugins, have you tried a binary search of all the plugins to make sure it's one of them and not Purpur?

Yes, the plugins are not the cause, ran vanilla, performance still dropped.
The FAWE interactions are when I summon the leaves.

**Comment by lele92007** [comment]
1. use java 17
2. what kind of weirdo are you to run a server on win11 ?
3. use aikar's flags for big amounts of ram

**Comment by jacklollz2** [comment]
> 1. use java 17
> 2. what kind of weirdo are you to run a server on win11 ?
> 3. use aikar's flags for big amounts of ram

1. I won't be downgrading my Java, I've been using the most recent builds of Temurin for years for production servers. It runs extremely well on RHEL ARM.
2. The server was executed on Windows 11 for diagnostic reasons, explicitly to provide this bug report.
3. Aikars flags are enabled except for the same Xmn and Xmx.
4. Sub point: Aikars flags are not great, the latest Ryzen 9 7590x, the G1GC isn't as efficient as ZGC. ZGC runs almost 3 times as fast on the 7950x.

**Comment by lele92007** [comment]
>1. I won't be downgrading my Java, I've been using the most recent builds of Temurin for years for production servers. It runs extremely well on RHEL ARM.

i've had lots of compatibility issues with java 19 for latest mc versions, so a least test with java 17
>2. The server was executed on Windows 11 for diagnostic reasons, explicitly to provide this bug report.

great
>3. Aikars flags are enabled except for the same Xmn and Xmx.

Xmn is useless, and having Xms=Xmx is the WHOLE POINT of aikar's flags, and a big part of the stability and perf uplift comes from that
>4. Sub point: Aikars flags are not great, the latest Ryzen 9 7590x, the G1GC isn't as efficient as ZGC. ZGC runs almost 3 times as fast on the 7950x.

yes and no
ZGC or Shenadoah are probably going to perform better, but they will use wayyyy more cpu power for the same result, since gc isn't going to run very often anyways

**Comment by jacklollz2** [comment]
> > 1. I won't be downgrading my Java, I've been using the most recent builds of Temurin for years for production servers. It runs extremely well on RHEL ARM.
> 
> i've had lots of compatibility issues with java 19 for latest mc versions, so a least test with java 17
> 
> > 2. The server was executed on Windows 11 for diagnostic reasons, explicitly to provide this bug report.
> 
> great
> 
> > 3. Aikars flags are enabled except for the same Xmn and Xmx.
> 
> Xmn is useless, and having Xms=Xmx is the WHOLE POINT of aikar's flags, and a big part of the stability and perf uplift comes from that
> 
> > 4. Sub point: Aikars flags are not great, the latest Ryzen 9 7590x, the G1GC isn't as efficient as ZGC. ZGC runs almost 3 times as fast on the 7950x.
> 
> yes and no ZGC or Shenadoah are probably going to perform better, but they will use wayyyy more cpu power for the same result, since gc isn't going to run very often anyways

Compatibility is irrelevant: Leaves are causing this. I have been using Temurin 19 when it first released and never had crashing problems due to it, until now when I tested the performance of leaf decay.

I had different memory values to test population of the memory and seeing if its the performance of populating dimms, which is not the cause.

"Yes and no" is irrelevant: My production servers run faster with ZGC, average player count 200 with a view distance of 32 server TPS never drops below 19.7.

The leaf decay is a serious performance issue and your responses are absolutely useless and unhelpful.

**Comment by lele92007** [comment]
yea let's get back to the main thing
you say it crashes in vanilla, could you send a vanilla crash report ?

**Comment by jacklollz2** [comment]
> yea let's get back to the main thing you say it crashes in vanilla, could you send a vanilla crash report ?

Vanilla? No, pluginless.
I can only trigger the crash when writing aggressively with FAWE
//replacenear 250 air birch_leaves
/gamerule randomTickSpeed 1000
The performance is still extremely slow with or without plugins, and even in the vanilla server.
This bug report is suggested to purpur to optimize leaf decay, pufferfish may be able to release a custom leaf decay optimization, I'm not sure.

**Comment by lele92007** [comment]
at that point you are just trying to crash your server
i'm surprised that it does this instead of just hanging and getting killed by watchdog

**Comment by jacklollz2** [comment]
> at that point you are just trying to crash your server i'm surprised that it does this instead of just hanging and getting killed by watchdog

Yes, and?
I can benchmark numerous other things, nothing remotely causes as much performance problems like leaves do.

**Comment by YouHaveTrouble** [comment]
> I won't be downgrading my Java, I've been using the most recent builds of Temurin for years for production servers. It runs extremely well on RHEL ARM.

only java 17 is supported by us.

> /gamerule randomTickSpeed 1000

so basically setting random tick speed into overdrive, that kills any server. If you have issues with values that high, then *reduce it*

> I can only trigger the crash when writing aggressively with FAWE

so you're trying to crash the server and are confused that it's crashing?

I'm closing this before it gets out of control.
