### ISSUE TITLE
Anvil and Sign colors not working 

### ISSUE THREAD

**Issue by 11robert11** [pl3xgaming/Purpur#1243]
### Spark link

https://spark.lucko.me/gHhcwPdmpb

### Expected behavior

Signs with color codes will have colored text and items renamed in anvils with color codes will have colored text.

### Observed/Actual behavior

Renaming items to a name with a color code dose not change the text color with an anvil. Typing color codes into a sign works while in the sign gui and if your able to see the sign while in the gui (flying then placing a sign so the sign is not covered by its gui) it works until you exit the gui where the sign's text reverts to plain text.

### Steps/models to reproduce

enable sign colors and anvil colors. Try entering a colored text into an anvil or sign. 

### Purpur version

Current: git-Purpur-1884 (MC: 1.19.3)*
Previous: git-Purpur-1882 (MC: 1.19.3)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

[Video demonstation](https://youtu.be/icyORvD1i2w)

**Comment by encode42** [comment]
Have you given players the respective permissions to use formatting, colors, etc. on anvils and/or signs?

**Comment by 11robert11** [comment]
I've tried as op, using luckperms setting purpur.sign.* and purpur.anvil.* set to true and the permissions.yml

**Comment by encode42** [comment]
None of those are valid permission nodes for Purpur. OP != all permissions.

<https://purpurmc.org/docs/Permissions/>

**Comment by 11robert11** [comment]
After reading that I fixed my issue, thanks.
