### ISSUE TITLE
Purpur icon not showing in icon tray

### ISSUE THREAD

**Issue by Dueris** [pl3xgaming/Purpur#1248]
### Spark link

fhttps://spark.lucko.me/docs/Command-Usage

### Expected behavior

It shows the purpur logo

### Observed/Actual behavior

It is showing the paper server icon instead. This is not a neccassary change, just thought it should be noted

### Steps/models to reproduce

Startup Minecraft Server with gui

### Purpur version

Current: agit-Purpur-1892 (MC: 1.19.3)*r
7Previous: git-Purpur-1888 (MC: 1.19.3)r
a* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by SageSphinx63920** [comment]
I can reproduce this issue. Maybe some patch was missed when updating to 1.19.3
