### ISSUE TITLE
Very low tps

### ISSUE THREAD

**Issue by Zoleeee** [pl3xgaming/Purpur#1251]
### Spark link

https://spark.lucko.me/Blga9R5vOe

### Description of issue

Very low fps and we can't figure out what's causing it.

### Purpur version

Current: git-Purpur-1835 (MC: 1.19.2)*
Previous: git-Paper-256 (MC: 1.19.2)
* You are 23 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by ImNotStable** [comment]
FPS or TPS?

**Comment by matipoirierg** [comment]
remove lag assist and add an entity limiter, also villagers and spawners are killing your performance

**Comment by SageSphinx63920** [comment]
So 1. TPS and FPS are two compeltly different things; 2. You dont match the first requirement here update 1.19.3 and @matipoirierg said some good things

**Comment by Zoleeee** [comment]
> FPS or TPS?

tps

**Comment by encode42** [comment]
GitHub is for reporting bugs. Join our Discord for support questions.
