### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WMGameLive** [pl3xgaming/Purpur#1253]
### Spark link

https://spark.lucko.me/Uf5Qz5PGIg

### Stack trace

---
https://paste.website/p/b636810c-3039-42f5-99a3-fd97f55ebcdd.txt
---

### Actions to reproduce (if known)

I don't know.

### Purpur version

> version
[19:16:39 INFO]: Current: git-Purpur-1894 (MC: 1.19.3)*
Previous: git-Purpur-1882 (MC: 1.19.3)
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I know I am not using the latest version, but it just 1 version behind.
According to the crash report, it seems to be related to chunk issue, but I don't see any chunk system changed in recent updates of paper or purpur. If latest version already fix it, please let me know.

**Comment by JanTuck** [comment]
As a general rule trying the newest version before submitting an issue report is preferred.

**Comment by WMGameLive** [comment]
> As a general rule trying the newest version before submitting an issue report is preferred.

I don't know how to reproduce this issue, so even if I update to the newest version, I have no way of knowing whether it is fixed or not. I already updated my server, I just want to report a possible potential bug, the reason is mentioned above. if this is really not allowed, please close it.

**Comment by granny** [comment]
Closing as it's not on the latest build version, which is one of the agreements you check off when submitting an issue.

If it continues to occur on the latest build of Purpur, then all I can say is that we don't really touch anything related to chunks. In that situation it's most likely either a Paper or Airplane bug.
