### ISSUE TITLE
Server keeps crashing some times

### ISSUE THREAD

**Issue by LcyDev** [pl3xgaming/Purpur#1257]
### Spark link

https://spark.lucko.me/uPXxNWrvVR

### Stack trace

https://paste.gg/p/ConaII_/b8a1e33025234bfcaead88cd873b2444

### Actions to reproduce (if known)

*N/A*

### Purpur version

Current: git-Purpur-1905 (MC: 1.19.3)*
Previous: git-Purpur-1900 (MC: 1.19.3)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
> `Running: Purpur version git-Purpur-1894 (MC: 1.19.3)` in Stack trace

The "I am running the latest version of Purpur available from https://purpurmc.org/downloads." agreement is there for a reason.

**Comment by LcyDev** [comment]
Oh yeah surely it totally was fixed :)
