### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WMGameLive** [pl3xgaming/Purpur#1258]
### Spark link

https://spark.lucko.me/i2epbSLqNY

### Stack trace

```
https://paste.gg/p/anonymous/01d32961e3ae47f980707063198dd543
```

### Actions to reproduce (if known)

idk

### Purpur version

[23:19:35 INFO]: Checking version, please wait...
[23:19:35 INFO]: Current: git-Purpur-1905 (MC: 1.19.3)*
Previous: git-Purpur-1900 (MC: 1.19.3)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I updated to latest version of purpur and still crash, it already crashed 3 times.

**Comment by granny** [comment]
Nothing in that stack trace tells me that it's a Purpur issue. If you can reproduce on Paper then bring it up to them.

**Comment by WMGameLive** [comment]
lol
Paper said it is Purpur issue, and Purpur said it is Paper issue, no one wants to admit it, waste my time.

**Comment by granny** [comment]
I said "If you can reproduce on Paper then bring it up to them." You never attempted to do that. 

Also, it was brought up that "something is messing with internals off the main thread", so that's your lead. It's most likely a plugin issue and has nothing to do with the server software.
