### ISSUE TITLE
Feature Request: Feather falling V

### ISSUE THREAD

**Issue by Titaniumtown** [pl3xgaming/Purpur#126]
Could someone add the ability to create Feather Falling V in survival? Feather falling V would remove all fall damage. Thanks!

**Comment by Decme** [comment]
Hold up. I'd very much like to have feather falling 5 yes, but not if it removed all fall damage. It should merely allow falling somewhat further than ff4 before taking damage.

**Comment by Titaniumtown** [comment]
According to the formula that feather falling uses to calculate fall damage, feather falling V would remove all fall damage.

**Comment by BillyGalbreath** [comment]
See my [reply](https://github.com/pl3xgaming/Purpur/issues/128#issuecomment-751462683) to datsanakas.

**Comment by Decme** [comment]
I wish you would reconsider, feather falling 5 (one that increases fall distance allowed before taking damage, not one that eliminates all fall damage) is something I'd very much like to have before starting my new Amplified world. Blocking a feature based on balance alone when said feature is optional anyway seems very limiting.

**Comment by kevindwitama** [comment]
The issue in this case appears to be less of balance, and more of it actually being unfeasible.

> We did [have this](https://github.com/pl3xgaming/Purpur/blob/ver/1.15/patches/server/0103-Configurable-enchantment-max-level.patch) for a short while. It was found to break most enchantments, though, so was removed

This is the reply that was previously referred to.
