### ISSUE TITLE
Server Crash from Turtle Eggs

### ISSUE THREAD

**Issue by kohlerpop1** [pl3xgaming/Purpur#1261]
### Spark link

https://spark.lucko.me/gbNLuSyl1X

### Stack trace

```
https://paste.gg/p/anonymous/37f543d866644c16bc49a6bf8fcf7829
```

### Actions to reproduce (if known)

Join world, immediately crashes!

### Purpur version

[16:32:39 INFO]: Checking version, please wait...
[16:32:39 INFO]: Current: git-Purpur-1905 (MC: 1.19.3)*
Previous: git-Purpur-1900 (MC: 1.19.3)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by encode42** [comment]
You have `random-tick-crack-chance` set to `-1` in Purpur's config. This is not a valid value, causing the game to throw an error. Set this to a positive value, as mentioned in the stacktrace. (default: `500`)
