### ISSUE TITLE
Server crashes when you level up a cartographer villager

### ISSUE THREAD

**Issue by itsBeaco** [pl3xgaming/Purpur#1266]
### Spark link

https://spark.lucko.me/bCfGtDwHfa

### Stack trace

```
https://paste.gg/p/anonymous/886439fc704244d3991d4099726df64f
```

### Actions to reproduce (if known)

Level up a cartographer villager

### Purpur version

Current: git-Purpur-1912 (MC: 1.19.3)*
Previous: git-Purpur-1895 (MC: 1.19.3)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

Apologies if this isn't Purpur related, I just can't see any plugins referenced during the crash so your help would be amazing. Thank you in advance.

**Comment by encode42** [comment]
This would be due to the villager's treasure map trade attempting to find the nearest treasure, and failing.

It's recommended to [disable treasure maps outright](https://docs.papermc.io/paper/reference/world-configuration#treasure-maps).

**Comment by itsBeaco** [comment]
Thank you for the quick response, that has solved the issues. I appreciate your help!
