### ISSUE TITLE
Feature Request: Blood Particles

### ISSUE THREAD

**Issue by ghost** [pl3xgaming/Purpur#127]
Whenever hitting a player or entity display redstone block break particles.

With the options to only work on players and to only work on death.

Perhaps even the ability to choose the particles.

**Comment by BillyGalbreath** [comment]
Something like this would be better suited as a plugin. Might I suggest something like [DeathEffects](https://www.spigotmc.org/resources/deatheffects-%E2%9C%B4-54-epic-particle-death-effects-%E2%9C%B4.65850/)?
