### ISSUE TITLE
can't remove a specific item from my inventory

### ISSUE THREAD

**Issue by diznover** [pl3xgaming/Purpur#1271]
### Spark link

it doesn't matter

### Expected behavior

when I or trough console run this command `/clear @a minecraft:white_wool` it would clear from all players inventories white wool

### Observed/Actual behavior

It does not delete items and writes to the chat  `could not find player @a` and `could not find player minecraft:white_wool`

### Steps/models to reproduce

write on purpur server `/clear @a minecraft:white_wool` with white wool and other items, or without any items, in your inventory

### Purpur version

Current: git-Purpur-1916 (MC: 1.19.3)*
Previous: git-Purpur-1913 (MC: 1.19.3)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
When a vanilla command is supposed to support entity selectors but it treats them as a player name, this is a strong sign that the command has been overridden by a plugin.

Try using the vanilla `minecraft` namespace in your command to ensure you are running the vanilla command, and not some plugin command.

```
/minecraft:clear @a minecraft:white_wool
```

**Comment by diznover** [comment]
Yes, it works now, I didn't install plugins for custom commands, thank you very much.

**Comment by diznover** [comment]
If someone has the same error, here the plugins I used
![изображение](https://user-images.githubusercontent.com/96264775/219954957-c0f3c766-38e2-4a78-8a40-e558c98b22ef.png)

**Comment by diznover** [comment]
I found what the error is, the minepacks plugin rewrites the clear command, if you want clear to work as it should, change it to false in the config
```
InventoryManagement:
  ClearCommand:
    # If enabled the plugin provides an inventory clear command that keeps the backpack item.
    Enabled: false
```
