### ISSUE TITLE
Corrupted player data file

### ISSUE THREAD

**Issue by Sebo-sudo** [pl3xgaming/Purpur#1272]
### Spark link

https://spark.lucko.me/1nDiyVEkBz

### Stack trace

https://paste.gg/p/anonymous/d7ee4759cd64470a846b447274510d89

### Purpur version

Current: git-Purpur-1919 (MC: 1.19.3)*
Previous: git-Purpur-1918 (MC: 1.19.3)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
> ```
> at me.roinujnosde.titansbattle.dao.ConfigurationDao.loadConfigurations(ConfigurationDao.java:42) ~[TitansBattle-6.2.0.
> at me.roinujnosde.titansbattle.dao.ConfigurationDao.<init>(ConfigurationDao.java:28) ~[TitansBattle-6.2.0.
> at me.roinujnosde.titansbattle.TitansBattle.onEnable(TitansBattle.java:80) ~[TitansBattle-6.2.0.jar:?]
> ```

This is a plugin issue, more specifically an issue with the `TitansBattle` plugin.
