### ISSUE TITLE
1.19.3 - Chat messages are sent in chat even tho they shouldn't be

### ISSUE THREAD

**Issue by Yertled** [pl3xgaming/Purpur#1274]
### Spark link

no

### Expected behavior

For example, with a plugin that I can either create Item names, Item Lore, Hologram text, etc. 
I type in chat what I want the text to say, and it creates it in X plugin.

But after recent purpur updates, it now sends the message in chat, even tho the text should not be sent.

Scenarion: 
I open CMI (Essentials plugin), I make a hologram. I type the hologram name in chat. The hologram gets created with the text I put in the chat.
But the chat should not be sent to the server, just the plugin.
But it gets sent to the whole server, as a chat.
This is happening with EVERY plugin I have on the server.

Small example list:
CMI
Lands
ExecutableItems

### Observed/Actual behavior

Read above

### Steps/models to reproduce

Read above

### Purpur version

[21:42:02 INFO]: Checking version, please wait...
[21:42:02 INFO]: Current: git-Purpur-1924 (MC: 1.19.3)*
Previous: git-Purpur-1921 (MC: 1.19.3)
* You are running the latest version
THAT IS ON THE SERVERS ITS NOT WORKING ^

[21:42:54 INFO]: Current: git-Purpur-1908 (MC: 1.19.3)*
Previous: git-Purpur-1894 (MC: 1.19.3)
* You are 16 version(s) behind
Download the new version at: https://purpurmc.org/downloads
WORKING ^

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by SrBedrock** [comment]
Problem seems to be upstream https://github.com/PaperMC/Paper/issues/8911

**Comment by encode42** [comment]
Indeed it is. They're working on it!
