### ISSUE TITLE
Unable to connect to the server if the nickname is Cyrillic

### ISSUE THREAD

**Issue by Sitmobedaf** [pl3xgaming/Purpur#1288]
### Spark link

https://spark.lucko.me/648VGmvU8s

### Expected behavior

I change the value of username-valid-characters to add the required range of letters, but it does nothing. Also, if you leave the field empty, then I can still log in with a nickname of Latin letters and numbers

### Observed/Actual behavior

^[a-zA-Z0-9_.]*$ - Default
->
^[a-zA-Zа-яА-Я0-9_.]*$ - Nothing changes
->
empty - Nothing changes

### Steps/models to reproduce

...

### Purpur version

1.19.3 (1933)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

[22:40:39] [Server thread/INFO]: /127.0.0.1:63690 lost connection: Internal Exception: java.lang.IllegalStateException: Invalid characters in username

**Comment by encode42** [comment]
> The game has character limitations for many things. The option for usernames we added is for things like geyser where some server owners use a different prefix [...]. It doesn't mean you can use literally anything you want there. You have to stay within the limits of the game itself

\- BillyGalbreath, the Discord server

<sub>also, you ticked all the boxes without actually reading them!</sub>
