### ISSUE TITLE
how to enable dup tnt?

### ISSUE THREAD

**Issue by elai-nya** [pl3xgaming/Purpur#1289]
### Spark link

I don't know what this is.

### Expected behavior

how to enable dup tnt?

### Observed/Actual behavior

~

### Steps/models to reproduce

~

### Purpur version

Current: git-Purpur-1858 (MC: 1.19.2)*
Previous: git-Purpur-1854 (MC: 1.19.2)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by encode42** [comment]
https://docs.papermc.io/paper/reference/global-configuration#allow-piston-duplication

Spark links are *required* to provide support.

Your version of Minecraft is *not* supported by Purpur.

And issues are *not* used for support or questions, the Discord server exists for that.
