### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by pan90** [pl3xgaming/Purpur#1291]
### Spark link

https://spark.lucko.me/KGVfjfpZ8m

### Expected behavior

When I tried to enter the game, I couldn't access the server because it crashed. I analyzed the relevant server logs. While it may not be a purpur bug, I don't think it's a plug-in bug. I have no way, so I decide to submit relevant logs to you.

[2023-03-19-1.log](https://github.com/PurpurMC/Purpur/files/11010066/2023-03-19-1.log)

### Observed/Actual behavior

No one was on the server at that time, and I didn't find out until I couldn't access the server.

### Steps/models to reproduce

I looked at the error log and found a villager who was in a breeder within loading range of the birth point.

### Purpur version

> version
[10:39:25 INFO]: Checking version, please wait...
[10:39:26 INFO]: Current: git-Purpur-1933 (MC: 1.19.3)*
Previous: git-Purpur-1926 (MC: 1.19.3)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
Watchdog killed the server since the server failed to respond for 10 seconds. This is neither a bug or a crash, so feel free to join our Discord server for help diagnosing your server issues: https://purpurmc.org/discord
