### ISSUE TITLE
Infinite disc duplication with jukebox + hopper

### ISSUE THREAD

**Issue by sofianedjerbi** [pl3xgaming/Purpur#1296]
### Spark link

https://spark.lucko.me/yEIAbjNd8W

### Expected behavior

After a jukebox has finished playing, only a single disc should be placed in the hopper.

### Observed/Actual behavior

After a jukebox has finished playing, an infinite amount of discs are placed into the hopper.

### Steps/models to reproduce

Place a jukebox with a hopper underneath.
Use any disc on the jukebox (stal works for me).
![https://i.ibb.co/QCTzqq4/image.png](https://i.ibb.co/QCTzqq4/image.png)
At the end of the music, the hopper is full.
![https://i.ibb.co/64Y89Qf/image.png](https://i.ibb.co/64Y89Qf/image.png)

### Purpur version

```
> version
[03:52:36 INFO]: Checking version, please wait...
[03:52:36 INFO]: Current: git-Purpur-1940 (MC: 1.19.4)*
Previous: git-Pufferfish-62 (MC: 1.19.4)
* You are running the latest version
```

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

Pufferfish/Paper latest builds does not have this bug.

**Comment by encode42** [comment]
This originates far upstream, we just hadn't updated upstream in a few days. This has been "fixed" in Purpur as of build #1941.
