### ISSUE TITLE
Error executing task on Client -  java.lang.IllegalArgumentException: Default value cannot be lower than minimum value!

### ISSUE THREAD

**Issue by mibby** [pl3xgaming/Purpur#13]
**Describe the bug**
@BillyGalbreath Similar to this issue https://github.com/Spottedleaf/Tuinity/issues/55 except the client seems to spam this separate error to the client, unique to connecting with Purpur.

```
[09:09:45] [Render thread/FATAL]: Error executing task on Client
java.lang.IllegalArgumentException: Default value cannot be lower than minimum value!
	at alx.<init>(SourceFile:21) ~[1.15.2.jar:?]
	at dnp.a(SourceFile:2167) ~[1.15.2.jar:?]
	at pf.a(SourceFile:70) ~[1.15.2.jar:?]
	at pf.a(SourceFile:15) ~[1.15.2.jar:?]
	at lv.a(SourceFile:21) ~[1.15.2.jar:?]
	at lv$$Lambda$2356/71536207.run(Unknown Source) ~[?:?]
	at ais.c(SourceFile:144) [1.15.2.jar:?]
	at aiw.c(SourceFile:23) [1.15.2.jar:?]
	at ais.w(SourceFile:118) [1.15.2.jar:?]
	at ais.bk(SourceFile:103) [1.15.2.jar:?]
	at dbn.d(SourceFile:956) [1.15.2.jar:?]
	at dbn.d(SourceFile:619) [1.15.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:204) [1.15.2.jar:?]
```

**To Reproduce**
Connect with a vanilla 1.15.2 client on Purpur dev 507 with Citizens2 dev 1852.

purpur.yml
https://paste.ubuntu.com/p/yYd9vk74JS/

tuinity.yml
https://paste.ubuntu.com/p/KzV4Y4j43j/

**Plugins**
[08:35:03 INFO]: Plugins (1): Citizens

**Version**
This server is running Purpur version git-Purpur-508 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
No to all. Just Purpur as far as I can tell from testing.

**Comment by BillyGalbreath** [comment]
This error is saying the client has received some attribute value that's lower the minimum allowed value.

I am unable to reproduce this with just Purpur (no plugins).

**Comment by mibby** [comment]
@BillyGalbreath Are you sure it isn't a conflict with a Purpur patch and Citizens (fake player entities)? Here is a self contained zipped test server you can use to easily reproduce the problem.

https://www.dropbox.com/s/7kafyl1yebhwpsr/test.zip?dl=1

Launch ``start-purpur.bat`` to run purpur dev 518.
Launch ``start-tuinity.bat`` to run tuinity dev 22 .
Launch ``start-paper.bat`` to run paper dev 146 .

Use a vanilla 1.15.2 client with ``Open output log when games start`` toggled on in the launcher settings. Only ``fatal`` log levels need to be enabled. Connect with ``localhost`` as the IP on the client. The errors should occur on login and also occur when flying away and back (triggering unload/reload of entities).

This error only occurs on Purpur. It does not occur with Tuinity or Paper.
```
Error executing task on Client
java.lang.IllegalArgumentException: Default value cannot be lower than minimum value!
```

This error occurs on Tuinity and Purpur, caused by Tuinity's patches. It does not occur with Paper.
```
Error executing task on Client
java.lang.NullPointerException
```

When testing with just Paper, no errors occur and client lag spikes when loading chunks are significantly less impactful.

**Comment by BillyGalbreath** [comment]
```
java.lang.IllegalArgumentException: Default value cannot be lower than minimum value!
```

Ok, so i spent more time looking into this than I wanted to. In the end, this is actually a vanilla bug in the client.

```
alr = dh.b(new alx(null, a2.a(), 0.0, Double.MIN_NORMAL, Double.MAX_VALUE));
```

Here is the constructor of the attribute
```
    public alx(alq a, String sb double d0, double d1, double d2) {
        super(a, b, d0);
        this.a = d1;
        this.maximum = d2;
        if (d1 > d2) {
            throw new IllegalArgumentException("Minimum value cannot be bigger than maximum value!");
        } else if (d0 < d1) {
            throw new IllegalArgumentException("Default value cannot be lower than minimum value!");
        } else if (d0 > d2) {
            throw new IllegalArgumentException("Default value cannot be bigger than maximum value!");
        }
    }
```

The middle check is the bit of code that's causing the error. The problem is `0.0` is evaluating to be smaller than `Double.MIN_NORMAL` so the condition is _always_ true.

![image](https://user-images.githubusercontent.com/332527/77821011-b0bfb780-70b4-11ea-8271-50938bc8f0b4.png)

There is nothing I can do to fix this.

I was able to easily recreate the problem, even without Citizens, by simply summoning a bat into the game. Purpur sets the `generic.flyingSpeed` of the bat to `0.6`, which is not a normal value for the bat so it sends this update attribute packet to the client. Sadly, the client has the above mentioned error in the code that is not fixable from the server's end.

**Comment by BillyGalbreath** [comment]
As for the NPE

```
java.lang.NullPointerException: null
```

This is something to do with Tuinity's optimized tracker. The error goes away if you disable that in `tuinity.yml`

**Comment by mibby** [comment]
Is there any reason as to why it only occurs with Purpur? I was not able to reproduce it on Tuinity or Paper. Is Purpur doing something to update or check attributes when entities are loaded into view of the client?

**Comment by mibby** [comment]
RE: NPE, are you sure the error goes away if you disable the optimized tracker? I have ``optimized-tracker: false`` set in all the worlds in the tuinity.yml but I still get the error. I'm able to trigger it by flying away from the NPCs and flying back -- forcing the NPCs to load into view again (but be invisible due to Tuinity's patch). 

It seems unrelated to the optimized tracker setting.

**Comment by BillyGalbreath** [comment]
> RE: NPE, are you sure the error goes away if you disable the optimized tracker? I have `optimized-tracker: false` set in all the worlds in the tuinity.yml but I still get the error. I'm able to trigger it by flying away from the NPCs and flying back -- forcing the NPCs to load into view again (but be invisible due to Tuinity's patch).
> 
> It seems unrelated to the optimized tracker setting but caused by the Tuinity patch.

You'll have to take this to Tuinity as it is tracker related. Tuinity optimizes the entity tracker for performance, but Citizens also modifies the tracker for their own use as well. The two are known to conflict.
