### ISSUE TITLE
Sometimes it happens for players that the block does not break the first time

### ISSUE THREAD

**Issue by 111Zeus111** [pl3xgaming/Purpur#1303]
### Spark link

 unknown

### Expected behavior

I would like all the blocks to break as expected, the server tps 20 is stable.

### Observed/Actual behavior

Sometimes it happens for players that the block does not break the first time. That is, if it starts not to break, it cannot be broken at all, only by switching to another block it can be broken later.
purpur kernel 1.19.3 latest version

### Steps/models to reproduce

-

### Purpur version

 Current: git-Purpur-1933 (MC: 1.19.3)*
Previous: git-Pufferfish-60 (MC: 1.19.3)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by encode42** [comment]
Issues are for bug reports, not support. Seek support in our [Discord server](https://purpurmc.org/discord).

Additionally, the *required* fields that you did not fill out, such as the Spark link, are required for a reason.
