### ISSUE TITLE
"/loot spawn" command not returning number of rolls if 0 items are spawned (breaks datapacks)

### ISSUE THREAD

**Issue by ninjakitty844** [pl3xgaming/Purpur#1308]
### Spark link

Not a performance problem.

### Expected behavior

Some datapacks use loot tables for RNG (it is inefficient to do it any other way currently). You can do this by setting the min and max rolls to the min and max of the random range you want. You can use the "set_count" function with a value of 0 to ensure you get your RNG value without actually spawning any items in the world. The "/loot spawn" command will return the number of rolls, so it can be saved as a scoreboard entry and used by the datapack.

For example, here is a loot table that is supposed to get between 1 and 30 rolls and output the number of rolls while spawning 0 items:
`{
  "type": "minecraft:empty",
  "pools": [{
    "rolls": {
      "min": 1,
      "max": 30
    },
    "entries": [{
      "type": "minecraft:item",
      "name": "stone",
      "functions": [{
        "function": "minecraft:set_count",
        "count": 0
      }]
    }]
  }]
}`

In vanilla Minecraft, spawning this loot table and storing the return value into a scoreboard entry will cause that entry to now hold a value between 1 and 30. 

### Observed/Actual behavior

**In Purpur it will only ever output 0 since no items were spawned in the world.**

### Steps/models to reproduce

I've made a datapack that will pick a random number between 1 and 30 every second using the loot table method of RNG. Just type `/scoreboard players get @p one_to_thirty.RNG` to see the current value.

[1_30.zip](https://github.com/PurpurMC/Purpur/files/11219788/1_30.zip)

It will work perfectly on vanilla, but on Purpur it will just say 0 always.

### Purpur version

Current: git-Purpur-1957 (MC: 1.19.4)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by encode42** [comment]
Can you reproduce this on Spigot or Paper?

**Comment by ninjakitty844** [comment]
it seems unfortunately that the problem runs deep, exists in the latest versions of both paper and spigot :[

**Comment by granny** [comment]
Report it to them, then. Paper *might* be interested in applying a fix before spigot, but no guarantee. There might also be a chance that it's already been reported to them, so make sure to check if that's the case.
