### ISSUE TITLE
Minecraft 1.19.4 asynchronous effect bug 

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [pl3xgaming/Purpur#1315]
### Spark link

My Server cannot update spark profilings on spark webapp, I uploaded .profiling in 'others'

### Stack trace

```
https://paste.gg/p/anonymous/0efae70c9f3f4d66945b81b9a55480a7/revisions
```

### Actions to reproduce (if known)

if player login in that place, server will crash immediately and the server then prints an error report

### Purpur version

[17:03:58 INFO]: Current: git-Purpur-1964 (MC: 1.19.4)*
Previous: git-Purpur-1963 (MC: 1.19.4)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

This error report has probably happened many times, and I think it is because Paper asynchronously spawns a hardmode-specific effect spider when executing asynchronous block generation, while Paper does not allow asynchronous effects
---------------------------------------------------------
This is plugins list:
![image](https://user-images.githubusercontent.com/71379165/233830321-90933f4d-1891-48c7-8be8-b6dbdee51527.png)

This is datapacks list:
![image](https://user-images.githubusercontent.com/71379165/233830350-64f5d160-6591-4f13-9f25-cc509a3fca64.png)
---------------------------------------------------------
This is spark profiling:
[spark.zip](https://github.com/PurpurMC/Purpur/files/11303298/spark.zip)

**Comment by xiaoyueyoqwq** [comment]
Oh maybe I wrote backwards the location of datapack and plugins ;)

**Comment by granny** [comment]
> - [x]  I ticked all the boxes without actually reading them

Please read through the issue template carefully when filling it out.

**Comment by granny** [comment]
For future reference,
1. Are you able to reproduce this issue on the latest version of Paper?
2. Are you able to reproduce this issue without any plugins installed?
3. Are you able to reproduce this issue with no datapacks enabled?

If any or all of the above are true, then it's not an issue with Purpur.
