### ISSUE TITLE
Multiservers cause a crash

### ISSUE THREAD

**Issue by thiagogebrimm** [pl3xgaming/Purpur#1317]
### Spark link

it is not necessary

### Stack trace

```
https://paste.gg/p/anonymous/4d96387e8e79423a81a2b54122bd6700
```

### Purpur version

git-Purpur-1964 (MC: 1.19.4)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by encode42** [comment]
The spark link *is* necessary, especially considering we have no idea what "Multiservers" is referring to.

Additionally, armor trims are causing your server to crash. Considering they're not in the game until 1.20, you're either using the **experimental** (and unsupported) 1.20 features datapack, or have a plugin that's messing with the game *really* jankily.

**Comment by Krakenied** [comment]
Did you mean MultiverseCore?
