### ISSUE TITLE
i cant start Purpur server with 13900K and Windows Server 2022 datacenter.

### ISSUE THREAD

**Issue by glowingstone124** [pl3xgaming/Purpur#1318]
### Spark link

i dont know what is Spark Link.

### Stack trace

```
> #
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe3822dd8a, pid=8804, tid=6216
#
# JRE version: Java(TM) SE Runtime Environment (17.0.7+8) (build 17.0.7+8-LTS-224)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (17.0.7+8-LTS-224, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x35dd8a]
#
# Core dump will be written. Default location: D:\srv\新建文件夹\hs_err_pid8804.mdmp
#
# An error report file with more information is saved as:
# D:\srv\新建文件夹\hs_err_pid8804.log
[12:18:37 INFO]: [SkinsRestorer] Detected Minecraft v1_19_R3, using MappingSpigotSkinRefresher.
> #
# Compiler replay data is saved as:
# D:\srv\新建文件夹\replay_pid8804.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
```
my server have 128GB ram. this is my startup function:
```
java -Dfile.encoding=UTF-8 -Xmx10G -jar purpur-1.19.4-1966.jar
```
when i run it in Ubuntu, it's fine. 

### Purpur version

 >version
[12:25:37 INFO]: Checking version, please wait...
[12:25:37 INFO]: Current: git-Purpur-1966 (MC: 1.19.4)*
Previous: git-Purpur-1933 (MC: 1.19.3)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

maybe caused by JVM?

**Comment by Dragon740f** [comment]
i found that there are another error report on Tieba.

**Comment by encode42** [comment]
GitHub issues are for bug reports, not support. Please join our [Discord server](https://purpurmc.org/discord) for that.

Spark links are required so we can understand the environment you're running your server in. You only need to run the `/spark upload` command to get a link.

This is likely caused by the JVM, yes. Windows Server typically isn't supported.

I am unsure what "Tieba" is.

![image](https://user-images.githubusercontent.com/34699884/235406726-7ae2043a-e94a-4913-b371-20cd0d2e7994.png)

**Comment by glowingstone124** [comment]
thanks. Tieba is a platform likes twitter. I will join Discord server for more informations. thanks
