### ISSUE TITLE
F3+N possesion don't work

### ISSUE THREAD

**Issue by Nicolol1234** [pl3xgaming/Purpur#1320]
### Spark link

not a real problem

### Expected behavior

when i clic on an entity, to see throught the entitie's eyes

### Observed/Actual behavior

nothing happened

### Steps/models to reproduce

use the F3+N feature

### Purpur version

version
[19:57:06 INFO]: Checking version, please wait...
[19:57:06 INFO]: Current: git-Purpur-1967 (MC: 1.19.4)*
Previous: git-Purpur-1964 (MC: 1.19.4)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by encode42** [comment]
Spark links *are* a required field. They help us debug your issue.

**Comment by granny** [comment]
I think there's some confusion on what the F3+N permission does. It does not allow you to see through an entity's eyes by clicking on them. Here's a link that explains what it does: https://purpurmc.org/docs/Permissions/#purpurdebugf3n

Also, please fill out the template properly next time you create a new issue.

**Comment by Nicolol1234** [comment]
No but the f3+n set me in spectator mode, and in spectator i can't see, and sorry for the templates

**Comment by Kichura** [comment]
Is it giving you blindness or does it show the block's texture(s) you are trying to go through?

**Comment by granny** [comment]
> No but the f3+n set me in spectator mode, and in spectator i can't see, and sorry for the templates

Correct. All it does it allow you to run F3+N without needing to be OP. Your issue is not related to Purpur at all.
