### ISSUE TITLE
Comparator not updating when connected to a hopper

### ISSUE THREAD

**Issue by TarkinMX** [pl3xgaming/Purpur#1321]
### Spark link

https://spark.lucko.me/ZrXgXxKCou

### Expected behavior

The comparator turns on when items are received in the hopper it's connected to. The comparator is then supposed to shut off once the hopper is empty.

### Observed/Actual behavior

The comparator turns on when items are received in the hopper but does not shut off once the hopper is empty. Placing a block next to the comparator forces it to update but only once.

### Steps/models to reproduce

Place a comparator next to a hopper that feeds into a chest and then place items into the hopper.

### Purpur version

[03:24:02 INFO]: Checking version, please wait...
[03:24:02 INFO]: Current: git-Purpur-1967 (MC: 1.19.4)*
Previous: git-Paper-514 (MC: 1.19.4)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

Doing a google search, this is the exact same issue that paper once had and can be found at [https://github.com/PaperMC/Paper/issues/505](https://github.com/PaperMC/Paper/issues/505). I'm running minecraft java edition version 1.19.4. I loaded up paper version 514 as this was the last version of paper I used before switching to purpur. I connected with my client and had no issue with the comparator. I then updated to the latest version of paper which is 524, loaded it up and the comparator still acts as expected.

**Comment by encode42** [comment]
I am unable to reproduce this issue on a fresh installation of Purpur and the Minecraft client.


https://user-images.githubusercontent.com/34699884/236378864-6e1696f8-0760-4bdb-90e0-407295e3d797.mp4

**Comment by xGinko** [comment]
![Screenshot from 2023-05-05 10-36-41](https://user-images.githubusercontent.com/83339096/236412915-e7533ba6-5ca9-488c-bff7-d650ea324727.png)

I see something doing something with the something you described

**Comment by TarkinMX** [comment]
I didn't think of trying it with a fresh install. I did that and it works so I'm assuming it's either plugins or config settings from when I was using paper. I'll troubleshoot these and report back later today so if anyone else comes across this issue then they'll know what to do.

**Comment by TarkinMX** [comment]
I found the culprit. It's the [sortify plugin](https://www.spigotmc.org/resources/sortify-item-filter-for-redstone-components.61856/) that I use. Strange that it doesn't have the problem I described with paper. Anyway, sorry for the trouble. I'll go report the bug to the plugin's developer.
