### ISSUE TITLE
Server Gets Stuck At Encryping When Joining The Server And Console Throws Multiple Erors Then Restarts

### ISSUE THREAD

**Issue by BlueMooon777** [pl3xgaming/Purpur#1331]
### Spark link

trying to run the spark profiler also spits out a huge eeror

### Stack trace

```
https://paste.gg/p/anonymous/a644260a172345bda53e4256b9d7185a
```

### Actions to reproduce (if known)

Join The Server

### Purpur version

Current: git-Purpur-1976 (MC: 1.19.4)*
Previous: git-Purpur-1968 (MC: 1.19.4)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by YouHaveTrouble** [comment]
Hi, issues page is for the issues with features, if you want help with troubleshooting, please join [our discord](https://discord.gg/mtAAnkk), will be way faster to ask followup questions for us.
