### ISSUE TITLE
(Suggestion) Option to change enchant/effects math

### ISSUE THREAD

**Issue by YouHaveTrouble** [pl3xgaming/Purpur#134]
An option to change the math for certain enchants like unbreaking and effects like resistance.

This would allow server owners to scale those effects however they want. For example you could scale unbreaking enchant with a flat percentage per level (1 = 10%, 2 = 20% etc) and allowing enabling higher numbers on them. This would mean there could be more progression, which means more content for players.

Most of the enchants with multiple leves would benefit from this, aswell as the effects like resistance, haste or weakness.

How this would be implemented is up to the patch creator, there are a couple options, like adding the ability to add equasion with a placeholder for enchant/effect level or straight up allow hard-coding percentage values per level one-by-one.

**Comment by BillyGalbreath** [comment]
As discussed, its not really something I want to toy with. I've experimented with changing enchantments before and it just ends up breaking many more things
