### ISSUE TITLE
Infinity Bow no arrow option + Shield block

### ISSUE THREAD

**Issue by yorik100** [pl3xgaming/Purpur#1342]
### Spark link

https://spark.lucko.me/CoRzHFvX9o

### Expected behavior

Charge arrows with right click while holding a bow and a shield

### Observed/Actual behavior

Shield block getting enabled and after blocking, an arrow gets shot even though there was no arrow charging animation

### Steps/models to reproduce

1. Get infinity bow
2. Get shield in offhand
3. Don't have any arrows
4. Have the option to allow infinity bows to fire without any arrows
5. Block with shield
6. Release after like 2 seconds
7. An arrow comes out even though there was no bow charging animation

### Purpur version

git-Purpur-1984 (MC: 1.19.4)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by katekerllenevich** [comment]
This is a client-sided issue (see #492), however nothing was ever done with PurpurClient as it is not really updated anymore.
