### ISSUE TITLE
Visual glitch from canceled item shift-click

### ISSUE THREAD

**Issue by PikaMug** [pl3xgaming/Purpur#1345]
### Spark link

https://spark.lucko.me/4XmmbBcJZm

### Expected behavior

Inventory would close without item appearing to enter hotbar, as is the case on Paper servers.

### Observed/Actual behavior

https://github.com/PikaMug/Quests/issues/2120

### Steps/models to reproduce

Relevent code: https://github.com/PikaMug/Quests/blob/main/core/src/main/java/me/blackvein/quests/listeners/PlayerListener.java#L84-L148

### Purpur version

```
Current: git-Purpur-1985 (MC: 1.19.4)*
Previous: git-Purpur-1784 (MC: 1.19.2)
* You are running the latest version
```

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

Was asked to create this ticket by 'granny' on Discord.
Possibly related to https://github.com/PurpurMC/Purpur/issues/611

**Comment by katekerllenevich** [comment]
~~Just to confirm, this works on Paper?~~

Just kidding, I read the linked issue.

**Comment by granny** [comment]
Unable to reproduce on a server with 0ms ping and a server with 22ms ping using the following code:

```java
public final class Test extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        this.getServer().getPluginManager().registerEvents(this, this);
    }

    @EventHandler(priority = EventPriority.HIGHEST)
    public void onInventoryClickEvent(final InventoryClickEvent event) {
        this.getLogger().info("Inventory opened!");

        // make sure to create a chest that has an item inside it. Name the chest "custom_inventory".
        if (event.getView().getTitle().contains("custom_inventory")) {
            this.getLogger().info("Custom Inventory confirmed.");
            final ItemStack clicked = event.getCurrentItem();

            if (isItem(clicked)) {
                this.getLogger().info("Attempting to grab item! Cancelling event...");
                event.setCancelled(true);
            }
        }
    }

    private boolean isItem(ItemStack is) {
        if (is == null) {
            return false;
        }
        return !is.getType().equals(Material.AIR);
    }
}
```

```
[07:51:29 INFO]: Checking version, please wait...
[07:51:29 INFO]: Current: git-Purpur-1995 (MC: 1.20.1)*
* You are running the latest version
```

**Comment by granny** [comment]
Make sure both you and the player who reported the issue aren't in creative mode when attempting to reproduce the issue.

**Comment by PikaMug** [comment]
I'll take a deeper look at this, but am able to reproduce whether gamemode is creative or survival.

**Comment by PikaMug** [comment]
It would appear our "relevant code" above executes the same on Paper and Purpur, but the results still differ. The effect appears to only be visual, however, as relogging removes the phantom item from the hotbar.

**Comment by granny** [comment]
What results differ between Paper and Purpur with the test code? I just tested it on the latest version of Paper and Purpur and both are doing the same thing.

<details open>
<summary>Paper</summary>

```
> version
[16:18:49 INFO]: Checking version, please wait...
[16:18:51 INFO]: This server is running Paper version git-Paper-43 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 3756f5b)
You are running the latest version
Previous version: git-Paper-405 (MC: 1.19.3)
```

</details>

<details open>
<summary>Purpur</summary>

```
> version
[16:20:04 INFO]: Checking version, please wait...
[16:20:05 INFO]: Current: git-Purpur-"991719a" (MC: 1.20.1)*
Previous: git-Purpur-"fa3166a" (MC: 1.20.1)
* You are running the latest version
```

</details>

**Comment by PikaMug** [comment]
The issue has been resolved by delaying close of the inventory by 1 tick.

I might have realized this was it sooner, but the glitch still doesn't occur on my 1.19.4 Paper test server, and does on 1.19.4 Purpur. Both platforms suffered on fresh 1.20.1 servers, regardless of gamemode. Perhaps some environmental quirk on my end?

At any rate, thank you for your patience on this!
