### ISSUE TITLE
Water Creatures (Specifically Salmon & Squids) Suffocate whilst in water

### ISSUE THREAD

**Issue by h-exx** [pl3xgaming/Purpur#1352]
### Spark link

N/A

### Expected behavior

Salmon & Squids to swim around

### Observed/Actual behavior

Fish suffocating/drowning
(I have only tested those 2. I assume all sea creatures have the same behaviour)

### Steps/models to reproduce

Look at a river

### Purpur version

1.20.1 - 1995

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
> - [X] I ticked all the boxes without actually reading them

**Comment by h-exx** [comment]
I'm sorry i rushed through the issue. It is very much still a valid issue however

**Comment by Soapy7261** [comment]
Chances are if you clicked all boxes without reading them, you've clicked boxes that aren't accurate

**Comment by BillyGalbreath** [comment]
> I'm sorry i rushed through the issue. It is very much still a valid issue however

we wouldn't know, because there's no spark report for us to view..

**Comment by h-exx** [comment]
Will open a new issue with all of it filled in later
