### ISSUE TITLE
1.20.1 Wither Wether cannot be saved by maps

### ISSUE THREAD

**Issue by CatTeaA** [pl3xgaming/Purpur#1355]
### Spark link

Not required

### Expected behavior

Wether can be saved

### Observed/Actual behavior

1.20.1 Wither Wether cannot be saved by maps
The map cannot save Wither

### Steps/models to reproduce

Summon Wither
Exit the game
Wether disappeared

Test paper-1.20.1-43.jar There is no such problem

### Purpur version

purpur-1.20.1-1996.jar

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

No plugins are installed
Profile default

**Comment by YouHaveTrouble** [comment]
> I ticked all the boxes without actually reading them

> Not required

yes it is

**Comment by CatTeaA** [comment]
Sorry, I don't speak English, so I use the translator all the time
