### ISSUE TITLE
Infinite arrow no arrow issue

### ISSUE THREAD

**Issue by yorik100** [pl3xgaming/Purpur#1358]
### Spark link

https://spark.lucko.me/msBpzLJ2PX

### Expected behavior

Pulling an infinity 1 bow instead of not doing anything when interacting with a block instead of interacting with air

### Observed/Actual behavior

When I try to pull an infinity 1 bow with the option to avoid having an arrow in inventory to use it, it doesn't work if I right click on any block with it when trying to pull an arrow

### Steps/models to reproduce

1. Get infinity 1
2. Enable option for infinity 1 no arrow required in Pupur settings
3. Try to pull the bow while looking at a block
4. No work

### Purpur version

git-Purpur-"625e4ad" (MC: 1.20.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
> - [x] I ticked all the boxes without actually reading them

Just tested on an older version of Purpur and it looks like it works that way then, so i'd say it's WAI.
