### ISSUE TITLE
Villagers not changing Professions when they should!

### ISSUE THREAD

**Issue by Bayanicool** [pl3xgaming/Purpur#1359]
### Spark link

https://spark.lucko.me/6H4pjbClpL

### Expected behavior

I expect villagers, when given a profession, you look in their inventory and it doesn't count as being traded with

### Observed/Actual behavior

Instead, what happens is, if you dont trade with them it counts as them trading and they are not able to lose their profession when their profession/job block (ex: lectern) is destroyed

### Steps/models to reproduce

https://imgur.com/a/hxukYdU
LINK TO THE BUG VIDEO

### Purpur version

Current: git-Purpur-2001 (MC: 1.20.1)*
Previous: git-Purpur-1996 (MC: 1.20.1)
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads
https://i.imgur.com/bu05qeD.png

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

I tried this in normal minecraft, it wasn't an issue, I tried with just PurPur installed, still happened. Seems like its a PurPur Issue, I love Purpur thx for the constant support!

I also found that they spawn with a little amount of EXP, I found this forum saying that they should spawn with XP and plugins do that to fix MC bug? https://www.reddit.com/r/Minecraft/comments/jfigz6/villagers_spawn_with_exp/ THANKS!

**Comment by BillyGalbreath** [comment]
https://github.com/dniym/IllegalStack/wiki/VillagerTradeCheesing

**Comment by Bayanicool** [comment]
Thx

**Comment by Hikutaatti** [comment]
I am having this exact same issue occur. 1 Version(s) behind so git-purpur-2004. Will update if still occurring on the newest

**Comment by granny** [comment]
Not a Purpur issue. OP's problem was the `VillagerTradeCheesing` option being enabled from the IllegalStack plugin. @Hikutaatti if you're still having issues and you *don't* have IllegalStack installed, please attempt to reproduce without any plugins installed.
