### ISSUE TITLE
Request: Update Pufferfish Upstream

### ISSUE THREAD

**Issue by Potothingi** [pl3xgaming/Purpur#1363]
### Spark link

none

### Description of issue

A performance improvement patch was recently added to pufferfish and I hope it applies to Purpur as well.
https://github.com/pufferfish-gg/Pufferfish/commits/ver/1.20

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
We're well aware of it. Upstreams happen when they happen
