### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by tomasalias** [pl3xgaming/Purpur#1365]
### Spark link

Idk

### Stack trace

https://paste.gg/p/anonymous/0df40cd72f964f7f9a3c30555240cceb

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [x] My version of Minecraft is supported by Purpur.

**Comment by tomasalias** [comment]
https://spark.lucko.me/7XHCXBxl8r

**Comment by katekerllenevich** [comment]
> This is (probably) not a Purpur bug.

Talk to us in #help-and-support on Discord please!
