### ISSUE TITLE
Upgrade from 1.19.4 to 1.20(.1) breaks world with datapacks

### ISSUE THREAD

**Issue by AjnebAlReves** [pl3xgaming/Purpur#1369]
### Spark link

Server does not start for use spark

### Stack trace

```
https://paste.gg/p/anonymous/f31b0e7b86de4170b6690ac79bf760f7
```

## Requeriments
> Use ServerJars Updater
-----
## Steps:
> Make a world in 1.19.4 and upgrade to 1.20
> Add some datapacks to world

### Purpur version

> version
[18:58:15 INFO]: Checking version, please wait...
[18:58:15 INFO]: This server is running Purpur version git-Purpur-2004 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)
[18:58:15 INFO]: You are running the latest version
[18:58:15 INFO]: Previous version: git-Purpur-2001 (MC: 1.20.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by AjnebAlReves** [comment]
Sorry, it's my server bug but not from purpur

**Comment by YouHaveTrouble** [comment]
Some worldgen datapacks get *really* tangled up in the world files. It's a problem even on vanilla sadly.
