### ISSUE TITLE
Disable note block updates setting not working

### ISSUE THREAD

**Issue by cometcake** [pl3xgaming/Purpur#1374]
### Spark link

https://spark.lucko.me/KCWjeZFLGV

### Expected behavior

When enabling the 'disable-note-block-updates' setting in the purpur.yml config, the note block instrument should never change automatically.

### Observed/Actual behavior

When placing a mob head on a note block, removing one that is above the note block or when changing the block below a note block, the instrument changes despite the setting to disable updates being enabled.

The blockdata also updates if a note block is placed using the /setblock command, even if specific blockdata is supplied in the command.

### Steps/models to reproduce

Load a server with the latest PurpurMC version.

Disable note block updates and restart the server.

Place a note block.

Place a mob head (e.g. a zombie head) above the note block, or a different instrument block below the note block.

The note block instrument updates to the corresponding instrument despite the updates being disabled.

To reproduce the command issue, use the following command:

/setblock ~ ~ ~ minecraft:note_block[instrument=creeper]

The note block instrument is not a creeper, despite the updates being disabled.

### Purpur version

Current: git-Purpur-2006 (MC: 1.20.1)*
Previous: git-Purpur-2005 (MC: 1.20.1)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by TheRealRyGuy** [comment]
granny: as of build #2005, the note block update option in the purpur config (`settings.blocks.disable-note-block-updates`) has been removed in favor of paper's. (`block-updates.disable-noteblock-updates` in the paper global config)
