### ISSUE TITLE
Lava Sponges Not Working

### ISSUE THREAD

**Issue by rockit7** [pl3xgaming/Purpur#1379]
### Spark link

NA

### Expected behavior

Updated to the latest 1.20.1 purpur version from 1.19.4 and lava sponges no longer work. I do have the sponge.absorbs-lava set to true in the purpur.yml

### Observed/Actual behavior

Enable lava sponges. Place sponge. No absorb. 

### Steps/models to reproduce

Enable lava sponges. Place sponge. No absorb. 

### Purpur version

1.20.1 - Latest / 2010

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

Thank you for the help in advance!

**Comment by RhythmicSys** [comment]
First of all: 
> - [x]  I ticked all the boxes without actually reading them
please read the boxes.

However I can confirm the bug

![image](https://github.com/PurpurMC/Purpur/assets/45906780/fa3cf0ab-fa9a-4e57-9d3e-c6b2cc42337c)

**Comment by rockit7** [comment]
OMG! Look, it's been a really long day with very little to no coffee. Thanks for confirming its a bug. 😂 Next time, I shall read everything twice.
