### ISSUE TITLE
Purpur Death Messages

### ISSUE THREAD

**Issue by NoViz22** [pl3xgaming/Purpur#1380]
### Spark link

https://spark.lucko.me/cC0etdKCoj

### Expected behavior

Dying from stonecutters or shears was expected to say "player slipped and fell on their shears" and "player has sawed themself in half"

### Observed/Actual behavior

The death messages for both appear as "killed by magic" rather than their respective death messages

### Steps/models to reproduce

Enable stonecutter/shears damage on the latest version and demise using them.

### Purpur version

Current: git-Purpur-2010 (MC: 1.20.1)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

This was tested for Purpur 1.19.4 and did not work there either so apparently this has been an issue for a while. I've also noticed the custom death messages for the Traincarts plugin does not work either in these versions however I'm not sure that would have anything to do with Purpur.

**Comment by RhythmicSys** [comment]
I can confirm this issue, death message given is "killed by magic" - first death is shears, second is stonecutter
```
[15:29:00] [Server thread/INFO]: RhythmicSystem was killed by magic
[15:29:28] [Server thread/INFO]: RhythmicSystem issued server command: /give RhythmicSystem minecraft:stonecutter
[15:29:28] [Server thread/INFO]: [RhythmicSystem: Gave 1 [Stonecutter] to RhythmicSystem]
[15:29:42] [Server thread/INFO]: RhythmicSystem was killed by magic
```

**Comment by granny** [comment]
I forgot to mention when we finished upstreaming 1.19.4 that those death messages were reverted to "killed by magic". There was an issue with the old implementation before the update so this was meant as a temporary solution until I had time to re-implement the death messages. Leaving the ticket open until it's "fixed".
