### ISSUE TITLE
Incorrect player head rotations.

### ISSUE THREAD

**Issue by Cookie-Kurokami** [pl3xgaming/Purpur#1382]
### Spark link

https://spark.lucko.me/eIo2bIeIMz

### Expected behavior

For player head rotations to properly and consistently sync up with where they are positioned client-side. 

### Observed/Actual behavior

Starting in build 2009 and continuing into build 2011, the heads of stationary players appear to face south by default when they come into view distance—regardless of which direction their body is facing. This persists until they update the position of their own head by moving it, and returns the moment they enter view distance again after leaving it. This problem affects not only real players, but also player NPCs added by plugins like Citizens.

https://github.com/PurpurMC/Purpur/assets/66750372/74836650-4e4f-411c-9e47-ad2b4e314752

### Steps/models to reproduce

1) Have a player remain stationary while facing a direction other than south, preferably north. 
2) Distance yourself from that player until they are no longer rendered.
3) Approach that player again until they are close enough to clearly observe.
4) Their head will be facing south, even though it was not previously, and even if their bodily rotation should make that impossible.

### Purpur version

Current: git-Purpur-2011 (MC: 1.20.1)*
Previous: git-Purpur-2006 (MC: 1.20.1)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

Although it says that 2006 is the version that I ran prior to running 2011, I have in fact tested this on 2008, 2009, and 2010 as well, and can confirm that the issue begins in 2009.

**Comment by granny** [comment]
Build 2009 is based off of a Paper upstream commit, so it's safe to assume that it's not a Purpur issue. The commit in question: https://github.com/PurpurMC/Purpur/commit/b21daa9622f317fd52962d33e8ce9305364c07cf. Paper had upstreamed Bukkit/CraftBukkit/Spigot in one of those commits, so that might be a good place to start. (Paper 1.20.1 # 63 is the relevant build)
