### ISSUE TITLE
Camel bug

### ISSUE THREAD

**Issue by WeihnachtsmannYT** [pl3xgaming/Purpur#1384]
### Spark link

N/A

### Expected behavior

The camel should sprint when you press Ctrl+W and leap when you press spacebar

### Observed/Actual behavior

The Camel dismount you when you press Str+W or spacebar

### Steps/models to reproduce

Tame Camel
give it a saddle
ride it and press str+w or spacebar

### Purpur version

Checking version, please wait...
Current: git-Purpur-2014 (MC: 1.20.1)*
Previous: git-Purpur-2011 (MC: 1.20.1)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

i get no errors in console

**Comment by granny** [comment]
Cannot reproduce. Might be an issue with whatever plugins you have installed, can't say for sure since a spark link was not shared.
