### ISSUE TITLE
Server crashed for unknown reason

### ISSUE THREAD

**Issue by nicolube** [pl3xgaming/Purpur#1391]
### Spark link

https://spark.lucko.me/moRU1jRGnk

### Stack trace

https://paste.gg/p/anonymous/055ec0ef5a1f43e399ec8b17afc4d127

### Purpur version

Current: git-Purpur-2016 (MC: 1.20.1)*
Previous: git-Purpur-2015 (MC: 1.20.1)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

We're encoutering some random crashes, they appear to be occuren on an Player#asyncTeleport, but I'm not rly sure about that.

We're running this server behind a Velocuty proxy.

None of the unkowen Plugins like Prime*, doing world modifiing tasks, The only ones that I'm awere of are P2 and FAWE.

**Comment by granny** [comment]
@WiIIiam278 We have verified the issue on both paper and Purpur

_Originally posted by @nicolube in https://github.com/WiIIiam278/HuskSync/issues/152#issuecomment-1653540878_
