### ISSUE TITLE
Coloured text not working on signs

### ISSUE THREAD

**Issue by itsBeaco** [pl3xgaming/Purpur#1392]
### Spark link

https://spark.lucko.me/jo037OD0oA

### Expected behavior

When using colour codes on a sign, I would expect the colour of the text to be a colour. For example: “&6Test” would be “Test” in gold. 

### Observed/Actual behavior

After typing my text and colour code, the sign will update and the text remains the default black. 

### Steps/models to reproduce

Write on a regular sign (any type): “&6Test”

### Purpur version

18.07 01:00:06 [Server] INFO Checking version, please wait...
18.07 01:00:06 [Server] INFO Current: git-Purpur-2016 (MC: 1.20.1)*
18.07 01:00:06 [Server] INFO Previous: git-Purpur-2015 (MC: 1.20.1)
18.07 01:00:06 [Server] INFO * You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

All relevant permissions have been used and it has been enabled in the purpur.yml file.

![IMG_3128](https://github.com/PurpurMC/Purpur/assets/77558094/51101870-b1b5-4f6a-b1f4-4b05ec1cd5af)

**Comment by NoobcoreNetwork** [comment]
+1 same issue here, same perms etc. Only happened after updating to 1.20.1 from 1.19.4

**Comment by kalakituks** [comment]
Maybe someone known WHEN it will be fixed?
