### ISSUE TITLE
Elder Guardian loot drop

### ISSUE THREAD

**Issue by Gallego991** [pl3xgaming/Purpur#1396]
### Spark link

N/A

### Expected behavior

Expect that one Elder Guardian drops a smithing template when defeated.

### Observed/Actual behavior

Elder Guardians are not dropping smithing template and instead of a “wet sponge” it drops a “dry sponge”.

### Steps/models to reproduce

Elder Guardian only has “dry sponge” in its loot drop on versions before 1.11.
Elder Guardian loot drop is not update to 1.20

### Purpur version

git-Purpur-2018(MC:1.20.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by hexadecimal233** [comment]
Cannot reproduce. I'm assuming one of your plugins has interfered with the loot table.
