### ISSUE TITLE
The POM for ca.spottedleaf.concurrentutil:concurrentutil:jar:1.0.0-SNAPSHOT is missing, no dependency information available

### ISSUE THREAD

**Issue by morfie78** [pl3xgaming/Purpur#14]
**Describe the bug**
When running ./purpur build after successfully running ./purpur up and ./purpur patch, I get the following error:
`[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< net.pl3x.purpur:purpur >-----------------------
[INFO] Building Purpur 1.15.2-R0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for ca.spottedleaf.concurrentutil:concurrentutil:jar:1.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.494 s
[INFO] Finished at: 2020-03-26T02:44:00Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project purpur: Could not resolve dependencies for project net.pl3x.purpur:purpur:jar:1.15.2-R0.1-SNAPSHOT: Failure to find ca.spottedleaf.concurrentutil:concurrentutil:jar:1.0.0-SNAPSHOT in https://hub.spigotmc.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of spigotmc-public has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project purpur: Could not resolve dependencies for project net.pl3x.purpur:purpur:jar:1.15.2-R0.1-SNAPSHOT: Failure to find ca.spottedleaf.concurrentutil:concurrentutil:jar:1.0.0-SNAPSHOT in https://hub.spigotmc.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of spigotmc-public has elapsed or updates are forced
`

**To Reproduce**
1. git clone'd the repo and change into the repo's directory
2.  git submodule update --init
3. ./purpur up
4. ./purpur patch
5. ./purpur build
6. Error occurs

**Screenshots or Videos**
git submodule update --init
./purpur up
https://share.getcloudapp.com/eDuxZq99

./purpur up continued
https://share.getcloudapp.com/nOuN2jNp

./purpur patch
https://share.getcloudapp.com/Qwu7JgKg

./purpur build
https://share.getcloudapp.com/Z4u59gk9

**Plugins**
No server running yet.

**Version**
No server running yet.

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
N/A

**Additional context**

**Comment by BillyGalbreath** [comment]
You need leaf's ConcurrentUtil in your local maven repo. He never published it on any public repo, and I haven't fully converted the byof scripts to be a complete fork of Tuinity. I'm still unsure if I am going to keep Tuinity or not (we shall see when 1.16 comes out).

Simplest way to get ConcurrentUtil in your local maven repo is to clone the project from git and run `mvn install` on it. Maven will then be able to find it when compiling Purpur.
