### ISSUE TITLE
Does jar build error matter?

### ISSUE THREAD

**Issue by CatTeaA** [pl3xgaming/Purpur#1400]
### Spark link

null

### Expected behavior

![Screenshot_20230727_105540](https://github.com/PurpurMC/Purpur/assets/135555687/a746ad5b-12ed-4466-95e4-14473b14d5af)

### Observed/Actual behavior

JAR built successfully

### Steps/models to reproduce

null

### Purpur version

You can close this issue at any time

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
The GitHub Actions don't really matter - It's only used for the build status in the repo README file. The commits build correctly in jenkins.

**Comment by Huge-mistake** [comment]
> GitHub 操作并不重要 - 它仅用于存储库自述文件中的生成状态。提交在 jenkins 中正确构建。

Got it，Thank you for your answer
