### ISSUE TITLE
TPSTaskBar NPE

### ISSUE THREAD

**Issue by metabrixkt** [pl3xgaming/Purpur#141]
**Describe the bug**
If you try to stop the server **before** the tps task bar instance is created, you'll see a NPE: `java.lang.NullPointerException: Cannot invoke "net.pl3x.purpur.task.TPSBarTask.cancel()" because "net.pl3x.purpur.task.TPSBarTask.instance" is null`

**To Reproduce**
Start the server, do ctrl+c (or send SIGTERM to the process) before tps task bar is instantiated, and see NPE.

**Screenshots or Videos**
-

**Plugins**
no plugins

**Version**
Using git-Yatopia-"074471c". But since tps task bar is purpur's patch, it's purpur bug.

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
it's purpur patch -> no

**Additional context**
actually it isn't a bug, but it's better to fix it I think (just add null check)

**Comment by JanTuck** [comment]
Already solved, please use latest purpur and not some derivative while making such bold claims.

https://github.com/pl3xgaming/Purpur/commit/4a9c0163d9d5048f14c74d24a0d5e73fdaebb1f6
