### ISSUE TITLE
silk-spawners setting in config turns spawners into pig spawners.

### ISSUE THREAD

**Issue by dev-stan** [pl3xgaming/Purpur#142]
After enabling the `silk-touch` setting in `purpur.yml`, broken spawners are renamed as they should, though after placing those broken spawners they turn into pig spawners.

To reproduce; assign a group the `purpur.place.spawners` and `purpur.drop.spawners` permission nodes.

**Comment by JanTuck** [comment]
Was this reproduced without any plugins?

**Comment by granny** [comment]
duplicate of #48
