### ISSUE TITLE
Refused to switch game mode message was not properly formatted

### ISSUE THREAD

**Issue by KioProject123** [pl3xgaming/Purpur#1421]
### Spark link

Using a blank server, this should not be necessary

### Expected behavior

Colors are displayed correctly in chat messages if denied to switch game mode due to lack of permission

### Observed/Actual behavior

Incorrectly formatted display of colors in messages

![image](https://github.com/PurpurMC/Purpur/assets/61594596/8fe136ee-be5a-4bd6-b8bb-c77ed4a8454a)
![image](https://github.com/PurpurMC/Purpur/assets/61594596/492401a4-1b68-4ea1-8246-4594bad388d1)

![image](https://github.com/PurpurMC/Purpur/assets/61594596/66ec3da8-c0b5-4ca0-97e2-3e9e0174b72c)
![image](https://github.com/PurpurMC/Purpur/assets/61594596/7320b228-ec71-41f2-9b59-4af59e2e40df)

### Steps/models to reproduce

1、Set `gamemode.requires-specific-permission: true` in purpur.yml
2、Using permission management plugins to grant oneself `minecraft.command.gamemode` permission
3、Give yourself negative permission `minecraft.command.gamemode.creative`
4、Enter `/gamemode creative` in the game

![image](https://github.com/PurpurMC/Purpur/assets/61594596/10902ce0-2d4c-401a-b326-93677ed3945f)

### Purpur version

[07:20:22 INFO]: Current: git-Purpur-2044 (MC: 1.20.1)*
Previous: git-kiocg-"8d2ce69" (MC: 1.20.1)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by RhythmicSys** [comment]
We need the spark report to see what your configs look like. 

On a new purpur server with base configs, I cannot replicate this, but I am getting a bug where denying the creative permission does absolutely nothing, lol 
![image](https://github.com/PurpurMC/Purpur/assets/45906780/1af0154a-25ca-45ff-b02d-d48fddf1fda3)
![image](https://github.com/PurpurMC/Purpur/assets/45906780/3812711b-35cd-44ef-b893-3c01a9d0cad1)
[Spark Link](https://spark.lucko.me/B5aIuczAZQ)

**Comment by KioProject123** [comment]
> Set `gamemode.requires-specific-permission: true` in purpur.yml

You should set gamemode.requires-specific-permission: true in purpur.yml

Here is my spark link https://spark.lucko.me/3sTVx7tOKz

**Comment by KioProject123** [comment]
> We need the spark report to see what your configs look like.
> 
> On a new purpur server with base configs, I cannot replicate this, but I am getting a bug where denying the creative permission does absolutely nothing, lol ![image](https://user-images.githubusercontent.com/45906780/263501260-1af0154a-25ca-45ff-b02d-d48fddf1fda3.png) ![image](https://user-images.githubusercontent.com/45906780/263501499-3812711b-35cd-44ef-b893-3c01a9d0cad1.png) [Spark Link](https://spark.lucko.me/B5aIuczAZQ)

You should set `gamemode.requires-specific-permission: true` in purpur.yml

Here is my spark link https://spark.lucko.me/3sTVx7tOKz

**Comment by RhythmicSys** [comment]
Ah, lol, yeah that would probably help.

![image](https://github.com/PurpurMC/Purpur/assets/45906780/efd1adde-2ee5-4fd7-b3fd-efe7937b209f)
So, can confirm this. Also, running a spigot command (`/tps`) that I don't have permissions for, does not cause this issue
![image](https://github.com/PurpurMC/Purpur/assets/45906780/c629f633-1d77-4670-9c8f-21beab84d6a1)
