### ISSUE TITLE
Performance issue with Inventory.getHolder method for barrel containers

### ISSUE THREAD

**Issue by 5522-VVII** [pl3xgaming/Purpur#1423]
### Spark link

https://spark.lucko.me/M5JO0t7Anp

### Description of issue

Hello developers,:purpur: 

I have encountered a significant performance impact when using the Inventory.getHolder method to detect barrel containers compared to chests. The delay is noticeably higher when accessing the getHolder method for barrel containers.

Here is an excerpt from the code snippet I'm using:

```java
static void GUIClick(InventoryInteractEvent event) {
    if (!(event.getInventory().getType().equals(InventoryType.CHEST))) return;
    if (!(event.getInventory().getHolder(true) instanceof SimSkillGUIHolder)) return;
    // Rest of the code...
}
```
I have observed that the delay occurs specifically when checking the getHolder method for barrel\chest\shulker_box containers. The delay is not present when checking double chests.
When there are items with a lot of lore rows in the container and a quick click on the backpack (or organise the backpack with a mod):think: 

Could you please provide some insights into why this discrepancy exists? Are there any known performance issues or optimizations related to the Inventory.getHolder method for barrel containers in Purpur? I would appreciate any guidance or suggestions to mitigate this performance impact.

Additionally, I have tested this issue on the latest version of Purpur (please let me know if any specific version is recommended for testing). If there are any specific details or test cases that would be helpful for you to understand and investigate this problem further, please let me know.

Thank you for your time and assistance. I look forward to hearing from you.:purpur: 

### Purpur version

Current: git-Purpur-1995 (MC: 1.20.1)*
Previous: git-Paper-169 (MC: 1.20.1)
* You are 55 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

Can Purpur provide a way to determine Inventory other than getHolder？

**Comment by granny** [comment]
> * You are 55 version(s) behind

> - [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.

You are *not* running the latest version of Purpur, so this issue is invalid as a result. I'll still respond to your query out of respect for your time, but please make sure to follow the template correctly in the future.

> [@Nullable](https://javadoc.io/doc/org.jetbrains/annotations/24.0.1/org/jetbrains/annotations/Nullable.html) [InventoryHolder](https://purpurmc.org/javadoc/org/bukkit/inventory/InventoryHolder.html) getHolder(boolean useSnapshot)
> Gets the block or entity belonging to the open inventory
> 
> Parameters:
>     useSnapshot - Create a snapshot if the holder is a tile entity

https://purpurmc.org/javadoc/org/bukkit/inventory/Inventory.html#getHolder(boolean)

By setting `useSnapshot` to `true`, you're creating a complete copy of the TileEntity that you're checking every time the `InventoryInteractEvent` is emitted. This will, of course, have a significant performance impact. Since you're only using this method for checking the container type, you'll want to pass `false` instead.

**Comment by 5522-VVII** [comment]
> > * You are 55 version(s) behind
> 
> > * [x]  I am running the latest version of Purpur available from https://purpurmc.org/downloads.
> 
> You are _not_ running the latest version of Purpur, so this issue is invalid as a result. I'll still respond to your query out of respect for your time, but please make sure to follow the template correctly in the future.
> 
> > [@Nullable](https://javadoc.io/doc/org.jetbrains/annotations/24.0.1/org/jetbrains/annotations/Nullable.html) [InventoryHolder](https://purpurmc.org/javadoc/org/bukkit/inventory/InventoryHolder.html) getHolder(boolean useSnapshot)
> > Gets the block or entity belonging to the open inventory
> > Parameters:
> > useSnapshot - Create a snapshot if the holder is a tile entity
> 
> https://purpurmc.org/javadoc/org/bukkit/inventory/Inventory.html#getHolder(boolean)
> 
> By setting `useSnapshot` to `true`, you're creating a complete copy of the TileEntity that you're checking every time the 
`InventoryInteractEvent` is emitted. This will, of course, have a significant performance impact. Since you're only using this method for checking the container type, you'll want to pass `false` instead.


(now :Current: git-Purpur-2050 (MC: 1.20.1)*Previous: git-Purpur-1995 (MC: 1.20.1)* You are running the latest version)
Thanks for the reply！！although I have written my own plugins that use this approach. After constant checking I found that most of the plugins don't seem to use this approach, but they are still important to me such as LoneLibs(Precedence of ItemsAdder), Brewery, ChestSort, etc., and they cause the server to be very laggy, is there a way to modify purpur to help getholder() to change it to the default getholder(true) instead of getholder(false)?
(And can I ask why double chest isn't lagging?)
