### ISSUE TITLE
Chunk Errors Crashing The Server

### ISSUE THREAD

**Issue by AtmosphereRGS** [pl3xgaming/Purpur#1429]
### Spark link

https://spark.lucko.me/JqdaGOZ5m8

### Stack trace

Crash - https://mclo.gs/9GvFGOq

Regular log - https://mclo.gs/adlHvww

### Actions to reproduce (if known)

1. Have a separate spawn world

2. Create a survival world via Multiverse with Terra

3. Wait a while and the server eventually gets a chunk error and crashes wiping the inventories of all online players

### Purpur version

git-Purpur-2053 (MC: 1.20.1)*

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

I have a separate world for the spawn and used Multiverse to create a survival world with Terra. However, the server randomly crashes. The 6th and before it would provide a crash report but now it just instantly crashes with nothing in log and no crash report generated. It seems to be just 2 random chunks causing it at this point - one of which is in the crash log above. Asked for support days ago in Terra's discord but no response. Hopefully the fine folks of Purpur have any ideas :)

**Comment by granny** [comment]
1. Were you able to replicate this issue with only Multiverse/Terra installed?
2. Have you attempted to replicate this using the latest version of Paper or Pufferfish? Purpur itself doesn't make any changes in the code in regards to Chunk Generation, so I don't believe it's an issue that stems from us.

**Comment by granny** [comment]
Closing since there hasn't been a response in 2 days & because I don't believe that this is a Purpur issue. If you'd like, you can try joining our discord to see if someone can help you figure out what's wrong with your server.
