### ISSUE TITLE
Items fire immunity is not works

### ISSUE THREAD

**Issue by Aeon2927** [pl3xgaming/Purpur#1431]
### Spark link

https://spark.lucko.me/6KEyqI3HP9

### Expected behavior

I have inserted in all immunity rows the same items. Example:
      item:
        immune:
          cactus:
          - minecraft:diamond
          explosion: 
          - minecraft:diamond
          fire: 
          - minecraft:diamond
          lightning: 
          - minecraft:diamond
Everything should to work in the same way

### Observed/Actual behavior

Items have cactus, explosion and lightning immunities, but they disappear in a regular fire and in a lava 

### Steps/models to reproduce

Set all immunities for the same items. Try to destroy it by those ways

### Purpur version

version
[22:46:45 INFO]: Checking version, please wait...
[22:46:45 INFO]: Current: git-Purpur-2054 (MC: 1.20.1)*
Previous: git-Purpur-2035 (MC: 1.20.1)
* You are 2 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

I'm using not the latest version of purpur, but this bug lasts pretty long time, so I think that having the latest version is not matter now

**Comment by Aeon2927** [comment]
Just tested on the separate clean server with git-Purpur-2056. The problem is here too

**Comment by BillyGalbreath** [comment]
Are the items _actually_ despawned, or is this just a client desync? Try walking to where the item _should_ be and see if you can pick it up.

There is a Purpur client mod for fabric which fixes this desync. https://modrinth.com/mod/purpurclient

Sadly it doesn't seem to be updated anymore. Might want to bug the devs about that ;)

**Comment by Aeon2927** [comment]
That's not the desync. I have dropped 10 stacks of diamonds on the burning netherrack and they are disappeared. Walking on that netherrack gives back nothing.
The problem was not existed in 1.19
