### ISSUE TITLE
Beehives release duping bees

### ISSUE THREAD

**Issue by AshKiano** [pl3xgaming/Purpur#1436]
### Spark link

https://spark.lucko.me/Hh9udYqjWY

### Expected behavior

Bees will be released from hive when this code used, it works in spigot and paper, but not purpur: 
final List<Bee> bees = hive.releaseEntities();

### Observed/Actual behavior

Now bees get released, but thea are still inside too, so they duplicate.

### Steps/models to reproduce

Use plugin HiveChecker and try manually release bees from hive.

### Purpur version

git-Purpur-2004 (MC: 1.20.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by Krakenied** [comment]
What about Pufferfish?

**Comment by Krakenied** [comment]
I managed to reproduce the dupe some months ago but I was unable to reproduce it with a clean config

**Comment by AshKiano** [comment]
Do you have any idea what setting could it be?

**Comment by Krakenied** [comment]
It seems to be caused by that patch but there is no config option
https://github.com/PurpurMC/Purpur/blob/fdadc8db2074dba80babc97ad1cb91240fa5d372/patches/server/0297-Stored-Bee-API.patch#L96-L103

**Comment by Krakenied** [comment]
And nothing changed (intentionally or not) since the original implementation

**Comment by AshKiano** [comment]
Yeah it seems like that problem...

**Comment by AshKiano** [comment]
So can someone fix it please, it would help me a lot

**Comment by granny** [comment]
@EOT3000 any chance you could take a look? Looks like we managed to overlook this issue with your PR. I'm able to reproduce it with the following code:

```java
public final class Testing extends JavaPlugin implements Listener {
    @Override
    public void onEnable() {
        this.getServer().getPluginManager().registerEvents(this, this);
    }

    @EventHandler(ignoreCancelled = false, priority = EventPriority.NORMAL)
    public void onPlayerClicked(PlayerInteractEvent event) {
        // ignore if not main hand
        if (event.getHand().equals(EquipmentSlot.OFF_HAND)) return;

        // ignore if not right click
        if (event.getAction().isLeftClick()) return;

        // ignore if not a stick
        if (!event.getMaterial().equals(Material.STICK)) return;

        // ignore if not a beehive
        if (!(event.getClickedBlock() != null && event.getClickedBlock().getState() instanceof Beehive beehive)) return;

        List<Bee> bees = beehive.releaseEntities();
    }
}
```

With this test plugin running, right-clicking a beehive with a stick will run the `beehive#releaseEntities()` method.

**Comment by EOT3000** [comment]
I believe I did that to fix an issue where if you stored a snapshot of the block, released the bees, then called update() on the block snapshot, since it released the bees from the block, and not from the snapshot, updating the block would put the bees back in (even though a copy of the bees were already in the world), though I might be misremembering. I don't know why I didn't see that it would cause this issue. It looks like you already fixed this bug, that was just why I think I did that.

**Comment by granny** [comment]
> if you stored a snapshot of the block, released the bees, then called update() on the block snapshot, since it released the bees from the block, and not from the snapshot, updating the block would put the bees back in (even though a copy of the bees were already in the world)
@EOT3000

Can reproduce with the code below... This is getting annoying lol.

```java
public final class Testing extends JavaPlugin implements Listener {
    @Override
    public void onEnable() {
        this.getServer().getPluginManager().registerEvents(this, this);
    }

    @EventHandler(ignoreCancelled = false, priority = EventPriority.NORMAL)
    public void onPlayerClicked(PlayerInteractEvent event) {
        // ignore if not main hand
        if (event.getHand().equals(EquipmentSlot.OFF_HAND)) return;

        // ignore if not right click
        if (event.getAction().isLeftClick()) return;

        // ignore if not a stick
        if (!event.getMaterial().equals(Material.STICK)) return;

        // ignore if not a beehive
        if (!(event.getClickedBlock() != null && event.getClickedBlock().getState() instanceof Beehive beehive)) return;

        List<Bee> bees = beehive.releaseEntities();
        beehive.update();
    }
}
```

**Comment by granny** [comment]
Nevermind. Can reproduce on Paper as well so this is technically Working As Intended :)

**Comment by AshKiano** [comment]
So you think that this error originated from paper and not purpur?

**Comment by granny** [comment]
Nono, I was commenting on the problem that EOT3000 brought up in regards to my fix. The error itself originated from Purpur and it's been fixed.
