### ISSUE TITLE
(Suggestion) Option to change explosion damage calculation

### ISSUE THREAD

**Issue by imDaniX** [pl3xgaming/Purpur#144]
Apparently, right now if you have your feet covered from explosions, you will receive almost no damage. So, I'm suggesting to add an option to change it - calculate the damage for both legs and head, and then average them.

**Comment by BillyGalbreath** [comment]
Do you have `optimize-explosions` enabled in `paper.yml`? Because that optimization picks either your feet _or_ your head as the point to check. Disabling that optimization will check the full hitbox.

**Comment by imDaniX** [comment]
@BillyGalbreath Oh, thank you. It actually helped the situation. Sorry for creating an useless issue.
