### ISSUE TITLE
World loading at start slow

### ISSUE THREAD

**Issue by samuxita** [pl3xgaming/Purpur#1442]
### Spark link

https://spark.lucko.me/PLB8GMFjBB

### Description of issue

There are serious performance issues, such as when you first enter the server, the world is not visible, and it takes a few seconds before it becomes visible. This problem occurs on various hosting versions that have been tried. Another issue is that when flying, chunks do not load in time. None of these issues occurred in the past and do not currently occur on vanilla or spigot.

### Purpur version

latest

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [ ] My version of Minecraft is supported by Purpur.

**Comment by SrBedrock** [comment]
![image](https://github.com/PurpurMC/Purpur/assets/51332006/b2386bd8-be47-4cc6-b42d-6694f99daf29)

**Comment by granny** [comment]
Feel free to ask for help with performance issues in #help-and-support of our discord server.
