### ISSUE TITLE
After changing engine from pufferfish to purpur server does not start.

### ISSUE THREAD

**Issue by shaqupl** [pl3xgaming/Purpur#1444]
### Spark link

No spark

### Expected behavior

Server starts normal

### Observed/Actual behavior

---- Minecraft Crash Report ----
// // DO NOT REPORT THIS TO PAPER! REPORT TO PURPUR INSTEAD!// There are four lights!

Time: 2023-10-09 22:52:25
Description: Exception in server tick loop

org.spongepowered.configurate.serialize.SerializationException: [entities, spawning, monster-spawn-max-light-level] of type java.lang.Integer: java.lang.NumberFormatException: For input string: "default"
	at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:346)
	at org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$9(NumericSerializers.java:254)
	at org.spongepowered.configurate.serialize.FunctionScalarSerializer.deserialize(FunctionScalarSerializer.java:40)
	at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:115)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48)
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48)
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48)
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204)
	at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151)
	at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520)
	at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:407)
	at io.papermc.paper.configuration.Configurations.initializeWorldDefaultsConfiguration(Configurations.java:154)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:211)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: org.spongepowered.configurate.serialize.SerializationException: [entities, behavior, zombie-villager-infection-chance] of type java.lang.Double: java.lang.NumberFormatException: For input string: "default"
		at org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$3(NumericSerializers.java:144)
		... 19 more
	Caused by: java.lang.NumberFormatException: For input string: "default"
		at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
		at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
		at java.base/java.lang.Double.parseDouble(Double.java:651)
		at org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$3(NumericSerializers.java:142)
		... 19 more
Caused by: java.lang.NumberFormatException: For input string: "default"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:344)
	... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 4.18.0-425.13.1.el8_7.x86_64
	Java Version: 17.0.8.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 563655320 bytes (537 MiB) / 1073741824 bytes (1024 MiB) up to 15032385536 bytes (14336 MiB)
	CPUs: 5
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 47738.24
	Virtual memory used (MB): 49277.92
	Swap memory total (MB): 15692.00
	Swap memory used (MB): 7477.21
	JVM Flags: 20 total; -Xms1G -Xmx14G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	CraftBukkit Information: 
   Running: Purpur version git-Purpur-2062 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) false
   Plugins: {}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { WAITING Log4j2-AsyncAppenderEventDispatcher-1-Async: [java.base@17.0.8.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.8.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.8.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465), java.base@17.0.8.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436), java.base@17.0.8.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.8.1/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:82), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:74)], TIMED_WAITING Craft Scheduler Thread - 2: [java.base@17.0.8.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.8.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.8.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833)], WAITING RegionFile I/O Thread #0: [java.base@17.0.8.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)], RUNNABLE Notification Thread: [], WAITING Worker-Main-1: [java.base@17.0.8.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.8.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.8.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465), java.base@17.0.8.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436), java.base@17.0.8.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.8.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833)], RUNNABLE DestroyJavaVM: [], TIMED_WAITING Common-Cleaner: [java.base@17.0.8.1/java.lang.Object.wait(Native Method), java.base@17.0.8.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.8.1/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140), java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833), java.base@17.0.8.1/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)], WAITING Tuinity Chunk System Worker #0: [java.base@17.0.8.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)], TIMED_WAITING Yggdrasil Key Fetcher: [java.base@17.0.8.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.8.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672), java.base@17.0.8.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@17.0.8.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Craft Scheduler Thread - 0: [java.base@17.0.8.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.8.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.8.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING process reaper: [java.base@17.0.8.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.8.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.8.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Craft Scheduler Thread - 1: [java.base@17.0.8.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.8.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.8.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Keep-Alive-Timer: [java.base@17.0.8.1/java.lang.Thread.sleep(Native Method), java.base@17.0.8.1/sun.net.www.http.KeepAliveCache.run(KeepAliveCache.java:238), java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833), java.base@17.0.8.1/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)], TIMED_WAITING Timer hack thread: [java.base@17.0.8.1/java.lang.Thread.sleep(Native Method), net.minecraft.SystemUtils$7.run(SystemUtils.java:712)], WAITING JNA Cleaner: [java.base@17.0.8.1/java.lang.Object.wait(Native Method), java.base@17.0.8.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.8.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), com.sun.jna.internal.Cleaner$1.run(Cleaner.java:58)], RUNNABLE Server thread: [java.base@17.0.8.1/java.lang.Thread.dumpThreads(Native Method), java.base@17.0.8.1/java.lang.Thread.getAllStackTraces(Thread.java:1662), org.bukkit.craftbukkit.v1_20_R1.CraftCrashReport.get(CraftCrashReport.java:33), org.bukkit.craftbukkit.v1_20_R1.CraftCrashReport.get(CraftCrashReport.java:17), net.minecraft.SystemReport.a(SystemReport.java:62), net.minecraft.CrashReport.<init>(CrashReport.java:38), net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1277), net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1221), net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322), net.minecraft.server.MinecraftServer$$Lambda$4676/0x00007f7e68a5b0e8.run(Unknown Source), java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833)], WAITING Finalizer: [java.base@17.0.8.1/java.lang.Object.wait(Native Method), java.base@17.0.8.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.8.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), java.base@17.0.8.1/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)], RUNNABLE Reference Handler: [java.base@17.0.8.1/java.lang.ref.Reference.waitForReferencePendingList(Native Method), java.base@17.0.8.1/java.lang.ref.Reference.processPendingReferences(Reference.java:253), java.base@17.0.8.1/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)], TIMED_WAITING Craft Scheduler Thread - 3: [java.base@17.0.8.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.8.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.8.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833)], RUNNABLE Signal Dispatcher: [], RUNNABLE ServerMain: [io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader.generateBFSOrder(RegionizedPlayerChunkLoader.java:347), io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.<clinit>(RegionizedPlayerChunkLoader.java:389), java.base@17.0.8.1/java.lang.Class.forName0(Native Method), java.base@17.0.8.1/java.lang.Class.forName(Class.java:375), org.bukkit.craftbukkit.Main.tryPreloadClass(Main.java:395), org.bukkit.craftbukkit.Main.tryPreloadClass(Main.java:391), org.bukkit.craftbukkit.Main.main(Main.java:384), java.base@17.0.8.1/java.lang.invoke.LambdaForm$DMH/0x00007f7e68011000.invokeStatic(LambdaForm$DMH), java.base@17.0.8.1/java.lang.invoke.LambdaForm$MH/0x00007f7e68011c00.invoke(LambdaForm$MH), java.base@17.0.8.1/java.lang.invoke.LambdaForm$MH/0x00007f7e68011800.invoke_MT(LambdaForm$MH), app//io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42), app//io.papermc.paperclip.Paperclip$$Lambda$23/0x00007f7e6800d458.run(Unknown Source), java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833)],}
   
   Force Loaded Chunks: {}
	Server Running: true
	Player Count: 0 / 9999; []
	Data Packs: vanilla, file/bukkit
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'Purpur'
	Type: Dedicated Server (map_server.txt)

### Steps/models to reproduce

1. Change engine from pufferfish to purpur
2. Start server
3. Server not starting

### Purpur version

Purpur version git-Purpur-2062 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) false

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Ya'll really got to read the text presented to you.. It's literally telling you what is wrong, so that you can fix it yourself..

```
org.spongepowered.configurate.serialize.SerializationException: [entities, spawning, monster-spawn-max-light-level] of type java.lang.Integer: java.lang.NumberFormatException: For input string: "default"
```
```
Suppressed: org.spongepowered.configurate.serialize.SerializationException: [entities, behavior, zombie-villager-infection-chance] of type java.lang.Double: java.lang.NumberFormatException: For input string: "default"
```
