### ISSUE TITLE
GameProfile now requires both the id and name, but OfflinePlayer doesn't allow you to specify both.

### ISSUE THREAD

**Issue by CC007** [pl3xgaming/Purpur#1445]
### Spark link

n/a

### Expected behavior

Being able to create a GameProfile object with either the id or the name and therefore the following code working:

```java
meta.setOwningPlayer(Bukkit.getOfflinePlayer(NOTCH_UUID)); // meta is a SkullMeta object,
```

See authlib v4.0.43:
```java
public GameProfile(final UUID id, final String name) {
    this.properties = new PropertyMap();
    if (id == null && StringUtils.isBlank((CharSequence)name)) {
        throw new IllegalArgumentException("Name and ID cannot both be blank");
    }
    this.id = id;
    this.name = name;
}
```

### Observed/Actual behavior

Being forced to provide both the id AND the name:

![275263138-9f46b60a-e11e-43a6-9e8a-195d7db6d3ab](https://github.com/PurpurMC/Purpur/assets/5381337/f97561af-9d02-459c-b65e-a069f15cbb2b)

See authlib 5.0.47:

```java
public GameProfile(final UUID id, final String name) {
    this.properties = new PropertyMap();
    this.id = Objects.requireNonNull(id, "Profile ID must not be null");
    this.name = Objects.requireNonNull(name, "Profile name must not be null");
}
```
Also, there is no method to create an OfflinePlayer where you specify both the id and name, so setOwningPlayer will fail when providing it with an OfflinePlayer.

### Steps/models to reproduce

Code that triggered this issue:
```java
private void initSkullMeta(@NonNull ItemStack playerHeadItemStack, @NonNull Head head) {
    final var headSkullMeta = Optional.ofNullable((SkullMeta) playerHeadItemStack.getItemMeta());
    headSkullMeta.ifPresentOrElse(meta -> {
        meta.setOwningPlayer(Bukkit.getOfflinePlayer(NOTCH_UUID)); // <- exception thrown here
        // set other meta fields. Not relevant to this bug
        playerHeadItemStack.setItemMeta(meta);
    }, () -> {
        log.warn("Couldn't find player skull meta.");
    });
}
```

### Purpur version

Minecraft version: 1.20.2, confirmed using purpur 2074 and 2078

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

Issue found by a user of HeadsPluginAPI. I'm tracking the issue in https://github.com/CC007/HeadsPluginAPI/issues/31

**Comment by granny** [comment]
Are you able to reproduce this on the latest version of Purpur? If you can, could you try testing this on the latest version of Paper as well? If you can reproduce this on Paper, then it's not a Purpur issue. I'm hoping this was fixed with the most recent upstream I did. We don't have any patches that touch that area of the code, so I'm inclined to believe it's a Paper issue.

**Comment by CC007** [comment]
I'll ask the user who had the issue to try to reproduce it with the latest version. I'll report back once they tested it.

**Comment by CC007** [comment]
Same error: 
![afbeelding](https://github.com/PurpurMC/Purpur/assets/5381337/9bddb4a5-caef-4232-91f8-48b790340c56)
![afbeelding](https://github.com/PurpurMC/Purpur/assets/5381337/797f42e2-be55-4fff-8083-00e3f4b759ce)

**Comment by CC007** [comment]
I have checked with Paper 1.20.2 (240, which is latest) too now. Same issue:
![afbeelding](https://github.com/PurpurMC/Purpur/assets/5381337/44ab0989-95b7-4d94-908c-a12a37dd39fd)

**Comment by granny** [comment]
Needs to be reported to Paper then.
