### ISSUE TITLE
Bring back Async-Pathfinding patch

### ISSUE THREAD

**Issue by MVanilla** [pl3xgaming/Purpur#1448]
### Spark link

not need

### Description of issue

Bring back Async-Pathfinding patch. Petal gave up on maintaining this, but now Kaiiju is fixing bugs and updating it. (Kaiiju is a performance fork of Folia.)
Maintainer: Petal -> Kaiiju
The commit that removed this patch (Pufferfish): https://github.com/pufferfish-gg/Pufferfish/commit/d960687de285480bb7253e1280514cce98d9da10

Since Pufferfish only provides Async-Pathfinding in the premium version(Pufferfish+), it is very unlikely that he will add this patch again. So it would be great to add this to Purpur. And you can make this disableable in Purpur configuration.

---

(1.20.2)
https://github.com/KaiijuMC/Kaiiju/blob/dev/1.20.2/patches/server/0040-Async-path-processing.patch
https://github.com/Dreeam-qwq/Mirai/blob/purpur/1.20.2/patches/server/0075-Async-Pathfinding.patch

(1.20.1)
https://github.com/KaiijuMC/Kaiiju/blob/ver/1.20.1/patches/server/0043-Async-path-processing.patch
https://github.com/Dreeam-qwq/Mirai/blob/purpur/1.20.1/patches/server/0076-Async-Pathfinding.patch

### Purpur version

not need

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
Not happening.
