### ISSUE TITLE
I can't break/place block when other player has op.

### ISSUE THREAD

**Issue by Vate3** [pl3xgaming/Purpur#145]
When I set an op from the console level and from another account (which has no op) I want to destroy/place a block, it is impossible. After deop my 1st account, all works proprerly.
This problem occurs on this engine as well as on Tuinity.

Plugins: Skellett, SkQuery, SkRayFall, Skript.

Sorry for my bad English.

**Comment by katekerllenevich** [comment]
Purpur is a fork of Tuinity, as such all issues on tuinity will (most likely) be on purpur. You already opened an issue on tuinity (Spottedleaf/Tuinity#237). Please don't open issues on multiple trackers.

**Comment by Vate3** [comment]
I know that, but I thought other developers were working on this engine, sorry.

**Comment by katekerllenevich** [comment]
Different developers are working on Purpur, but this is a tuinity (maybe even a paper) issue.

**Comment by jpenilla** [comment]
Without further details, this looks to me like a support question, not an issue. Feel free to join our Discord and ask for help, or open a more detailed report, including troubleshooting without plugins, and testing on Paper.

**Comment by BillyGalbreath** [comment]
This is vanilla behavior, btw.

https://minecraft.gamepedia.com/Spawn_protection
