### ISSUE TITLE
Publsih to maven local doesn't work

### ISSUE THREAD

**Issue by vortexthedev** [pl3xgaming/Purpur#1454]
### Spark link

no

### Expected behavior

pushed libs to my maven local so I can use it

### Observed/Actual behavior

Execution failed for task ':generateDevelopmentBundle'.
> java.io.IOException: Cannot run program "diff": CreateProcess error=2, Не удается найти указанный файл

### Steps/models to reproduce

Run publishToMavenLocal and wait

### Purpur version

Current: git-Purpur-"26433d6" (MC: 1.20.2)*
Previous: git-Purpur-"4510336" (MC: 1.20.1)
* Error obtaining version information

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
Works on my machine :shrug:
