### ISSUE TITLE
Mob riding bug

### ISSUE THREAD

**Issue by LucidAPs** [pl3xgaming/Purpur#1455]
### Observed/Actual behavior

lost connection: Invalid move player packet received
Disconnected on accept teleport packet. Was not expecting position data from client at this time

sends this error and keeps disconnecting players when they disconnect while riding a mob and then try to connect again
its a specially problematic when failover-on-unexpected-server-disconnect is enabled on velocity

### Steps/models to reproduce

Under a network use Velocity 3.2.0-SNAPSHOT Build 294
backend purpur 1.20.2  Build 2088
make a mob like a bee ridable and controllable
ride the bee
disconect
reconnect

### Purpur version

purpur 1.20.1  Build 2088

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by YouHaveTrouble** [comment]
You're missing spark report

**Comment by LucidAPs** [comment]
I cannot recreate it without plugins. I am closing this.
