### ISSUE TITLE
Sheep do not eat when PlayerNaturallySpawnCreaturesEvent is cancelled

### ISSUE THREAD

**Issue by radiant-ai** [pl3xgaming/Purpur#1456]
### Spark link

https://spark.lucko.me/MV4KLUeYVK

### Expected behavior

Sheep should grass and regrow their wool when all `PlayerNaturallySpawnCreaturesEvent` are cancelled.

### Observed/Actual behavior

Sheep do not eat grass and regrow their wool when all `PlayerNaturallySpawnCreaturesEvent` are cancelled.

### Steps/models to reproduce

Make a plugin:
```
package com.example.test;

import com.destroystokyo.paper.event.entity.PlayerNaturallySpawnCreaturesEvent;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.JavaPlugin;

public final class Test extends JavaPlugin {

    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(new Listener() {
            @EventHandler(ignoreCancelled = true)
            public void onSpawnChunkMap(PlayerNaturallySpawnCreaturesEvent event) {
                event.setCancelled(true);
            }
        }, this);
    }

    @Override
    public void onDisable() {
        // Plugin shutdown logic
    }
}
```
Start server with a plugin, spawn some sheep and shear them. Notice they refuse to eat.

### Purpur version

```
> version
[22:05:59 INFO]: Checking version, please wait...
[22:05:59 INFO]: Current: git-Purpur-2088 (MC: 1.20.2)*
* You are running the latest version
```

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

The issue is not present on Paper-280.

**Comment by radiant-ai** [comment]
[test-1.0-SNAPSHOT.jar.zip](https://github.com/PurpurMC/Purpur/files/13292006/test-1.0-SNAPSHOT.jar.zip)
Simple plugin to test the issue.

**Comment by granny** [comment]
We don't touch anything related to `PlayerNaturallySpawnCreaturesEvent`, and build 2088 is not aligned with Paper's 280 build. Are you able to reproduce with Purpur-2090?

**Comment by radiant-ai** [comment]
> We don't touch anything related to `PlayerNaturallySpawnCreaturesEvent`, and build 2088 is not aligned with Paper's 280 build. Are you able to reproduce with Purpur-2090?

Hey! I don't know how I tested before but I see the same issue in Paper now... I guess I will take this to the Paper issue tracker then. Thank you.

**Comment by granny** [comment]
No worries!
