### ISSUE TITLE
Fall damage

### ISSUE THREAD

**Issue by Pi-T3ch** [pl3xgaming/Purpur#1457]
### Spark link

https://spark.lucko.me/1ZJLnL6ZjO

### Expected behavior

Receive the normal fall damage on Minecraft.

### Observed/Actual behavior

When a player falls down, the player receive damage on each movement (walking or moving mouse) and finally dies faster. feather fall on boots, doesn't have the effect or less damage on falls..

I don't know if it is an issue or an option configurable.

Thank you,

### Steps/models to reproduce

Just jump and fall receiving damage.

### Purpur version

 git-Purpur-2089 (MC: 1.20.2)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
I don't understand your issue. Are you able to reproduce this without plugins?

**Comment by Pi-T3ch** [comment]
Yea, I have just tried. NoCheatPlus cause this issue.

Sorry, you can close this issue.
