### ISSUE TITLE
ensure-secure-profile error

### ISSUE THREAD

**Issue by LittleShyStar02** [pl3xgaming/Purpur#1459]
### Spark link

https://spark.lucko.me/ThiJHVbcD6

### Expected behavior

Player can write in chat

### Observed/Actual behavior

With ensure-secure-profilo=true player cannot write in chat (all players operator and guests)

### Steps/models to reproduce

Run purpur build 2091.
Enable ensure-secure-profile (ensure-secure-profile=true on server.properties)
Restart server
Join server
Send message in chat

Server run under proxy (waterfall latest build 554)

### Purpur version

latest version
build 2091

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by YouHaveTrouble** [comment]
Context from discord conversation:
Proxy under which server was being run in offline mode, not providing the chat secure profiles
