### ISSUE TITLE
(Suggestion) Exclusive nether portal linking

### ISSUE THREAD

**Issue by femboyfin** [pl3xgaming/Purpur#146]
Having a config option to make nether portal linking exclusive (one overworld portal only links to one nether portal and vice versa in pairs) since the default of overworld portals within 16 nether blocks of each other linking is very annoying for servers with players that live close to each other in one general region.

**Comment by BillyGalbreath** [comment]
Not really possible with how nether portals work. You can change their search radius in `paper.yml` to have finer control over their ranges, but ultimately players just need to understand how nether portals work. It's not rocket science.

![image](https://user-images.githubusercontent.com/332527/106389552-692b4b80-63a9-11eb-96b5-7810bda6be27.png)
