### ISSUE TITLE
Buried treasure maps

### ISSUE THREAD

**Issue by Nicolol1234** [pl3xgaming/Purpur#1462]
### Spark link

https://spark.lucko.me/Ca7y18HA0o

### Description of issue

Opening a buried treasure causes a massive lag, and taking the map in the inventory make me unable to join the server

### Purpur version

[20:14:15 INFO]: Checking version, please wait...
[20:14:16 INFO]: Current: git-Purpur-2062 (MC: 1.20.1)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

![image](https://github.com/PurpurMC/Purpur/assets/98613217/b08a3742-38b8-4f5b-be1e-2a3e669407ea)
This is my error while connecting to the server

**Comment by RhythmicSys** [comment]
This is, unfortunately, a vanilla issue. There are options within both paper and purpur to disable or limit treasure searching. 
Paper has an option to only look for already found chests, and to disable cartographers from generating treasure maps. Purpur has an option for disabling dolphins from searching for treasure.

**Comment by Nicolol1234** [comment]
Oh i see
