### ISSUE TITLE
Failed to handle packet net.minecraft.network.protocol.game.PacketPlayInWindowClick@5e107648

### ISSUE THREAD

**Issue by JamieIsGeek** [pl3xgaming/Purpur#1463]
### Spark link

Unable to get one during the lag but here is one now: https://spark.lucko.me/OGxCNsPt6m

### Stack trace

https://paste.gg/p/anonymous/572eb75263ec4f61ae05a869d9c2117a

This is the server timeout message we got: https://paste.gg/p/anonymous/b693078c554747ff8ef5b1421bc163d1

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

Only thing we are aware of is that this managed to hault all server activity for 45 seconds at least and then everyone got kicked. Basically made the server unplayable.

**Comment by JanTuck** [comment]
The stacktrace is from 1.20.1, latest is 1.20.2 and the issue is fixed there.

**Comment by JamieIsGeek** [comment]
Ok will update asap
