### ISSUE TITLE
random html warns 

### ISSUE THREAD

**Issue by SL-69** [pl3xgaming/Purpur#1471]
### Spark link

https://spark.lucko.me/eCN9juY89w

### Expected behavior

work without randomly big warns

### Observed/Actual behavior

https://logpaste.com/cqvIW20A

### Steps/models to reproduce

it appears randomly, I noticed it several times, really

### Purpur version

 Current: git-Purpur-2120 (MC: 1.20.4)*
Previous: git-Purpur-2119 (MC: 1.20.4)
* You are running the latest version
>

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

warnings appear both when the server is turned on and while it is running

**Comment by granny** [comment]
not a purpur issue.
