### ISSUE TITLE
Dragon death sound is everywhere

### ISSUE THREAD

**Issue by BlindMag** [pl3xgaming/Purpur#1473]
### Spark link

https://spark.lucko.me/KLyd3BUmK6

### Expected behavior

Dragon sounds should only be happening in a radius defined in the spigot.yml config

### Observed/Actual behavior

Dragon sound is happening globally and ignores the settings in spigot.yml for dragon death radius sounds.

### Steps/models to reproduce

kill dragon, all players can hear it everywhere on the server

### Purpur version

git-Purpur-2122

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by YouHaveTrouble** [comment]
`/gamerule globalSoundEvents false`
Paper fixed a bug where vanilla gamerule was ignored. The gamerule has priority over the config setting :)

**Comment by BlindMag** [comment]
Thank you so much!
