### ISSUE TITLE
Bug between Paper and Purpur

### ISSUE THREAD

**Issue by NoltoxGit** [pl3xgaming/Purpur#1476]
### Spark link

https://spark.lucko.me/Gh6o24LAKI

### Expected behavior

Ensure that mobcaps values are the same between Paper and Purpur

### Observed/Actual behavior

I just found a problem between Paper and Purpur, the `/paper mobcaps` is not the same (without plugin), why ?

1st screen is the mobcaps with Paper : https://prnt.sc/VY2GB6coLuOl
2nd screen is the mobcaps with Purpur : https://prnt.sc/gorCwVkcz2Dp

### Steps/models to reproduce

1. Start a server with Paper
2. Start a server with Purpur
3. See the difference

### Purpur version

\> version
[21:47:24 INFO]: Checking version, please wait...
[21:47:24 INFO]: Current: git-Purpur-2127 (MC: 1.20.4)*
Previous: git-Paper-392 (MC: 1.20.4)
\* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
Are you able to reproduce this on Pufferfish?

**Comment by NoltoxGit** [comment]
> Are you able to reproduce this on Pufferfish?

I think so, and I've also seen users on the Pufferfish side reporting the same bug on their Discord.

**Comment by granny** [comment]
Then it's most likely a Pufferfish issue and not a Purpur issue. Closing this issue unless more information is found that indicates it's a Purpur issue
