### ISSUE TITLE
The problem with the hopper

### ISSUE THREAD

**Issue by TianmuTNT** [pl3xgaming/Purpur#1477]
### Spark link

https://spark.lucko.me/KWHNvhAkp7

### Expected behavior

I want my hopper to work like Vanilla

### Observed/Actual behavior

My hopper leaks two items at a time
And this situation only exists when both the top and bottom are hoppers

### Steps/models to reproduce

Just follow the usual steps to open a purpur server, place a hopper below and a hopper above, and place some items in the top hopper to see that the hopper is leaking two items at once

### Purpur version

version
[04:16:06 INFO]: Checking version, please wait...
[04:16:06 INFO]: Current: git-Purpur-2128 (MC: 1.20.4)*
Previous: git-Purpur-1985 (MC: 1.19.4)
You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

My English is not good, and I am using a translator. If you don't understand what I am saying, I'm sorry
When I tested, I did not change any configuration files or install any plugins
I did not test whether this situation exists on paper, but it does exist on purpur

**Comment by TianmuTNT** [comment]
If you think this is my personal problem, please make sure to tell me how to solve it!

**Comment by CatTeaA** [comment]
这不是正常行为吗，上面的漏斗会移动一个物品到下面容器，下面的漏斗会吸上面容器一个物品，刚好两个
