### ISSUE TITLE
Custom placeholders dont work

### ISSUE THREAD

**Issue by dmitr-ukhin** [pl3xgaming/Purpur#148]
**Describe the bug**
I have custom placeholders on my server. They dont work with purpur (version 1.16.4, 1.16.5) (config attached)

**To Reproduce**
Last tested purpur version: purpurclip-1.16.5-961.jar
PlaceholderAPI version: PlaceholderAPI 2.10.9
PlaceholdersAPI config and plugins used in custom scripts attached

**Screenshots or Videos**
Purpur core:
![image](https://user-images.githubusercontent.com/67899937/105693096-5f6c9880-5f10-11eb-8631-53a807b0c77c.png)
Other core:
![image](https://user-images.githubusercontent.com/67899937/105693162-77441c80-5f10-11eb-96ce-8fdcc1a9e7ac.png)

**Plugins**
![image](https://user-images.githubusercontent.com/67899937/105693229-8925bf80-5f10-11eb-8a95-32e32e4377b3.png)

**Version**
![image](https://user-images.githubusercontent.com/67899937/105693482-d6099600-5f10-11eb-981c-418a9e080fd9.png)

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
no:
![image](https://user-images.githubusercontent.com/67899937/105693753-2b45a780-5f11-11eb-8b90-e91da47cf4c4.png)

**Additional context**
All important files attached:
[bug.zip](https://github.com/pl3xgaming/Purpur/files/5865890/bug.zip)
broken scripts located at PlaceholderAPI/javascripts

**Comment by BillyGalbreath** [comment]
Purpur ships with an internal JavaScript engine called Rhino. PlaceHolderAPI seems to be trying to use it by default, but your scripts are coded against Nashorn script engine.

To fix, specify the Nashorn script engine in PlaceHolderAPI's `config.yml`

```yaml
expansions:
  javascript:
    engine: nashorn
```
