### ISSUE TITLE
teleport-if-outside-border broken

### ISSUE THREAD

**Issue by ItsMCB** [pl3xgaming/Purpur#1481]
### Spark link

https://spark.lucko.me/SAsY5KOv0X

### Expected behavior

I expect to be teleported to the spawn of the world when I move outside of the world border.

### Observed/Actual behavior

Nothing happens when I move outside of the world border despite having the setting enabled.

### Steps/models to reproduce

1) Set the `teleport-if-outside-border` config option in `purpur.yml` to `true`.
2) Try to escape the border in spectator mode in a void world.

### Purpur version

Current: git-Purpur-2136 (MC: 1.20.4)*
Previous: git-Purpur-2134 (MC: 1.20.4)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

The following screenshot displays the issue. I listed plugins to show that there are no plugin conflicts causing the issue.

![image](https://github.com/PurpurMC/Purpur/assets/33915290/1cac8f3a-b2f9-40a1-91e2-b31499544c7e)

**Comment by Krakenied** [comment]
Your damage per block has to be set to something > 0
