### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by japlic** [pl3xgaming/Purpur#1483]
### Spark link

sparkeroor.com

### Expected behavior

* What went wrong:
Script compilation errors:

  Line 36:     val projName = name.lowercase(Locale.ENGLISH)
                                   ^ Unresolved reference: lowercase

  Line 37:     include(projName)
               ^ Overload resolution ambiguity:
                   public open fun include(vararg p0: String!): Unit defined in org.gradle.api.initialization.Settings
                   public abstract fun include(p0: (Mutable)Iterable<String!>!): Unit defined in org.gradle.api.initialization.Settings

2 errors

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

### Observed/Actual behavior

that

### Steps/models to reproduce

no

### Purpur version

1.20.1

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by skyeredwood** [comment]
this is not an issue with purpur you've used a method that doesn't exist or spelt something wrong in your gradle config. go to the line reference given in your editor and fix it instead
