### ISSUE TITLE
No any monster spawn

### ISSUE THREAD

**Issue by AliyahZombie** [pl3xgaming/Purpur#1486]
### Spark link

https://spark.lucko.me/Nn6iSVTiib

### Expected behavior

monster spawning 

### Observed/Actual behavior

animals spawn correctly, but no monster spawned

### Steps/models to reproduce

Create any new world 

### Purpur version

current: git-Purpur-2140
previous: git-Purpur-2139
![Screenshot_20240212-111349_Lemur Browser](https://github.com/PurpurMC/Purpur/assets/61051765/363454b3-19e8-4334-b34f-b0abcfb4b4d5)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

I tried set difficulty to Hard and I ran /gamerule doModSpawning true
And I tried updating purpur but it didn't work

**Comment by granny** [comment]
Please join our discord for support. https://purpurmc.org/discord
