### ISSUE TITLE
allow-unsafe-enchants still works even if disabled

### ISSUE THREAD

**Issue by czychuuu** [pl3xgaming/Purpur#1495]
### Spark link

https://spark.lucko.me/qKqF0Cl3kJ

### Expected behavior

you cant put protection on a sword

### Observed/Actual behavior

protection book applies to sword
![image](https://github.com/PurpurMC/Purpur/assets/60987404/958eafe7-3b0a-4f91-a7ef-86e7c3443b3b)

### Steps/models to reproduce

  enchantment:
    allow-infinity-and-mending-together: true
    allow-infinity-on-crossbow: false
    allow-looting-on-shears: false
    anvil:
      allow-unsafe-enchants: false
      allow-inapplicable-enchants: false
      allow-incompatible-enchants: false
      allow-higher-enchants-levels: false

### Purpur version

[18:39:20 INFO]: Checking version, please wait...
[18:39:20 INFO]: Current: git-Purpur-2062 (MC: 1.20.1)*
* You are running the latest version

also same happens on
[18:40:06 INFO]: Checking version, please wait...
[18:40:07 INFO]: Current: git-Purpur-2141 (MC: 1.20.4)*
* You are 9 version(s) behind
Download the new version at: https://purpurmc.org/downloads

and
[18:54:27 INFO]: Checking version, please wait...
[18:54:27 INFO]: Current: git-Purpur-2150 (MC: 1.20.4)*
Previous: git-Purpur-2141 (MC: 1.20.4)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by Krakenied** [comment]
That's how vanilla works, change your gamemode to 0

**Comment by granny** [comment]
What @Krakenied said. You're able to do this when you're in creative mode.
