### ISSUE TITLE
 Sometimes tnt destroys ancient remnants.

### ISSUE THREAD

**Issue by ytpoma08** [pl3xgaming/Purpur#1496]
### Spark link

https://spark.lucko.me/RphwzQcNQB

### Expected behavior

Destroys stone or minerals except blocks that tnt cannot destroy.

### Observed/Actual behavior

The ancient wreckage was destroyed and the item did not drop.
Also, items around it did not drop.

### Steps/models to reproduce

1. Install the tnt on the ancient wreckage and ignite it.
2. tnt를 점화합니다.
3. TNT sometimes destroyed ancient remnants and deleted some items.

### Purpur version

Current: git-Purpur-2152 (MC: 1.20.4)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

All unsupported settings are allowed.

Additionally, the xray prevention function of the paper has been activated.
The remaining features only increase the default or rendering distance.

The RAM allocated to the server is 6 GB and the CPU of the server is i5 6200U.

**Comment by ElFrod0** [comment]
Just for clarification, did you mean Ancient Debris (minecraft:ancient_debris) ?

**Comment by granny** [comment]
I do not understand the issue. In vanilla, when Ancient Debris is dropped as an item entity, it can be destroyed through an explosion. When it is placed as a block, TNT does not break it. The latest version of Purpur does not differentiate from vanilla.
