### ISSUE TITLE
End Crystal in end issue.

### ISSUE THREAD

**Issue by arturek1666** [pl3xgaming/Purpur#1497]
### Spark link

https://spark.lucko.me/TEqthofgx2

### Expected behavior

It's expected for  the end crystal to explode on hitting it. 
(Please not I am not talking about placed end crystal as that works fine) 

### Observed/Actual behavior

The end crystal is not getting destroyed however if Dragon is next to crystal it actually damage the dragon while hitting end crystal.

### Steps/models to reproduce

The only thing required is to go to end and try to destroy the end crystal, that was generated by the world

### Purpur version

> purpur version
[20:46:47 INFO]: Checking version, please wait...
[20:46:47 INFO]: Current: git-Purpur-2153 (MC: 1.20.4)*
Previous: git-Purpur-2152 (MC: 1.20.4)
* You are running the latest version
I had updated version as I tested the newest and also has issue.
### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.
- [ ] I ticked all the boxes without actually reading them 🥇 

### Other

Please also note that I had tested older version of the purpur and it worked fine, I tested like 4-5 generation old ones. 
_No response_

### Video for reference:
https://youtu.be/3YkCXazifJ0

**Comment by granny** [comment]
![image](https://github.com/PurpurMC/Purpur/assets/43185817/6a20fd8f-1e2a-4cbc-8c51-3beec7583f26)

Set it back to `true`.

**Comment by arturek1666** [comment]
Thank you it worked, just strange that the previous version of purpur worked fine with the same settings, thank you.
