### ISSUE TITLE
No colors in console

### ISSUE THREAD

**Issue by Deb4ikOff** [pl3xgaming/Purpur#1498]
### Spark link

https://spark.lucko.me/6lvs9wb4c7

### Expected behavior

No colors in console, hard to read information
![изображение_2024-03-03_104703312](https://github.com/PurpurMC/Purpur/assets/69901675/7d8d3ce4-5cef-4cff-8a46-b34931627b11)

### Observed/Actual behavior

No colors in console

### Steps/models to reproduce

1. Run server 1.20.4 build 2152
2. Just see

### Purpur version

> version
[10:49:31 INFO]: Checking version, please wait...
[10:49:31 INFO]: Current: git-Purpur-2152 (MC: 1.20.4)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

On Patina 1.20.2 colors was be

**Comment by granny** [comment]
>  I ticked all the boxes without actually reading them

I see you've already asked in our discord for help, so I'm closing this issue unless it turns out to be an actual bug.
