### ISSUE TITLE
Expired chat suppression is not working

### ISSUE THREAD

**Issue by Strahilchu** [pl3xgaming/Purpur#1502]
### Spark link

I don't use Spark

### Expected behavior

For expired chat messages to not produce warning.

### Observed/Actual behavior

[17:51:44 WARN]: Received expired chat: 'Player'. Is the client/server system time unsynchronized?

### Steps/models to reproduce

Not sure, only one player has been able to have this "expired chat", even though it is suppressed in the config!

### Purpur version

git-Purpur-2160 (MC: 1.20.4)*

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by YouHaveTrouble** [comment]
![image](https://github.com/PurpurMC/Purpur/assets/6951472/d1251636-79cb-4eab-b9d0-4c330dca7091)
![image](https://github.com/PurpurMC/Purpur/assets/6951472/d8f6bf20-b3e5-4b43-b4c5-da22176bd521)

Invalid issue. Things we ask for are not optional.
