### ISSUE TITLE
(Suggestion) Add toggle for Ghast mobgreifing

### ISSUE THREAD

**Issue by soupglasses** [pl3xgaming/Purpur#151]
In the per world configuration, one can toggle both Creepers and Endermens `allow-greifing` setting. But ghast who are the main mobgriefers in the nether has no such option. This suggestion is to add a `allow-greifing` option to the ghast mob.

**Comment by encode42** [comment]
This can be done by setting `fireballs-bypass-mob-griefing` to `true` in the config.

**Comment by soupglasses** [comment]
@Encode42 Following the docs `fireballs-bypass-mob-griefing` is described as

> Set to true for fireballs to bypass the mob griefing gamerule

But i have the mobgreifing gamerule on and want to disable the Ghast fireballs from doing damage. So for my usecase i dont think that this config is useful for me. Unless im misunderstanding the documentation.

**Comment by encode42** [comment]
Oh, no, I misunderstood your question. The setting I referenced is the opposite of what you want and is available on everything that `mobGriefing` touches. You could set `mobGriefing` to `false` and set `bypass-mob-griefing` to `true` on all of the things you don't want to be disabled by the gamerule.

**Comment by soupglasses** [comment]
Thats a way to do it. But its also needs many changes in the config file simply to change the behaviour of one mob. It would be nice to have a `allow-greifing` for Ghasts as well, similar to Creepers and Endermen.

Feel free to close it if its not a feasible thing to implement, and also there is already a way to do this with purpur. It just has a lot of initial steps if you dont already have mobgreifing off.

**Comment by BillyGalbreath** [comment]
just touching base. this is a great idea, and i'll definitely add it soon(tm) ^_^

**Comment by BillyGalbreath** [comment]
Implemented in [build 977](https://ci.pl3x.net/job/Purpur/977/)

https://github.com/pl3xgaming/Purpur/commit/b15a2e9bf2569560a62a34956334708e602bc76e
