### ISSUE TITLE
AttributeModfiers is not removed when the player dies

### ISSUE THREAD

**Issue by huimanrmmm** [pl3xgaming/Purpur#1512]
### Spark link

https://spark.lucko.me/NnlzCaOpaP

### Expected behavior

All modifiers added by /attribute are removed upon death

### Observed/Actual behavior

The modifiers added by /attribute to still exist after rebirth

### Steps/models to reproduce

1. run /attribute @s minecraft:generic.armor modifier add 1-0-0-0-0 "" 1 add_value
2. run /attribute @s minecraft:generic.armor modifier value get 1-0-0-0-0
3. run /kill @s
4. Respawn
5. Run again /attribute @s minecraft:generic.armor modifier value get 1-0-0-0-0

### Purpur version

Current: git-Purpur-2193 (MC: 1.20.6)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
I am able to reproduce this issue on paper. Please pass this along to [their issue tracker](https://github.com/PaperMC/Paper/issues/new?assignees=&labels=status%3A+needs+triage%2Ctype%3A+bug&projects=&template=behavior-bug-or-plugin-incompatibility.yml).
