### ISSUE TITLE
the 'tps' command cannot use in rcon mode

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [pl3xgaming/Purpur#1518]
### Spark link

https://spark.lucko.me/SlBTYwUQDG

### Expected behavior

the 'tps' command can be use in rcon mode

### Observed/Actual behavior

the 'tps' command cannot use in rcon mode

### Steps/models to reproduce

https://github.com/PurpurMC/Purpur/assets/86163024/cea1fecc-dac1-47c5-aa30-5e559d31e2f2

use [NectarRCON](https://github.com/zkhssb/NectarRCON) Manager to connect the purpur server and send 'tps' command to server

### Purpur version

> version
[23:17:34 INFO]: Checking version, please wait...
[23:17:35 INFO]: Current: git-Purpur-2176 (MC: 1.20.4)*
Previous: git-Paper-496 (MC: 1.20.4)
* You are running the latest version

### Agreements

- [x] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by YouHaveTrouble** [comment]
![image](https://github.com/PurpurMC/Purpur/assets/6951472/07ed2e7b-aef3-4e22-85db-500b24fffee9)

**Comment by YuYue-Amatsuki** [comment]
> ![image](https://github.com/PurpurMC/Purpur/assets/6951472/07ed2e7b-aef3-4e22-85db-500b24fffee9)
> 

I'm sorry, because I'm not an English user and I don't understand the meaning. After your reminder,I used machine translation, and I have checked and I want to reopened this issue.


And this message is translated by machine, which may lead to incorrect grammar.

**Comment by YouHaveTrouble** [comment]
tps command is not a command added by purpur. Reproduce the issue on upstream (paper/spigot) and report it there.
