### ISSUE TITLE
People unable to join: getsockopt

### ISSUE THREAD

**Issue by NBS-Paste** [pl3xgaming/Purpur#1519]
### Spark link

https://spark.lucko.me/ehuLa9h5PF

### Expected behavior

Players able to join the server

### Observed/Actual behavior

when people not on host network they get getsockopt

### Steps/models to reproduce

Be in minecraft on friends pc
click onto server
unable to connect to server: getsockopt

### Purpur version

 Current: git-Purpur-2176 (MC: 1.20.4)*
* You are running the latest version
>

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

works on devices on host network

**Comment by YouHaveTrouble** [comment]
Cannot reproduce the issue. We do not have your friends PC.

**Comment by NBS-Paste** [comment]
I have this problem on all pcs trying to connect to my server. Here are a few forums I found that are also having this problem:
https://www.minecraftforum.net/forums/support/java-edition-support/3199164-connection-timed-out-getsockopt
https://www.reddit.com/r/Minecraft/comments/1cd38f7/cant_join_server_network_is_unreachable_getsockopt/

**Comment by granny** [comment]
If you're having the same issue they are, then it's definitely not a purpur issue. This would mean it's either an issue that stems all the way back to the vanilla server software, or a some misconfiguration on your part & your friend's part.

**Comment by NBS-Paste** [comment]
I think it is an issue with 1.20.6. Where could I find a 1.20.5 version of purpur?

**Comment by ryderbelserion** [comment]
There is no 1.20.5 version of Purpur. It just went right to 1.20.6...

**Comment by NBS-Paste** [comment]
Ok, I guess I’ll use paper until the next update

**Comment by granny** [comment]
> I think it is an issue with 1.20.6. Where could I find a 1.20.5 version of purpur?

how can it be an issue with 1.20.6 if the version you reported was 1.20.4??
