### ISSUE TITLE
(Suggestion) Controllable End Crystal explosions like the respawn anchor and beds!

### ISSUE THREAD

**Issue by GalaxyGamerMC** [pl3xgaming/Purpur#152]
What the title says. The idea is to probably nerf the end crystal pvp, that it's kinda gross

**Comment by BillyGalbreath** [comment]
i like it ^_^ will add soon(tm)

**Comment by BillyGalbreath** [comment]
Implemented in [build 975](https://ci.pl3x.net/job/Purpur/975/)

https://github.com/pl3xgaming/Purpur/commit/631520c8c41feda165fefed814a28b33200f4049
