### ISSUE TITLE
Disconnection with use-alternative-keepalive: true

### ISSUE THREAD

**Issue by colterfink** [pl3xgaming/Purpur#1520]
### Spark link

https://spark.lucko.me/7c0ommaBi4

### Expected behavior

Connect to the server.

### Observed/Actual behavior

Logging in... > Encrypting... > Joining World... > Disconnected

Error in console:
```
lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Pipeline has no outbound protocol configured, can't process packet net.minecraft.network.protocol.common.ClientboundKeepAlivePacket@74d01eb2
```

### Steps/models to reproduce

1. Install latest Purpur 1.20.6 build 
2. Set `use-alternative-keepalive: true`
3. Attempt to connect

### Purpur version

```
[11:25:49 INFO]: Checking version, please wait...
[11:25:49 INFO]: Current Purpur Version: 1.20.6-2227-79d199c (MC: 1.20.6)*
* You are running the latest version
Previous: 1.20.6-134-4f13be9 (MC: 1.20.6)
```

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by Krakenied** [comment]
```
com.mojang.authlib.GameProfile@7e51ef41[...] lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Pipeline has no outbound protocol configured, can't process packet net.minecraft.network.protocol.common.ClientboundKeepAlivePacket@5142fd68
```
It happened only once to me (my `use-alternative-keepalive` is enabled). Not that easy to reproduce so I can't test if it's its fault.

edit:
There are no reports for this error on both PaperMC Discord server and Paper GitHub issues and there are at least 3-4 reports on Purpur so probably we can assume it's a Purpur thing

**Comment by colterfink** [comment]
Perhaps I'm more susceptible to encountering the issue due to a poor baseline ping ranging between 200-250, as I'm from Australia. One of my American moderators reportedly only got disconnected once, while another from Europe couldn't login at all. 

Yep, switched to Paper initially to get my server online ASAP and spent more time later determining it was alt-keepalive :)
