### ISSUE TITLE
TPS Problem

### ISSUE THREAD

**Issue by Keffori** [pl3xgaming/Purpur#1544]
### Spark link

https://spark.lucko.me/Q9PGkzHAcQ

### Description of issue

My tps just going from 20 to very low, 4-6, I use good hosting service, 10gb ram, 500gb ssd, idk what but intel xeon.
mc 1.21
![image](https://github.com/PurpurMC/Purpur/assets/90979483/b3351c16-eb36-4096-9796-b59983a51494)

### Purpur version

Current Purpur Version: 1.21-2251-ac6c312 (MC: 1.21)*
* You are running the latest version
Previous: 1.21-38-1f5db50 (MC: 1.21)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by Keffori** [comment]
oh sorry, 5.5 gb not 10

**Comment by Onako2** [comment]
Your system doesn't have enought RAM (119.5 GB/125.8 GB). 
When you have addressed the issue with your system do the following steps:
- Also it is good practive to make Xms same to Xmx or a bit lower.
- -Xmx12288M is a bit overkill in most situations.
- Always leave a bit overhead for other stuff e.g. OS, other server and JVM

**Comment by granny** [comment]
Please join our discord for support. https://purpurmc.org/discord
