### ISSUE TITLE
Cannot Prohibit Reinforcements

### ISSUE THREAD

**Issue by Huge-mistake** [pl3xgaming/Purpur#1548]
### Spark link

The newly generated default profile...

### Expected behavior

When the 'spawn_reinforcements' option is set to 0,or 0.0, or -1, it turns off the reinforcements for this monster.

### Observed/Actual behavior

When I set the 'spawn_reinforcements' option to 0, or 0.0, or -1, the reinforcements can still be triggered.

### Steps/models to reproduce

Build a test platform in the air at will
![Zulu-21 Screenshot 2024 07 07 - 02 43 15 82](https://github.com/PurpurMC/Purpur/assets/137968615/85af79cf-9eef-443b-a64a-5a5fec0d6250)

Hard difficulty
The higher the 'local-difficulty，Clamped regional difficulty', the better. https://minecraft.wiki/w/Difficulty#Regional_difficulty
/time set midnight

In the middle of the built aerial test platform, place some experimental zombies and use a sword to perform a sweeping attack.
![Zulu-21 Screenshot 2024 07 07 - 02 51 04 55](https://github.com/PurpurMC/Purpur/assets/137968615/bfffb360-b981-4e9b-a45e-54af12161113)
Without any surprises, reinforcements should still be triggered.
Monsters generated by reinforcements have a characteristic, which is that they spawn at the edges of blocks, rather than in the middle of blocks.
![Zulu-21 Screenshot 2024 07 07 - 02 45 18 10](https://github.com/PurpurMC/Purpur/assets/137968615/60883227-d28f-4f8f-a8ef-c0c421d70264)
If reinforcements are not triggered, you can try several batches of zombies in the experiment, and it should be reproducible.

### Purpur version

Purpur1.20.6  #  2233

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

I'm not sure if the 'spawn_reinforcements' option provided by purpur.yml is designed to prohibit the reinforcement function. If not, can Purpur add a new feature to prohibit monster reinforcements? That would be fantastic.
(zombie, zombified_piglin, zombie_villager, drowned, husk):spawn_reinforcements

According to the Purpur documentation, I believe it should be possible to control the feature that prohibits reinforcements.
spawn_reinforcements[🔗](https://purpurmc.org/docs/purpur/configuration/#spawn_reinforcements_4)
default: 0.1
description: Percent chance (0.0 - 1.0) this mob will spawn reinforcements

**Comment by granny** [comment]
Not sure what to tell you - The option correctly sets the spawn_reinforcements attribute value. You can easily check by getting close to a naturally spawning zombie, then running the following command to view all attributes set to the zombie: `/data get entity @e[type=minecraft:zombie,limit=1,distance=..5] attributes`.

Keep in mind I tested this on the latest 1.21 build of Purpur. If the spawn_reinforcements attribute is not being properly set on 1.20.6, no fix will be backported for that version.

**Comment by Huge-mistake** [comment]
> Not sure what to tell you - The option correctly sets the spawn_reinforcements attribute value. You can easily check by getting close to a naturally spawning zombie, then running the following command to view all attributes set to the zombie: .`/data get entity @e[type=minecraft:zombie,limit=1,distance=..5] attributes`
> 
> Keep in mind I tested this on the latest 1.21 build of Purpur. If the spawn_reinforcements attribute is not being properly set on 1.20.6, no fix will be backported for that version.

Hello, I have successfully reproduced it on the build version 1.21#2275.
"Leader zombies still trigger Reinforcements."
![Zulu-21 Screenshot 2024 07 28 - 04 09 00 12](https://github.com/user-attachments/assets/b32965b8-d718-4d4d-a74b-bd34be6826aa)

The image shows the attribute information of Leader zombies, even with a Reinforcements value of 0, they can still trigger Reinforcements.
![338e60aa-ba4c-486b-bfa2-51c5a5398bbf](https://github.com/user-attachments/assets/d6fcac07-0ff0-4a36-a9ca-722de1ac2668)

![86525f95-08cf-4857-98e5-377b9a45753c](https://github.com/user-attachments/assets/4771648b-8505-4459-b800-507c16d2874f)
Is there any way to completely disable Reinforcements?
Leader zombies seem to be able to ignore that Reinforcements is set to 0.

**Comment by granny** [comment]
@Huge-mistake are you able to reproduce this on paper, spigot, or in vanilla?

**Comment by Huge-mistake** [comment]
> Leader zombies

When testing with Paper, I cannot set the "Reinforcements" attribute of Leader zombies to 0, as I rely on the "spawn_reinforcements: 0.0" option in purpur.yml to conduct the test.

**Comment by Huge-mistake** [comment]
> @Huge-mistake are you able to reproduce this on paper, spigot, or in vanilla?

Hello, I just used this command to set the "Reinforcements" attribute of Leader zombies to 0, and it also triggered "Reinforcements" on Paper.

> /attribute @e[type=minecraft:zombie,distance=..1,limit=1] minecraft:zombie.spawn_reinforcements base set 0

**Comment by granny** [comment]
@Huge-mistake Then it's either a Paper, Spigot, or Vanilla issue. Try to reproduce on Vanilla and then Spigot to see if it's an vanilla issue or a bukkit-based software issue.

**Comment by Huge-mistake** [comment]
> @Huge-mistake Then it's either a Paper, Spigot, or Vanilla issue. Try to reproduce on Vanilla and then Spigot to see if it's an vanilla issue or a bukkit-based software issue.

It seems to be a problem with the vanilla, there's no way out, I give up.

**Comment by Huge-mistake** [comment]
Hello, I apologize for disturbing you again, I have reported this issue to Mojang, but was told it is a normal phenomenon.
https://bugs.mojang.com/projects/MC/issues/MC-274727?filter=addedrecently
Has Purpur considered adding an option to completely prohibit Reinforcements behavior?
