### ISSUE TITLE
Shulkers riding boats not teleporting through end gateways

### ISSUE THREAD

**Issue by ChiboYen** [pl3xgaming/Purpur#1552]
### Spark link

Not applicable

### Expected behavior

Shulkers in boats should be allowed to teleport with the player riding them through the end gateway.

### Observed/Actual behavior

The boat does not teleport if it has shulkers or a player riding it.
![image](https://github.com/PurpurMC/Purpur/assets/69435677/407e42e4-3c2f-45d5-bd20-88e63873af9f)

### Steps/models to reproduce

Summon a shulker and ride a boat into it, then proceed to ride it into the end gateway.

Tested on Paper 1.20.6-148 (latest at the time) and it worked, the problem somehow popped up with Purpur (even with a reset config).

### Purpur version

```
Current Purpur Version: 1.20.6-2233-0d6766e (MC: 1.20.6)*
* You are running the latest version
Previous: 1.20.6-2230-eac4198 (MC: 1.20.6)
```

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
Spark report is very much applicable. Please properly fill out bug reports as requested.

This has already been fixed on 1.21 builds. A fix will not be backported to 1.20.6
