### ISSUE TITLE
Using essentialsx /kit featuring a signed book causes an insta discconect, can be abused to duplicate items.

### ISSUE THREAD

**Issue by AdaptableRuben** [pl3xgaming/Purpur#1556]
### Spark link

https://spark.lucko.me/OJy0T4dRb0

### Expected behavior

Should be able to get the book from the kit without any issues

### Observed/Actual behavior

You get disconnected and the playerdata fails to save causing it rollback to the point where you last logged off

### Steps/models to reproduce

1. Install a server with purpurmc
2. Install essentialsX and Purpurmc on the server or every plugin in this screenshot if possible
![2024-07-14_09 44 58](https://github.com/user-attachments/assets/4e3d4cd5-8b2d-40a5-a65c-3fd8422d3c87)

3. Write and sign a book
4. create a kit with the book with /createkit (name) (time)
5. Redeem the kit with /kit (name)
6. See the error happened

Note: This error does not happen in a locally hosted server, you must use an offsite server for it to work.

### Purpur version

Current Purpur Version: 1.21-2261-14136b8 (MC: 1.21)*
* You are running the latest version
Previous: 1.21-2260-5e70800 (MC: 1.21)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

This issue might be related to other plugins like Essentialx or Procollib since im using dev version installs to update the server to 1.21 earlier.

Error from console:  https://pastebin.com/T67Kwh43

**Comment by granny** [comment]
Known Paper issue. This has already been fixed by them, so next time I pull upstream the fix will be in Purpur.

**Comment by AdaptableRuben** [comment]
Great
