### ISSUE TITLE
 22/10000 实时翻译 划译 Where to adjust the Hell's Gate repair for the new feature 1.21.0

### ISSUE THREAD

**Issue by EthanAxew** [pl3xgaming/Purpur#1557]
### Spark link

https://spark.lucko.me/8dnjJ13gj2

### Expected behavior

Find where to adjust the Hell's Gate repair for the new feature 1.21.0

### Observed/Actual behavior

Unable to find where to adjust the Hell's Gate repair for the new feature 1.21.0

### Steps/models to reproduce

28/10000
实时翻译
划译
For the new feature of Hell Gate 1.21.0, items will not create a new Hell Gate

### Purpur version

[16:09:28 INFO]: Checking version, please wait...
[16:09:30 INFO]: Current Purpur Version: 1.21-2251-ac6c312 (MC: 1.21)*
* You are 14 version(s) behind

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by YouHaveTrouble** [comment]
![image](https://github.com/user-attachments/assets/7c53206c-f205-4ef9-87df-840527193f25)
