### ISSUE TITLE
Cactus does not break at new growth rate

### ISSUE THREAD

**Issue by Xlikes** [pl3xgaming/Purpur#1558]
### Spark link

not relevant

### Expected behavior

Cactus breaks on solid blocks. (growth)

### Observed/Actual behavior

As soon as the growth rate for cacti is reduced, cactus farms no longer work, as the cacti no longer break when growing on solid blocks.

### Steps/models to reproduce

    growth:
      cactus-modifier: 50

### Purpur version

1.20.,6

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by Onako2** [comment]
Could reproduce issue on 1.21 2265. 
![grafik](https://github.com/user-attachments/assets/e46dea84-3633-4917-846f-e8b85d395417)
Usually that problem fixes by itself when having a block update.

**Comment by Onako2** [comment]
Seems to be Spigot/Paper issue? On Paper the problem also occurs.

**Comment by granny** [comment]
Reproduce on Paper/Spigot and report it to the respective party.
