### ISSUE TITLE
Where is pufferfish.yml

### ISSUE THREAD

**Issue by f1f1stashka** [pl3xgaming/Purpur#1559]
### Spark link

https://spark.lucko.me/z8BPcvdCEe

### Expected behavior

pufferfish.yml in root folder

### Observed/Actual behavior

no pufferfish.yml in root folder

### Steps/models to reproduce

download latest experimental build of purpur
start

### Purpur version

Current Purpur Version: 1.21-2265-8f0f20d (MC: 1.21)*
* You are running the latest version
Previous: 1.21-40-b45d9b6 (MC: 1.21)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

i have not pufferfish.yml, i need it to config dab from pufferfish fork

**Comment by Onako2** [comment]
The pufferfish.yml isn't yet in Purpur because their 1.21 builds aren't yet out (The patches are I think already finished but unstable?). When Pufferfish does 1.21 then Purpur will also add the patches from Pufferfish

**Comment by f1f1stashka** [comment]
> The pufferfish.yml isn't yet in Purpur because their 1.21 builds aren't yet out (The patches are I think already finished but unstable?). When Pufferfish does 1.21 then Purpur will also add the patches from Pufferfish

so i cant configure DAB from pufferfish?

**Comment by Onako2** [comment]
> > The pufferfish.yml isn't yet in Purpur because their 1.21 builds aren't yet out (The patches are I think already finished but unstable?). When Pufferfish does 1.21 then Purpur will also add the patches from Pufferfish
> 
> so i cant configure DAB from pufferfish?

You can't configure DAB from Pufferfish yet. There are currently no ETAs.

**Comment by GreeningSiren** [comment]
Is this solved for purpur 1.21?

**Comment by Potothingi** [comment]
> Is this solved for purpur 1.21?

https://github.com/PurpurMC/Purpur/pull/1575#issuecomment-2279915012
It will be merged today or tomorrow.
