### ISSUE TITLE
Certain consumables are not being consumed right

### ISSUE THREAD

**Issue by SynaBytez** [pl3xgaming/Purpur#1562]
### Spark link

https://spark.lucko.me/8NTNdWIEqJ

### Expected behavior

When you drink stew in survival or adventure mode, it should be removed from your inventory and leave behind a wooden bowl. 

When you drink from any kind of bottle, it should leave behind a glass bottle.

### Observed/Actual behavior

The stew just stays there and nothing happens, so you can drink it infinitely.

The whole bottled drink gets consumed without leaving behind a bottle.

### Steps/models to reproduce

Drink stew or a bottled potion/drink in survival or adventure mode.

### Purpur version

[15:46:33 INFO]: Current Purpur Version: 1.21-2273-61b63b1 (MC: 1.21)*
* You are running the latest version
Previous: 1.20.6-2233-0d6766e (MC: 1.20.6)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by Onako2** [comment]
I couldn't reproduce on Purpur 1.21-2273-61b63b1 (MC: 1.21). Check your Skripts
