### ISSUE TITLE
This error occurs when starting the server

### ISSUE THREAD

**Issue by foxya27** [pl3xgaming/Purpur#1566]
### Spark link

https://spark.lucko.me/eUSyKd7OMb

### Expected behavior

No mistakes

### Observed/Actual behavior

![image](https://github.com/user-attachments/assets/1b1b95fb-cfa0-46c2-90ed-ee4a46f1cd1d)

### Steps/models to reproduce

Starting the server, namely look at the last lines

### Purpur version

Current Purpur Version: 1.21-2275-82ccc76 (MC: 1.21)*
* You are running the latest version
Previous: 1.21-2272-b2d1fea (MC: 1.21)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
You're being rate limited (That's what a 429 HTTP status means). A plugin is probably sending way too many requests to Mojang.

**Comment by foxya27** [comment]
> You're being rate limited (That's what a 429 HTTP status means). A plugin is probably sending way too many requests to Mojang.

Any suggestion on what plugin this could be?

**Comment by Onako2** [comment]
> > You're being rate limited (That's what a 429 HTTP status means). A plugin is probably sending way too many requests to Mojang.
> 
> Any suggestion on what plugin this could be?

Try disabling all plugins that do something with auth or skins such as AuthMe, then begin to enable them all until the issue occurs.

**Comment by granny** [comment]
If you need more help you can always join our discord; https://purpurmc.org/discord

**Comment by Krakenied** [comment]
> > > You're being rate limited (That's what a 429 HTTP status means). A plugin is probably sending way too many requests to Mojang.
> > 
> > 
> > Any suggestion on what plugin this could be?
> 
> Try disabling all plugins that do something with auth or skins such as AuthMe, then begin to enable them all until the issue occurs.

AuthMe doesnt send any requests

**Comment by Onako2** [comment]
> > > > You're being rate limited (That's what a 429 HTTP status means). A plugin is probably sending way too many requests to Mojang.
> > > 
> > > 
> > > Any suggestion on what plugin this could be?
> > 
> > 
> > Try disabling all plugins that do something with auth or skins such as AuthMe, then begin to enable them all until the issue occurs.
> 
> AuthMe doesnt send any requests

Never used AuthMe before but it sounded something that could use Mojang servers lol

**Comment by foxya27** [comment]
> > > > > You're being rate limited (That's what a 429 HTTP status means). A plugin is probably sending way too many requests to Mojang.
> > > > 
> > > > 
> > > > Any suggestion on what plugin this could be?
> > > 
> > > 
> > > Try disabling all plugins that do something with auth or skins such as AuthMe, then begin to enable them all until the issue occurs.
> > 
> > 
> > AuthMe doesnt send any requests
> 
> Never used AuthMe before but it sounded something that could use Mojang servers lol
 
Of the similar plugins I have: SkinsRestorer, Authme, and a plugin for mini heads from wandering trader

**Comment by Krakenied** [comment]
Its an auth plugin for offline mode so it doesn't need to. Firstly, I would try testing it without plugins applying any textures to skulls or players

**Comment by foxya27** [comment]
It's just that I used a head plugin before, and my developer says that it's possible, it causes a lot of requests, which is very strange...

**Comment by foxya27** [comment]
Ok, thanks for the help, I'll try to fix the bugs in the plugins and test again

**Comment by foxya27** [comment]
> If you need more help you can always join our discord; https://purpurmc.org/discord

Buddy, I'm already there)

**Comment by granny** [comment]
Then feel free to continue asking for support there to avoid spamming github notifications :)
