### ISSUE TITLE
Infinity not working on spectral and tipped arrows

### ISSUE THREAD

**Issue by fredagsguf** [pl3xgaming/Purpur#1567]
### Spark link

https://spark.lucko.me/y1u057U934

### Expected behavior

That it does work...

### Observed/Actual behavior

Infinity does not work on spectral and tipped arrows when shooting

### Steps/models to reproduce

Run server
Set the infinity options to true
Try to shoot, does not work.

### Purpur version

Current Purpur Version: 1.21-2273-61b63b1 (MC: 1.21)*
* You are 2 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.21-2264-bf63cfa (MC: 1.21)

### Agreements

- [x] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

I'm 2 versions behind the latest, but given the patch notes does not specify this exact issue - I'm assuming its fine.

**Comment by granny** [comment]
This was outlined in the announcement for 1.21 experimental builds. I've pasted a snippet with the relevant information below.

> ## Config Changes
> 
> ### Removed
> 
> 1. `gameplay-mechanics.entities-can-use-portals`
> 1. `gameplay-mechanics.infinity-bow.normal-arrows`
>   `gameplay-mechanics.infinity-bow.spectral-arrows`
>   `gameplay-mechanics.infinity-bow.tipped-arrows`
>   
>   A template is available here: <https://github.com/PurpurMC/PurpurPacks/tree/master/packs/infinity-works-with-any-arrow>. Just follow the README instructions on how to configure it to your liking.
> 1. `settings.enchantment.allow-infinity-and-mending-together`, use [Infinity Mending Bows [PurpurPack]](<https://modrinth.com/datapack/purpurpacks-infinity-mending-bows>) instead
> 1. `settings.enchantment.allow-infinity-on-crossbow` - use [Infinity on Crossbows [PurpurPack]](<https://modrinth.com/datapack/purpurpacks-infinity-on-crossbows>) instead
> 1. `gameplay-mechanics.mending-multiplier` - A template is available here: <https://github.com/PurpurMC/PurpurPacks/tree/master/packs/mending_multiplier>. Just follow the README instructions on how to configure it to your liking.
> 1. `gameplay-mechanics.elytra.ignore-unbreaking` - use [No Unbreaking On Elytra [PurpurPack]](<https://modrinth.com/datapack/purpurpacks-no-unbreaking-on-elytra>) instead
