### ISSUE TITLE
Above Vanilla enchants.

### ISSUE THREAD

**Issue by bobross2103301** [pl3xgaming/Purpur#1568]
### Spark link

N/A

### Expected behavior

Enchants above the vanilla level to work when being combined within an anvil when having (allow-unsafe-enchants, allow-higher-enchants-levels and allow-unsafe-enchant-command) set to true.

### Observed/Actual behavior

Unable to combine the items within the anvil.
![image](https://github.com/user-attachments/assets/8c8b4219-3867-4aa9-8ad9-49208e8ad005)
![image](https://github.com/user-attachments/assets/080ef8d7-3dc5-49c7-a6fb-1deae333c4ed)

### Steps/models to reproduce

Load up a clean server, enable (allow-unsafe-enchants, allow-higher-enchants-levels and allow-unsafe-enchant-command)

### Purpur version

1.21-2275-82ccc76 (MC:1.21)*

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by Krakenied** [comment]
![image](https://github.com/user-attachments/assets/efe3458e-818f-4b1d-a6f3-0501235413f6)
![image](https://github.com/user-attachments/assets/83b0dfec-b4e4-480f-b503-13d5f413232e)
![image](https://github.com/user-attachments/assets/33f929fb-27c5-4b66-a4e0-b0d84b59c8f7)
