### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by lackooka** [pl3xgaming/Purpur#1569]
### Spark link

lost

### Stack trace

```
https://paste.gg/p/anonymous/e0fc8c5c5dd743c9b4f84fa1c31037c3
```

### Purpur version

1.21 2276 (latest)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by Onako2** [comment]
Please provide full logs. You can also ask on our Discord https://purpurmc.org/discord
