### ISSUE TITLE
(Suggestion) Ridable mob heads shouldn't follow player's head pitch

### ISSUE THREAD

**Issue by Nehemek** [pl3xgaming/Purpur#157]
(Suggestion) Ridable mob heads shouldn't follow player's head pitch
When riding a mob, the mob's head follows the exact yaw and pitch of the player. While yaw is fine, the pitch is not very aesthethically pleasing, specially in first person when it seems like the mob is always looking to the floow everytime you want to look at it.

Maybe mobs should not follow the pitch at all or it should be weighted by a factor of .5 or .35.

**Comment by BillyGalbreath** [comment]
Works as intended
