### ISSUE TITLE
Entities can not use portal after reverting settings

### ISSUE THREAD

**Issue by Truongvv10** [pl3xgaming/Purpur#1570]
### Spark link

https://spark.lucko.me/6UAD4oQx6q

### Expected behavior

Hi, I'm having an issue where I changed the setting `entities-can-use-portals: false` to `entities-can-use-portals: true`. But it's not working, entities can still not go through portals

### Observed/Actual behavior

After restarting the server multliple times, this issue still persist for me. What should happen was that entities don't collide against the portal anymore and able to use portal.

### Steps/models to reproduce

1. Set `entities-can-use-portals: false` 
2. Restart
3. Set to `entities-can-use-portals: true`
4. Restart

### Purpur version

![image](https://github.com/user-attachments/assets/4ee8674c-b757-4cde-ad05-cf28e3ba4a1b)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by Krakenied** [comment]
This option was removed in Purpur 1.21

**Comment by Krakenied** [comment]
I can port it to 1.21 though as I will probably want to use it on my server
