### ISSUE TITLE
Gamerule playersNetherPortalCreativeDelay is not working correctly

### ISSUE THREAD

**Issue by thedankeststorm** [pl3xgaming/Purpur#1573]
### Spark link

https://spark.lucko.me/4hw9hPtTJE

### Expected behavior

When setting playersNetherPortalCreativeDelay to a certain value different than 0, the time when player step into a Nether Portal until they are teleported must be reflected accordingly.

### Observed/Actual behavior

This behavior only works correctly when traveling from Nether to Overworld. However, going from Overworld to Nether will always be instantaneous, no matter what value playersNetherPortalCreativeDelay was set to.

( It behaves like playersNetherPortalCreativeDelay = 0 )

### Steps/models to reproduce

Set gamerule playersNetherPortalCreativeDelay to a value different than 0.

### Purpur version

Current Purpur Version: 1.21-2280-930003b (MC: 1.21)*
* You are running the latest version
Previous: 1.21-2275-82ccc76 (MC: 1.21)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by thedankeststorm** [comment]
Forgot to say: Cannot replicate issue on vanilla Minecraft, so I assume it's Purpur's issue.

**Comment by Krakenied** [comment]
> However, going from Overworld to Nether will always be instantaneous, no matter what value playersNetherPortalCreativeDelay was set to.

Gamerules are set per world. Also, Purpur has `purpur.portal.instant` permission for instant portal teleportation (I haven't tested it yet though)

**Comment by thedankeststorm** [comment]
> > However, going from Overworld to Nether will always be instantaneous, no matter what value playersNetherPortalCreativeDelay was set to.
> 
> Gamerules are set per world. Also, Purpur has `purpur.portal.instant` permission for instant portal teleportation (I haven't tested it yet though)

Oh, that explains it. I thought it'd be consistent for both sides. Just tested it again in Overworld and can confirm that it works per world.

Issue resolved. Thanks for letting me know.
