### ISSUE TITLE
Elytra settings break elytras similarly to armor

### ISSUE THREAD

**Issue by ChiboYen** [pl3xgaming/Purpur#1574]
### Spark link

https://spark.lucko.me/UYx0jOshLh

### Expected behavior

Elytras shouldn't break/disappear, they should only become disabled and unusable until repaired, but still stay in the player's chest plate slot/inventory. Not present on Paper, this is a bug that only happens on Purpur.

### Observed/Actual behavior

With Purpur 1.21 builds, I'm starting to notice that the following elytra settings result in cases where breaking the elytra instead of simply disabling them like in Vanilla occurs:
- Setting `damage-per-second:` to more than 1.0
- Setting `damage-multiplied-by-speed` to more than 1.0
- Setting any `damage-per-boost` setting to more than 0.0

### Steps/models to reproduce

By doing the following:
- Setting `damage-per-second:` to more than 1.0
- Setting `damage-multiplied-by-speed` to more than 1.0
- Setting any `damage-per-boost` setting to more than 0.0

And then getting elytras with near 0 durability, you can fly normally or with fireworks. Try variations of flying styles, like flying straight up and then gliding down at a 90 degree angle for maximum speed.

### Purpur version

purpur version
[15:37:10 INFO]: Checking version, please wait...
[15:37:11 INFO]: Current Purpur Version: 1.21-2280-930003b (MC: 1.21)*
* You are running the latest version
Previous: 1.21-124-df3b654 (MC: 1.21)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by Krakenied** [comment]
So it's works properly with default config?

**Comment by ChiboYen** [comment]
With the default config it does nothing, as intended. This feature doesn't "work" as intended when you stray from the default config.
