### ISSUE TITLE
After updating to the 1.21 server, the CPU usage is very high

### ISSUE THREAD

**Issue by Cobyqwq** [pl3xgaming/Purpur#1577]
### Spark link

https://spark.lucko.me/YXsqCkLSXE

### Description of issue

After updating to the 1.21 server, the CPU usage is very high, usually fluctuating from 5% to 50%. Even if the server has only one player, it will still occupy 0-10%, and even if there is no player, it will be the same

### Purpur version

1.21-2280-930003b (MC: 1.21)*
* You are running the latest version
Previous: 1.21-126-7e44684 (MC: 1.21)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by Onako2** [comment]
Please send the spark profiler link (/spark profiler start) and after a few minutes do (/spark profiler stop). You sent a Heap Summary which doesn't help at all to solve your issue. 

You can also join our [Discord](https://purpurmc.org/discord).

**Comment by Cobyqwq** [comment]
> 请发送 spark 分析器链接 （/spark profiler start），几分钟后执行 （/spark profiler stop）。您发送了堆摘要，这根本无助于解决您的问题。
> 
> 您也可以加入我们的 [Discord](https://purpurmc.org/discord)。

https://spark.lucko.me/9kqex2d8jF

**Comment by Cobyqwq** [comment]
> 请发送 spark 分析器链接 （/spark profiler start），几分钟后执行 （/spark profiler stop）。您发送了堆摘要，这根本无助于解决您的问题。
> 
> 您也可以加入我们的 [Discord](https://purpurmc.org/discord)。



> Please send the spark profiler link (/spark profiler start) and after a few minutes do (/spark profiler stop). You sent a Heap Summary which doesn't help at all to solve your issue.
> 
> You can also join our [Discord](https://purpurmc.org/discord).

G1 Old 1300ms,Is it abnormal?

**Comment by Cobyqwq** [comment]
> Please send the spark profiler link (/spark profiler start) and after a few minutes do (/spark profiler stop). You sent a Heap Summary which doesn't help at all to solve your issue.
> 
> You can also join our [Discord](https://purpurmc.org/discord).

G1 Old 1300ms,Is it abnormal?

**Comment by Cobyqwq** [comment]
> Please send the spark profiler link (/spark profiler start) and after a few minutes do (/spark profiler stop). You sent a Heap Summary which doesn't help at all to solve your issue.
> 
> You can also join our [Discord](https://purpurmc.org/discord).

https://spark.lucko.me/9kqex2d8jF

**Comment by Onako2** [comment]
Oh just noticed, there is a bit too much in SWAP, SWAP is when your RAM stuff is written onto a SSD or HDD(Which hurts SSD and performance)

**Comment by granny** [comment]
Please join our discord for support. https://purpurmc.org/discord
