### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by studysnack** [pl3xgaming/Purpur#1579]
### Spark link

https://spark.lucko.me/xZXKwfon8u

### Stack trace

https://paste.gg/p/anonymous/d77b7fbfa36f475da3aa55afa623a33a

### Purpur version

[17:15:27 INFO]: Current Purpur Version: 1.21.1-2287-07979c3 (MC: 1.21.1)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by YouHaveTrouble** [comment]
![image](https://github.com/user-attachments/assets/f272fcf0-de0d-4bfd-8cdb-92dc10bfa599)
