### ISSUE TITLE
(Suggestion) Configurable ridable mob speed parameter

### ISSUE THREAD

**Issue by Nehemek** [pl3xgaming/Purpur#158]
Ridable mobs is a really cool feature of Purpur, however not all mobs translate into good experiences when ridable even if their mechanics are interesting.

Example: The blaze hovers and can be used as a construction tool, however it is very slow to move, an aditional parameter for movement speed when being riden would solve that issue.

_Addendum: Speaking of blazes, perhaps an option to disable it's particles when ridden since they obstruct the view a lot._

**Comment by BillyGalbreath** [comment]
This is on my todo list already (see discord)
