### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by studysnack** [pl3xgaming/Purpur#1580]
### Spark link

https://spark.lucko.me/xZXKwfon8u

### Stack trace

https://paste.gg/p/anonymous/d77b7fbfa36f475da3aa55afa623a33a

### Purpur version

[17:15:27 INFO]: Current Purpur Version: 1.21.1-2287-07979c3 (MC: 1.21.1)*
You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by CyberFlameGO** [comment]
Was a crash report file generated?

**Comment by granny** [comment]
Please join our discord for support. https://purpurmc.org/discord
