### ISSUE TITLE
ServerLevel.saveIncrementally() - A lot of ticks.

### ISSUE THREAD

**Issue by GG-MD** [pl3xgaming/Purpur#1584]
### Spark link

https://spark.lucko.me/hyvDFzAPPU

### Expected behavior

The report was done correctly by tracking ticks, using /spark profiler start --only-ticks-over 200
https://i.imgur.com/HtQLeVd.png

### Observed/Actual behavior

Not sure why or how, but an abnormal load.

### Steps/models to reproduce

--

### Purpur version

```
ver
[20:19:02 INFO]: Checking version, please wait...
[20:19:02 INFO]: Current Purpur Version: 1.21.1-2299-5c0d2f7 (MC: 1.21.1)*
* You are running the latest version
Previous: 1.21.1-2298-a61db94 (MC: 1.21.1)
```

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by YouHaveTrouble** [comment]
change `max-auto-save-chunks-per-tick` in your paper config back to default 24 and do not touch settings you do not understand.

**Comment by YouHaveTrouble** [comment]
I'm assuming that 👍🏻 reaction means the problem was solved
