### ISSUE TITLE
Excessive enchanting player client crashes

### ISSUE THREAD

**Issue by NeglectDream** [pl3xgaming/Purpur#1587]
### Spark link

https://spark.lucko.me/RnthZWQksd

### Expected behavior

The player client can enter normally and obtain items with high enchantments (greater than 255)

### Observed/Actual behavior

When a player obtains or the client loads an enchanted item greater than 255, the connection will drop and they will not be able to re-enter

### Steps/models to reproduce

Send an item with an enchanting level greater than 255 in the player's backpack

### Purpur version

> version
[22:31:22 INFO]: Checking version, please wait...
[22:31:25 INFO]: Current Purpur Version: 1.21.1-2304-dee41bc (MC: 1.21.1)*
* You are running the latest version
Previous: 1.21.1-DEV-c5edeac (MC: 1.21.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

purpur.yml
https://pastebin.com/S30TNHku

disconnect-2024-09-11_22.21.26-client.txt
https://pastebin.com/AtHp9Lpc

**Comment by NeglectDream** [comment]
This issue can be used normally in the latest paper core, but it will not exceed the 255 level enchantment

**Comment by YouHaveTrouble** [comment]
You have enabled unsafe enchants. This behavior is intended. Unsafe enchants hand you the wheel and responsibility for caring if the enchant will work on a level it was never intended to work with. You get to shoot yourself in the foot.
