### ISSUE TITLE
Add an option to prevent phantom flames from causing tile entity damage.

### ISSUE THREAD

**Issue by mibby** [pl3xgaming/Purpur#159]
**Describe the bug**
Phantom flames currently cause tile entity damage, causing destruction of things such as item frames, minecarts, armor stands, etc. Would it be possible to add an option so phantom flame breath only hurts entities such as the player and other mobs? 

**Version**
Purpur dev 967

**Additional Context**
Getting reports from players about phantoms causing griefing because of this. Like the flames, not okay with destroying their home.

**Comment by BillyGalbreath** [comment]
Most definitely. Dont know why i didnt think of that before ^_^

**Comment by mibby** [comment]
It would certainly be most appreciated with my players. :)

**Comment by BillyGalbreath** [comment]
Implemented in [build 978](https://ci.pl3x.net/job/Purpur/978/)

https://github.com/pl3xgaming/Purpur/commit/9537c770b0820b8b7a9915a7d571de528dc5ce8c
