### ISSUE TITLE
com.mojang.authlib.GameProfile [build PurPur #2307]

### ISSUE THREAD

**Issue by GG-MD** [pl3xgaming/Purpur#1590]
### Spark link

-

### Expected behavior

After upgrading to build #2307, there are errors everywhere:
_I found this out by going back to build #2305._

`[02:31:39] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile`

### Observed/Actual behavior

-

### Steps/models to reproduce

-

### Purpur version

latest build 1.21.1

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by GG-MD** [comment]
_Because of this, such plugins as BattlePass, PlayerWarps did not work._

**Comment by ryderbelserion** [comment]
~~This has to do with the recent Paper upstream, Please reproduce on Paper and report your findings to Paper's issue tracker or their support channels.~~

Paper seems to have fixed it in their recent builds, will just have to wait for another upstream.

**Comment by GG-MD** [comment]
> ~This has to do with the recent Paper upstream, Please reproduce on Paper and report your findings to Paper's issue tracker or their support channels.~
> 
> Paper seems to have fixed it in their recent builds, will just have to wait for another upstream.

Okay, we're waiting :)

**Comment by granny** [comment]
https://github.com/PurpurMC/Purpur/commit/8332fa45d9886aed8cf0c114e08c6671a06794c8

**Comment by GG-MD** [comment]
@granny no fixes

**Comment by granny** [comment]
are you able to reproduce on the latest version of paper?

**Comment by GG-MD** [comment]
> are you able to reproduce on the latest version of paper?

I won't test the paper, really :)

**Comment by GG-MD** [comment]
> are you able to reproduce on the latest version of paper?

The problem persists also on 2310 build .....

**Comment by GG-MD** [comment]
I can't update because of this, I've already missed 5 versions.

**Comment by granny** [comment]
keeping closed, refer to Machine's answer here: https://github.com/PaperMC/Paper/issues/11428#issuecomment-2366830328
