### ISSUE TITLE
/perf command not working

### ISSUE THREAD

**Issue by T1MOXA** [pl3xgaming/Purpur#1591]
### Spark link

https://spark.lucko.me/mKn0E2bCcg

### Expected behavior

`/perf start` command to start profiling, then `/perf stop` can stop profiling erarly if needed.

### Observed/Actual behavior

```
/perf start
[17:48:11 INFO]: Started 10 second performance profiling run (use '/perf stop' to stop early)
/perf stop
[17:48:15 INFO]: The performance profiler hasn't started
```
And debug folder is also not created.

### Steps/models to reproduce

1. Download latest purpur build
2. Start a server
3. Run /perf start
4. Run /perf stop immideately to see that profiler is not running.

### Purpur version

[17:47:55 INFO]: Checking version, please wait...
[17:47:56 INFO]: Current Purpur Version: 1.21.1-2308-8332fa4 (MC: 1.21.1)*
* You are running the latest version
Previous: 1.21.1-2307-8af4ea6 (MC: 1.21.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by Dreeam-qwq** [comment]
/perf command uses vanilla profiler to function, and vanilla profiler is removed in Purpur

You can use spark profiler, which is more recommended.

**Comment by T1MOXA** [comment]
Can it be disabled optionally ?
(I've set disable-method-profiler: false)
For example, spark profiler doesn't provide info about functions and commands from datapack's, where /perf and /debug does.
But /debug command also not working, even on paper (and spigot as far as I know)

**Comment by Krakenied** [comment]
Spark profiler provides literally all the info that can be provided (including functions and commands from datapacks) - you just need to find it in the profile (if you don't see it at first glance then the performance loss isn't enough high)

**Comment by T1MOXA** [comment]
I see only a stack trace, with no hint what command, function or entity from which datapack or command block causes load.
IMO, Spark is an excellent debugger for debugging cores and plugins, however, it is not suitable for debugging in-game functions or commands in Minecraft.

Using one debugger or another is a personal choice.
But what about the problem I've described ?

**Comment by granny** [comment]
Making the command work would mean reverting the removal of the mojang profiler, which isn't going to happen. I recommend sending a feature request on the [spark github repo](https://github.com/lucko/spark) (There already exists a request for showing function calls; https://github.com/lucko/spark/issues/392)

**Comment by FaultyFunctions** [comment]
Why was the default profiler removed in the first place? I am also running into the situation where I'd like to see the exact functions from datapacks running to find a source of lag. IMO a vanilla feature shouldn't be removed in a favor of an alternative if that alternative doesn't have all the features of the original.

**Comment by granny** [comment]
@FaultyFunctions Mostly because we could 🤷 It was removed alongside the Timings removal since both made a lot of the same calls. Nobody had brought it up as an issue until now in the past 2 years that it has been removed.

I've reverted the removal of the Mojang Profiler for 1.21.3 since Mojang implemented the Tracy profiler alongside/into the default Profiler. This means the profiler should work for you again in the current experimental builds of Purpur. CC: @T1MOXA

I'd have to check the code again (haven't looked into the profiler stuff since updating to 1.21.3) but iirc it seems there's been improvements to how the Profiler runs so I don't think there's any benefit in removing it again.

**Comment by FaultyFunctions** [comment]
Thank you so much for the quick response. I had to revert my server to paper to diagnose the solve the issue with a datapack taking up too much of my server's resources (and then revert back to purpur afterwards) so this change will be great for streamlining this process in the future. Thanks again!
