### ISSUE TITLE
I can't start the server on debian

### ISSUE THREAD

**Issue by zknb-666** [pl3xgaming/Purpur#1593]
### Spark link

can't use

### Stack trace

```
[paste your stack trace or a paste.gg link here!](https://paste.gg/p/anonymous/b3d141d1c732488691a78634a77bf5fa)
```

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
> - [X] I ticked all the boxes without actually reading them

Please join our discord for support. https://purpurmc.org/discord
