### ISSUE TITLE
Looting Shears

### ISSUE THREAD

**Issue by Katables** [pl3xgaming/Purpur#1596]
### Spark link

https://spark.lucko.me/MCtcVe2Dln

### Expected behavior

When combining Looting 3 book and Shears, the result would be Shears with the Looting 3 Enchant. 

### Observed/Actual behavior

When combining Looting 3 Book and Shears, no result shows in Anvil.
When forcing Combination in Creative the Enchant shows on Shears.. but does not provide Extra Wool when Shearing Sheep.

### Steps/models to reproduce

Grab Looting 3 Book, and Shears. Place Shears in first slot in Anvil, place Looting 3 book in 2nd slot, cry that the enchant wont attach to shears :'( lol.

Repeat steps above but in creative.. and cry that the Looting effect doesn't actually work, and no extra Wool is being gathered from Sheep, Despite the Shears showing with Looting Enchant.

### Purpur version

01.10 21:28:47 [Server] INFO Current Purpur Version: 1.21.1-2298-a61db94 (MC: 1.21.1)*
01.10 21:28:47 [Server] INFO * You are 17 version(s) behind
01.10 21:28:47 [Server] INFO Download the new version at: https://purpurmc.org/downloads
01.10 21:28:47 [Server] INFO Previous: 1.21-2273-61b63b1 (MC: 1.21)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

Tried to manually update our Purpur version using Apex Server Hosting.. but it wont automatically update using **Purpur 1.21.1 [Latest]**
Tried Apex's Manual Updating work around of renaming the file to custom.jar to manually force it to update but the server would not load/start up. Apex Server Hosting doesn't seem to want to update to the latest version. 
That being said I'm going to click the "I am running the latest version of Purpur" button.. because technically for Apex Server Hosting I am.. but its not true.. I dont know why they wont allow it :( sorry!

**Comment by Katables** [comment]
Was able to update our server with some help from Apex support.. Idk why it was so hard lol. Problem still consist even with updated version of Purpur though :(

**Version**
01.10 22:06:58 [Server] INFO Current Purpur Version: 1.21.1-2315-2a50638 (MC: 1.21.1)*
01.10 22:06:58 [Server] INFO * You are running the latest version
01.10 22:06:58 [Server] INFO Previous: 1.21.1-2298-a61db94 (MC: 1.21.1)

**New Spark** 
https://spark.lucko.me/Hf9giWAwdr

**Comment by Onako2** [comment]
1.21.1 vanilla:
![Screenshot with an anvil screen opened that shows that shears and lootin 3 cannot be crafted together in vanilla Minecraft](https://github.com/user-attachments/assets/e242324b-d149-4916-9b99-d7c25f1ad299)

24w40a vanilla:
![Screenshot with an anvil screen opened that shows that shears and lootin 3 cannot be crafted together in vanilla Minecraft in the version 24w40a](https://github.com/user-attachments/assets/8437f6d1-2d7f-4de5-b860-8b1b5ee6d7c3)

![looting](https://github.com/user-attachments/assets/e7782ce9-2607-4b4a-a248-e380ff5d7382)

Seems to be intended by vanilla? A bug in vanilla?
**The issue isn't on Purpur's side**

**Comment by Katables** [comment]
Yes, Im aware you cant do this in vanilla. I think there might be some confusion. The problem is the Setting in Purpur.yml is set to allow Looting on Shears. Which prior to 1.21 it was working. 
![image](https://github.com/user-attachments/assets/180a91f1-fc0d-4b00-a21c-54a064eb0924)

**Comment by Onako2** [comment]
Seems to be related to the new data driven enchantment registry stuff?

**Comment by Katables** [comment]
Yeah idk, I was told by Granny to make a Github bug report.. So I did with all the info I had. Lol *shrug*

**Comment by granny** [comment]
Enable `settings.enchantment.anvil.allow-inapplicable-enchants` to allow Looting on shears. This also means that any enchantment can be placed on any weapon/tool, so if you want to only allow the Looting enchantment on shears then you'll want to modify the Looting enchantment using a datapack to include shears as an acceptable tool.

Unable to reproduce the shearing issue on latest 1.21.1 build on 7950960. Looting successfully adds extra wool to the drops when looting is applied to shears.
