### ISSUE TITLE
Creature Mobcaps feel inflated above limits

### ISSUE THREAD

**Issue by netcore10** [pl3xgaming/Purpur#1597]
### Spark link

https://spark.lucko.me/U8pfnNEBAF

### Expected behavior

To have mobcaps fit their limits

### Observed/Actual behavior

creature mobcaps seem to spawn above the limits. 

### Steps/models to reproduce

I don't really know

### Purpur version

1.21.1-2321

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

![image](https://github.com/user-attachments/assets/c87f64d4-9ff1-476f-8f39-2ec87c1df4df)

**Comment by YouHaveTrouble** [comment]
Mob caps are only effective for natural spawning. Breeding animals for example does not count as natural spawning. Everything here is working as intended, no more animals will spawn naturally as you're above the mob cap already.
