### ISSUE TITLE
players randomly disconnect

### ISSUE THREAD

**Issue by levitskyyy** [pl3xgaming/Purpur#1600]
### Spark link

https://spark.lucko.me/M9nVe5CLKt

### Expected behavior

Fix this problem

### Observed/Actual behavior

# Console logs
```
[13:16:32 INFO]: _Klayn1_ lost connection: Disconnected
[13:16:32 INFO]: [voicechat] Disconnecting client _Klayn1_
```

### Steps/models to reproduce

1. go to the server
2. play
3. you are randomly disconnected from the server

### Purpur version

Current Purpur Version: 1.21.1-2327-4b57bed (MC: 1.21.1)*
* You are running the latest version
Previous: 1.21.1-2326-4f2fe31 (MC: 1.21.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by Onako2** [comment]
![grafik](https://github.com/user-attachments/assets/694807a8-bea9-44f2-b926-7a8e7c055d45)

We also have a Discord!
https://purpurmc.org/discord
