### ISSUE TITLE
The newly generated configuration file has the 'clamp-levels' option not set to true as expected by default.

### ISSUE THREAD

**Issue by CatTeaA** [pl3xgaming/Purpur#1606]
### Spark link

null

### Expected behavior

The option 'clamp-levels' should be set to true by default.

### Observed/Actual behavior

The configuration file option 'clamp-levels' defaults to false.

### Steps/models to reproduce

Regenerate purpur.yml to observe 'clamp-levels'

### Purpur version

(Purpur1.21.3#2333) and (Purpur1.21.1#2329)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

In the Discord discussion, someone pointed out a potential issue

https://github.com/PurpurMC/Purpur/blob/74d1b4c10a92d8f77dddb73018b90f19b33c19ab/patches/server/0236-Add-toggle-for-enchant-level-clamping.patch#L17
It defaults to `false` because `getBoolean` isn't given a default value there

**Comment by Onako2** [comment]
Can confirm in 1.21.3-DEV-eb7fe2d
