### ISSUE TITLE
Note blocks can't change notes

### ISSUE THREAD

**Issue by netcore10** [pl3xgaming/Purpur#1608]
### Spark link

https://spark.lucko.me/1ONVookJUl

### Expected behavior

When clicking, note should change.

### Observed/Actual behavior

Stays the same note. 

### Steps/models to reproduce

https://github.com/user-attachments/assets/85d5ce56-ec9d-4b6f-b2fc-1136f4abe287

### Purpur version

2024-11-13T21:19:22.612470684Z > 
[21:19:22 INFO]: Current Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)*
2024-11-13T21:19:22.612486122Z * You are running the latest version
2024-11-13T21:19:22.612490741Z Previous: 1.21.1-2328-d49ca07 (MC: 1.21.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

No plugins were running, as i was testing if it was plugins, i removed them all.

**Comment by CatTeaA** [comment]
The 'paper-global.yml' you have set up includes <disable-noteblock-updates: true>.
