### ISSUE TITLE
Break sand really fast by swapping between a pickaxe that has efficiency on it

### ISSUE THREAD

**Issue by realduziy** [pl3xgaming/Purpur#1617]
### Spark link

Not a crash

### Expected behavior

As explained in the title

### Observed/Actual behavior

The sand breaking very fast

### Steps/models to reproduce

As stated in the title

### Purpur version

1.21.3 2349 11/26/24, 20:34

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

there are also no plugins on the server and it was a fresh install of Purpur and no config files were edited

heres a video

https://www.youtube.com/watch?v=8ScBWwX5HUQ

**Comment by Onako2** [comment]
Could you reproduce that on Paper?

**Comment by realduziy** [comment]
good question, let me check quick

**Comment by realduziy** [comment]
it appears to be on normal paper to yes

**Comment by granny** [comment]
Submit a report to Paper then. Make sure to re-record the video when you do. Make sure to show the output of `/version` and `/plugins` when you do. Don't mention Purpur, otherwise there's a chance it'll be dismissed. (Creeper at the end of the video is funny)

**Comment by realduziy** [comment]
So I did report this on Papermcs github and apparently it is a vinnila issue; it did not even cross my mind that it could be a vinnila bug, apparently its been like this for years already
