### ISSUE TITLE
minecart.max-speed setting overrides minecartMaxSpeed gamerule in Minecart Improvements experiment

### ISSUE THREAD

**Issue by Diamondback88** [pl3xgaming/Purpur#1618]
### Spark link

N/A

### Expected behavior

When the Minecart Improvements experiment is enabled, the gamerule `minecartMaxSpeed` should be the sole manipulator of a minecart's max speed.

### Observed/Actual behavior

The minecart.max-speed setting overrides the value of the `minecartMaxSpeed` gamerule

### Steps/models to reproduce

1. Create a new world with the Minecart Improvements experiment enabled.
2. Set the `minecartMaxSpeed` value to 1000 (minecarts should be going light speed with this, just to visually see the distinction).
3. Observe that the max speed of a minecart doesn't change.

### Purpur version

Current Purpur Version: 1.21.3-2351-2b694c9 (MC: 1.21.3)*
* You are running the latest version
Previous: 1.21.1-2290-f2307b8 (MC: 1.21.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
I think I'll make it so the option still works for the experiment, but instead the gamerule will take priority if it's set to anything other than the default value.

**Comment by Diamondback88** [comment]
Awesome, thanks!
