### ISSUE TITLE
Controllable Riding Broken for all Mobs

### ISSUE THREAD

**Issue by talkincyber** [pl3xgaming/Purpur#1620]
### Spark link

https://spark.lucko.me/EiKtjir14r

### Expected behavior

I have my config set to allow all the animals in the purpur.yml to be ridable and controllable. I should be able to move the mob with WASD and jump with space, none of those apply.

### Observed/Actual behavior

Currently, the mob only responds to looking around, WASD and any other movement commands do not make the mob move. They are completely uncontrollable.

### Steps/models to reproduce

Attempt to control any mobs in the current build 2355, it will not work.

### Purpur version

Current Purpur Version: 1.21.3-2355-de20ba9 (MC: 1.21.3)* 
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

This was brought up in https://github.com/PurpurMC/Purpur/issues/1507 and I was told to create a new issue.

**Comment by granny** [comment]
Thanks, I'll look into this as soon as I can.
