### ISSUE TITLE
1.21.4 Building no purpurclip.jar

### ISSUE THREAD

**Issue by upchui** [pl3xgaming/Purpur#1623]
### Spark link

n/a

### Expected behavior

./gradlew applyPatches && ./gradlew rebuildPatches && ./gradlew build && ./gradlew createMojmapBundlerJar && ./gradlew publishToMavenLocal

To get purpurclip.jar

### Observed/Actual behavior

No purpurclip.jar

user@mc:~/data/build/Purpur$ ls -la build/libs/
total 121820
drwxr-xr-x 2 user user     4096 Dec  6 11:25 .
drwxr-xr-x 6 user user     4096 Dec  6 11:21 ..
-rw-r--r-- 1 user user 26286908 Dec  6 11:25 paperweight-development-bundle-1.21.4-R0.1-SNAPSHOT.zip
-rw-r--r-- 1 user user      261 Dec  6 11:19 purpur-1.21.4-R0.1-SNAPSHOT.jar
-rw-r--r-- 1 user user 98442373 Dec  6 11:21 purpur-bundler-1.21.4-R0.1-SNAPSHOT-mojmap.jar

### Steps/models to reproduce

./gradlew applyPatches && ./gradlew rebuildPatches && ./gradlew build && ./gradlew createMojmapBundlerJar && ./gradlew publishToMavenLocal

### Purpur version

1.21.4 git [2af2e71](https://github.com/PurpurMC/Purpur/commit/2af2e717b36bd19c4232328f9cdf18ef904a2061)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

1.21.4

**Comment by ElFrod0** [comment]
iirc you should use `.\gradlew createMojmapPaperclipJar`
