### ISSUE TITLE
Head rotation bug

### ISSUE THREAD

**Issue by jd07159** [pl3xgaming/Purpur#1625]
### Spark link

https://spark.lucko.me/zDcvo7p2A3

### Expected behavior

When the head rotates, the body should rotate as well.

### Observed/Actual behavior

When the head rotates, the body should rotate as well, but it rotates after a few seconds.
I also tested it on Paper, and it worked properly. This bug is definitely an issue with Purpur.

### Steps/models to reproduce

https://github.com/user-attachments/assets/279e913c-e32e-42fc-a202-beace04d8eaf

### Purpur version

Current Purpur Version: 1.21.3-2358-16ce24a (MC: 1.21.3)*
* You are running the latest version
Previous: 1.21.3-81-da71382 (MC: 1.21.3)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by Onako2** [comment]
Try without any mods installed, afaik. rotations are handled on the client, no on the server

**Comment by jd07159** [comment]
> Try without any mods installed, afaik. rotations are handled on the client, no on the server

When I tested it on paper under the same conditions, there was no problem. Is this really a mod issue?



https://github.com/user-attachments/assets/c119a501-e281-4c99-9cf7-7279f4471b68

**Comment by granny** [comment]
Cannot give support for 1.21.3 since builds for 1.21.4 are out. Does this issue continue on 1.21.4 builds?

**Comment by jd07159** [comment]
The bug has been occurring since build 2354. It might be related to the pufferfish issue.
I haven't tested it on the latest version yet.

**Comment by granny** [comment]
Can confirm on the latest build of Purpur for 1.21.4. Removing Pufferfish patches fixes this bug. Will most likely drop pufferfish patches at some point tomorrow and wait for the Pufferfish devs to update to 1.21.4 before merging them back in. Once they do and you're able to reproduce this on Pufferfish 1.21.4 builds, report this bug to them.
