### ISSUE TITLE
Redstone completely broken

### ISSUE THREAD

**Issue by Kai-Denzel-Jane** [pl3xgaming/Purpur#1627]
### Spark link

https://spark.lucko.me/boOJ2azCYQ

### Expected behavior

Redstone should work as expected normal I think issue is due to 1.21.X redstone changes.

### Observed/Actual behavior

Redstone often just doesn't activate or stays active after being deactivated
![2024-12-25_17 44 05](https://github.com/user-attachments/assets/dc49540c-f530-47fb-a10a-988668302a24)

### Steps/models to reproduce

Use any redstone related features in a server running Purpur 1.21.4 Latest Build

### Purpur version

Current Purpur Version: 1.21.4-2376-4bf1b98 (MC: 1.21.4)*
* You are running the latest version
Previous: 1.21.4-2372-73dae7f (MC: 1.21.4)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

Yes I know its a beta just giving some insight as this would be something good to fix as soon as possible in time for a full release

**Comment by Onako2** [comment]
Hi,
Could you provide a spark link because it allows us to see the configuration of the server and what plugins are installed.

Am 25. Dezember 2024 09:46:45 UTC schrieb Kai Jane ***@***.***>:

**Comment by Kai-Denzel-Jane** [comment]
> Hi, Could you provide a spark link because it allows us to see the configuration of the server and what plugins are installed. Am 25. Dezember 2024 09:46:45 UTC schrieb Kai Jane ***@***.***>:
> […](#)
> ### Spark link N/A ### Expected behavior Redstone should work as expected normal I think issue is due to 1.21.X redstone changes. ### Observed/Actual behavior Redstone often just doesn't activate or stays active after being deactivated ![2024-12-25_17 44 05](https://github.com/user-attachments/assets/dc49540c-f530-47fb-a10a-988668302a24) ### Steps/models to reproduce Use any redstone related features in a server running Purpur 1.21.4 Latest Build ### Purpur version Current Purpur Version: 1.21.4-2376-4bf1b98 (MC: 1.21.4)* * You are running the latest version Previous: 1.21.4-2372-73dae7f (MC: 1.21.4) ### Agreements - [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads. - [X] I have searched for and ensured there isn't already an open issue regarding this. - [ ] I ticked all the boxes without actually reading them - [X] My version of Minecraft is supported by Purpur. ### Other Yes I know its a beta just giving some insight as this would be something good to fix as soon as possible in time for a full release -- Reply to this email directly or view it on GitHub: #1627 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

https://spark.lucko.me/boOJ2azCYQ

**Comment by Kai-Denzel-Jane** [comment]
@Onako2 Not sure why GitHub just re posted the whole quote reply but there it is at the bottom

**Comment by YouHaveTrouble** [comment]
Reproduce the issue without any plugins.

**Comment by Kai-Denzel-Jane** [comment]
> Reproduce the issue without any plugins.

Ok it seems to be a plugin if you had to guess what plugins are most likley to be it

**Comment by Kai-Denzel-Jane** [comment]
> Reproduce the issue without any plugins.

ok the culprit seemed to be LetYourMemoryRest
