### ISSUE TITLE
(Suggestion) Add config option to allow pickaxes without silk to mine spawners.

### ISSUE THREAD

**Issue by markusew** [pl3xgaming/Purpur#164]
**Reason**
Spawner mining is cool, and it's cool that purpur offers this. But one frustration I have is that you often carry more than 1 pickaxe, 1 for fortune and 1 for silk. And a lot of the time you use the wrong one on spawners resulting in them breaking. It's obviously the players fault but it's a honest mistake. So to alleviate the potential breakdowns, it would be nice to allow for any pickaxe to mine spawners :)

**Comment by BillyGalbreath** [comment]
This would be out of scope for such a niche feature. The system built into Purpur was designed to be very basic, at most. There are a number of freely available plugins that handle much more if more advanced features are needed.
