### ISSUE TITLE
(Suggestion) Make Bookshelves into usable containers for books and alike

### ISSUE THREAD

**Issue by LichLord91** [pl3xgaming/Purpur#169]
Something similar to this https://www.spigotmc.org/resources/bookshelf-enchantment-table-boosting-supports-protection-plugins-pistons-hoppers-droppers.75804/ would be pretty hecken cool.

**Comment by danechek** [comment]
if it is added, please leave the option to choose how to open this container type by "right-clicking" or "shift (sneaking) with right-clicking"

**Comment by BillyGalbreath** [comment]
After discussing this it has been decided that this is just too big of a change to the server code that leads to numerous issues. It is best to just handle this feature in a plugin which will be much more optimized, much more configurable, and with far less code.

**Comment by LichLord91** [comment]
Thanks everyone for looking into this. Sorry it ended up as a wild goose chase. I'll get that plugin if its something I really want to add :).
