### ISSUE TITLE
Add config getMaxLevel by Enchantment

### ISSUE THREAD

**Issue by DoctaEnkoda** [pl3xgaming/Purpur#17]
Hello, 

I am a suggestion, add config by enchantment for restrain or unleash an enchantment. 
Example : Sharpness 8 with an Anvil

**Comment by BillyGalbreath** [comment]
Explain this a little better. I'm not sure I understand what you mean, currently

**Comment by DoctaEnkoda** [comment]
Sorry My english is not good, i am create an example for explain https://hastebin.com/lekakerafo.java

**Comment by BillyGalbreath** [comment]
Have you tested that? I'm curious is the client even allows it

**Comment by DoctaEnkoda** [comment]
Yes i am try just in Anvil by example

Sharpness 5 + Sharpness 5 = lore Sharpness 5 but when we take, its Sharpness 6

**Comment by DoctaEnkoda** [comment]
Ah no I retry with 1.15.2 and Lore Enchant is not broken :D I create actualy a video for you

**Comment by DoctaEnkoda** [comment]
https://youtu.be/EtMIOUqdhM8
You can inspect :)
