### ISSUE TITLE
Both Purpur and PaperSpigot have a PlayerItemCooldownEvent.

### ISSUE THREAD

**Issue by sya-ri** [pl3xgaming/Purpur#173]
What is the difference between Purple and Paper about PlayerItemCooldownEvent?

Paper: https://purpur.pl3x.net/javadoc/io/papermc/paper/event/player/PlayerItemCooldownEvent.html  
Purpur: https://purpur.pl3x.net/javadoc/net/pl3x/purpur/event/player/PlayerItemCooldownEvent.html

**Comment by YouHaveTrouble** [comment]
iirc paper's event is just an event ported from purpur. Only difference is purpur one was there earlier.

**Comment by sya-ri** [comment]
Thank you. I understand very well.

Pupur's event might be a good to change deprecated.
