### ISSUE TITLE
Hex color codes not work in EssentialsX chat display name

### ISSUE THREAD

**Issue by andris155** [pl3xgaming/Purpur#177]
**Describe the bug**
Hex color codes not work in EssentialsX display name.

**To Reproduce**
Use hex color codes in nick name or prefix with EssentialsX chat.
Use displayname/player placeholder. Example.: Default EssentialsX welcome message.

**Screenshots or Videos**
<img width="296" alt="Screenshot 2021-02-23 154155" src="https://user-images.githubusercontent.com/8324198/108859598-ac19c100-75ed-11eb-9600-c7a370a31e56.png">

**Plugins**
Plugins (15): Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, LiteXpansion, LuckPerms, Multiverse-Core, PlugMan, ProtocolLib, SafeNBT, Slimefun, Vault, WorldEdit, WorldGuard

**Version**
This server is running Purpur version git-Purpur-991 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by ghost** [comment]
Better to report to Paper most likely caused by adventure. I had this issue aswell with CMI.

**Comment by andris155** [comment]
https://github.com/PaperMC/Paper/issues/5216
