### ISSUE TITLE
Add new setting to Anvil color patch to always force italic rewrite.

### ISSUE THREAD

**Issue by mibby** [pl3xgaming/Purpur#179]
Would it perhaps be possible to add an option to update the item automatically to remove italic unless specified with the formatting code? Instead of requiring players to use &r.

I also noticed if you put in a name and then ctrl + a delete all text in the text field, the preview item doesn't update / refresh to remove the text. This is probably a minecraft bug since it also occurs with ColoredAnvil.

**Comment by katekerllenevich** [comment]
Does this permission not work? `purpur.anvil.remove_italics`

**Comment by mibby** [comment]
No. It wasn't removing italic automatically, only allowing me to remove it with formatting codes. Or at least the preview item didn't have the italic removed.

**Comment by BillyGalbreath** [comment]
Unfortunately there is no way to please everyone when it comes to this. Best thing we can all do is just go with what upstream does and learn to get used to it.
