### ISSUE TITLE
Suggest : Add option auto-update

### ISSUE THREAD

**Issue by DoctaEnkoda** [pl3xgaming/Purpur#18]
Hello, 

It's possible of create an Auto Update when serveur Start with config defined to false ? 
And let old server to jara for come back and delete next update.

**Comment by Puremin0rez** [comment]
You truly do not want your server binaries to auto update - regardless if you're running a MC server or any other kind of server. There is too much that can and will go wrong if a bad update ever gets pushed.

You should always be doing your own testing on a cloned server before pushing a new build to your live server :)

**Comment by DoctaEnkoda** [comment]
Yes i haven't thought about it after I suggest only ^-^
