### ISSUE TITLE
(Suggestion) Make Parrots Breed-able

### ISSUE THREAD

**Issue by Munchkinnibbler** [pl3xgaming/Purpur#183]
Having the ability to breed parrots would be really cool. It wouldn't have to be huge nor involve baby parrots (although I imagine they'd be adorable) but it would just add a little something that would make sense in the game.

**Comment by BillyGalbreath** [comment]
Baby parrots are not possible without a client side mod, but I do think I can make them pop out a full size one ^_^ I'll see what I can do

**Comment by Munchkinnibbler** [comment]
Alright thanks! Best of luck!

**Comment by squishycat92** [comment]
I've seen a plugin that does this (it doesn't work but has the right idea). Instead of popping out a full-size parrot, perhaps they could lay eggs when breeded that have a custom chance to hatch a parrot?

**Comment by BillyGalbreath** [comment]
https://github.com/pl3xgaming/Purpur/commit/2015fe5f717ec3e0d0cf2d2ca6ae6d52b64c86a4
