### ISSUE TITLE
(Suggestion) Prevent Snow formation on Blue Ice

### ISSUE THREAD

**Issue by Munchkinnibbler** [pl3xgaming/Purpur#186]
Apologies for the 2 suggestions in quick succession but I just wanted to get my ideas out before I forgot!

I find it odd that snow can't form on ice and packed ice but is able to form on blue ice. If possible, could there be a setting to prevent snow from forming on blue ice, please? It would be really good to have the 'no snow on ice' mechanic actually make sense.

Thanks!

**Comment by BillyGalbreath** [comment]
Implemented with https://github.com/pl3xgaming/Purpur/commit/c54e65f87670aad19861efc16ff2325592a87d48
