### ISSUE TITLE
Nether roof block placement

### ISSUE THREAD

**Issue by RidaThe94** [pl3xgaming/Purpur#189]
Players can't place blocks above y-level 128 in the nether and it sends a message to the player "Height limit for building is 128 blocks" ops bypass the limit

**Comment by Munchkinnibbler** [comment]
I believe that is actually possible, I've got purpur running on my server with no issues like that. Check your paper.yml file

**Comment by BillyGalbreath** [comment]
This has to be a restriction from a plugin you have installed. That phrase is nowhere in the server code, and the server doesn't restrict building higher than 128 in the nether
