### ISSUE TITLE
Feature Suggestion - Functional formatting codes in books.

### ISSUE THREAD

**Issue by mibby** [pl3xgaming/Purpur#19]
Would it be feasible at all to create a patch that lets people use formatting codes in book with &? Since 1.14, you can no longer type or use ``§`` so people can't color or format text in books.

**Comment by MiniDigger** [comment]
that should be done via a plugin, just listen to the book edit event and replace the text

**Comment by BillyGalbreath** [comment]
I like this idea. Purpur already does it for signs. I can probably extend the logic for books and anvils, too.

**Comment by BillyGalbreath** [comment]
This is finally done ^_^
