### ISSUE TITLE
[Suggestion] Configurable Ravager break blocks

### ISSUE THREAD

**Issue by AfkF24** [pl3xgaming/Purpur#193]
Hi,

Having an option to configure a list of blocks that Ravagers can break while charging at players would definitely be interesting to have and would add some spice to the game. Currently on Java Edition it's mainly [only leaves](https://minecraft.gamepedia.com/Ravager#Behavior).

Cheers :)

**Comment by BillyGalbreath** [comment]
https://github.com/pl3xgaming/Purpur/commit/c004236dec916b27a9a3013abcd9af39779c0799
https://github.com/pl3xgaming/Purpur/commit/c6dce38b4f768995fd84b764d49498e7fca02574
