### ISSUE TITLE
[Feature Request] Completely disable farmland trampling

### ISSUE THREAD

**Issue by Roan-V** [pl3xgaming/Purpur#198]
Currently it's possible to disable farmland trampling through anything but players, but this obviously still allows players to trample farmland.
A setting to completely enable/disable farmland trampling regardless of what entity is doing the trampling would be nice.

**Comment by BillyGalbreath** [comment]
https://github.com/pl3xgaming/Purpur/commit/a99a83bdf3768c9b95f455c312e63141d0c33612
