### ISSUE TITLE
[Suggestion] Include airplane.air in timings

### ISSUE THREAD

**Issue by YouHaveTrouble** [pl3xgaming/Purpur#199]
Title says it all, we already have all other configs in timings, so adding airplane.air seems like a consistent thing to do.

**Comment by katekerllenevich** [comment]
We should also add purplane.yml to flare.

**Comment by katekerllenevich** [comment]
purpur*

**Comment by LaurenceBarnes** [comment]
purpul*

lol

**Comment by BillyGalbreath** [comment]
Airplane doesnt use the built in YamlConfiguration, so it would be a bit of work to add this. Shoot the request upstream to Airplane, maybe Paul will handle it there like Tuinity does.
