### ISSUE TITLE
[Suggestion] Config option to turn off Llama caravans

### ISSUE THREAD

**Issue by StrangeOne101** [pl3xgaming/Purpur#202]
# Description
The ability to disable Llama's caravan feature. This should be a simple option within purpur.yml in the Llama section.

# Reason for the change
1. The caravan feature of Llamas can cause extreme lag under some circumstances. I've had a server drop to 8 TPS with 3 players, and from looking at timings, it was all because of the Llama's caravan feature. It was because 7 Llamas were tied to a fencepost with a leash, and because of that, they were attempting to follow each other - and failing. 
2. No one really uses the caravan feature of Llamas. Any player is better off carrying shulker boxes or using a mule/donkey for transport, and I've never once seen a player ACTUALLY use it.

**Comment by kevindwitama** [comment]
I've only used the feature once, and that was only to move a bunch of llamas into one area with just a single leash. I agree that this should be added.
