### ISSUE TITLE
Switch of big mushroom in cfg

### ISSUE THREAD

**Issue by danechek** [pl3xgaming/Purpur#211]
I would like to be able to return the old minecraft mechanics of the growth of large mushrooms to the server, that is, so that they can grow only on mycelium blocks. Surely this will be useful to many servers, because of this, the meaning of the mushroom island and mycelium is lost.

**Comment by BillyGalbreath** [comment]
This will break other mechanics, such as the large mushrooms in the dark forest biomes.

**Comment by danechek** [comment]
> This will break other mechanics, such as the large mushrooms in the dark forest biomes.

This is the point for such mushrooms to be only on the mushroom island, as it was before. You can add this to the config so that people themselves can choose the mechanical growth of large mushrooms on the server (new versions - mushroom island and dark forest, old - only mushroom island and blocks of mycelium)

**Comment by BillyGalbreath** [comment]
Ok, I looked around at this, and turns out its 100% doable using a tiny datapack.

[no_dark_forest_mushrooms.zip](https://github.com/pl3xgaming/Purpur/files/6207116/no_dark_forest_mushrooms.zip)
