### ISSUE TITLE
Improve vanilla mechanics of phantoms 

### ISSUE THREAD

**Issue by danechek** [pl3xgaming/Purpur#212]
Phantoms are invented by the authors of the game so that they will spawn near the players who do not sleep N of time, but they attack not these players, and all in a row - is it possible to fix it? so that phantom attacked only that player, because of whom spawned

**Comment by BillyGalbreath** [comment]
I already did this a long time ago and sent it to Paper. It is the default behavior of phantoms to ignore players that have not slept (insomniacs) or are in creative mode.

You can find these settings in paper.yml (defaulted to true)

https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0458-Add-phantom-creative-and-insomniac-controls.patch

**Comment by danechek** [comment]
> I already did this a long time ago and sent it to Paper. It is the default behavior of phantoms to ignore players that have not slept (insomniacs) or are in creative mode.
> 
> You can find these settings in paper.yml (defaulted to true)
> 
> https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0458-Add-phantom-creative-and-insomniac-controls.patch

so, on the contrary, I meant that they only attacked non-sleeping  (insomniacs), and not everyone who is near them
