### ISSUE TITLE
Players getting timed out randomly

### ISSUE THREAD

**Issue by YouHaveTrouble** [pl3xgaming/Purpur#213]
Sometimes players are unable to play on the server due to instant timeout. They join, they log into the server and instantly lag out on their side. After about 30 seconds they are kicked from the server due to keepalive timeout. I observed this for multiple people and on multiple servers on multiple machines with multiple network setups. I can track this issue down to the last 2 months or earlier. It happens with alternate-keepalive enabled or disabled, doesn't matter. 

This issue has been consistant on my server and on the servers of people that I know. It sometimes fixes itself on its own, sometimes it's fixed by player updating java.

From what I've gathered, problem does not appear to exist on latest purpur 1.16.4, so assuming it exists 1.16.5+

I will update this report if I get more information about the issue.

**Comment by katekerllenevich** [comment]
I'm assuming you've tested on Paper? If it works there, it wouldn't surprise me if the issue is created by Tuinity.

**Comment by YouHaveTrouble** [comment]
> I'm assuming you've tested on Paper? If it works there, it wouldn't surprise me if the issue is created by Tuinity.

I personally cannot reproduce the issue,(and I can't switch to paper on my prod) so it's hard for me to test it, I'm just gathering the information around from people experiencing this. It's really random, can't point out what triggers it.

**Comment by katekerllenevich** [comment]
I wonder if this could be related to PaperMC/Paper#5173

**Comment by YouHaveTrouble** [comment]
I asked around, apparently paper experiences the same issue. Will open the issue there, but don't close this one, so people know what's up.

**Comment by BillyGalbreath** [comment]
This has been an ongoing vanilla bug for as long as I can remember. It hasn't always effected everyone, and it seems to come in waves. Some people it happens all the time, some people it never happens to. Others, like you and me, seems to have it only sometimes. The version I had major issues with it was 1.10.x but it went away for me after that, but it wasn't fixed and others got the problem. Paper became aware of the problem in 1.12.x (see https://github.com/PaperMC/Paper/issues/895)

There is nothing anyone can do about this, as it all boils down to the client's network. Lowering your view distance can help, but isn't always the answer (it helped my server in the past).

**Comment by YouHaveTrouble** [comment]
Thing is, I've never had this on 1.16.4 on my server, neither on my previous 1.14.4 server, neither on my first server on 1.13.2, and I see more and more people with this problem on 1.16.5. Something definitely went wrong somewhere.

And it's not the error that is mentioned in the paper issue, it's just this. no visible errors, just timeout.
`[Netty Epoll Server IO #0/DEBUG]: Timeout
io.netty.handler.timeout.ReadTimeoutException: null`
