### ISSUE TITLE
(Suggestion) No Hostile Mob Spawns on Ice

### ISSUE THREAD

**Issue by Munchkinnibbler** [pl3xgaming/Purpur#214]
I think it would make sense for hostile mobs to not be able to spawn on any type of ice, so ice, packed ice and blue ice. If possible, adding that would be great! It would also allow for some really cool dark builds. Thanks

**Comment by katekerllenevich** [comment]
RIP Polar Bears

**Comment by Munchkinnibbler** [comment]
Pretty sure they can spawn on grass blocks so that wouldn't remove polar bear spawns.

**Comment by katekerllenevich** [comment]
*RIP Most Polar Bears lol

**Comment by Munchkinnibbler** [comment]
lol Polar bear spawns on grass would simply increase if I'm understanding the game mechanics correctly
