### ISSUE TITLE
Durability/full inventory alerts 

### ISSUE THREAD

**Issue by danechek** [pl3xgaming/Purpur#216]
I suggest adding durability/full inventory alerts if that comply the Purpur theme. It is writes a message in the chat or action/title bar if the item in the hand is almost broken or the inventory is full. Also, so that it is configurable on what residual durability it will warn, and separately enable/disable these both functions + choose where the notifications will be in the chat or action/title bar.

**Comment by BillyGalbreath** [comment]
This is best left up to a tiny 5 line plugin or skript
