### ISSUE TITLE
Suggestion : Modify GenericAttributes.MAX_HEALT to Enderdragon

### ISSUE THREAD

**Issue by DoctaEnkoda** [pl3xgaming/Purpur#22]
Add parameter for modify GenericAttributes.MAX_HEALTH on Entity EnderDragon. 
He is actualy to : 200.0D
Files : EntityEnderDragon.java
code : this.getAttributeInstance(GenericAttributes.MAX_HEALTH).setValue(200.0D);

**Comment by DoctaEnkoda** [comment]
up ?

**Comment by BillyGalbreath** [comment]
I have plans to add all the attributes of all mobs eventually
