### ISSUE TITLE
[Suggestion] Bulk composter fill

### ISSUE THREAD

**Issue by shateq** [pl3xgaming/Purpur#220]
There is always that moment, when I have got 64 of seeds or something other, and I have to stand still for some time and spam click to fill the composter with those seeds.

**I would like to see "Bulk composter fill"**, you hold shift, and then the right click - composter has been filled with right amount of your item and percent to filling (got this percents from [this place](https://minecraft.gamepedia.com/Composter)). As usual, we can have configuration section for this one 😅

**Comment by BillyGalbreath** [comment]
https://github.com/pl3xgaming/Purpur/commit/f754a7b6161f5fb0c0c8342cef75727ad0e8c7b5
