### ISSUE TITLE
gradle dont work java 16

### ISSUE THREAD

**Issue by Euphillya** [pl3xgaming/Purpur#225]
**Describe the bug**
Impossible compile with java 16

**To Reproduce**
Use jdk 16

**Screenshots or Videos**
java.lang.IllegalAccessError: class org.gradle.internal.compiler.java.ClassNameCollector

**Comment by TheDGOfficial** [comment]
Not a Purpur problem. See
https://github.com/gradle/gradle/issues/13481 .

To resolve it, you have four common options:

1) Use JDK 15 for running Gradle but fork the compiler to use/target JDK 16,

2) Use Gradle 7.0 milestone/RC versions,

3) Just use and target Java 15 or 11,

4) Add all required —add-opens directives (or —illegal-access=permit)

**Comment by jpenilla** [comment]
Not a Purpur issue. See the comment from @TheDGOfficial.
