### ISSUE TITLE
[Suggestion] Configurable anvils 

### ISSUE THREAD

**Issue by shateq** [pl3xgaming/Purpur#226]
## **As in the title, abilities to:** 
- Disable anvil 'too expensive' note
- Disable anvil breaking
- Make renaming free

(These I have got in my head for now)

**Comment by craftish37** [comment]
Maybe a configurable cost factor ?

Ex.: Mending cost 2lvl on a new item
       --> Make it cost 4lvl with a cost factor = 2
       
I love your idea, it looks great !

**Comment by YouHaveTrouble** [comment]
It's impossible to remove the "too expensive" note without setting a hard limit of 39 on every anvil repair. The note is given client side and you can only remove it via client side mod.

**Comment by ghost** [comment]
https://github.com/Jikoo/AnvilUnlocker ; what i have been using. It's not a perfect solution.

**Comment by YouHaveTrouble** [comment]
https://github.com/pl3xgaming/Purpur/issues/25

**Comment by BillyGalbreath** [comment]
Anvils are a tricky thing, tbh. I've already added [as much API to anvils as I can](https://github.com/pl3xgaming/Purpur/blob/ver/1.16.5/patches/api/0018-Anvil-API.patch), including ways to allow plugins to bypass max cost. But as mentioned, its a bit tricky to pull it off correctly. You can take a look at my Hats plugin to see [how I made a crown bypass max cost](https://github.com/pl3xgaming/Hats/blob/master/src/main/java/net/pl3x/bukkit/hats/listener/AetherialListener.java) when worn. The rest of your request is already possible with the existing API. Just have to make yourself a tiny plugin to handle it with the specifics you want.
