### ISSUE TITLE
Clerics farm potatoes/carrots on soul sand

### ISSUE THREAD

**Issue by Maroon28** [pl3xgaming/Purpur#227]
**Describe the bug**
With  `clerics-farm-warts: true` enabled in the purpur config, clerics actually farm potatoes/carrots rather than netherwarts, which is what the option said they would. They don't farm them anywhere, they do it over soul sand, which is impossible to do by any normal means.
**To Reproduce**
Seems like just putting the clerics in an area with netherwarts does the trick. I believe they're also influenced by the farms near them.
**Screenshots or Videos**
https://imgur.com/a/2BJYP0F
**Plugins**
Plugins (81): AAC5, AdvancedEnchantments, AntiXrayHeuristics, AuctionHouse, AutoMessage, AutoRestart, BetterReports, BungeeGuard, BuycraftX, ChatBot, ChatBrawl, ChatControl, ChatItemDisplay, Chunky, Citizens, ColorCodes, CombatLogX, CommandCooldown, CommandPanels, CommandWhitelist, CoreProtect, CubCustomDrops, DeathMessages, DeluxeTags, Duels, Essentials, EssentialsSpawn, ExtractableEnchantments, FarmLimiter, GSit, GadgetsMenu, GoldenChallenges, GoldenCrates, GriefPrevention, GriefPreventionFlags, HolographicDisplays, ImageOnMap, InventoryRollbackPlus, LPC, LastLoginAPI, LibsDisguises, LiteBans, LoginStreak, LuckPerms, Marriage, MineableSpawners, MobHeads, Multiverse-Core, MyCommand, NamelessMC, NexEngine, NoMobLag, OldCombatMechanics, OpenInv, OreAnnouncer, Parties, PlaceholderAPI, PlayerWarps, ProtocolLib, QuickShop, RandomTeleport, SAML, ServerUtils, Snowboard, StatsSB, TAB, Tamablefoxes, TradePlus, UltraWelcome, Vault, ViaBackwards, ViaVersion, ViewDistanceTweaks, VoidGenerator, Votifier, VotingPlugin, WorldEdit, WorldGuard, WorldGuardExtraFlags, ajParkour and spark

**Version**
This server is running Purpur version git-Purpur-1015 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 10 version(s) behind
Previous version: git-Purpur-966 (MC: 1.16.5)
**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
It is not present in either of these.
**Additional context**
No

**Comment by jpenilla** [comment]
Should be fixed in c3de3ac665d530a852f21949d1fa731de570c550 (build 1033)
