### ISSUE TITLE
[Feature] Configurable 6 row shulker boxes

### ISSUE THREAD

**Issue by Draycia** [pl3xgaming/Purpur#24]
I'd like to have an option to set the size of shulker boxes, similar to barrels and ender chests.

**Notes**
In my attempts to do this, I've unintentionally made it so shulker boxes can be put in shulker boxes. For obvious reasons I would not like this to be the case.

**Comment by DoctaEnkoda** [comment]
The best I think and do like the enderchest, by permission :)

**Comment by BillyGalbreath** [comment]
Gonna scrap this idea. It's just a nightmare all around to implement :3
