### ISSUE TITLE
Separate Slab breaking triggers every single time

### ISSUE THREAD

**Issue by kohy-creates** [pl3xgaming/Purpur#240]
**Describe the bug**
break-individual-slabs-when-sneaking triggers every time, even when player isn't sneaking

**Plugins**
Plugins (29): ChestShop, Chunky, Citizens, eco, EcoEnchants, GriefPrevention, HeadDatabase, HolographicDisplays, LibsDisguises, LuckPerms, Multiverse-Core, OpenAudioMc, ProtocolLib, SkBee, skDragon, SkQuery, skRayFall, Skript, skript-reflect, Tablisknu, ThatPacketAddon*, TheNewEconomy, TuSKe*, Vault, Vixio*, Votifier, WorldEdit, WorldEditSelectionVisualizer, WorldGuard

**Version**
This server is running Purpur version git-Purpur-1042 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Purpur-1038 (MC: 1.16.5)

**Comment by BillyGalbreath** [comment]
Oh man, this is my bad ^_^ I got so excited about the feature itself that I completely forgot to make it only work on sneak :3 I'll get this fixed soon.
