### ISSUE TITLE
[Suggestion] Changing liquid flow distance

### ISSUE THREAD

**Issue by Cypphi** [pl3xgaming/Purpur#242]
This would be an option in the purpur.yml. It would basically have the value of the default flow distance which you can change to let's say, let water flow 20 blocks far on a flat area...

**Comment by BillyGalbreath** [comment]
this wouldn't look good on the client, since flowing liquids are not a flat top surface. it would also generate a _lot_ of lag (liquids are one of the laggiest things in the game, which is why so many lag machines use water)
