### ISSUE TITLE
(Suggestion) Ability to give a poppy to an Iron Golem to calm him down.

### ISSUE THREAD

**Issue by Piki-dev** [pl3xgaming/Purpur#245]
Whenever a Iron golem is mad at the player you can give him a poppy to put his behavior back to normal. The Iron golem will simply equip the poppy in his hand and not be aggressive to the player anymore until it gets provoked again.

**Comment by danechek** [comment]
Good idea

**Comment by SeasonalFerret** [comment]
this is cute af ngl

**Comment by BillyGalbreath** [comment]
https://github.com/pl3xgaming/Purpur/commit/552d783c644528db64c6e19a78bef3a729580d8a
