### ISSUE TITLE
Suggestion: dispenser tweaks/functions

### ISSUE THREAD

**Issue by emielderckx** [pl3xgaming/Purpur#246]
I don't know if you guys want this but I like these idea's. And this is a big one I'm sorry. If there are questions ask them!

1. Dispensers containing shears can carve pumpkins.
2. Dispensers can feed animals.
3. Dispensers can fill minecarts: filling them with hoppers, chest, tnt or furnaces.
4. Dispensers can milk cows (nothing need to happen when you power a dispenser with a already filled milk bucket).
5. Dispenser can play records (I'm not sure about this one).
6. Dispensers with hoes can till soil. (grass to farmland, grass path to farmland and coarse dirt to dirt).
7. Dispensers with shovels can turn grass blocks to grass paths.
8. Dispensers can feed zombie villagers golden apples to cure them.
9. Dispensers can dye mobs (sheep).
10. Dispensers can name mobs when filled with nametags.
11. Dispensers can get  suspicious stew from mushroom cows
12. Dispensers can plant flowers in flower pots (Idk why this would ever be usefull so idk)

**Comment by BillyGalbreath** [comment]
I really don't like touching the dispenser stuff, only because the recipe handler for it kinda blows (blame mojang). This is something a plugin should handle so it doesnt effect servers that dont want this feature
