### ISSUE TITLE
Suggestion: When guardian is struck with lighting it turns to elder guardian

### ISSUE THREAD

**Issue by emielderckx** [pl3xgaming/Purpur#250]
When guardian is struck with lighting it turns to elder guardian. If this was in the game I could make sponges renewable in a fun way

**Comment by craftish37** [comment]
Sponges are farmables :
https://www.youtube.com/watch?v=c7eoLnMnNYE
But it's of course a very simple way and very funny :)

**Comment by emielderckx** [comment]
> Sponges are farmables :
> https://www.youtube.com/watch?v=c7eoLnMnNYE
> But it's of course a very simple way and very funny :)

This looks like a bug not a feature...

**Comment by craftish37** [comment]
![tempo](https://user-images.githubusercontent.com/63811617/112629481-abff2200-8e34-11eb-8791-38364916f0ef.jpg)

**Comment by BillyGalbreath** [comment]
This wouldn't really work because [lightning doesnt strike underwater](https://minecraft.fandom.com/wiki/Thunderstorm#Lightning_mechanics).

![image](https://user-images.githubusercontent.com/332527/112691573-8598b100-8e4b-11eb-818f-accd40a691cc.png)
