### ISSUE TITLE
Unsupported Java detected (60.0). Only up to Java 15 is supported. - Build 956 (1.16.4)

### ISSUE THREAD

**Issue by kyngs** [pl3xgaming/Purpur#251]
So, recently I've installed Java 16 and found out that it is infact not supported, I do not see a reason why it shouldn't because backward compatibility with Java 15 should be 100%. So please update it to Java 16.

**Comment by encode42** [comment]
~~That's not our fault, see #225.~~

Edit: Wrong issue, but that's still not our fault but may be resolved soon.

**Comment by kyngs** [comment]
> ~That's not our fault, see #225.~
> 
> Edit: Wrong issue, but that's still not our fault but may be resolved soon.

Where should I post this issue then? Is it in Paper, Bukkit, or right in the Vanilla version?

**Comment by encode42** [comment]
Nowhere, it's already been fixed IIRC. Just have to wait.

**Comment by kyngs** [comment]
Ok thanks, however, will this update be available for 1.16.4?

**Comment by encode42** [comment]
No. The upgrade from .4 to .5 is nearly seamless. You may have to update a couple of plugins, that's all.

**Comment by Euphillya** [comment]
Why dont use 1.16.5 ?

**Comment by kyngs** [comment]
> Why dont use 1.16.5 ?

Simple reason, still a lot of fabric mods are not available, so it is not a good option for players, however, I guess I will need to update then.

**Comment by encode42** [comment]
1.16.4 clients can connect to 1.16.5 servers, you don't have to worry about that.

**Comment by kyngs** [comment]
> 1.16.4 clients can connect to 1.16.5 servers, you don't have to worry about that.

oh ok, ty.
