### ISSUE TITLE
Suggestion: Chat config options

### ISSUE THREAD

**Issue by xcodian** [pl3xgaming/Purpur#253]
- The option to disable the chat entirely. (Do not process `ChatEvent`s)
- The option to not *show* the chat to players, but still *process* the `ChatEvent` internally (for BC configs like BungeeChat's)
- (unsure) Potentially a very basic chat formatting option?
- (unsure) Potentially an in-built method to prevent players from executing `/pl` `/version` etc.

**Comment by encode42** [comment]
The plugin and version commands can be easily blocked by negating their permission, or a plugin such as CommandWhitelist if so needed. A patch dedicated to those wouldn't really be deserved. I'll look into the other suggestions when time comes.

**Comment by BillyGalbreath** [comment]
> * The option to disable the chat entirely. (Do not process `ChatEvent`s)

Just create a plugin to cancel the chat events on lowest priority..

> * The option to not _show_ the chat to players, but still _process_ the `ChatEvent` internally (for BC configs like BungeeChat's)

Just create a plugin that removes the recipients from the chat event on lowest priority

> * (unsure) Potentially a very basic chat formatting option?

the chat events are there for editing the chat formatting...

> * (unsure) Potentially an in-built method to prevent players from executing `/pl` `/version` etc.

as stated, these are already behind permission nodes..
