### ISSUE TITLE
Suggestion: Crop replace

### ISSUE THREAD

**Issue by KaspianDev** [pl3xgaming/Purpur#257]
Option to enable crop auto replanting on right click with hoe :) with durability use option

**Comment by YouHaveTrouble** [comment]
This can be easily accomplished by a plugin, just listen to BlockBreakEvent while holding a hoe, and if it's any of the crop blocks, just set it back as that.

**Comment by KaspianDev** [comment]
still i think its a thing that should be added to purpur
