### ISSUE TITLE
Issue: Mob Heads do not Move and are frozen to where mob body is facing.

### ISSUE THREAD

**Issue by ghost** [pl3xgaming/Purpur#258]
**Describe the bug**
When standing next to a mob it will slowly turn towards the player instead of the usual fast turning and fast looking up and down motion that mobs tend to do.

**To Reproduce**
Stand next to any mob and wait for it to slowly turn without looking at the player. Preferably a pet such as a dog or cat as they can be sat down allowing it to be easier to notice.

**Video**
https://www.youtube.com/watch?v=J2rNnOtUAmE
https://www.youtube.com/watch?v=Vb1Eq0BZhwE

**Plugins**
https://imgur.com/a/xu64Mzy

**Version**
https://imgur.com/a/Xgx4FTE

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
Bug is not present on Paper, Spigot, CraftBukkit or Vanilla.

**Additional context**
All players are experiencing this, not just a client side bug.

**Comment by BillyGalbreath** [comment]
Reproduce without plugins, please

**Comment by BillyGalbreath** [comment]
I'm still unable to reproduce this. Closing this due to lack of response.

I'm 99% sure this is a plugin issue. Try reproducing it without any plugins.
