### ISSUE TITLE
[Suggestion] Wandering trader custom sell

### ISSUE THREAD

**Issue by Misio12320** [pl3xgaming/Purpur#259]
Add a feature to create custom trades for wandering trader ex:
Purchase cost: 1 emerald
Sell result: 2 sand
Chance to add this trade after spawn: 50 (percent)

**Comment by jpenilla** [comment]
Either use a datapack or a plugin for this. See [VanillaTweaks](https://vanillatweaks.net/picker/datapacks/) for a datapack you can start editing, or [WanderingTrades](https://www.spigotmc.org/resources/wandering-trades.79068/) for a plugin to do the same thing.
