### ISSUE TITLE
Suggestion: Add configurable chance for nether portal zombified piglin spawn

### ISSUE THREAD

**Issue by ChiboYen** [pl3xgaming/Purpur#262]
From the Minecraft wiki:
> When a nether portal block in the Overworld receives a block tick, there is a chance of 1⁄2000 (0.05%) on Easy, 1⁄1000 (0.1%) on Normal and 3⁄2000 (0.15%) on Hard for it to spawn a zombified piglin.

However, players build massive piglin farms such as the one below:
![](https://ofsyad.wheres-my-ta.co/BRdEO0.png)

This results in 300+ entities per farm within seconds, so hopefully a way to change this value (chance) is added. There is already an option somewhere to nerf piglins spawning from portals, but they still spawn and I would prefer not to break the farms.

**Comment by danechek** [comment]
It would also be nice to be able to set the chance of skeletons spawning in the form of a skeleton rider (on a spider) and the chance of spawning skeletons on skeletal horses, as well as the chance of music records falling from a creeper killed by a skeleton. Well, and a charged creeper :) All these are vanilla parameters of rare mobs/items that would be good to configure in the core configuration, and not using additional plugins

**Comment by encode42** [comment]
Origami has this feature iirc, I'll look into it.

**Comment by encode42** [comment]
Isn't this closed by 24d9e61d2e9e395a5172d644965c931b01b0234d?
