### ISSUE TITLE
Server crashes when a player disconnect

### ISSUE THREAD

**Issue by MrLolok** [pl3xgaming/Purpur#263]
**Describe the bug**
Since I transformed the main world from a normal world to a slime world, it happens that when a player disconnects the server crashes with this error: https://pastebin.com/Fb6Kcc8D

**To Reproduce**
Just change all chunks to slime chunks and disconnect from the server

**Plugins**
Plugins (29): BedWars1058, BedWars1058-TeamSelector, BuycraftX, Citizens, Clans, CMI, CMILib, DeluxeMenus, GPerm-Support, IPWhitelist*, ItemJoin, LeaderHeadsRevamped, LPX*, LuckPerms, OldCombatMechanics, PlaceholderAPI, PlugMan*, ProtocolLib, SlimeWorldManager, spark, TimeActions, Vault, Verus*, ViaBackwards, ViaRewind, ViaVersion, VoidGenerator, WorldEdit, WorldGuard

**Version**
This server is running Purpur version git-Purpur-1051 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
No, this bug is present only with Purpur

**Comment by danechek** [comment]
> **To Reproduce**
> Just change all chunks to slime chunks and disconnect from the server
In paper config? All chunks = slime chunks?

**Comment by MrLolok** [comment]
However this error occurs with all-chunks-are-slime-chunks: true either with all-chunks-are-slime-chunks: false in paper.yml
