### ISSUE TITLE
Suggestion: Number of enderchest, chests and barrel's rows

### ISSUE THREAD

**Issue by zeus1921** [pl3xgaming/Purpur#264]
Make it customizable from 1 to 6 rows

**Comment by encode42** [comment]
The enderchest rows can be changed via a permission, see the wiki page

**Comment by granny** [comment]
<https://pl3xgaming.github.io/PurpurDocs/Configuration/#ender_chest>
<https://pl3xgaming.github.io/PurpurDocs/Configuration/#barrel>
