### ISSUE TITLE
Suggestion: Chance of piglin trade some extra items

### ISSUE THREAD

**Issue by zeus1921** [pl3xgaming/Purpur#266]
add option to enable chance of piglin trade some extra items (default: 0) from a list that server owner could customize

**Comment by danechek** [comment]
https://www.spigotmc.org/resources/custom-piglins-trades-1-16-custom-trades-with-simple-gui.81234/ haven't tried using this?

**Comment by Darwin1546** [comment]
You can even do it with datapack

**Comment by zeus1921** [comment]
ah nice. thanks folks.
