### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Roshanxy** [pl3xgaming/Purpur#268]
Would it be possible to add a feature were it is possible to import a .json world generation file, a feature that is available in single player?
https://minecraft.fandom.com/wiki/Custom

You can create a .json file with custom generation such as custom noise seeds and structure seeds etc. 
Perhaps with a line in config that says something like

customjson=

customjson=data.json (json file must be in root directory then)

**Comment by encode42** [comment]
https://syldium.github.io/worldgen/
What you're looking for is datapacks which are already part of the vanilla server.

There's a couple of examples in the datapacks channel of the Discord server.
