### ISSUE TITLE
Question about building upstream

### ISSUE THREAD

**Issue by x1p** [pl3xgaming/Purpur#27]
**Describe the feature**
I really would like to know if it's possible for non-devs like me to create an upstream myself.
Building the current version of purpur works fine. Although I find it peculiar that my jars are bigger and contain more folders.

**To Reproduce**
I tried ./purpur up up. Paper is then newer than than purpur expects. But during the ./purpur build step, things get into numerous errors.
I tried to follow the console output of the jenkins site. But even the first commands are impossible to execute.
I tried all possible combinations but I'm a bit stuck.

**Setup**
Linux workstation

**Comment by BillyGalbreath** [comment]
If upstream has changed anything relative to what I've changed in Purpur then there will be conflicts. This is a normal part of development and is part of the upgrade process, but it's honestly above non-developer's scope.

If you want to look more into it, its just simply fixing all the merge conflicts. Lots of articles on Google on how to do it. Just know, it's not really for non-developers.

In the cases where nothing conflicts, then an upstream merge is pretty straight forward as expected, though.
