### ISSUE TITLE
Suggestion: Don't load/generate chunks outside of the worldborder

### ISSUE THREAD

**Issue by ghost** [pl3xgaming/Purpur#270]
If it's possible a option to have any chunks that are outside of the worldborder not load or generate.

**Comment by ChiboYen** [comment]
You could just set a generous buffer zone around the worldborder that's pre-generated if you don't want the border to be unsightly

**Comment by pop4959** [comment]
Perhaps a better request: "Don't render tiles for chunks outside of a region." Plugins like BlueMap have this feature, where you can specify minimum and maximum bounding coordinates.

Preventing chunk loading itself is typically something that a mapping plugin like Pl3xMap wouldn't handle. Usually you can also handle this yourself by leaving some buffer space outside of your world border (e.g. if your world border is at 10,000, generate to 10,200; just past the render distance to make it look clean) or using a void generator plugin to ensure that any chunks that *do* generate aren't populated and thus won't display on the map.
