### ISSUE TITLE
Diamond veins generation is highly predictable now!

### ISSUE THREAD

**Issue by RealRONiN** [pl3xgaming/Purpur#272]
**Describe the bug**
You can find diamond ore veins by doing some maths with clay and gravel patches in rivers/swamp-rivers

**To Reproduce**
1) Find a big clay patch in river or swamp river biome
2) Count 6 blocks from the middle of that patch in south direction.
3) Dig down on sixth block.

Note: if the sixth block is on chunk border then there is a chance that the veins will generate on the opposite edge of the chunk border.

**Screenshots or Videos**
https://youtu.be/5Icj5TNmBUI

**Plugins**
None.

**Version**
1.16.5

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
It is present in Vanilla, and it works on latest Purpur #1051

**Additional context**
If we can just swap the diamond generation with a different given seed in purpur.yml, that will be great. I'm sorry for this very messy report and I really don't know about how the backend stuff(coding) works, but this.... this is gonna ruin the server economies :(

**Comment by RealRONiN** [comment]
I'm sorry I forget to mention this, but I tried this with four different random seeds and it works every freaking time.

**Comment by emielderckx** [comment]
This is just math and vanilla behaviour you could just use a datapack to change world gen

**Comment by RealRONiN** [comment]
> This is just math and vanilla behaviour you could just use a datapack to change world gen

Pleas, can you provide any certain datapack which can do the job? My server gonna release this Sunday and few players sent me this video, I don't want it to die in the first week :(

**Comment by craftish37** [comment]
I'm doing it with Starmute, post it in a couple hours

**Comment by craftish37** [comment]
~[sorry-but-no.zip](https://github.com/pl3xgaming/Purpur/files/6274945/sorry-but-no.zip)~
~For me it's fixed, use this, it will enlarge a bit the clay, sand and gravel patches in swamps and mess this if I've correctly do my work 👍~

**Comment by craftish37** [comment]
Fix - Forgot to put clay instead of gravel
[sorry-but-no.zip](https://github.com/pl3xgaming/Purpur/files/6275007/sorry-but-no.zip)
