### ISSUE TITLE
Anti X-Ray not working when player random teleports

### ISSUE THREAD

**Issue by Inxity** [pl3xgaming/Purpur#275]
**Describe the bug**
Random Teleport breaking Paper's Anti X-Ray

**To Reproduce**
Use a Random Teleport plugin in a Paper's Anti X-Ray world, when you random teleport anti xray wont work.

**Screenshots or Videos**
![image](https://user-images.githubusercontent.com/61350916/114018831-56843580-9876-11eb-86c3-b56f73459a9b.png) First photo is after randomteleport

![image](https://user-images.githubusercontent.com/61350916/114018866-63a12480-9876-11eb-9df5-9c2c7a630bea.png)Second photo is not randomteleporting

**Plugins**
![image](https://user-images.githubusercontent.com/61350916/114018957-829fb680-9876-11eb-8ddf-2b1713196e55.png)

**Version**
![image](https://user-images.githubusercontent.com/61350916/114018999-8f240f00-9876-11eb-9a58-2dad2cc00b93.png)

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
Maybe on Paper, not tested.

**Additional context**
nope

**Comment by skw359** [comment]
I can't reproduce the issue. Tried EssentialsX's /tpr or /rtp (different plugin). Perhaps its a plugin messing with packets? Anti xray seems to work fine for me.

**Comment by Inxity** [comment]
I tried Orebfuscator and disabled Paper Anti-Xray and worked fine, problem still occurs in my server when i use Paper's.

**Comment by encode42** [comment]
Try reproducing the issue with the same plugin and configurarion setup on Paper. I don't believe Purpur would be causing this issue.
