### ISSUE TITLE
Add ArmorEquipEvent 

### ISSUE THREAD

**Issue by DoctaEnkoda** [pl3xgaming/Purpur#28]
Possible Add ArmorEquipEvent ? 
https://hastebin.com/korenixeto.java

**Comment by BillyGalbreath** [comment]
This is definitely something that's doable, imo. I just dont have the time to do it myself. I'm open to accepting a PR ^_^

There's also libraries out there that you can use, like https://www.spigotmc.org/resources/lib-armorequipevent.5478/
