### ISSUE TITLE
Op whitelist 

### ISSUE THREAD

**Issue by danechek** [pl3xgaming/Purpur#283]
White-list for players who can be dopped (username/uuid). Like a bukkit whitelist in a separate file

**Comment by encode42** [comment]
Why would you want this? You shouldn't be giving players that can't be trusted not to de-op others op. If you really want this, you can create a small plugin that blocks commands from being run by certain players.

**Comment by BillyGalbreath** [comment]
The vanilla commands have permissions. Just assign the permissions for the op and deop commands to whoever you want to be able to use those commands...
