### ISSUE TITLE
Exp Dropped on Death Doesn't Seem to be Working

### ISSUE THREAD

**Issue by Munchkinnibbler** [pl3xgaming/Purpur#288]
Hello, as the title suggests, the exp dropped on death feature doesn't seem to be working. Either that or it isn't set up correctly my end. At the moment it is configured as:

exp-dropped-on-death:
          equation: expLevel / 4
          maximum: 32766
   
with the intention of 25% of your experience level being dropped. That does not seem to work. I have tried to seek assistance on the discord's support channel on 5 separate occasions and each time I have been entirely ignored.

Any help you can offer will be greatly appreciated.

**Comment by BillyGalbreath** [comment]
`expLevel` is just their level. you want to use `expTotal` if you want to get 25% of the total exp. It still will not give them 25% of their levels back, but it will give their total. Remember, that [each level is worth more exp than the previous](https://minecraft.fandom.com/wiki/Experience#Leveling_up), so an even 25% is not easy to do.

https://minecraft.fandom.com/wiki/Experience#Useful_numbers
> Level 16 is a quarter of the way to level 30, while level 22 is about halfway there. Level 30 in turn, is halfway to level 39.
