### ISSUE TITLE
Piglin Brutes do not become aggro when near the player in survival mode.

### ISSUE THREAD

**Issue by piuvas** [pl3xgaming/Purpur#289]
Whenever going near a piglin brute, it does not reproduce the expected behavior of becoming aggressive, this seems to be an issue already present in newer versions of Paper and it is incredibly game-breaking.

Summon or get in contact with a naturally generating piglin brute in survival mode, any difficulty and any armor to reproduce this bug.

Plugins: DiscordSRV, ViewDistanceTweaks.

Version: Purpur version git-Purpur-1060 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

This was tested in Paper version as early as 1.16.5-526 and seems to be an issue experienced by other players.
https://github.com/PaperMC/Paper/issues/5330 (it should be noted that in my testing, hoglins reproduced expected behavior)

It seems to be useful to note that in git-Purpur-1056 piglin brutes showed normal behavior.

**Comment by BillyGalbreath** [comment]
If you can reproduce this on Paper then it is an upstream bug. It should be reported to them so they can get it fixed.
