### ISSUE TITLE
Purpur API item.setImmuneToCactus()  makes item invisible when thrown onto cactus.

### ISSUE THREAD

**Issue by YouHaveTrouble** [pl3xgaming/Purpur#290]
**Describe the bug**
Items marked to be indestructible by a cactus via the API disappear for the client when thrown into a cactus. This does not happen with setImmuneToExplosion nor setImmuneToFire. Bug has been present since setImmuneToCactus was introduced.

**To Reproduce**
Create a plugin with ItemSpawnEvent listener and do 
```java
Item item = event.getEntity();
item.setImmuneToCactus(true);
 ```

**Plugins**
None.

**Version**
This server is running Purpur version git-Purpur-1060 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by encode42** [comment]
I'm pretty sure this is an issue with the client which still kills the item client-side despite it not being killed on the server.

**Comment by granny** [comment]
Yeah, there's nothing we can do server-side to fix this issue since it's a client-side issue.

**Comment by YouHaveTrouble** [comment]
Item is getting killed client side in case of explosion and fire too. I don't see why the cactus would behave differently.

Let me make things clear: the bug does not occur when the item is set to be immune to cactus from the config. It only happens with the api cactus immunity.
