### ISSUE TITLE
Lava Source Blocks disappear from underneath Furnaces

### ISSUE THREAD

**Issue by SamSam33333** [pl3xgaming/Purpur#293]
I have enabled the feature to have unlimited smelting when lava is placed underneath furnaces, but for some reason once the furnace is done smelting whatever is in it, the lava source underneath disappears.

This is kind of counterproductive to the infinite smelting feature and I did not know if anyone else was having this issue, but I feel like it needed to be brought up.

**Comment by encode42** [comment]
That's how it works. You're meant to enable the infinite lava source option as well and create one underneath the furnace. The option on the furnace only enables the ability to use lava from beneath the furnace.

**Comment by SamSam33333** [comment]
Ahhhhh ok. I do apologize then. I thought it was an issue Thank you so much for clarifying
