### ISSUE TITLE
[global] TIMING_STACK_CORRUPTION

### ISSUE THREAD

**Issue by ezenity** [pl3xgaming/Purpur#30]
### Link/paste of stack trace
- https://hasteb.in/detixiqo.md

### Plugin list:
- Pl3xCraft
- Reach
- SmartInvs
- Vault

### Paper build number:
- purpurclip-517

**Comment by BillyGalbreath** [comment]
Try using build 606 https://ci.pl3x.net/job/Purpur/606/

**Comment by ezenity** [comment]
Okay, if it appears again I will post the stack trace here. Want to note that this stack trace only occurred once with build 517 and it was when I forced closed the server while a phantom was above me.
