### ISSUE TITLE
Add a feature to disable tick-villager via a command.

### ISSUE THREAD

**Issue by Misio12320** [pl3xgaming/Purpur#306]
I would like to have it because when I'm not online on my server I want to have tick-inactive-villagers to true. But when I join I would like to disable it because I have a lot of lags in TPS and I can't play. When I want to play without lags I need to restart/reload the server to set tick-inactive-villagers to false. A command which can disable the tick-inactive-villagers would be cool without restarting/reloading the server.

**Comment by katekerllenevich** [comment]
you can change the value in `spigot.yml` and then run `/spigot reload` to reload the spigot.yml file only. this is the only safe reloading.
