### ISSUE TITLE
Keep grass grass when digging

### ISSUE THREAD

**Issue by ChrystiGalbreath** [pl3xgaming/Purpur#307]
When digging grass type blocks without silk touch keep them grass/mycelium/podzol/snow grass..

**Comment by YouHaveTrouble** [comment]
Can be done relatively easily using datapack. There is drop modifier for silk touch iirc

**Comment by craftish37** [comment]
Try this :
[Only-Grass.zip](https://github.com/pl3xgaming/Purpur/files/6407750/Only-Grass.zip)
Tell me if the grass works, I'll do the same with podzol & cie

**Comment by BillyGalbreath** [comment]
> Try this :
> [Only-Grass.zip](https://github.com/pl3xgaming/Purpur/files/6407750/Only-Grass.zip)
> Tell me if the grass works, I'll do the same with podzol & cie

you missed out the match_tool condition ;) still want it to only be a grass block if the proper tool is used instead of hand

```json
{
  "type": "minecraft:block",
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:alternatives",
          "children": [
            {
              "type": "minecraft:item",
              "conditions": [
                {
                  "condition": "minecraft:match_tool",
                }
              ],
              "name": "minecraft:grass_block"
            },
            {
              "type": "minecraft:item",
              "conditions": [
                {
                  "condition": "minecraft:survives_explosion"
                }
              ],
              "name": "minecraft:dirt"
            }
          ]
        }
      ]
    }
  ]
}
```
