### ISSUE TITLE
[feature request] Sit in stonecutter and get damage without getting unmount

### ISSUE THREAD

**Issue by cardanawandra** [pl3xgaming/Purpur#309]
or gsit support for stonecutter, because gsit can't get damage

**Comment by BillyGalbreath** [comment]
This isn't something Purpur is doing, so it's nothing Purpur can change. All Purpur does is deal damage. The sit plugin (gsit) has an option specifically for getting up (unmounting) on damage.

```yaml
  # Defines whether the Player gets up when they take Damage
  get-up-on-damage: false
  ```

**Comment by cardanawandra** [comment]
![image](https://user-images.githubusercontent.com/38995778/116955676-677d6680-acbd-11eb-80c4-384c225e6363.png) even can't get damage when shifting

**Comment by DereC4** [comment]
Late but this is because gsit spawns an entity underneath you when you "sit", so you are technically not touching the stonecutter
