### ISSUE TITLE
[Feature Request] Faster Furnaces

### ISSUE THREAD

**Issue by goosBanny** [pl3xgaming/Purpur#310]
Hello there! I was wondering if you could add a feature into Purpur which allows for faster smelting in furnaces. You could make it so specific types of furnaces can smelt faster by a multiplier or something else. Thanks!

**Comment by Grabsky** [comment]
Sounds like this could be done within a plugin and there is an API for that.
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Furnace.html

**Comment by 12emin34** [comment]
Yeah, it could be done with a plugin, there's a method that sets the cooking multiplier in the API. https://purpur.pl3x.net/javadoc/org/bukkit/block/Furnace.html#setCookSpeedMultiplier(double)

**Comment by craftish37** [comment]
Can be made really easily with datapacks : 
https://crafting.thedestruc7i0n.ca/

**Comment by encode42** [comment]
As stated above, this would be best suited for a plugin or even a datapack.
