### ISSUE TITLE
Suggestion: Respawnable Shulkers

### ISSUE THREAD

**Issue by RealityTest** [pl3xgaming/Purpur#316]
The fact that shulkers are not respawnable is a problem for bigger or technical oriented servers because it makes shulker boxes a limited resource. A way to fix this would be making shulkers respawnable in end cities, same as witches in witch huts for example. The carpet mod by gnembon also has this feature:
https://github.com/gnembon/fabric-carpet/blob/master/src/main/java/carpet/mixins/EndCityFeatureMixin.java

There are plugins that do this by replacing spawning endermen, however they are not really a proper solution for the following reasons:
- They usually work by checking if an enderman spawns on a purpurblock and don't check if it's within the bounding box of an end city (This would require the usage of NMS as there is no API for structures).
- Even if they check whether the spawn occurs within the bounding box of an end city, it is a hacky way. There are problems like the fact that endermen have different spawning conditions (They need a 3 high space, whereas shulkers are only 1 block tall)

Therefore I believe it would be a good addition to make a toggle in the purpur.yml that allows to enable respawnable shulkers.

**Comment by LaurenceBarnes** [comment]
I do agree

**Comment by BillyGalbreath** [comment]
My wife would agree with you. She thinks shulkers should respawn as well ^_^ Thats why on my server we've been using the Shulker Respawner plugin for awhile now. It works exactly as you described, by replacing enderman spawns in end cities with shulkers. \o/

https://www.spigotmc.org/resources/shulker-respawner.81659/

**Comment by LaurenceBarnes** [comment]
Well but the reason this was suggested was that the plugin deals with it worse than a real implementation would.

**Comment by RealityTest** [comment]
> 
> 
> My wife would agree with you. She thinks shulkers should respawn as well ^_^ Thats why on my server we've been using the Shulker Respawner plugin for awhile now. It works exactly as you described, by replacing enderman spawns in end cities with shulkers. \o/
> 
> https://www.spigotmc.org/resources/shulker-respawner.81659/

@BillyGalbreath right, but my suggestion was that it shouldn't work like this for the reasons I listed. The plugin actually doesn't check if the enderman spawns in an end city (even though it claims to do so) but only checks if it spawns on a purpur block. The spawn conditions of endermen are also different from shulkers as I said which makes it hard to build farms like these for example: https://www.youtube.com/watch?v=QhiLBeLBZGk

There could also be other reasons why this isn't that great for example if you still want endermen to spawn on purpur blocks / in end cities for whatever reason.

The carpet mod implemented it by adding shulkers as a special mob do the endcity, the same way witches are implemented for swamp huts.
