### ISSUE TITLE
Suggestion: API for bartering with Piglins

### ISSUE THREAD

**Issue by kohy-creates** [pl3xgaming/Purpur#317]
It isn't yet in the Spigot, nor Paper api, and it could be so useful

There would be an event for bartering, syntax to get and set the bartered item, getting the entity and the player

**Comment by BillyGalbreath** [comment]
I've thought about doing this a number of times, but there's already API upstream in both Spigot _and_ Paper that are just sitting there gathering dust. Knowing my luck, the day I decide to code something up for Purpur is the day one (or both) of those get merged in making my work moot.

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/pull-requests/703/overview

https://github.com/PaperMC/Paper/pull/3766

**Comment by Machine-Maker** [comment]
Spigot just added this, and PaperMC/Paper#5736 has improvements on top of spigot's event, impl
