### ISSUE TITLE
Nether mobs doesn't spawn on Purpur

### ISSUE THREAD

**Issue by rudde0** [pl3xgaming/Purpur#32]
**Describe the bug**
I couldn't see any mob on wilderness(except nether fortress e.g. builds) in nether.

**Plugins**
I tried without plugins

**Version**
Purpur version git-Purpur-640 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
There is no problem when using Paper.

**Comment by MrEDok** [comment]
Have you edit your biome.yml?

This what Billy said

If you still have your biomes.yml left over from 1.15.2 then you have a few things to change in it.

I've posted up a diff for your convenience, here: https://pl3x.net/purpur-biomes.html

You can also just delete biomes.yml and it will recreate the new one on server startup

**Comment by BillyGalbreath** [comment]
This happens if you have an outdated biomes.yml file as mentioned in discord announcements channel.

Delete biomes.yml and restart the server for it to build a new one with all the new biomes ;)
