### ISSUE TITLE
Packet Processing error when initiating Dragon Battle/Placing end crystal

### ISSUE THREAD

**Issue by JoshA20** [pl3xgaming/Purpur#323]
**Describe the bug**
When placing an end crystal *ONLY in the end, it will crash the user and send an error to the console

**To Reproduce**
Teleport to end world, ensure dragon is ALREADY dead, and place an end crystal anywhere 

**Screenshots or Videos**

[Video of the Crash can be found here](https://i.josha.wtf/img/end-client-crash.mp4)
Error in console: https://paste.dedimc.io/ewolaqifus.css

**Plugins**

[REDACTED]

**Version**

Purpur 1085, 1.16.5
Java 11

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
Be sure you test the upstream projects for this bug and include if it is present or not here, include `/version` output for each upstream project you tested.

TESTED PAPER 651, WORKS PERFECTLY FINE, NO BUG
TESTED TUINITY b12d0cc (255) WORKS PERFECTLY FINE, NO BUG

**Additional context**
Add any other context about the problem here you think will help resolve the problem.

**Comment by embeddedt** [comment]
Not sure that this is a Purpur-specific issue. I updated an ancient world from 1.2 to 1.16 using Paper and got the exact same stack trace and kicking behavior when I tried to place end crystals in the end.

**Comment by JoshA20** [comment]
that'd make sense, but this is a native 1.16 world.

**Comment by Euphillya** [comment]
Hello,

I tested and I have no problems, can you retest without a plugin and with the latest update from Purpur?

**Comment by BillyGalbreath** [comment]
The stacktrace says your end world doesnt have an exit portal (in code, I can see you have one in the video)..

I'm unable to recreate the issue, so I'm willing to bet this is a faulty plugin doing something naughty. I'm going to recommend you try to recreate this without plugins and let me know what happens.

**Comment by JoshA20** [comment]
tested on a flat purpur server, didnt experience the issue. However we do reset the end every 2 months, which for some odd reason. Doesnt generate the exit portal, nor does it make any of the gateways. (nor does it spawn a dragon) So we just kinda retrofit that, and build it ourselves/spawn in a dragon for the players.

Not the best, no idea why it does that. But I'm betting that, that's the cause with what you've said

**Comment by JoshA20** [comment]
(by resetting end, I mean:

shutdown server
rename/delete end folder
startup server)

**Comment by BillyGalbreath** [comment]
> which for some odd reason. Doesnt generate the exit portal, nor does it make any of the gateways

That sounds like you have a certain paper setting disabled - Make sure this setting is `true` in paper.yml

```
scan-for-legacy-ender-dragon: true
```

Its a bad name for a setting, tbh (its my patch, my bad lol). I named it based on what we thought the code was at the time (looking at the debug output mojang called it). When this setting is disabled it actually prevents the dragon from spawning and the exit portal from generating. We havent renamed it in paper's code yet because we honestly dont even know what to name it to. Its a bizzarre option, to say the least.

**Comment by embeddedt** [comment]
FWIW, that setting was `true` for my 1.2 world, but it's possible the old End world generation causes other problems.

**Comment by embeddedt** [comment]
My issue turned out to be [MC-104897](https://bugs.mojang.com/browse/MC-104897) which is now fixed (in 1.17). I tested my world in vanilla 1.17-pre1 and the dragon did respawn properly, so I expect this will also work in Purpur when the full release comes.
