### ISSUE TITLE
(Suggestion) Totem popping in void

### ISSUE THREAD

**Issue by Cypphi** [pl3xgaming/Purpur#324]
Normally having a totem while falling in the void just kills you instead of pop the totem.
Maybe an option to make totems pop in the void as well (this would be compatible with inventory totems)

**Comment by LaurenceBarnes** [comment]
and how would that help? You would still fall to death anyway lol.
Would only make sense if it teleported you to the next safe spot, which is not necessarily close (if we talk about the end)

**Comment by Cypphi** [comment]
> and how would that help? You would still fall to death anyway lol.
> Would only make sense if it teleported you to the next safe spot, which is not necessarily close (if we talk about the end)

gives you time to do /home or anything idk

**Comment by LaurenceBarnes** [comment]
Well assuming the command is activated on the server, yeah, but a more elaborated and universal solution would be what I suggested then

**Comment by Cypphi** [comment]
Yeah maybe, but I don't think such an option will harm anyone. It could be used by the few servers out there that use /home or anything related. And if this would be added a tp option could also help, something that basically tps you to the last block you stood on also known as antivoid

**Comment by BillyGalbreath** [comment]
> gives you time to do /home or anything idk

If you have time to type the command then you haven't died yet, so the totem wasn't used. In fact, having a totem doubles your available time to type the command, which would save the rest of your inventory from certain destruction otherwise ;)
