### ISSUE TITLE
(Enhancement suggestion) - Powered Rails configurable speed boost

### ISSUE THREAD

**Issue by ghost** [pl3xgaming/Purpur#329]
For ages I've dreamt of Mojang making Minecarts & rails have any sort of relevance in modern Minecraft other than uses in redstone contraptions. Long distance travelling is just not worth the effort of creating the track for anymore when it travels at a fraction of the speed of ice boat tracks or Elytras.

However I hear that this is something that can theoretically be implemented by a server jar that cares about adding relevant and cool options, and so I've ended up here after being advised to add my suggestion.

Things that I can imagine could cause issues is that this option would likely ruin Minecart with Hoppers for redstone contraptions and other redstone-related uses of minecarts.
The only thing I can imagine would fix this would be if you could someone control how it'd reach a new configured speed. Such as requiring the minecart to have travelled over a certain amount of powered rails before it starts applying the new speed boost, to prevent the new speed limit of affecting any redstone contraptions as I imagine few use longer tracks of only powered rails.
So for example you could need it to have travelled 16 blocks on powered rails before it starts ramping up the speed further.

This suggestion on how it could be fixed comes from someone who has zero experience developing stuff for real, and I really have no clue of the limitations there are so do take all I've said with a grain of salt.

**Comment by BomBardyGamer** [comment]
I've done some work on this, and I've implemented in to my experimental fork of Purpur, [Laboratory](https://github.com/BomBardyGamer/laboratory), just to allow for some people to test this, so feel free to test it by going to the actions tab on that GitHub page and downloading either the Java 8 or Java 11 ZIP file that contains labclip.jar (will be called labclip.jar.jar in that file). You can use this JAR file to run your server, just like you would with any other JAR file (java -jar labclip.jar).

The option to actually change this setting is in the world settings, under gameplay mechanics, minecart, then powered-rail-boost-modifier. Note that to notice a difference in the boost, you need to also increase the maximum speed of the Minecart, which can also be changed within the minecart options.

If you find any issues with it, please feel free to make an issue on the Laboratory GitHub page.

(I am already aware that furnace minecarts are unaffected, and I will be looking in to this and attempting to fix it soon)
