### ISSUE TITLE
repo.pl3x.net inaccessable

### ISSUE THREAD

**Issue by morfie78** [pl3xgaming/Purpur#33]
**Describe the bug**
When performing a ./purpur build, the build process is unable to download the maven-metadata.xml files located on the repo.pl3x.net repo.

**To Reproduce**
Follow the normal build steps for a ./purpur build

**Screenshots or Videos**
`Downloading from pl3x: https://repo.pl3x.net/net/md-5/bungeecord-chat/1.15-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata net.md-5:bungeecord-chat:1.15-SNAPSHOT/maven-metadata.xml from/to pl3x (https://repo.pl3x.net/): Connect to repo.pl3x.net:443 [repo.pl3x.net/54.39.28.52] failed: Connection timed out (Connection timed out)
[WARNING] Failure to transfer net.md-5:bungeecord-chat:1.15-SNAPSHOT/maven-metadata.xml from https://repo.pl3x.net/ was cached in the local repository, resolution will not be reattempted until the update interval of pl3x has elapsed or updates are forced. Original error: Could not transfer metadata net.md-5:bungeecord-chat:1.15-SNAPSHOT/maven-metadata.xml from/to pl3x (https://repo.pl3x.net/): Connect to repo.pl3x.net:443 [repo.pl3x.net/54.39.28.52] failed: Connection timed out (Connection timed out)
Downloading from pl3x: https://repo.pl3x.net/net/md-5/bungeecord-parent/1.15-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata net.md-5:bungeecord-parent:1.15-SNAPSHOT/maven-metadata.xml from/to pl3x (https://repo.pl3x.net/): Connect to repo.pl3x.net:443 [repo.pl3x.net/54.39.28.52] failed: Connection timed out (Connection timed out)
Downloading from pl3x: https://repo.pl3x.net/co/aikar/cleaner/1.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata co.aikar:cleaner:1.0-SNAPSHOT/maven-metadata.xml from/to pl3x (https://repo.pl3x.net/): Connect to repo.pl3x.net:443 [repo.pl3x.net/54.39.28.52] failed: Connection timed out (Connection timed out)
[WARNING] Failure to transfer co.aikar:cleaner:1.0-SNAPSHOT/maven-metadata.xml from https://repo.pl3x.net/ was cached in the local repository, resolution will not be reattempted until the update interval of pl3x has elapsed or updates are forced. Original error: Could not transfer metadata co.aikar:cleaner:1.0-SNAPSHOT/maven-metadata.xml from/to pl3x (https://repo.pl3x.net/): Connect to repo.pl3x.net:443 [repo.pl3x.net/54.39.28.52] failed: Connection timed out (Connection timed out)
Downloading from pl3x: https://repo.pl3x.net/co/aikar/cleaner-8/1.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata co.aikar:cleaner-8:1.0-SNAPSHOT/maven-metadata.xml from/to pl3x (https://repo.pl3x.net/): Connect to repo.pl3x.net:443 [repo.pl3x.net/54.39.28.52] failed: Connection timed out (Connection timed out)
[WARNING] Failure to transfer co.aikar:cleaner-8:1.0-SNAPSHOT/maven-metadata.xml from https://repo.pl3x.net/ was cached in the local repository, resolution will not be reattempted until the update interval of pl3x has elapsed or updates are forced. Original error: Could not transfer metadata co.aikar:cleaner-8:1.0-SNAPSHOT/maven-metadata.xml from/to pl3x (https://repo.pl3x.net/): Connect to repo.pl3x.net:443 [repo.pl3x.net/54.39.28.52] failed: Connection timed out (Connection timed out)
Downloading from pl3x: https://repo.pl3x.net/co/aikar/cleaner-9/1.0-SNAPSHOT/maven-metadata.xml
`

**Plugins**
N/A

**Version**
N/A  (Latest pull from github)

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
N/A

**Additional context**
N/A

**Comment by R00tB33rMan** [comment]
> **Describe the bug**
> When performing a ./purpur build, the build process is unable to download the maven-metadata.xml files located on the repo.pl3x.net repo.
> 
> **To Reproduce**
> Follow the normal build steps for a ./purpur build
> 
> **Screenshots or Videos**
> `Downloading from pl3x: https://repo.pl3x.net/net/md-5/bungeecord-chat/1.15-SNAPSHOT/maven-metadata.xml [WARNING] Could not transfer metadata net.md-5:bungeecord-chat:1.15-SNAPSHOT/maven-metadata.xml from/to pl3x (https://repo.pl3x.net/): Connect to repo.pl3x.net:443 [repo.pl3x.net/54.39.28.52] failed: Connection timed out (Connection timed out) [WARNING] Failure to transfer net.md-5:bungeecord-chat:1.15-SNAPSHOT/maven-metadata.xml from https://repo.pl3x.net/ was cached in the local repository, resolution will not be reattempted until the update interval of pl3x has elapsed or updates are forced. Original error: Could not transfer metadata net.md-5:bungeecord-chat:1.15-SNAPSHOT/maven-metadata.xml from/to pl3x (https://repo.pl3x.net/): Connect to repo.pl3x.net:443 [repo.pl3x.net/54.39.28.52] failed: Connection timed out (Connection timed out) Downloading from pl3x: https://repo.pl3x.net/net/md-5/bungeecord-parent/1.15-SNAPSHOT/maven-metadata.xml [WARNING] Could not transfer metadata net.md-5:bungeecord-parent:1.15-SNAPSHOT/maven-metadata.xml from/to pl3x (https://repo.pl3x.net/): Connect to repo.pl3x.net:443 [repo.pl3x.net/54.39.28.52] failed: Connection timed out (Connection timed out) Downloading from pl3x: https://repo.pl3x.net/co/aikar/cleaner/1.0-SNAPSHOT/maven-metadata.xml [WARNING] Could not transfer metadata co.aikar:cleaner:1.0-SNAPSHOT/maven-metadata.xml from/to pl3x (https://repo.pl3x.net/): Connect to repo.pl3x.net:443 [repo.pl3x.net/54.39.28.52] failed: Connection timed out (Connection timed out) [WARNING] Failure to transfer co.aikar:cleaner:1.0-SNAPSHOT/maven-metadata.xml from https://repo.pl3x.net/ was cached in the local repository, resolution will not be reattempted until the update interval of pl3x has elapsed or updates are forced. Original error: Could not transfer metadata co.aikar:cleaner:1.0-SNAPSHOT/maven-metadata.xml from/to pl3x (https://repo.pl3x.net/): Connect to repo.pl3x.net:443 [repo.pl3x.net/54.39.28.52] failed: Connection timed out (Connection timed out) Downloading from pl3x: https://repo.pl3x.net/co/aikar/cleaner-8/1.0-SNAPSHOT/maven-metadata.xml [WARNING] Could not transfer metadata co.aikar:cleaner-8:1.0-SNAPSHOT/maven-metadata.xml from/to pl3x (https://repo.pl3x.net/): Connect to repo.pl3x.net:443 [repo.pl3x.net/54.39.28.52] failed: Connection timed out (Connection timed out) [WARNING] Failure to transfer co.aikar:cleaner-8:1.0-SNAPSHOT/maven-metadata.xml from https://repo.pl3x.net/ was cached in the local repository, resolution will not be reattempted until the update interval of pl3x has elapsed or updates are forced. Original error: Could not transfer metadata co.aikar:cleaner-8:1.0-SNAPSHOT/maven-metadata.xml from/to pl3x (https://repo.pl3x.net/): Connect to repo.pl3x.net:443 [repo.pl3x.net/54.39.28.52] failed: Connection timed out (Connection timed out) Downloading from pl3x: https://repo.pl3x.net/co/aikar/cleaner-9/1.0-SNAPSHOT/maven-metadata.xml `
> 
> **Plugins**
> N/A
> 
> **Version**
> N/A (Latest pull from github)
> 
> **Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
> N/A
> 
> **Additional context**
> N/A

Greetings. This bug is only present, due to the Purpur site(s) being down. I'm currently awaiting for them to bring them back up, too.

**Comment by BillyGalbreath** [comment]
It's back up ^_^

**Comment by morfie78** [comment]
Thank you!
