### ISSUE TITLE
The cartographer sleeps causing the server to crash

### ISSUE THREAD

**Issue by wykwey** [pl3xgaming/Purpur#335]
The cartographer (probably all the villagers) sleeps at night and the server crashes unexpectedly
I used the stratos plugin
Just put a bed in the snow (I used pink) and put a cartographer
So that the first level of his experience is full
And then put him to sleep, removing the bed
Put on the bed. The server crashed
I use Purpur-1087 
I can't use other servers but I used the original version, and it did not show any errors 

[latest.log](https://github.com/pl3xgaming/Purpur/files/6483694/latest.log)
![2021-05-15_15 06 02](https://user-images.githubusercontent.com/73051894/118351940-45bf9180-b591-11eb-90b4-af9b014acc6e.png)
![2021-05-15_15 06 04](https://user-images.githubusercontent.com/73051894/118351942-48ba8200-b591-11eb-8e19-5f6ba1a8cc0f.png)

I can't use other servers but I used the original version, and it did not show any errors

**Comment by cittyinthecloud** [comment]
This looks like either you're just locking up generating the treasure map, or Stratos is breaking Mojang's structure finding algorithm there.

**Comment by wykwey** [comment]
> 这看起来像你可能只是锁定生成宝藏图， 或斯特拉托斯正在打破莫扬的结构查找算法。
how to solve this problem

**Comment by wykwey** [comment]
> 这看起来像你可能只是锁定生成宝藏图， 或斯特拉托斯正在打破莫扬的结构查找算法。

how to solve this problem

**Comment by BillyGalbreath** [comment]
Offline mode servers are not supported here. We do not condone piracy.
