### ISSUE TITLE
Suggestion: Chunk loading idea (if possible)

### ISSUE THREAD

**Issue by RidaThe94** [pl3xgaming/Purpur#341]
Tthis may not impact the server performance, but may impact the client performance FPS and may be helpful against anti xray in some sort.

If the player in y 60 or higher load chunks from y 40 to y 255, and if the player in y 45 or lower load chunks from y 0 to y 128.

Now lets say a player dug down from y 65 to 43 check if the entire chunk details is sent to that player or not, if not update all the loaded chunks that doesn't have their full details sent to the player to have chunks details from y 0 to y 255. The same thing should be applied for a player that build or climb up from y 13 to y 67.

**Comment by BillyGalbreath** [comment]
Im fairly certain the game already does this. If it doesn't, though, this would be a good request for Tuinity.
