### ISSUE TITLE
Unable to compile purpur from sources

### ISSUE THREAD

**Issue by derklaro** [pl3xgaming/Purpur#342]
Im trying to compile purpur the apply patches task failes with

```
Applying: Tuinity Server Changes
error: invalid object 100644 cb993ca102402d9c19ea9fa04e5db09c21205896 for 'src/main/java/com/mojang/brigadier/arguments/BoolArgumentType.java'
error: Repository lacks necessary blobs to fall back on 3-way merge.
Patch failed at 0001 Tuinity Server Changes
```

How can i fix this?

**Comment by Euphillya** [comment]
Hello, 

in `mcdevimports.conf`, add: 
```js
library-imports=[
    {
        file=BoolArgumentType
        group="com.mojang"
        library=brigadier
        prefix="com/mojang/brigadier/arguments"
    },
    {
        file=SuggestionsBuilder
        group="com.mojang"
        library=brigadier
        prefix="com/mojang/brigadier/suggestion"
    },
    {
        file=LiteralCommandNode
        group="com.mojang"
        library=brigadier
        prefix="com/mojang/brigadier/tree"
    },
    {
        file=CommandDispatcher
        group="com.mojang"
        library=brigadier
        prefix="com/mojang/brigadier"
    }
]
```
and remove Purpur-Server, after that you can run `./gradlew applyPatches`

**Comment by derklaro** [comment]
Ah, thank you :)

**Comment by jpenilla** [comment]
This is not a proper solution by any means. If you are able to reproduce this, please open an issue at the [Toothpick tracker](https://github.com/jpenilla/Toothpick/issues), and provide as much detailed information about your environment and reproduction steps as possible.

**Comment by jpenilla** [comment]
@derklaro Issue should be resolved on the Toothpick side, if you run `./gradlew applyPatches --refresh-dependencies` you will no longer need the manually added entries in `mcdevimports.conf` (in fact, you should get a warning for having duplicate entries).
