### ISSUE TITLE
Configurable despawn rate

### ISSUE THREAD

**Issue by craftish37** [pl3xgaming/Purpur#345]
Make it possible to configure the despawn rate like this:

world-despawn-rate
  tick: {number}
    - minecraft: item
world-nether-despawn-rate
  tick: {anotherexemple}
    - minecraft:anotheritem

and so on for dimensions, this would be a good way to prevent items from being everywhere, like when a mountain is destroyed and thousands of stone blocks are on the ground

**Comment by emielderckx** [comment]
This is already in paper right. Its called: alt-item-despawn-rate

**Comment by BillyGalbreath** [comment]
This has already been a part of Spigot and Paper for a long time.
