### ISSUE TITLE
Patrol don't spawn when the player have bad omen effect

### ISSUE THREAD

**Issue by Kylepoops** [pl3xgaming/Purpur#347]
**Describe the bug**
Patrol don't spawn when the player have bad omen effect

**To Reproduce**
Make a machine that can spawn patrols, and stand there with bad omen effect, with Tuinity it wotks well but in purpur it will spawn only once and then no patrol will spawn
**Screenshots or Videos**

**Plugins**
Reproduce with Tuinity with exactly the same environment and plugins enven and it works without any issues so i think it won't be caused by plugin
**Version**
Build 1118

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
Test on Tuinity and it works without any issue

**Additional context**
\

**Comment by Xarius86** [comment]
Are you talking about **raids** and not **patrols**? Patrols are random events. Meanwhile, raids are what gets triggered when you have Bad Omen near a village.

**Comment by Xarius86** [comment]
Also, I just tested the raid farm on my server using Purpur 1118, and it is working perfectly fine. Either your farm is not built properly, a plugin is stopping it from working, or you have set something in your config that prevents how your machine works from operating in a vanilla-like way.

Do you have some highly restrictive activation ranges or tick distances in your config?
