### ISSUE TITLE
Suggestion: Add Plated Elytra (and have it be compatible with netherite armor fire resistance)

### ISSUE THREAD

**Issue by Mister-16** [pl3xgaming/Purpur#349]
I very much like the feature of allowing players to get fire res when they wear netherite armor, but I also think something similar to this would be great too; http://mc.voodoobeard.com/#plated_elytra

Maybe I'm the only one who would want this, but as I know of, there is no plugin out there right now that allows you to have fire-res netherite armor combined with plated elytra.

**Comment by BillyGalbreath** [comment]
Looking into this, the way armor ratings are implemented into the server it would be rather difficult to add this into the system. It would be way easier to do it as a plugin.
