### ISSUE TITLE
Suggestion: Add a feature where you can teleport from the overworld to the nether, and/or from the end to the overworld

### ISSUE THREAD

**Issue by Mister-16** [pl3xgaming/Purpur#350]
A similar data pack does this, and I think it'd be a great feature to add into pupur as an option in the config. Many plugins make the "falling from the end void tps you to the overworld" kind of thing, and even more data packs do it. I propose to have it be where if you fall through the nether floor bedrock you end up in the same coords in the overworld, and If you fall from the overworld bedrock floor, you end up in the nether coords. The reason i don't think it should happen from the nether bedrock ceiling is cause there's a lot of player activity that goes on there like farms or highways that would cease to exist if it worked in this way. the end to overworld is simple; if the dragon is already killed, you can fall from the end void into the overworld sky, and if you fly to, say, y= 500, you get tped to the end (if dragon is defeated).

**Comment by BillyGalbreath** [comment]
This is one of those things that everyone would have a differing opinion on, so would be best left up to a small plugin to implement so that everyone's needs could be met.
