### ISSUE TITLE
Option to stop the "Prevent players from moving into unloaded chunks" patch from causing death by kinetic energy

### ISSUE THREAD

**Issue by Decme** [pl3xgaming/Purpur#354]
From recent discussion on the Purpur discord it has come to my attention that Paper's function preventing players from moving into unloaded chunks causes anyone flying with an elytra to do so in a manner which causes them to hit an invisible barrier & die from kinetic energy.

While it's painfully obvious why the Paper setting is necessary & I'd rather have it on than off, my assumption was that it merely halted the player mid-air, rather than outright killing them in such an unfair manner.

My suggestion/request is for an additional option for the setting to halt players mid-air without dealing damage to them.

I'd post on Paper's github, but they are notorious for ignoring issues.

**Comment by BillyGalbreath** [comment]
It is an unintentional side effect, really. I dont think it can be prevented because if you dont stop them from hitting an invisible wall then they will still move into unloaded chunks. Plus, I like the side effect a lot ^_^ Abusers should be abused ;)
