### ISSUE TITLE
Suggestion: option to add cooldown on weapons after a crit attack

### ISSUE THREAD

**Issue by kohy-creates** [pl3xgaming/Purpur#357]
It could be smth like that:
```
crit-attack-cooldown: 0
``` 
where 0 would be the basic value equal to 0 ticks
If someone would want to have a 5 second crit attack cooldown, it would be

```
crit-attack-cooldown: 100
```
EDITS: spelling and codeblock being weird

**Comment by kohy-creates** [comment]
Also, my dumb ass forgot to add how this could possibly work

There could be like 2 modes or smth, in 1st one all attacks would be normal until cooldown ends, while in the 2nd one this would deactivate weapon completely

**Comment by BillyGalbreath** [comment]
This is one of those things everyone would have differing opinions on how to implement/customize. I've already exposed these values to the API in Paper many years ago, so this would best left up to a plugin to implement
