### ISSUE TITLE
Suggestion: Nerf mobs from mobspawner

### ISSUE THREAD

**Issue by Blobbie01** [pl3xgaming/Purpur#358]
Heya.

In spigot.yml there is an option to nerf mobs spawned by spawner. This option just makes the mob unable to move/attack. I was hoping you could add a real nerf (less xp/item drops & slower spawns) from the mobspawner.

Not sure if it’s possible, but if it is… would love to see it in Purpur😄💖

**Comment by BillyGalbreath** [comment]
API for this has already been exposed in Paper, so would be best left up to a plugin to implement where everyone's differing opinions and needs could be met
