### ISSUE TITLE
Craftbook5

### ISSUE THREAD

**Issue by danechek** [pl3xgaming/Purpur#359]
https://pastebin.com/raw/8d23rhXf
I have Purpur bug with Craftbook5

**Comment by katekerllenevich** [comment]
please send the output of the `/version` command and a full server log

**Comment by granny** [comment]
Please follow the issues template created for reporting bugs.
<https://github.com/pl3xgaming/Purpur/issues/new?assignees=&labels=&template=bug_report.md>
