### ISSUE TITLE
Cannot build server jar

### ISSUE THREAD

**Issue by ignissak** [pl3xgaming/Purpur#36]
**Describe the bug**
Running `./purpur build` would throw an error because maven modules are not initialized (Purpur-API, Purpur-Server)

**To Reproduce**
Pull all changes from `ver/1.16` branch and use recommended commands stated in the readme:
```
git submodule update --init
./purpur up
./purpur patch
./purpur build
```
Everything works perfectly until you run the last command that should build Purpur artifacts. This command will throw an error which states that child modules do not exist. I tried to run `apply.sh` from scripts but this has thrown another error:
 ```
/home/jacobbordas/Documents/Development/Purpur/scripts/apply.sh: line 83: ./scripts/importmcdev.sh: No such file or directory
```
I commented this line in the file and ran it again, it worked. Then I could properly build Purpur with `./purpur build`.

**Screenshots or Videos**
Error while building:
![image](https://user-images.githubusercontent.com/25119437/88477763-01500000-cf43-11ea-8c3d-510cdf88b2a7.png)
Error while running apply.sh:
![image](https://user-images.githubusercontent.com/25119437/88477755-e7aeb880-cf42-11ea-970d-ba3bbaf37ede.png)

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
Purpur

**Comment by BillyGalbreath** [comment]
`./purpur patch fast` was the fix here. But, I just removed that option as it wasnt very intuitive. I was trying it on for size, but honestly I just didnt like it much. Now the normal commands shown in readme will be enough to build again ;)
