### ISSUE TITLE
Cannot ride players with rideable entities :)

### ISSUE THREAD

**Issue by snoopdoooggyttv** [pl3xgaming/Purpur#366]
**Describe the bug**
Cannot right click to ride player with rideable entities enable

**To Reproduce**
Turn on rideable entities and right click a player

**Plugins**
no, none

**Version**
latest, 1133

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
Paper does not have ride stuff as far as i know, i have not tried MakeBukkit though.

**Additional context**
Add any other context about the problem here you think will help resolve the problem.

**Comment by YouHaveTrouble** [comment]
That's not a bug. There is no ridable option for players in the config.

**Comment by snoopdoooggyttv** [comment]
Hmmm yes, but when i make issue, no issue template for feature.

i guess i am saying i want it 😁😈
:shipit:

**Comment by granny** [comment]
More of a plugin thing. Purpur only makes things ridable for the WASD controls, and riding a player would not give you WASD control over them, so it's not something that's gonna happen.
