### ISSUE TITLE
Wiki redirects to the wrong page

### ISSUE THREAD

**Issue by 4P5** [pl3xgaming/Purpur#367]
## Is your feature request related to a problem?
  From the wiki: _The documentation has migrated to https://purpur.pl3x.net/docs_. However, the hyperlink leads to https://pl3xgaming.github.io/PurpurDocs/, which does not exist.

## Describe the solution you'd like.
  Changing the hyperlink so that both the text and the link direct to the same place.

## Agreements
Please agree to the following.
- [✓] I have searched for and ensured there isn't already an open issue regarding this.
- [✓] I have ensured the feature I'm requesting isn't already in the latest supported Purpur build.

**Comment by katekerllenevich** [comment]
fixed.
