### ISSUE TITLE
Split "rideable" into "rideable" and "controllable"

### ISSUE THREAD

**Issue by 4P5** [pl3xgaming/Purpur#368]
## Is your feature request related to a problem?

Currently riding a mob and piloting a mob are under the same setting; `ridable: true`. I'd like to let players ride mobs like phantoms and dragons, but not to control them, to add some unique combat.

(While we're on the topic of hostile mobs, perhaps a "damage-amount" and "damage-rate" option for riding them? Defaults to 0/0, but would stop players from just riding a wither for an hour, with something like 2/1)

## Describe the solution you'd like.

For the default config, something like `rideable: false`, with the additional of `controllable`, which defaults to `true` (for compatibility), and is dependant on rideable. This won't break any previous versions, but admins can then disable the control feature and only enable riding.

## Agreements
Please agree to the following.
- [✓] I have searched for and ensured there isn't already an open issue regarding this.
- [✓] I have ensured the feature I'm requesting isn't already in the latest supported Purpur build.

**Comment by TheAwesome98-Real** [comment]
btw for markdown, you don't need to put fancy ticks in the box, put a capital X and it renders like that anyway

**Comment by 4P5** [comment]
> btw for markdown, you don't need to put fancy ticks in the box, put a capital X and it renders like that anyway

Oh, thanks!
