### ISSUE TITLE
Accidently riding animals: require-shift-to-mount

### ISSUE THREAD

**Issue by x1p** [pl3xgaming/Purpur#37]
**Describe the suggestion**
As discussed today in the discord (Social, General), I thought, let's make it official.
It's about the missing option `require-shift-to-mount`.
My players have trouble breeding animals because they often forget which animal is feed. So they often 'ride' the animals by accident as the shift is no longer required.

So the suggestion of some of us is to require an empty hand to be able to mount on an animal in order to ride it.
Is that possible?
Or if the player is holding something that is not meant to breed, so nothing eatable.

**Alternative?**
I sadly had to disable the ridables for now because the annoyance is to great for us.

**Version**
Purpur version git-Purpur-682 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by ghost** [comment]
It is already possible with horses being only able to tame with an empty hand, i would think this would be possible to do and not that hard.
