### ISSUE TITLE
[Bug] Messaging Channel "PlayerCount" don't work for back-end servers

### ISSUE THREAD

**Issue by x9nico** [pl3xgaming/Purpur#371]
## Expected behavior

Through BungeeCord messaging channel, it should show online players of the specified back-end servers.

## Observed/Actual behavior

It show the number of all players on the proxy, not on the specified server.

## Purpur version

  [16:45:15 INFO]: Checking version, please wait...
  [16:45:15 INFO]: This server is running Purpur version git-Purpur-1151 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
   [16:45:15  INFO]: You are running the latest version
   [16:45:15 INFO]: Previous version: git-Purpur-1120 (MC: 1.16.5)

## Agreements
Please agree to the following.
- [x ] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [ x] I have searched for and ensured there isn't already an open issue regarding this.
- [ x] My version of Minecraft is supported by Purpur.

## Other

There is my code: 

https://pastebin.com/YrzxQ4gD

**Comment by BillyGalbreath** [comment]
This has nothing to do with Purpur.

**Comment by x9nico** [comment]
> This has nothing to do with Purpur.

Where must I report it ?

**Comment by BillyGalbreath** [comment]
> Where must I report it ?

Sorry for late reply. The proxy is the one that's 100% in control over that number and API. You'd have to consult the provider of your proxy (bungee, waterfall, velocity, whoever)
