### ISSUE TITLE
Suggestion: Allow one nether per overworld

### ISSUE THREAD

**Issue by ProClifo** [pl3xgaming/Purpur#378]
An option in the config like this:
`one-nether-per-overworld: <true/false>`
The default vanilla option is false.

Normally, there is only one Nether on your server. No matter which overworld you're in, the game takes you to "worldname_nether" determined by the world name set in server.properties. If you have two or more overworlds on the server, it's a one-way street when using the Nether portal in these worlds. This config would solve that.

Let's say you have "world" set as the world name in server.properties. This is how they link in vanilla:
'world' --> 'world_nether'
'newoverworld' --> 'world_nether'

How they would link with `one-nether-per-overworld` enabled:
'world' --> 'world_nether'
'newoverworld' --> 'newoverworld_nether'

Perhaps there could be a `one-end-per-overworld` config also? Just a thought.

**Comment by TwoLeggedCat** [comment]
Question is: how do you define "overworld?" If a plugin adds a new dimension to the server, the server doesn't know whether that's a void world, a world made purely of lava, one made to perfectly match the nether, etc.
This also sounds more a job for Velocity or Bungee to me.

**Comment by YouHaveTrouble** [comment]
https://github.com/Multiverse/Multiverse-Core/wiki/Basics-(NetherPortals)
