### ISSUE TITLE
Paper problem with mcfunction and shifting biome IDs

### ISSUE THREAD

**Issue by craftish37** [pl3xgaming/Purpur#380]
**--> 1st part of the report <--**

_Version impacted :_ Any Paper version or fork of paper

_Expected :_ mcfunctions executed in less than a second

_Observed :_ Just crash the server occasionally

_Steps :_ Use a datapack who uses mcfunctions with tasks executed in less than one second

_Special note of the original reporter :_ "spigot/paper have a optimization code, and the inferno has a lot of mcfunction running in one second, i guess Paper can not handle all that functions and it just crash!"

Attached to this report, the said datapack "Incendium"

**--> 2nd part of the report <--**

_Version impacted :_ Any version of minecraft

_Expected :_ Add biomes in a server 

_Observed :_ Biomes are added, but the old biomes are blend, so you can have :

1: a
2: b
3: c
and add 4 & 5 later
4: d
5: e
who become
1: b
2: c
3: a
4: d
5: e

_Steps :_ Use a datapack add biomes to minecraft, then after a restart, add another datapack who add biomes

_Special note : This bug is report to mojang since months, but no news since 29/10/20
Link of the report : https://bugs.mojang.com/browse/MC-202036

I'll let the people of Incendium explain you any more details you need because I don't know enough about the 1st bug
[Incendium_v3.1.8.zip](https://github.com/pl3xgaming/Purpur/files/6603007/Incendium_v3.1.8.zip)

**Comment by Euphillya** [comment]
Hello i use Incendium v3.1.10 and I am 0 bug. You use Paper Version of Incendium ?

**Comment by craftish37** [comment]
They made a version for Paper which deactivates the boss in question on purpose so that the Paper servers can "use" the datapack, it remains problematic for other reasons (obviously), but no, I no longer use the Paper version of the datapack, because too private by disabling this boss.

**Comment by granny** [comment]
Since this happens on Paper then it’s a Paper issue and should be reported on their github page.
