### ISSUE TITLE
Async chat thread error

### ISSUE THREAD

**Issue by falcoignis** [pl3xgaming/Purpur#381]
I'm attempting to setup the GreifDefender plugin on my Purpur server and upon boot I receive a message about "An illegal reflective access operation has occurred". I then receive an Async chat error when attempting to use the plugins "chat gui" to add player trust to a claim.  I've tested on a clean server with only Greifdefender and Luckperms (hard dependecy) and get the same issue. Error is not present with identical setup on Paper. Log attached
[latest.log](https://github.com/pl3xgaming/Purpur/files/6604504/latest.log)

**Comment by katekerllenevich** [comment]
Please use the correct issue formats, or for quicker support, join our discord.
