### ISSUE TITLE
Add a option for "Fix dangerous end portal logic" patch added by Paper 

### ISSUE THREAD

**Issue by Redlnn** [pl3xgaming/Purpur#384]
## Is your feature request related to a problem?

Paper has recently added a new [patch](https://github.com/PaperMC/Paper/commit/7d751ad8d33b85f2bb6b1cddc438b19418c01318) named `Fix dangerous end portal logic`, which broken the feature of `world-settings.default.blocks.sand.fix-duping` option in `purpur.yml`. 

## Describe the solution you'd like.

Restore this patch or disable this patch when `sand.fix-duping` is set to `true`

## Agreements
Please agree to the following.
- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [x] I have ensured the feature I'm requesting isn't already in the latest supported Purpur build.

## Other

This patch also prevents players use End Portal to dupe other falling block (such as anvil, dragon egg, etc.)

**Comment by BillyGalbreath** [comment]
I believe you are mistaken, as the end portal fix has nothing to do with sand duping.

**Comment by Redlnn** [comment]
> I believe you are mistaken, as the end portal fix has nothing to do with sand duping.

After testing, I think the problem does exist.
And I have made a [video](https://youtu.be/jmdUXHFPPTk) to explain this problem.
In this video, I made a new patch to restore the patch from Paper. And show its impact on sand duping.

[0224-Restore-Fix-dangerous-end-portal-logic.zip](https://github.com/pl3xgaming/Purpur/files/6621000/0224-Restore-Fix-dangerous-end-portal-logic.zip)

**Comment by BillyGalbreath** [comment]
That is a different dupe glitch that was fixed in a different patch. They are not the same thing. The option in Purpur adds a toggle for the piston sand dupe that they patched last summer. It has nothing to do with end portals.

**Comment by BillyGalbreath** [comment]
Went ahead and added a separate toggle for the thing you're talking about.

https://github.com/pl3xgaming/Purpur/commit/c7ccefa1c03806f3d176f8122b9893c51846295a

Do note, though, that this _is_ dangerous for other reasons not related to gravity block duping. Use at your own risk ;)
