### ISSUE TITLE
Make Purpur for 1.17

### ISSUE THREAD

**Issue by Minionguyjpro** [pl3xgaming/Purpur#385]
Make Purpur available for 1.17 because its out now.

**Comment by emielderckx** [comment]
We need to wait on bukkit, spigot and paper. Please have patience

For everyone wondering about Purpur for 1.17, it has not been released yet.

We must wait for Spigot and Paper to update before we start updating our own patches. Once the latter is ready, we'll temporarily drop Tuinity's patches to speed up the update process. Don't worry! Tuinity be added back once it's also updated. If you want to track Paper's progress, check out Paper#5785 which has a checklist of what must be done before their 1.17 release. (https://github.com/PaperMC/Paper/issues/5785)

Once we've updated our patches, there will be a #jenkins build with Purpur 1.17 and the downloads page will be updated.

**Comment by 12emin34** [comment]
We are waiting for Paper to update (and they are waiting for Spigot). Just give it some time. We aren't magicians you know?

**Comment by katekerllenevich** [comment]
Read the latest announcement in our discord for more info.

**Comment by LaurenceBarnes** [comment]
gib purpur :kekw:

**Comment by Minionguyjpro** [comment]
> We need to wait on bukkit, spigot and paper. Please have patience
> 
> For everyone wondering about Purpur for 1.17, it has not been released yet.
> 
> We must wait for Spigot and Paper to update before we start updating our own patches. Once the latter is ready, we'll temporarily drop Tuinity's patches to speed up the update process. Don't worry! Tuinity be added back once it's also updated. If you want to track Paper's progress, check out Paper#5785 which has a checklist of what must be done before their 1.17 release. ([PaperMC/Paper#5785](https://github.com/PaperMC/Paper/issues/5785))
> 
> Once we've updated our patches, there will be a #jenkins build with Purpur 1.17 and the downloads page will be updated.

ok then

**Comment by BillyGalbreath** [comment]
Good thing this ticket was made. We might have forgotten to update otherwise.
