### ISSUE TITLE
Cactus destroy item toggleable.

### ISSUE THREAD

**Issue by RealRONiN** [pl3xgaming/Purpur#386]
## Is your feature request related to a problem?
Kinda, I heard people talking about a dupe in latest 1.17 where you have to drop items at a specific items around cactus to dupe it.

## Describe the solution you'd like.
A toggle option in Purpur that defines if cactus can delete items dropped on it or not.

## Describe alternatives you've considered.
None at the moment ;-;

## Agreements
Please agree to the following.
- [ ✔️  ] I have searched for and ensured there isn't already an open issue regarding this.
- [ ✔️  ] I have ensured the feature I'm requesting isn't already in the latest supported Purpur build.

## Other
None.

**Comment by granny** [comment]
Sounds like you didn't look hard enough \:P already a thing. Keep in mind it bugs out visually and may make the items go invisible (Client bug)
https://purpur.pl3x.net/docs/Configuration/#cactus
```yml
gameplay-mechanics:
  item:
    immune:
      cactus:
        - "*"
```
