### ISSUE TITLE
teleport-if-outside-border broken for spectating players

### ISSUE THREAD

**Issue by Decme** [pl3xgaming/Purpur#39]
purpur.yml
teleport-if-outside-border: true

this setting causes players in creative to get "stuck" if they fly past the world border, and they can no longer enter commands, exiting the game & rejoining loads them back in at the point that they got stuck, rebooting the server does not help. Only changing the setting to false helps.

Purpur-671 (yes I know I need to update)

Plugins (9): CoreProtect, Essentials, IllegalStack, LuckPerms, ProtocolLib, Reminder*, spark, Vault, VoidSpawn

**Comment by fredagsguf** [comment]
I can confirm this.

**Comment by Decme** [comment]
Thanks Billy ^-^
