### ISSUE TITLE
Flying Axolotls

### ISSUE THREAD

**Issue by saboooor** [pl3xgaming/Purpur#390]
## Is your feature request related to a problem?

No, I want it added because we have flying squids and i feel like if axolotls were the same it would be cool

## Describe the solution you'd like.

Add flying axolotls, like how we have flying squids

## Describe alternatives you've considered.

Tried making a plugin, but it was too hard and would most likely end up having to use NMS

## Agreements
Please agree to the following.
- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [x] I have ensured the feature I'm requesting isn't already in the latest supported Purpur build.

**Comment by bwmp** [comment]
maybe instead of specifically axolotl all aquatic animals like fish too

**Comment by BillyGalbreath** [comment]
As funny as this would be to have, I'm going to have to pass. Squids only got in on it because they are the [original flying mob](https://bugs.mojang.com/browse/MC-936) before flying was cool.
