### ISSUE TITLE
Sand duper toggle doesn't work

### ISSUE THREAD

**Issue by n0k0m3** [pl3xgaming/Purpur#392]
## Expected behavior

Sand blocks spawn at the end when using duper

## Observed/Actual behavior

Sand doesn't spawn

## Steps/models to reproduce

(Make sand duper with PaperMC)
(With existing sand duper (not working))
- Set `sand.fix-duping` to `false`
- Go to strong hold where duper is.
- Turn on machine for 5 mins
- Turn off and go to the end
- No sand block spawned

## Purpur version

```
> version
[09:28:43 INFO]: Checking version, please wait...
[09:28:43 INFO]: This server is running Purpur version git-Purpur-1169 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-"e04368045" (MC: 1.16.5)
```

## Agreements
Please agree to the following.
- [x] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [x] My version of Minecraft is supported by Purpur.

## Other

Migrated from Paper to Purpur because Paper doesn't allow sand duping. Existing duper was built on paper but also didn't work (obviously)

**Comment by BillyGalbreath** [comment]
Related to #384 

The sand duper you are talking about is actually fixed in a different way in Paper. We added a new option for end portal stuff

Set this option to false:

```yaml
blocks.end_portal.safe-teleporting: false
```

We're gotten reports that this option also doesn't work, so get back to us if it works for you or not.

**Comment by n0k0m3** [comment]
Turned off `end_portal.safe-teleporting` is the solution.
In short setting both `end_portal.safe-teleporting` and `sand.fix-duping` to `false` will bring back sand duping.

Thanks @BillyGalbreath for the support and a great Paper fork

**Comment by Frozenwhiskers** [comment]
> Related to #384
> 
> The sand duper you are talking about is actually fixed in a different way in Paper. We added a new option for end portal stuff
> 
> Set this option to false:
> 
> ```yaml
> blocks.end_portal.safe-teleporting: false
> ```
> 
> We're gotten reports that this option also doesn't work, so get back to us if it works for you or not.



im new to git hub so idk if thats how i should reply but anyway. it didnt work for me as i couldnt find the "blocks.end_portal.safe-teleporting: false"   in my purpur config and idk why (i did ctr+f to find it but it was not there) is there anything i can do (i am running the 1.21 version on aternos)

**Comment by Roan-V** [comment]
`blocks.end_portal.safe-teleporting: false`
Means it's structured like
```
blocks:
  end_portal:
    safe-teleporting: true
```

Try just searching for `safe-teleporting`

**Comment by Frozenwhiskers** [comment]
thank you very much :D

**Comment by Squawkykaka** [comment]
This 100% Works

**Comment by MCdiax** [comment]
where can I change it tho?

**Comment by antonny107846** [comment]
I don't know why but in the last version 1.21.4 the blocks.end_portal.safe-teleporting and the sand.fix-duping are not available to make the change so I'm still trying to figure out how to make the sand duping available in my purpur server. 

> This 100% Works

How did you fixed it?

**Comment by Roan-V** [comment]
I forgot when, but that option has moved to paper at some point :)
https://docs.papermc.io/paper/misc/paper-bug-fixes#duplication-bugs
