### ISSUE TITLE
1.17 Feature: resourcepack options

### ISSUE THREAD

**Issue by emielderckx** [pl3xgaming/Purpur#398]
## Idea:
In 1.17 you can require a resourcepack in server.properties. It would be nice if we could tweak this a bit more:

1. If possible a permission for certained people to not require this.
2. A config option to change the kick message you get when you decline the resourcepack

Maybe these things are not possible to change server side, if so close the issue.

## Agreements
Please agree to the following.
- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [x] I have ensured the feature I'm requesting isn't already in the latest supported Purpur build.

**Comment by BillyGalbreath** [comment]
This is all possible already using plugins. There is specific API in Bukkit for these things ^_^
