### ISSUE TITLE
TerraformGenerator 4.5.0 failed to load chunks in nether and end

### ISSUE THREAD

**Issue by 72Xion** [pl3xgaming/Purpur#399]
https://pastebin.com/fzrzCF1C

Expected:

That it loads the generator correctly in all worlds.

Observed/Actual behavior:

Only load the overworld well, in the nether and end there was a problem loading the chunks.

Steps/models to reproduce

1._Run the server
2._Stop the server
3._Delete all worlds and modify bukkit.yml for run TerraformGenerator
4._Run the server
5._Only load overworld

Purpur version

[22.06 08:56:15] [Server] [INFO] This server is running Purpur version git-Purpur-1176 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
[22.06 08:56:15] [Server] You are running the latest version

**Comment by katekerllenevich** [comment]
> You will not be offered any support as long as the server allows offline-mode players to join.

also this is an issue with that plugin using NMS

**Comment by 72Xion** [comment]
https://pastebin.com/ypHx9FDU In online mode true is the same

**Comment by emielderckx** [comment]
Omega said that it is an issue with that plugin using NMS, the plugin will need to update

**Comment by 72Xion** [comment]
ok ty
