### ISSUE TITLE
Configurable Ore Generation Seed

### ISSUE THREAD

**Issue by UsainSrht** [pl3xgaming/Purpur#403]
ore-generation under seed option would be really cool.

Why do you want it added?
- Because I want to make cracking seed even harder.

- [1] I have searched for and ensured there isn't already an open issue regarding this.
- [2] I have ensured the feature I'm requesting isn't already in the latest supported Purpur build.

![Screenshot_3](https://user-images.githubusercontent.com/59025999/123096182-7ec40f00-d437-11eb-9f8a-dc81802ba605.png)

**Comment by BillyGalbreath** [comment]
Implemented in [build 1182](https://purpur.pl3x.net/api/v1/purpur/1.17/1182/download)

https://github.com/pl3xgaming/Purpur/commit/0babd7cad818328865ce3655ac9c2e250fdd6ebe

Not only can you customize the ore seed, but any other feature seed that uses a random. `scattered_ore` is another one you might be interested in ^_^
