### ISSUE TITLE
Failed to register packet listener on channel

### ISSUE THREAD

**Issue by Elikill58** [pl3xgaming/Purpur#409]
## Expected behavior
Getting channel thanks to reflection, and then load pipeline on it to get all packets

## Observed/Actual behavior
I get an issue: https://pastebin.com/Ldtmubnz so the pipeline isn't registered

## Purpur version
Version download few minutes ago:
![image](https://user-images.githubusercontent.com/17381066/123408893-d71d1d00-d5ad-11eb-9071-606b396241b8.png)

## Agreements
Please agree to the following.
- [x] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [x] My version of Minecraft is supported by Purpur.

## Other
My project is on github.
This is the code where the issue appear: https://github.com/Elikill58/Negativity/blob/master/src/com/elikill58/negativity/spigot/packets/custom/channel/INC2Channel.java#L32

I hope this can help you to help me.

**Comment by katekerllenevich** [comment]
can you reproduce this on paper, or even better, tuinity?

**Comment by Elikill58** [comment]
Tuinity isn't on 1.17, but even with 1.16 (and ViaVersion to login with 1.17 client) I get the same issue.

On paper, everything seem fine.

**Comment by katekerllenevich** [comment]
> Tuinity isn't on 1.17

yes it is, you can download it from their actions page. please note they are **dev builds**

**Comment by Elikill58** [comment]
> yes it is, you can download it from their actions page. please note they are **dev builds**

The github https://github.com/Tuinity/Tuinity isn't active for 2 weeks, and so it's the same for build: https://ci.codemc.io/job/Spottedleaf/job/Tuinity/

**Comment by katekerllenevich** [comment]
wrong again, check the branches. and you can download them here https://github.com/Tuinity/Tuinity/actions?query=branch%3Aver%2F1.17

**Comment by Elikill58** [comment]
Oh yes ! That's why i give link, it's because now we are talking about same thing x)

On latest build (make 15h ago) I also get the same issue

**Comment by katekerllenevich** [comment]
In that case, please report to Tuinity.
