### ISSUE TITLE
Players crash against an invisible wall

### ISSUE THREAD

**Issue by ghost** [pl3xgaming/Purpur#41]
I am using the kernel version of purpur 1.16.2 build 727. And I have a problem, if a player accelerates to high speed with a trident with the “thrust 3” enchant and puts on the wing covers, then at some point he can crash into an invisible wall. The player's death messages look something like "Kinetic energy converted to internal energy." I think this is a bug, because in the file settings in the server root folder, I did not find the parameter that is responsible for this. By the way, this problem applies to purpur 1.16.1 too.

Steps to the bug: Take the trident with the "thrust3" enchantment, then take and put on the elytra. Then turn on a thunderstorm or rainy weather and start flying on the elytra, then grab the trident and start pulling and releasing very quickly. After a few seconds, you will reach the speed at which the error occurs and die by crashing into an invisible wall in the air. In this case, of course, you need to be in survival mode.

Plugins on server: Chatty, CoreProtect, CoreProtectTNT, EasyWhitelist*, Harbor, HolographicDisplays, InventoryRollback, LightChatBubbles*, LimitPillagers, LuckPerms, Matrix, MaxBans*, nLogin, OpenInv, PlaceholderAPI, PlugMan, ProtocolLib, rHideTags*, SAML, ServerlistMOTD*, SimpleLay, SkinsRestorer, SuperVanish, TAB, ViewDistanceTweaks

Version of server: 
[16:48:27 INFO]: This server is running Purpur version git-Purpur-727 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
[16:48:27 INFO]: Checking version, please wait...
[16:48:27 INFO]: You are running the latest version

Such a bug does not happen on the spigot, it just stops me when I develop too high speed.
[Server thread/INFO]: This server is running CraftBukkit version git-Spigot-379750e-43c7ff9 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
And also this bug does not happen on paper, it loads chunks faster and more rarely stops me in unloaded chunks.
Paper version: This server is running Paper version git-Paper- "47740f67c" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

Additional context:
And I turned off the matrix (anti-cheat) during the test, everything was the same thing.

**Comment by BillyGalbreath** [comment]
This is fixed in [build 736](https://ci.pl3x.net/job/Purpur/736/). But you have to make sure your `paper.yml` has the option `prevent-moving-into-unloaded-chunks` set to `false`.
