### ISSUE TITLE
Auto Updater

### ISSUE THREAD

**Issue by TheFlood424K** [pl3xgaming/Purpur#410]
## Is your feature request related to a problem?
  It is not related to a problem, I just like having the latest updated build, and I run my server on a command line install. So, it is difficult to update.

## Describe the solution you'd like.
  Add an option in the config file to update to the latest jar on server reboot. If this were added, I would officially swap to Purpur from PaperMC. I have an automated script created that will auto update paper.

## Describe alternatives you've considered.
  I have tried using serverjars from serverjars.com, but it causes multiple Java syntax errors and frequent crashes.

## Agreements
Please agree to the following.
- [Yes ] I have searched for and ensured there isn't already an open issue regarding this.
- [ Yes] I have ensured the feature I'm requesting isn't already in the latest supported Purpur build.

## Other
Add any other context or screenshots about the feature request below.

**Comment by katekerllenevich** [comment]
Please fill out the proper template.

**Comment by TheFlood424K** [comment]
Sorry, first time opening an issue. It's fixed.

**Comment by katekerllenevich** [comment]
Auto updating is a very dangerous practice, but you can use Purpur's download API to get the latest version `https://purpur.pl3x.net/api/v1/purpur/1.17/latest/download`

**Comment by TheFlood424K** [comment]
I am aware of the issues involved with auto updating, I was just wondering if you could create an optional way to do so.

**Comment by katekerllenevich** [comment]
We will not create an option for this, but you can update your script to download from the link I specified above.

**Comment by TheFlood424K** [comment]
Ok, thanks!
