### ISSUE TITLE
bug: missing default permission for join full server

### ISSUE THREAD

**Issue by emielderckx** [pl3xgaming/Purpur#415]
## Expected behavior
The permission purpur.joinfullserver that was added in #406 should popup in luckperms editor

## Observed/Actual behavior
purpur.joinfullserver doesn't popup

Should add a default permission for join full server (@notOM3GA)

## Purpur version
```
This server is running Purpur version git-Purpur-1191 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: bdcea0e on HEAD)
You are running the latest version
Previous version: git-Purpur-1187 (MC: 1.17)
```

## Agreements
Please agree to the following.
- [x] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [x] My version of Minecraft is supported by Purpur.

**Comment by Euphillya** [comment]
Luckperms adds permission only when it has been requested at least once.

**Comment by katekerllenevich** [comment]
I’ll do it when I get home
