### ISSUE TITLE
Endermen don't run at a pearl spawned Endermite. Not /summon. The survival way.

### ISSUE THREAD

**Issue by iT3g4n** [pl3xgaming/Purpur#418]
## Timings link
https://timings.pl3x.net/?id=b492d11219f8479898518b7f9f3ee8e2

## Expected behavior
enderman run at the endermite

## Observed/Actual behavior
the endermen were not aggro to the endermite

## Steps/models to reproduce
get an endermite with enderpearls

## Purpur version
 version
This server is running Purpur version git-Purpur-1197 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 51c1df9 on HEAD)
You are 0 version(s) behind
Previous version: git-Paper-43 (MC: 1.17)

## Agreements
Please agree to the following.
- [ ] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [x] My version of Minecraft is supported by Purpur.

**Comment by iT3g4n** [comment]
timings: https://timings.pl3x.net/?id=b492d11219f8479898518b7f9f3ee8e2
expected behaviour: endermen run at the endermite.
Observed/Actual behavior: they don't. they stand there normally.
Steps/models to reproduce: latest version and spawn an endermite the survival way - with enderpearls. in the end.
Purpur version:

This server is running Purpur version git-Purpur-1197 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 51c1df9 on HEAD)
You are 0 version(s) behind
Previous version: git-Paper-43 (MC: 1.17)

**Comment by katekerllenevich** [comment]
i went ahead and fixed your format, you put all the answers in comments.

**Comment by iT3g4n** [comment]
thx :)

**Comment by BillyGalbreath** [comment]
Fixed with https://github.com/pl3xgaming/Purpur/commit/f690dd42ebf834e5edb8cde7c22148809f5f756e

**Comment by iT3g4n** [comment]
thanks!
