### ISSUE TITLE
Disabling/enabling certain entities collision.

### ISSUE THREAD

**Issue by Agaloth** [pl3xgaming/Purpur#419]
## Is your feature request related to a problem?
  For certain cases, players want villagers to have collisions for farms or another type of farms but it's not possible due to the collision disabling it on all entities.

## Describe the solution you'd like.

  A similar system as SugarcaneMC, they did another way but I'm fairly certain it could be implemented better:

    collisions:
      players: false
      animals: false
      ambient: false
      monsters: false
      villagers: false
      pillagers: false
      iron-golems: false
      misc: false
      items: false
      water-creature: false
      water-ambient: false

## Agreements
Please agree to the following.
- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [x] I have ensured the feature I'm requesting isn't already in the latest supported Purpur build.

**Comment by katekerllenevich** [comment]
i went ahead and fixed your format, as all your answers were in comment blocks :P.

**Comment by Agaloth** [comment]
Thanks, I never use GitHub so I was confused LOL
