### ISSUE TITLE
TacoSpigot integration

### ISSUE THREAD

**Issue by kolakz** [pl3xgaming/Purpur#420]
## Please give some context for this request. Why do you want it added?
TacoSpigot has a lot of optimizations from what I've heard, especially with Paper's anti-xray feature.

## Describe the solution you'd like.
It would be great to see Purpur integrate some of TacoSpigot's patches!

## Agreements
Please agree to the following.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Purpur build.

**Comment by BillyGalbreath** [comment]
TacoSpigot has been long dead since 1.8, with a short-lived revival to update to 1.12/1.13 which was quickly cancelled. It was a fork designed for PvP servers (mostly cannon/tnt optimizations). None of it's patches are relevant for modern servers.

**Comment by kolakz** [comment]
Fair enough.
