### ISSUE TITLE
Disable server.properties date comment config option

### ISSUE THREAD

**Issue by femboyfin** [pl3xgaming/Purpur#422]
## Is your feature request related to a problem?

My typical procedure for testing plugin and server changes is to check details about the changes from the authors, update the plugin on a local test server, then check for differences in server files and check each file for new settings that I may want to change. This system has worked very well for me with one caveat, it gets annoying to have server.properties changed with the last launch date on every single launch as I have to address it before I'm able to send my changes off to my official testing server for staff to access and test. 

## Describe the solution you'd like.

A config option to disable the time and date comment in `server.properties`.

## Describe alternatives you've considered.

I've tried marking the file as ignored but that causes trouble if I ever need to edit server.properties.

## Agreements
Please agree to the following.
- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Purpur build.

## Other

```yaml
#Minecraft server properties
#Sat Jun 26 20:29:02 EDT 2021
```

**Comment by BillyGalbreath** [comment]
Sadly, this doesn't seem to be possible, as the timestamp is a hardcoded feature of Properties files in the Java language.

https://stackoverflow.com/questions/6184335/properties-store-suppress-timestamp-comment

**Comment by TheAwesome98-Real** [comment]
I suppose we could implement our own `Properties` parser based off of Java's, but that's too much work for a minor issue.

**Comment by granny** [comment]
Thought I'd let you know that there has been a PR created for Paper that does what you want. PaperMC/Paper#6251
