### ISSUE TITLE
Sign Formatting Codes No Longer Working On 1.17

### ISSUE THREAD

**Issue by Xarius86** [pl3xgaming/Purpur#424]
## Expected behavior
In all previous versions I've used (referring to 1.16.x), when allowing a group or user the following permissions:

```
purpur.sign.color
purpur.sign.style
purpur.sign.magic
```

Along with having `sign.allow-colors` set to `true` 

My players and I have been able to make signs using an ampersand followed by the applicable formatting code to make signs to our liking.

## Observed/Actual behavior

In Purpur #1204, when attempting to use a formatting code on a sign, the ampersand is simply removed, and the code number/letter left behind. 

For example, when making a sign like: `&4My Sign` it is just truncated to `4My Sign`
More complex formatting with multiple codes has the same behavior. 

It should be noted that existing signs will display as they did in the past UNTIL you attempt to edit them. As soon as you attempt an edit, all ampersands are removed, and just the letter/number code is left behind.

## Steps/models to reproduce

To rule out any plugin issues, I duplicated my entire server and removed everything in the plugins folder. I then added only LuckPerms back in order to handle permissions. It should be noted here that it doesn't appear to be a LuckPerms issue, as right click editing works properly thus suggesting LuckPerms is functioning as desired. 

To be doubly sure there wasn't a configuration issue elsewhere, I fired up a brand new test world, added LuckPerms and the proper permissions, made the config change to allow sign colors in purpur.yml, and had exactly the same results. 

## Purpur version

```
This server is running Purpur version git-Purpur-1204 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: b4e0fc7 on HEAD)
You are running the latest version
Previous version: git-Purpur-1200 (MC: 1.17)
```

## Agreements
Please agree to the following.
- [ x] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [ x] I have searched for and ensured there isn't already an open issue regarding this.
- [ x] My version of Minecraft is supported by Purpur.

**Comment by katekerllenevich** [comment]
This is definitely an issue with the way I ported this patch, Mojang implemented "filtered" text and that messed the entire patch up.
