### ISSUE TITLE
[Feature Request] Glow berries should give glowing effect

### ISSUE THREAD

**Issue by ChiboYen** [pl3xgaming/Purpur#428]
Glow berries are a complete and utter scam! You eat them... and they just give you saturation and hunger points, but NO glowing effect! pls fix purpur devs

## Is your feature request related to a problem?
pls help

## Describe the solution you'd like.
help

## Describe alternatives you've considered.
no info

## Agreements
Please agree to the following.
- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [x] I have ensured the feature I'm requesting isn't already in the latest supported Purpur build.
## Other
just help

**Comment by craftish37** [comment]
I swear this guy is a genius

**Comment by encode42** [comment]
Been watching Hermitcraft? :smirk:

I also believe this is a good idea. I'll look into whether it's easier to implement as a plugin.
