### ISSUE TITLE
Suspicious Stew isn't Suspicious enough

### ISSUE THREAD

**Issue by kronusdev** [pl3xgaming/Purpur#445]
Play the Among Us theme whenever you drink Suspicious Stew in game, I don't know why this has never been implemented before but I am quite frankly being scammed by Mojang... People who drink Suspicious Stew are sussy! (They may even be the imposter) 

## Is your feature request related to a problem?
Yes, drinking suspicious stew doesn't make you sus enough

## Describe the solution you'd like.
"amogus" sound effect and theme played when you drink suspicious stew (toggleable of course)

## Describe alternatives you've considered.
There is no alternative, make the stew sussy

## Agreements
Please agree to the following.
- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [x] I have ensured the feature I'm requesting isn't already in the latest supported Purpur build.

## Other
PLEASE FIX NOW (ily Billy)

**Comment by EuanM199** [comment]
+1 This is a great idea
