### ISSUE TITLE
Respawning causes no interaction

### ISSUE THREAD

**Issue by adelando** [pl3xgaming/Purpur#450]
### Timings link

https://timings.pl3x.net/?id=559024efcf4542759809cbdb160070fb

### Expected behavior

Respawning with normal interactions (break blocks and interact with doors)

### Observed/Actual behavior

After dying players can't seem to break any blocks or interact with blocks or items (trapdoors, buttons, doors etc)

### Steps/models to reproduce

A player dies from natural causes (any sort of death)
Instant respawn gamerule or normal respawn does not effect results

I have also disabled CombinedSpawn plugin to see if that was effecting the results and it didnt change.

Also if i relog or change world (from the world i respawned in) then i can once again interact with blocks and items.

### Purpur version

This server is running Purpur version git-Purpur-1219 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 34c8295 on HEAD)
You are running the latest version
Previous version: git-Purpur-1199 (MC: 1.17)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
I am unable to reproduce this

**Comment by katekerllenevich** [comment]
Can you reproduce this without plugins?

**Comment by adelando** [comment]
I’m so sorry to have wasted your time on this bug, I was trying to reproduce on a fresh server install and turns out it was essentialsx 
Sorry guys
