### ISSUE TITLE
Sit on stonecutter still has no damage

### ISSUE THREAD

**Issue by cardanawandra** [pl3xgaming/Purpur#457]
### Expected behavior

damage when sit on stonecutter

### Observed/Actual behavior

![Uploading image.png…]()

it's not get damaged

### Steps/models to reproduce

-use sit plugin as GSit
-do /sit on

### Purpur version

1084

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

i think it's about height of damage, because sit is below 0.5 blocks

**Comment by BillyGalbreath** [comment]
Like I've said many times in the past, you have to talk to the plugin developer for GSit for them to implement such a feature.

**Comment by DereC4** [comment]
Late but this is because gsit spawns an entity underneath you when you "sit", so you are technically not touching the stonecutter
