### ISSUE TITLE
Essentials EC overriding Purpur

### ISSUE THREAD

**Issue by itsaderm** [pl3xgaming/Purpur#46]
**Describe the bug**
When using /ec or /enderchest, players have all rows irrespective of purpur permissions. However when they open a physical enderchest, they have the right amount of rows respective of the purpur permissions assigned to them.

**To Reproduce**
Get essentials, set 6 rows to 6 and do as above and you should see the issue.

**Screenshots or Videos**
N/A

**Plugins**
https://quak.ovh/2gR23Xv.png

**Version**
https://quak.ovh/282DFdC.png

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
Unsure due to this being a purpur specific feature.

**Comment by AZFire1** [comment]
Yeah, tried it. Happens to me as well.

**Comment by MrIvanPlays** [comment]
[my poor attempt at fixing this](https://github.com/YatopiaMC/Yatopia/blob/ver/1.16.2/patches/server/0046-Respect-permissions-when-constructing-InventoryEnder.patch)

**Comment by ghost** [comment]
This seems to work perfectly with CMI, perhaps a fix at essentials is more convenient?

**Comment by jpenilla** [comment]
Essentials is using proper API for this, the fact that CMI works makes me think maybe they use NMS or something. Can't tell because they are not open source and I haven't bought their plugin to de compile it though.

**Comment by ghost** [comment]
Probaly NMS they use it a lot and not in a good way. Good to know tho thanks.
