### ISSUE TITLE
Infinite fuel doesn't work

### ISSUE THREAD

**Issue by ghost** [pl3xgaming/Purpur#462]
### Expected behavior

When furnace-infinite-fuel is set to true, the furnace will have a never ending duration when lava is placed under it.

### Observed/Actual behavior

Nothing happens. Placing lava directly under the furnace doesn't power it.

### Steps/models to reproduce

1. Place down a furnace
2. Place lava under it.
3. Put raw food in the furnace.

### Purpur version

This server is running Purpur version git-Purpur-1238 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 1ca029c on HEAD)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Just a heads up, while I fixed this bug I also renamed this option to make it more clear what it actually does.

Instead of `furnace.infinite-fuel` it is now `furnace.use-lava-from-underneath`

The option will automatically rename itself when you update.
