### ISSUE TITLE
Cannot open shulker boxes when in front, or on top, or when an entity is blocking it.

### ISSUE THREAD

**Issue by Apprisco** [pl3xgaming/Purpur#463]
### Expected behavior

Shulker boxes should be able to be opened in any way if it has block space.
On purpur, entities block it from opening.

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/34324909/124351229-24dff800-dc34-11eb-9d87-d05ceb10b492.png)
![image](https://user-images.githubusercontent.com/34324909/124351236-2c9f9c80-dc34-11eb-8e35-fe9f065ef456.png)
![image](https://user-images.githubusercontent.com/34324909/124351254-44772080-dc34-11eb-99fa-ebdac4b52b6b.png)

any entity, including players, will block shulker boxes from opening.

### Steps/models to reproduce

Get the latest build of purpur 1.17.
Issue exists immediately.

### Purpur version

This server is running Purpur version git-Purpur-1238 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 1ca029c on HEAD)
You are running the latest version
Previous version: git-Purpur-1233 (MC: 1.17)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by katekerllenevich** [comment]
I can only reproduce something on top of the shulker box. Although, I was able to reproduce this on Tuinity, so please send your issue request there ^_^.
