### ISSUE TITLE
Sign Right Click To Edit Not Working in 1.17

### ISSUE THREAD

**Issue by UsainSrht** [pl3xgaming/Purpur#470]
### Expected behavior

Sign gui should open when you right click on a placed sign with sign in your hand.

### Observed/Actual behavior

Sign gui didn't open.

### Steps/models to reproduce

Place a sign and type something
right click the sign you have placed with sign in your hand

### Purpur version

This server is running Purpur version git-Purpur-1251 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: b2fe934 on HEAD)
You are running the latest version
Previous version: git-Purpur-1245 (MC: 1.17)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Yes it's true. right-click-edit: true

**Comment by UsainSrht** [comment]
I Have figured it out. It was my problem, I didn't have the permission but I'm OP why I am need a special permission?

**Comment by BillyGalbreath** [comment]
We recently fixed a bug where OP players were incorrectly given every permission ever, even the ones that were designed to be always off.

https://github.com/pl3xgaming/Purpur/blob/ver/1.17/patches/api/0044-Fix-default-permission-system.patch

All of Purpur's features are designed to be off by default. This includes all of it's permissions, even for OP players. We do this to make sure our jar aligns with the upstream experience unless the server admin specifically enables the features themselves.

<https://github.com/pl3xgaming/Purpur/blob/ver/1.17/patches/api/0004-Default-permissions.patch>

Remember, OP is not a rank. It is a tool ;)
