### ISSUE TITLE
Formatting code in books doesn't work

### ISSUE THREAD

**Issue by Vulby** [pl3xgaming/Purpur#477]
### Expected behavior

When using ampersand plus any character (0-9,a-f,k-r) in a book and quill and clicking done. It should update correctly to reflect the formatting

### Observed/Actual behavior

When attempting to use any formatting code in a book, It doesn't update the book to show the formatting correctly.
_Video attached below_

### Steps/models to reproduce

To rule out any plugin or datapack issues, I duplicated my entire server and removed everything in the plugins/datapack folders.  

https://user-images.githubusercontent.com/27425253/124539361-e9ba1080-de4f-11eb-850c-bfd0244e0bcf.mp4

### Purpur version

 ```
This server is running Purpur version git-Purpur-1254 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: a0fae1b on HEAD)
You are running the latest version
Previous version: git-Purpur-1236 (MC: 1.17)
```

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I enabled all things relating to colors in purpur.yml and enabled the following permissions relating to color.

```
blocks:
      anvil:
        allow-colors: true
      sign:
        allow-colors: true
        right-click-edit: true
```

```
purpur.sign.color
purpur.sign.style
purpur.sign.magic

```

**Comment by granny** [comment]
Make sure you have the `purpur.book.color.edit` and `purpur.book.color.sign` perms set

**Comment by Xarius86** [comment]
As a side note, it looks like the docs are missing anything about `purpur.book.*`

**Comment by Vulby** [comment]
> Make sure you have the `purpur.book.color.edit` and `purpur.book.color.sign` perms set

Ah I see, that works thanks. As Xarius said the docs don't have anything about those perms on the docs

**Comment by granny** [comment]
Correct, it's something I missed when the formatting patch was added. Added them in just now pl3xgaming/PurpurDocs@4b1fe38
