### ISSUE TITLE
Abnormal nether portal generation

### ISSUE THREAD

**Issue by KioProject123** [pl3xgaming/Purpur#484]
### Expected behavior

Only one portal is generated

### Observed/Actual behavior

Many portals have been generated
![image](https://user-images.githubusercontent.com/61594596/125074574-0d9b8180-e0f0-11eb-850d-a4ba11104a40.png)

### Steps/models to reproduce

1、Install Caves & Cliffs datapack
2、Building portal at high altitude (Y > 256)
3、Enter the Nether
4、Go back and then enter

and I tested it on paper, everything is ok

### Purpur version

> version
[19:57:11 INFO]: Checking version, please wait...
[19:57:12 INFO]: This server is running Purpur version git-Purpur-1260 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 444413b on HEAD)
You are running the latest version
Previous version: git-Paper-92 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by katekerllenevich** [comment]
Please test this on Tuinity!

**Comment by KioProject123** [comment]
> Please test this on Tuinity!

This is a Tuinity bug，I'll report it to tuinity
