### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 96 

### ISSUE THREAD

**Issue by taka1945** [pl3xgaming/Purpur#487]
### Timings link

https://timings.pl3x.net/?id=f43fdd680e054804ba1b865d3d78f91e

### Expected behavior

play normal.

### Observed/Actual behavior

player will be kick out.

### Steps/models to reproduce

player just need to put Axolotl in the water ... than boom 

### Purpur version

 Purpur version git-Purpur-1261 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

https://pastebin.com/re0wk19E

**Comment by katekerllenevich** [comment]
Can you reproduce this without plugins?

**Comment by taka1945** [comment]
> Can you reproduce this without plugins?

great idea, I will make clean 1.17.1 try this.

**Comment by taka1945** [comment]
others players don't get trouble  in same server , sorry about this.
