### ISSUE TITLE
Bowstring is not drawn back when using a Shield

### ISSUE THREAD

**Issue by Lycrom** [pl3xgaming/Purpur#492]
### Expected behavior

Expected to see the Bowstring be drawn back while holding right click. 

### Observed/Actual behavior

The Bowstring is not drawn back but will still fire an arrow when released.

### Steps/models to reproduce

Purpur setting required to observe behavior: 
infinity-bow: 
   works-without-arrows: true
Right Hand: Bow with Infinity but no arrows in inventory. 
Off Hand: Shield

### Purpur version

This server is running Purpur version git-Purpur-1265 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2824f64 on HEAD)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

If there are Arrow in the inventory everything works as it should.

**Comment by encode42** [comment]
The method utilized in that patch can be janky at times, and I plan on looking it over again to find a better way.

**Comment by encode42** [comment]
From what I can tell, this is a client-side visual bug that cannot be fixed server-side. I'll look into developing a patch to put in [PurpurClient](https://modrinth.com/mod/purpurclient).
