### ISSUE TITLE
Entites are getting ticked before the chunk is loaded.

### ISSUE THREAD

**Issue by Nervaq** [pl3xgaming/Purpur#495]
### Expected behavior

Assembled TNT duper should be stable and not break on its own.

### Observed/Actual behavior

When I teleport away from TNT duper then back in. It works fine but then teleport away again and then load it, the TNT gets updated and breaks the duper.

### Steps/models to reproduce

1.Assemble simple TNT duper
2.Try if it works.
3.TP away and wait until chunks are properly unloaded.
4. TP back in.
If this doesn't work just try it couple times. I'm not the only one who expirienced this. It's not 100% reliable reproduce but it can happen which means at some point it will happen.

### Purpur version

build #1265

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I would like to note that this feature is essential to minecraft and Mojang himself said that they won't patch TNT duping until they implement MTE along with renewable sand. Also Deepslate mining is based around having a tunnel bore if you wanna dig a large area, developers were aware of this and that's why deepslate has Blast resistance 6, same as Stone and other variants.

Also plugins do not affect this behavior at all. Since we tested this on 2 servers with plugins and without them.

**Comment by BillyGalbreath** [comment]
Test this in the upstream forks and report it to the one where the problem is introduced. Purpur doesnt change anything that would cause this behavior.

Let us know after you test them, and drop a link here to the issue ticket you create upstream.

**Comment by BillyGalbreath** [comment]
https://github.com/PaperMC/Paper/issues/6168
