### ISSUE TITLE
Mobs keep despawning/disappearing

### ISSUE THREAD

**Issue by dbrighthd** [pl3xgaming/Purpur#499]
### Expected behavior

Mobs like named axolotls from buckets should not despawn

### Observed/Actual behavior

they are despawning.

this is really frustrating me because mobs like horses, cows, bees, sheep, and axolotls are despawning to the dismay of all my server members, and I feel helpless

### Steps/models to reproduce

I placed 8 axolotls all named from the number 1 through 8 in this safe water area
![image](https://user-images.githubusercontent.com/68525639/125605990-0bcd3de0-4301-4c82-b937-edbe13def477.png)

after a couple days, i go back to see that 4 of them are gone. 
![image](https://user-images.githubusercontent.com/68525639/125606092-15759f16-4882-4acd-82b9-9a5b6f3f98eb.png)

this is not due to kills, as there are none logged with CoreProtect.

### Purpur version

This server is running Purpur version git-Purpur-1265 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2824f64 on HEAD)
You are 2 version(s) behind
Previous version: git-Purpur-1262 (MC: 1.17.1)

this had to be behind because it only happens in the course of multiple days

### Agreements

- [x] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by dbrighthd** [comment]
More info:  here are my plugins
![image](https://user-images.githubusercontent.com/68525639/125611521-e2cdc9ef-6810-40be-aab2-ec20547591be.png)

this is what I see after searching for recent axolotl deaths with coreprotect:
![image](https://user-images.githubusercontent.com/68525639/125611556-35619ba6-97e9-41cc-9135-47c97e1bd111.png)

and this seems to happen after server crashes, which is followed by these errors (which may be unrelated, but just in case)
![image](https://user-images.githubusercontent.com/68525639/125611471-c42f1bb1-4185-4713-a094-7128a68c0db3.png)

**Comment by BillyGalbreath** [comment]
This has been a long standing vanilla issue. Mojang is aware of it, and they keep trying to fix it every new release for a few years now. However, it appears they haven't fixed it completely for everyone.

There is nothing I can do about this in Purpur. You can try to report it to Paper, but it'll likely not get fixed there as well. Best bet is to just get in contact with Mojang and let them know it's still not fixed.

https://bugs.mojang.com/browse/MC-27535
