### ISSUE TITLE
Double strip logs

### ISSUE THREAD

**Issue by Apprisco** [pl3xgaming/Purpur#507]
### Expected behavior

In vanilla, when you right click on a log to strip it, it only does it once.

### Observed/Actual behavior

In purpur based servers, it seems that the axe triggers twice, along with the sound.
This does not strip more logs than you expected, but is still quite an annoyance.

### Steps/models to reproduce

Install purpur.
Strip a log with any axe.

### Purpur version

This server is running Purpur version git-Purpur-1287 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 01b35a2 on ver/1.17.1)
You are running the latest version
Previous version: git-Purpur-1285 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by cardanawandra** [comment]
this is happen when vanilla blocks strip meet purpur, also happen with hoe

they trigger twice

i suggest, cancel purpur custom strip on vanilla blocks stripable

**Comment by BillyGalbreath** [comment]
I just tried this out myself and I am not seeing these actions double up. I tested using a diamond axe on an oak log, and a diamond hoe on grass and a plugin listening to the PlayerInteractEvent. The event fired once per hand, like normal. I then enabled sound subtitles to see if the sound was playing twice, which it is not. I also only see one arm swing animation for these actions.

Tested on Purpur #1313 using this plugin:

```java
public final class Test extends JavaPlugin {
    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(new Listener() {
            @EventHandler
            public void on(PlayerInteractEvent event) {
                if (event.getHand() != EquipmentSlot.HAND) {
                    return;
                }
                event.getPlayer().sendMessage("Hmm");
            }
        }, this);
    }
}
```

**Comment by ghost** [comment]
That might be true but when you listen carefully you can really hear the sound being played twice, tested on build 1314

**Comment by katekerllenevich** [comment]
>  That might be true but when you listen carefully you can really hear the sound being played twice, tested on build 1314

you don't need to listen closely with sound subtitles
