### ISSUE TITLE
Villager mob-griefing bypass doesn't let villager pick up food

### ISSUE THREAD

**Issue by n0k0m3** [pl3xgaming/Purpur#511]
### Expected behavior

(With: `villager.bypass-mob-griefing = true` and `/gamerule mobgriefing false`)
Farmer break crops (in my case, carrots), **pick drops up**, drop to villager, love, breed child

Villager breeder farm used: https://www.youtube.com/watch?v=rPPqspS2wX0

### Observed/Actual behavior

Farmer only break crops, but doesn't pick drops up, villager can't pick up crop drops, can't breed

### Steps/models to reproduce

Set `/gamerule mobgriefing false`
Set `villager.bypass-mob-griefing = true` (purpur.yml) and `tick-inactive-villager = true` (spigot.yml)

Build villager farm: https://www.youtube.com/watch?v=rPPqspS2wX0

(Optional: drop stacks of carrots/crops in front of villagers)

### Purpur version

```
[20:26:04 INFO]: Checking version, please wait...
[20:26:04 INFO]: This server is running Purpur version git-Purpur-1288 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 246383a on ver/1.17.1)
[20:26:04 INFO]: You are running the latest version
[20:26:04 INFO]: Previous version: git-Purpur-1279 (MC: 1.17.1)
```

### Agreements

- [x] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Try using this option

```yaml
gameplay-mechanics:
  entities-pick-up-loot-bypass-mob-griefing: true
```

This is a global setting for all mobs, sadly, because of the way mojang implemented the feature

**Comment by n0k0m3** [comment]
That's sad but it works at least for my need atm (villager breed but crepper doesn't destroy things). Thanks the suggestion
