### ISSUE TITLE
Villagers can smell emeralds even in their sleep

### ISSUE THREAD

**Issue by fredagsguf** [pl3xgaming/Purpur#512]
### Expected behavior

Villagers shouldn't follow emerald blocks when they are sleeping...
but they do..

### Observed/Actual behavior

Villagers following emerald blocks held by players even when sleeping and through blocks..
the villager is then stuck in a state of laying down...
![image](https://user-images.githubusercontent.com/46964809/126385132-05b27a3e-5eef-48ed-8312-c9cd70d11a56.png)
![image](https://user-images.githubusercontent.com/46964809/126385143-b7d17078-41bc-42ca-b4ff-f1e03802f29f.png)

### Steps/models to reproduce

Just enable villagers following emerald blocks.

### Purpur version

Purpur version: 1287

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by Euphillya** [comment]
Fixed Purpur build 1310
