### ISSUE TITLE
Massive lagspikes when players join for the first time, or when some players die

### ISSUE THREAD

**Issue by VRILGQD** [pl3xgaming/Purpur#522]
### Timings link

https://timings.pl3x.net/?id=ac0865ec14aa4da49455a0991e159397

### Description of issue

Hello, so on my server there have been massive amounts of lag spikes as of recently due to players joining for the first time or from some players dying.

From what I've seen in the timings, the server is loading chunks at an extremely high rate when somebody dies. I narrowed down the first join lagspikes to the plugin _TheNewEconomy_'s autosaver, but I have no idea what in the hell is causing the death lag. I also think player packets are causing the issue as well.

The timings report is in there and here is also the link for the spark profiler: https://spark.lucko.me/YCcqmWiWbQ

### Purpur version

Purpur 1.16.5 build 1171

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by IllagerCaptain** [comment]
Your version is not supported by Purpur.

**Comment by ATMmachin3** [comment]
So much for those Agreements

**Comment by granny** [comment]
Closing this issue since it's not the __latest version of Purpur available__. You're 126 builds behind.
