### ISSUE TITLE
Chunk Affect TPS input front timings on

### ISSUE THREAD

**Issue by yuankun1** [pl3xgaming/Purpur#529]
I really can't find any way

**Comment by yuankun1** [comment]
> ### Timings link
> https://timings.pl3x.net/?id=8af58ff47ea74be8b425dd47f3c00a76
> 
> ### Description of issue

> input front  timings on
> ![TPS](https://user-images.githubusercontent.com/19505154/127319279-11604522-2565-4902-b447-f20a9326d9e2.png)
> 
> close later  timings off
> ![TPS2](https://user-images.githubusercontent.com/19505154/127319361-d4faffcc-e157-43ec-80f6-70a054f96ed7.png)
> 
> ### Purpur version
> _No response_
> 
> ### Agreements
> * [x]  I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
> * [x]  I have searched for and ensured there isn't already an open issue regarding this.
> * [x]  My version of Minecraft is supported by Purpur.
> 
> ### Other
> _No response_

**Comment by granny** [comment]
1. You didn't include a description of your issue
2. You are ___not___ running the latest version of Purpur available
