### ISSUE TITLE
[Feature Request] Disable cannot-ride-mob message

### ISSUE THREAD

**Issue by AZFire1** [pl3xgaming/Purpur#53]
**Feature Description:**
Maybe a way to completely disable the cannot-ride-mob message? As, maybe you'd want the ridable mob feature enabled on a specific mob though you'd want to disable the message it sends when players try to ride it so they don't know if it's enabled or not? Not sure, it could be a cool idea.

**Comment by ghost** [comment]
This is already possible, simply set the message to ''

`    cannot-ride-mob: ''`

**Comment by granny** [comment]
@Alejandro-Sosa is correct. Just make sure the format is set to empty quotes and it'll remove the message.
