### ISSUE TITLE
Minecart speed maxes out at 107.6 km/h

### ISSUE THREAD

**Issue by helpimnotdrowning** [pl3xgaming/Purpur#531]
### Expected behavior

Minecart speed configured in the purpur.yml should not cap out and let me make minecarts as fast as possible. 

### Observed/Actual behavior

Minecart speed caps out at 107.6 km/h (measured by Custom HUD fabric mod) no matter how high I set world-settings.default.gameplay-mechanics.minecart.max-speed in the purpur.yml file.

### Steps/models to reproduce

I verified off-video that `/purpur reload` is actually doing things by changing the powered rail boost to 0 and seeing if that changed. It did. This shows the speed capping at 107.6 km/h after having the max speed be 100 and 255.
https://user-images.githubusercontent.com/35247379/127392406-5881bb3d-dff7-4452-9f6a-2f21ee12c2f0.mp4

### Purpur version

```
> version
[15:21:14 INFO]: Checking version, please wait...
[15:21:15 INFO]: This server is running Purpur version git-Purpur-1299 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9e63e8f on ver/1.17.1)
[15:21:15 INFO]: You are running the latest version
[15:21:15 INFO]: Previous version: git-Purpur-1275 (MC: 1.17.1)
```

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by cittyinthecloud** [comment]
30ish blocks per second for anyone working on this who might need the speed

**Comment by BillyGalbreath** [comment]
https://purpur.pl3x.net/docs/Configuration/#max-speed

That doesn't do what you think it does.

![image](https://user-images.githubusercontent.com/332527/127418824-b1a6b147-c08f-45a1-8952-360b3326bf63.png)

...

![image](https://user-images.githubusercontent.com/332527/127418868-bd13e6c9-2e2a-43c9-ad1a-0b7640dcfa1f.png)

You're looking for this one

https://purpur.pl3x.net/docs/Configuration/#boost-modifier

**Comment by helpimnotdrowning** [comment]
Changing the boost modifier and keeping the max-speed to 2 (which I found out is the max/what caps it at 107.6) only makes it take less time to hit the limit. Setting max-speed to 2 and boost-modifier to .1, 2, and 100 all still make it hit the limit.
