### ISSUE TITLE
Enderpearl not effected by blast

### ISSUE THREAD

**Issue by nimnot94** [pl3xgaming/Purpur#536]
### Expected behavior

The enderpearl should recive acceleration from tnt 

### Observed/Actual behavior

The enderpearl doesn't move no matter how much tnt u put next to it

### Steps/models to reproduce

U can build a TNT cannon and test it

### Purpur version

im just a user that tried purpur for the first time, don't own any server

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by TwoLeggedCat** [comment]
Probably https://github.com/PaperMC/Paper/issues/5429
