### ISSUE TITLE
[Feature Request] Built in chairs?

### ISSUE THREAD

**Issue by AZFire1** [pl3xgaming/Purpur#54]
**Feature Description:**
Maybe a built in chairs as Purpur already has so much to do with riding things and all. Sorry for all these feature requests, I'll stop after this.

**Comment by ghost** [comment]
Would indeed be a fitting addition to Purpur + a sit command.

**Comment by granny** [comment]
Already a thing as a separate plugin: 
https://github.com/pl3xgaming/EasyChairs
https://ci.pl3x.net/job/EasyChairs/

**Comment by ghost** [comment]
He meant built in not a plugin. To be fair its kinda something for a plugin, none the less fits well into Purpur.

**Comment by granny** [comment]
It's made by Billy, the same developer of Purpur. I understand that his suggestion is about having it built in. I was letting him know that Billy's implementation would be similar if not the same to the plugin he made.

**Comment by AZFire1** [comment]
Sounds good.
