### ISSUE TITLE
Players without purpur.place.spawner can still place default spawners

### ISSUE THREAD

**Issue by RhythmicSys** [pl3xgaming/Purpur#542]
### Expected behavior

If purpur.place.spawner isn't true, or is false, it's expected to be unable to place spawners at all

### Observed/Actual behavior

Players without the permission, can place spawners, it just changes to a default pig spawner. Spawner is functional.

### Steps/models to reproduce

Give user without any permissions a spawner
have them place it
it converts to a pig spawner

### Purpur version

This server is running Purpur version git-Purpur-1310 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d5017e9 on ver/1.17.1)
You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
That's intended design. In vanilla any player can place any spawner, but the game converts it to a pig spawner. The permission is for changing the type to the expected type, not to cancel placement.
