### ISSUE TITLE
[Feature Request] Add a config option to only ride (tamable mobs) if they are tamed.

### ISSUE THREAD

**Issue by AZFire1** [pl3xgaming/Purpur#56]
_Sorry for yet another feature request, though I just have many ideas and wanted to share._

**Feature Description:**
There could be a configurable option that is added per tamable mob which could be called "ridable-only-if-tamed" to allow riding mobs only if they are tamed. This could be useful (for example), if you wanted to restrict players from riding wolves/moving them somewhere if they haven't tamed them yet. Not sure if it's "needed" though. It's up to you.

**Comment by BillyGalbreath** [comment]
https://github.com/pl3xgaming/Purpur/blob/ver/1.16.2/patches/server/0119-Ridables.patch#L2293-L2298

**Comment by jpenilla** [comment]
I  think what they are asking for is actually a bit different. I think what they want is for [this line](https://github.com/pl3xgaming/Purpur/blob/de30a3e5e293a5ece224bac0bb2301095ad6ddbf/patches/server/0119-Ridables.patch#L2295) to be changed from
``if (tameable.isTamed() && !tameable.isOwner(entityhuman)) {``
to
``if (!tameable.isTamed() || !tameable.isOwner(entityhuman)) {``

I tested myself, and right now I can ride a wild wolf, or my own wolf, but I cannot ride a wolf tamed by another player. The requested behavior is that you can only ride the wolf if you have tamed it yourself. This could maybe be a config option for all tamable mobs, or a toggle for each? There are a couple different ways this could be implemented, but I don't think it's a bad idea.

**Comment by AZFire1** [comment]
Correct, yes that's what I meant jmanpenilla.
