### ISSUE TITLE
Armour hot swapping not respecting Curse of Binding.

### ISSUE THREAD

**Issue by wholenewmess** [pl3xgaming/Purpur#569]
### Expected behavior

Not being able to hot swap an item (using the armour-click-equip) function if the worn item has Curse of Binding.

### Observed/Actual behavior

You're able to remove items with Curse of Binding (if they're the same type of item) when you right click to hot swap.

### Steps/models to reproduce

Hot swap while wearing an item with Curse of Binding.

### Purpur version

[09.08 00:10:58] [Server] [INFO] This server is running Purpur version git-Purpur-1300 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cdc0e32 on ver/1.17.1)
[09.08 00:10:58] [Server] [INFO] You are 26 version(s) behind
[09.08 00:10:58] [Server] [INFO] Previous version: git-Purpur-1296 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I'm not using the latest version at the moment, but I went through the patches and it doesn't appear that this has been fixed. I am updating to the latest version now.

**Comment by encode42** [comment]
Closed in 5f7ab09ea67c74481582121430727a47dcea3fce
