### ISSUE TITLE
Crash the server with books and shulker

### ISSUE THREAD

**Issue by FastJoe0** [pl3xgaming/Purpur#571]
### Timings link

none

### Stack trace

```
https://paste.gg/p/FastJoe0/af3d44e6006743e098891a1e22fb0f8a
```

### Actions to reproduce (if known)

A players can make a server crash using a shulker filled all with copied books (books must be large, for example 100 pages).
Then if they click on the shulker the server stops responding.

### Purpur version

git-Purpur-1309 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by katekerllenevich** [comment]
The fix for this is to:

A) disable books.
B) change book size limits in paper.yml (which if you don't understand we will be happy to assist in our discord)
