### ISSUE TITLE
Mending only repairing items actively used

### ISSUE THREAD

**Issue by woodmichl** [pl3xgaming/Purpur#572]
### Timings link

https://timings.pl3x.net/?id=d67f5b1dd5324afba9a339bfd6d94e99

### Expected behavior

When having an item with the mending enchantment in my inventory it should be repaired on receiving EXP.

### Observed/Actual behavior

Instead I get the EXP added to my levels and nothing gets repaired unless I'm holding the item in my hand or left hand or have it equipped as armor. The problem is occuring both either with better-mending turned off or on

### Steps/models to reproduce

1. Enchant one or multiple items with mending.
2. Earn some EXP either with farming or EXP bottles

### Purpur version

git-Purpur-1327

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by sxphirus** [comment]
> Any items with Mending in the player's main hand, offhand, or armor slots that are not at maximum durability are repaired by experience orbs collected from any source. The rate of repair is two durability per point of experience contained in the orb. 

Source : https://minecraft.fandom.com/wiki/Mending

This is working as intended ^.^
