### ISSUE TITLE
Extreme lag spikes upon a player's death or first join

### ISSUE THREAD

**Issue by VRILGQD** [pl3xgaming/Purpur#580]
### Timings link

https://timings.pl3x.net/?id=2c1931e2ad7f43ab8079e21b11ba8040

### Description of issue

Before I tried to report on this issue on an outdated Purpur version (the last version of 1.16.5). But since now I've updated to 1.17.1 and the latest build, I think its time I solve this once and for all.

On my server when a player joins for the first time or dies, the TPS drops at a large amount for an unknown reason. After extensive research into it, I figured out that it is due to chunk loading. My world is about 460 GB (Its a 1:200 Earth Map) and from my hypothesis I think the lag is caused by the filesize of the map. 

The history of the lagspikes starts from a month ago when i updated my panel to Java 16 (Mojang was forcing people to do it for 1.17). Ever since then these lagspikes have been happening and none of my developers can figure out a way to patch it. So I want to ask anyone here if they know what could potentially be the source of the issue.

P.S. I originally thought BKCommonLib/TrainCarts and TNE were causing it, but the lag still occurs when I unload them from the server.

### Purpur version

git-Purpur-1328 (1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

The Spark report

https://spark.lucko.me/mlzTNEUiJW

**Comment by OmegaShaman** [comment]
UPDATE:

https://timings.pl3x.net/?id=acff9013859d4aec8dca261ba751c7d8

I made another timings report, and it seems that the issue has to do with Packets, specifically the value "net.minecraft.network.protocol.game.PacketPlayInClientCommand". If I know correctly, this has to be due to some sort of respawning plugin or feature that's causing massive amounts of packets.

**Comment by Euphillya** [comment]
Hello,

I am looking at your Spark report and I see that Dynmap is consuming a lot (34%), can you try to deactivate it and see if it happens again? I have never used Dynmap so I don't know how it works. 

org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call()33.95%

**Comment by OmegaShaman** [comment]
> Hello,
> 
> I am looking at your Spark report and I see that Dynmap is consuming a lot (34%), can you try to deactivate it and see if it happens again? I have never used Dynmap so I don't know how it works.
> 
> org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call()33.95%

Yeah, I was generating dynmap with that active, but even without it the packet value is really high.

**Comment by OmegaShaman** [comment]
heres a new timings report.

https://timings.pl3x.net/?id=7ccb7c9128e344a0b89cda7e8b1665f8

**Comment by BillyGalbreath** [comment]
This simply boils down to large amounts of work the server has to do when a player joins/teleports. Could be plugin induced, or even just a massive amount of chunks loading at once. Try lowering your view distance (that includes the no-tick) so less chunks have to load when a player joins/teleports.
