### ISSUE TITLE
Silk touch not working with mushroom block

### ISSUE THREAD

**Issue by NightLife-SG** [pl3xgaming/Purpur#582]
### Expected behavior

We suppoose to get mushrrom block using silk touch

### Observed/Actual behavior

Nothing is drop when mined with silk touch.

### Steps/models to reproduce

Used axe/shear/pickaxe with silk touch

Cant get mushroom block anyhow

### Purpur version

This server is running Purpur version git-Purpur-1328 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c8befee on ver/1.17.1)
You are 1 version(s) behind
Previous version: git-Purpur-1316 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Cannot reproduce

![image](https://user-images.githubusercontent.com/332527/129115618-daf881df-4f97-4e61-bb0c-4ae28cb022d5.png)

**Comment by LoneDev6** [comment]
It may be a plugin interfering, did you try removing all the plugins?

**Comment by emielderckx** [comment]
also tested on my server can not reproduce
