### ISSUE TITLE
allow-unsafe-enchants not working

### ISSUE THREAD

**Issue by znopp** [pl3xgaming/Purpur#583]
### Expected behavior

When enabled in purpur.yml, being able to put 2 max level books or items together in an anvil should make one, 1-higher-level book or item when merged.

### Observed/Actual behavior

Instead, putting two max tier items / books in an anvil and merging does not increase the enchantment level. 

### Steps/models to reproduce

Enable allow-unsafe-enchants in purpur.yml, turn off the server and turn it on again, and try to merge two items / books with a max tier enchant in an anvil.

### Purpur version

This server is running Purpur version git-Purpur-1329 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d1d6bc2 on ver/1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I have other plugins, here is the list:
Chatco
Coreprotect
Essentials (including Chat and Spawn)
Lifesteal-Smp-Plugin (kill someone, gain a heart)
Luckperms
OpenInv
SkQuery
Skript ( Currently loaded scripts: axr.sk)
SpigotPing
Vault

**Comment by BillyGalbreath** [comment]
This setting does not change the level logic in the server. It simply allows you to use enchantments where you otherwise couldn't (incompatible types together, on wrong items, etc)
