### ISSUE TITLE
Bypass-mob-griefing does not let zombies break doors.

### ISSUE THREAD

**Issue by VonSparq** [pl3xgaming/Purpur#587]
### Expected behavior

When the server is either on "hard" difficulty, or break-door-minimum-difficulty is set to "easy", and /gamerule mobGriefing is set to "false", setting bypass-mob-griefing: to "true" under "zombie" should allow them to bypass the mobGriefing gamerule and break down doors.

### Observed/Actual behavior

In the described conditions, the zombie stands in front of the door, unable to break it. Setting /gamerule mobGriefing to "true" allows them to break the door. so the gamerule is not being bypassed.

### Steps/models to reproduce

Download the latest version of Purpur.
Set difficulty to "hard" and bypass-mob-griefing: to "true" under "zombie".
Launch the server.
Run the command /gamerule mobGriefing flase.
Make a dark room so the zombie won't burn, divide it in half with a 2 block tall wall and put a door in the middle.
Spawn a zombie on one side, agro the zombie, go through the door and close it before the zombie goes through it.

![2021-08-12_19 43 00](https://user-images.githubusercontent.com/78357458/129243643-bba3cfe5-e298-4965-ba67-74991cebfdeb.png)

### Purpur version

[19:35:44 INFO]: Checking version, please wait...
[19:35:45 INFO]: This server is running Purpur version git-Purpur-1329 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d1d6bc2 on ver/1.17.1)
[19:35:45 INFO]: You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] My version of Minecraft is supported by Purpur.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by BillyGalbreath** [comment]
This one will be tricky to manage. The bypasses were designed to disable griefing where it was enabled, not really the other way around. I'll leave this ticket open until we can look deeper into this to see if its even fixable.

**Comment by BillyGalbreath** [comment]
Yeah, looking at this again there is no clean way to do what you are wanting here. Since the gamerule is set to `false`, there is nothing to bypass.
