### ISSUE TITLE
Boats placed on water sometimes sink

### ISSUE THREAD

**Issue by PiotrO15** [pl3xgaming/Purpur#590]
### Expected behavior

Boat should float on water after placing them

### Observed/Actual behavior

In some cases (as seen in the video posted below) boats just sink

### Steps/models to reproduce

Place a boat on water above Y: 65 or place it on tall seagrass

https://streamable.com/w8t9zw

### Purpur version

[18:07:42] [Server thread/INFO]: This server is running Purpur version git-Purpur-1330 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 158ae61 on ver/1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Not using any plugins, default config

**Comment by BillyGalbreath** [comment]
Upstream bug.

https://github.com/PaperMC/Paper/issues/6312

**Comment by BillyGalbreath** [comment]
Turns out Tuinity fixed this the other day. We've pulled in that fix with build 1331

https://github.com/pl3xgaming/Purpur/commit/635d108ae267993505a12e393f2fa8756899ddde
