### ISSUE TITLE
Portal linking is incredibly broken.

### ISSUE THREAD

**Issue by Apprisco** [pl3xgaming/Purpur#597]
### Expected behavior

portals within a 128 block radius are properly linked, and portal links aren't overridden by the creation of new portals nearby.

### Observed/Actual behavior

Creating portals will absolutely ruin everything, previous portal links will be ignored, and portals at y128 are created at y40, etc.

### Steps/models to reproduce

Latest version of purpur.
Place portal at y128, then teleport to the nether.
Place portal at the correct coordinates, and return via the portal.
Notice that these portals are linked.
Fly through the overworld portal again, and then back.
Purpur creates a new portal.

### Purpur version

This server is running Purpur version git-Purpur-1333 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d783ad7 on ver/1.17.1)
You are running the latest version
Previous version: git-Purpur-1332 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Not a Purpur bug. We dont touch the portal radius. Mojang and Paper changed it all up some time last year. Will have to take it up with them.

**Comment by Apprisco** [comment]
> Not a Purpur bug. We dont touch the portal radius. Mojang and Paper changed it all up some time last year. Will have to take it up with them.

Sigh, I meant that the distance is literally 0, and yet it keeps creating portals.
What's broken is Y heights in portal calculations.

**Comment by BillyGalbreath** [comment]
I know. Not my issue, though. I tried talking to Paper about this mess before, but it fell on deaf ears. Maybe if someone thats _not_ me talks to them they'll listen. Its been so long I dont even remember the specifics of the issue anymore. I just kinda moved on and learned to deal with it.

**Comment by Apprisco** [comment]
> I know. Not my issue, though. I tried talking to Paper about this mess before, but it fell on deaf ears. Maybe if someone thats _not_ me talks to them they'll listen. Its been so long I dont even remember the specifics of the issue anymore. I just kinda moved on and learned to deal with it.

Alright, I'll talk to them, but I just want to confirm if this is the issue you've tried to talk about.
https://streamable.com/0rresc

**Comment by Apprisco** [comment]
![image](https://user-images.githubusercontent.com/34324909/130115649-b4ad391c-9a4c-4a1f-a17e-26133b530588.png)
Welp, this is why I hate paper.

**Comment by BillyGalbreath** [comment]
Yup. Should never have mentioned Purpur. Welcome to my world.

**Comment by Xarius86** [comment]
Had this problem reporting an EssX bug the other day as well. "Did you try it on Paper?" as if Purpur was the problem.

**Comment by Apprisco** [comment]
> Yup. Should never have mentioned Purpur. Welcome to my world.

Just wondering though, is the video I sent pretty much the issue?

**Comment by BillyGalbreath** [comment]
One of many. Portals often screw up the Y so badly they end up at Y 0 or Y 128 and eat through the bedrock. Sometimes they stack on top of each other, or right next to each other. Sometimes they line up just right where they sync load too many chunks and crash servers. Its pretty bad.

**Comment by Apprisco** [comment]
> One of many. Portals often screw up the Y so badly they end up at Y 0 or Y 128 and eat through the bedrock. Sometimes they stack on top of each other, or right next to each other. Sometimes they line up just right where they sync load too many chunks and crash servers. Its pretty bad.

Rip any hope of using them properly to do some technical builds then, I'll just use my advanced portals
