### ISSUE TITLE
java.lang.IllegalStateException: Cannot add a chunk to a region which already has the chunk!

### ISSUE THREAD

**Issue by EuanM199** [pl3xgaming/Purpur#60]
**Describe the bug**
java.lang.IllegalStateException: Cannot add a chunk to a region which already has the chunk!

**To Reproduce**
Sadly not sure, was pregenerating with chunky, and it had finished, then it crashed the server

**Plugins**
[Screenshot](https://cdn.discordapp.com/attachments/716405933105872938/754045625045090324/unknown.png)

**Version**
Show the full output of `/version` here. ("latest" is not a version!)
[screenshot](https://cdn.discordapp.com/attachments/716405933105872938/754045278562156715/unknown.png)

**Additional context**
[crash-2020-09-11_11.59.40-server(1).txt](https://github.com/pl3xgaming/Purpur/files/5210920/crash-2020-09-11_11.59.40-server.1.txt)

Reported [here](https://github.com/pop4959/Chunky/issues/30) to Chunky, 

Note : had 3-5 people on and a dynmap surface render running, it was pregenerating A void world

**Comment by Spottedleaf** [comment]
Can you please add the flag `-Dtuinity.strict-thread-checks=true` to your jvm startup arguments? (This flag can just be placed before the memory settings) The flag should tell me whether the issue is due to asynchronous access or something else.

**Comment by EuanM199** [comment]
https://mcpaste.io/0f96df338b04c31d
here is the Server log,
i have now removed the flag, lmk if you need anything else

**Comment by EuanM199** [comment]
Also, dont worry about the betterend warnings, thats due to 1.15 backwards compatibility and causes no issues

**Comment by BillyGalbreath** [comment]
If you still have this issue, report it upstream to Tuinity. I can't fix this in Purpur
