### ISSUE TITLE
[Feature Request] Disable bed re-spawn messages.

### ISSUE THREAD

**Issue by AZFire1** [pl3xgaming/Purpur#61]
**Feature Description:**
I'm unsure if this would fit in Purpur at all, but I'd say it would be useful. The entire idea of this is to disable the "Respawn point set" message and the "Bed is obstructed" message. I personally don't/can't have these features on as a plugin like Essentials blocks setting respawn points with beds. While Essentials blocks this feature from working and overrides it with their (warps) feature they don't block the bed messages from being sent which tends to spam the chat. Not sure if this is possible to do, nor do I think it would necessarily fit Purpur though I think it could be useful to have.

**Comment by BillyGalbreath** [comment]
This message is client side. You can edit it using a resource pack
