### ISSUE TITLE
player_interacted_with_entity advancement trigger does not work on entities

### ISSUE THREAD

**Issue by kruthers** [pl3xgaming/Purpur#611]
### Expected behavior

The advancement to trigger when you right click an entity

### Observed/Actual behavior

Nothing happens, the advancement fails to trigger

### Steps/models to reproduce

1. Summon an non-ai villager (ai and non-ai is the same): `/summon minecraft:villager ~ ~ ~ {NoAI:1}`
2. Download the following datapack: [testing.zip](https://github.com/pl3xgaming/Purpur/files/7062842/testing.zip)
3. Right click on the villager and you should see 2 chat message when the advancement triggers.

### Purpur version

This server is running Purpur version git-Purpur-1336 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c82d29a on ver/1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by kruthers** [comment]
I have done some more invistegation, the bug is caused by the ridable pach, when you are not able to ride a entity, the event is not getting passed, causing the advancement trigger to not be called. If you enable ridable entities and give yourself permissions to ride it, when you click it the advancement is now called.

**Comment by BillyGalbreath** [comment]
I see the issue here. The criterion only triggers if the interaction was consumed. My ridables patch returns either success or pass, never consume. I'll have to add the consume in where it's supposed to be, but this will take some time.

**Comment by InsaanNotFound** [comment]
Any update on this issue? @BillyGalbreath
