### ISSUE TITLE
Phantom burn-in-light not work

### ISSUE THREAD

**Issue by DoreK333** [pl3xgaming/Purpur#613]
### Expected behavior

Phantoms should be burned when the light level is equal to or higher than the set light level in config.

### Observed/Actual behavior

After updating to 1.17.1, the option to burn phantoms by the light has stopped working (phantoms will not burn). 
https://purpur.pl3x.net/docs/Configuration/#burn-in-light

### Steps/models to reproduce

1. Set https://purpur.pl3x.net/docs/Configuration/#burn-in-light to 8
2. /time set night
3. Place torches
4. /spawnmob phantom
5. Phantoms should burn...

### Purpur version

This server is running Purpur version git-Purpur-1346 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: a2fb41a on ver/1.17.1)
You are running the latest version
Previous version: git-Purpur-1291 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by itsMarkiS** [comment]
im having the same issue, and also, when deactiving burn in daylight doesnt work
i tried to make them burn in lanterns/glow light but not in daylight
