### ISSUE TITLE
Colors do not convert on pages with purpur.book.color.sign enabled

### ISSUE THREAD

**Issue by RhythmicSys** [pl3xgaming/Purpur#624]
### Expected behavior

Color codes on pages to turn text colorful while purpur.book.color.sign is enabled, after the book has been signed.

### Observed/Actual behavior

Only colors the title text, the page text remains the same
![image](https://user-images.githubusercontent.com/45906780/131239301-344a08c1-4b3c-4455-a54d-b59a45a7b7e0.png)

![image](https://user-images.githubusercontent.com/45906780/131239291-0424cef3-3bab-4396-afeb-05cd769331a8.png)

### Steps/models to reproduce

Have the purpur.book.color.sign permission, without the edit permission
write a book with color codes inside
sign it

### Purpur version

This server is running Purpur version git-Purpur-1351 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8fc7931 on ver/1.17.1)
You are running the latest version
Previous version: git-Purpur-1350 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
If you want the book contents to allow color codes, you have to give the `edit` permission. The `sign` permission is for the text involved when _signing_ a book, like the title and author (not the contents)
