### ISSUE TITLE
Cannot tick distance manager while unloading playerchunks

### ISSUE THREAD

**Issue by LucidAPs** [pl3xgaming/Purpur#631]
### Expected behavior

No errors?

### Observed/Actual behavior

Console Error https://nekobin.com/wububumiro
![image](https://user-images.githubusercontent.com/42933023/131344695-2ade3013-e38b-4bda-8007-629d23d61d63.png)

### Steps/models to reproduce

I am not sure, I think the dev of quick shop is just sifting the blame?

### Purpur version

patched_1.17.1.jar:git-Purpur-1355

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Paper recently added this check into the server. Falls on the plugin dev to fix their plugin.

<https://github.com/PaperMC/Paper/blob/master/patches/server/0753-Do-not-allow-ticket-level-changes-while-unloading-pl.patch#L26>
