### ISSUE TITLE
suppress-unrecognized-recipe-errors: true causing invalid player data

### ISSUE THREAD

**Issue by RhythmicSys** [pl3xgaming/Purpur#636]
### Expected behavior

suppress-unrecognized-recipe-errors: true to supress the recipe errors

### Observed/Actual behavior

Blocks users from joining if they have old recipes in their data, message:
lost connection: Invalid player data

### Steps/models to reproduce

purpur 1350 or later with suppress-unrecognized-recipe-errors: true 
custom recipes (I tested with a datapack, unsure if it happens with plugin recipes)
users with those recipes loaded (logged in, did /recipe give *)
stop server, remove datapack/recipes
start server
attempt to log in
![image](https://user-images.githubusercontent.com/45906780/131410836-c4ed64cd-9af2-475b-9c87-046af2f2aba1.png)

### Purpur version

This server is running Purpur version git-Purpur-1356 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 759a038 on ver/1.17.1)
You are running the latest version
Previous version: git-Purpur-1351 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

reverting the setting to 'false' allows the user to relog.
Full log of this test:
[latest.log](https://github.com/pl3xgaming/Purpur/files/7079816/latest.log)

**Comment by katekerllenevich** [comment]
Can you reproduce with suppress-unrecognized-recipe-errors: false?

**Comment by RhythmicSys** [comment]
suppress-unrecognized-recipe-errors: false does not cause any issues. It behaves as normal, your console floods with unrecognized recipe errors, and the user joins. 
suppress-unrecognized-recipe-errors: true prevents the errors in console by preventing the user from entering the server entirely

so, I guess the answer is no? Cause it's not an issue that would occur with it on false cause the issue is with it being on true? Sorry I'm not entirely sure how to answer that question
