### ISSUE TITLE
[Feature Request] AFK Sugguestions

### ISSUE THREAD

**Issue by fredagsguf** [pl3xgaming/Purpur#66]
Hi, i think the AFK system is lacking a bit - don't get me wrong its really nice and also nice to hook into, but i'd like more options e.g an option to make it change the tab suffix of a player instead of tab prefix.
maybe make it sort all AFK lowest on scoreboard, could be done by hooking into nametagedit?

Maybe also a option to execute commands when a player is set as afk?

Not sure i'm asking the right place but oh well...

**Comment by BillyGalbreath** [comment]
The AFK system isn't meant to be fancy. I've included the needed plugin API to the system for anyone to enhance as they see fit by using a plugin
