### ISSUE TITLE
Phantoms burn in daylight with `phantom.burn-in-daylight: false`

### ISSUE THREAD

**Issue by itsMarkiS** [pl3xgaming/Purpur#660]
### Expected behavior

Phantoms to not burn in daylight with `phantom.burn-in-daylight: false`

### Observed/Actual behavior

Phantoms still burn in daylight with `phantom.burn-in-daylight: false`

### Steps/models to reproduce

1) set `phantom.burn-in-daylight: false` in purpur.yml
2) /time set noon
3) /summon phantom
4) watch it burn

### Purpur version

[21:49:42 INFO]: Checking version, please wait...
[21:49:43 INFO]: This server is running Purpur version git-Purpur-1385 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 529daae on ver/1.17.1)
[21:49:43 INFO]: You are running the latest version
[21:49:43 INFO]: Previous version: git-Purpur-1377 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
`0b` represent a false boolean, and `1b` represents a true boolean. So, naturally if you have the option set to false it will set this nbt tag to false, and vice versa..

**Comment by itsMarkiS** [comment]
> `0b` represent a false boolean, and `1b` represents a true boolean. So, naturally if you have the option set to false it will set this nbt tag to false, and vice versa..

bruh... it never sets it to false, thats the problem!!! its not working, no maters if the option is false or true

**Comment by BillyGalbreath** [comment]
Updated this ticket with actual relevant information and reproduction steps. Removed all the confusing talk about NBT datas.

**Comment by itsMarkiS** [comment]
This server is running Purpur version git-Purpur-1502 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0494fff on HEAD)
You are running the latest version
Previous version: git-Purpur-1498 (MC: 1.18.1)

not working again....
