### ISSUE TITLE
Being in a boat, getting kicked out due to flying when not flying

### ISSUE THREAD

**Issue by TheRedXD** [pl3xgaming/Purpur#672]
### Timings link

https://timings.aikar.co/?id=8b7bd110fdac4960928d0925a3073efd

### Expected behavior

Just regular boat usage

### Observed/Actual behavior

Being kicked for flying while in a boat when not flying (only happens on purpur)

### Steps/models to reproduce

It has to do with boats. This only happens on purpur but not paper. Might be something to do with high ping, so you might want to use a client or a mod with tries to reproduce high ping (pingspoofing). You want to try to move around with the boat, I'm not exactly sure how to do it. Please check both the mentioned below purpur version as well as the newest one to see if its patched.

### Purpur version

This server is running Purpur version git-Purpur-1383 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6856a5d on ver/1.17.1)
You are 8 version(s) behind
Previous version: git-Purpur-1378 (MC: 1.17.1)

### Agreements

- [ ] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Unfortunately, the 1st agreement isn't correct, since I can't update the version at this time.

**Comment by Pantera07** [comment]
https://bugs.mojang.com/browse/MC-98727
