### ISSUE TITLE
All water animals just fly down at lightspeed

### ISSUE THREAD

**Issue by Tjibbe01** [pl3xgaming/Purpur#673]
### Timings link

https://timings.pl3x.net/?id=7a27777e13604bd580494b17db45351e

### Expected behavior

Randomly water mobs just fly down while swimming and die

### Observed/Actual behavior

https://user-images.githubusercontent.com/47983188/133835981-efcfb4cf-1c6d-447e-8ca6-081fd9984c88.mp4

### Steps/models to reproduce

Wait in water and it should happen

### Purpur version

This server is running Purpur version git-Purpur-1391 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8096340 on ver/1.17.1)
You are running the latest version
Previous version: git-Purpur-1385 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by encode42** [comment]
Could you attempt to reproduce this issue on [Airplane](https://airplane.gg)? They recently made some changes relating to entities and water

**Comment by PaulBGD** [comment]
This is absolutely hilarious, but should be fixed with https://github.com/TECHNOVE/Airplane/commit/a74424ab0212a924c7ef921bfb7ec143c874cba4
