### ISSUE TITLE
Cannot dump mySQL using direct access method [jdbc]

### ISSUE THREAD

**Issue by James-P-Bennett** [pl3xgaming/Purpur#677]
_No content available._

**Comment by Euphillya** [comment]
Hello,

It is not for Purpur to fix this but for the plugin you are using. Contact the EasyBackup developer to update their connector.

**Comment by encode42** [comment]
As above, this is an issue the plugin authors must deal with. The old connector has vulnerabilities that should be dealt with rather than looked over.
