### ISSUE TITLE
API Issue Downloading PurPur.jar

### ISSUE THREAD

**Issue by Boastful1353** [pl3xgaming/Purpur#679]
### Timings link

not relevant for this issue

### Expected behavior

My server is set to automatically update daily using AMP from cubecoders and the Purpur API. I have brought the issue to them and was told your API broke or changed Please See https://github.com/CubeCoders/AMP/issues/500

### Observed/Actual behavior

Purpur does not download correctly and refuses to start.

### Steps/models to reproduce

Run the update command from AMP to trigger the Purpur API Download of purpur.jar

### Purpur version

This server is running Purpur version git-Purpur-1393 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3ff85ed on ver/1.17.1)
You are running the latest version
Previous version: git-Purpur-1390 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

https://github.com/CubeCoders/AMP/issues/500

**Comment by BillyGalbreath** [comment]
As per the announcement from months ago, the v1 download api has been deprecated for some time now and that everyone needed to switch to v2 api. Two days ago another announcement was made that v1 is no longer in service, and v2 is now mandatory.

Amp (@PhonicUK) apparently didn't receive these notices, or chose to ignore them.
