### ISSUE TITLE
Items still dropping in PlayerDeathEvent when setKeepInventory set to true

### ISSUE THREAD

**Issue by YouHaveTrouble** [pl3xgaming/Purpur#681]
### Timings link

https://timings.aikar.co/?id=86cc39aae73546bf979ea5719ec4ae62

### Expected behavior

Items are kept in the inventory and do not drop to the ground.

### Observed/Actual behavior

Player keeps the items, but they also get dropped on the ground.

### Steps/models to reproduce

1. Write small plugin listening to PlayerDeathEvent
2. `event.setKeepInventory(true);`
3. Die.

### Purpur version

This server is running Purpur version git-Purpur-1393 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3ff85ed on ver/1.17.1)
 You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
You have to clear the dropped list in the event, too. This is a thing all the way up the fork chain to whoever wrote that API in the first place.
