### ISSUE TITLE
Items cannot be dropped when using inventory

### ISSUE THREAD

**Issue by TheCiROMG** [pl3xgaming/Purpur#682]
### Expected behavior

I was hoping to see that the item was thrown away

### Observed/Actual behavior

But automatically, it returns to inventory

### Steps/models to reproduce

1) Delete the configuration files / Use already configured
2) Start the server
3) Get into survival
4) Try to drop an item from inventory

### Purpur version

Purpur 1393 - Minecraft 1.17.1

This happened in 3 previous versions (I cannot confirm it)

### Agreements

- [x] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by YouHaveTrouble** [comment]
Timings link is a field in bug reporting for a reason.

Do you have any plugins? Can you reproduce on a fresh server without any?

**Comment by TheCiROMG** [comment]
I can assure you that the plugins work perfectly, we use them for months, and their updates do not touch anything that has to do with the gameplay in the sense of grabbing or throwing things, right now I will pass the timings, I apologize for not putting it, it is I made the report very fast

**Comment by YouHaveTrouble** [comment]
Please just try reproducing on a clean server without plugins.

**Comment by TheCiROMG** [comment]
Timings Here : https://timings.pl3x.net/?id=1a9ee122d83f415e9e5dc65a3eadadd9

**Comment by YouHaveTrouble** [comment]
Yep. Like I said, you have multiple plugins that might cause the issue, please reproduce on clean server.

**Comment by TheCiROMG** [comment]
On a clean server it works fine, now I'm seeing what it is, which one do you recommend taking out?

**Comment by TheCiROMG** [comment]
The problem is due to the WorldGuardGUI plugin

It has been withdrawn and it is solved

Here link of the plugin in question: https://www.spigotmc.org/resources/worldguardgui-1-8-8-1-17-1.95870/

**Comment by katekerllenevich** [comment]
Also we don't support piracy here.
