### ISSUE TITLE
Compass boss bar remains visible when dropping compass or switching hands

### ISSUE THREAD

**Issue by JLyne** [pl3xgaming/Purpur#689]
### Timings link

https://timings.pl3x.net/?id=c42dfc8ee0044dbe87041b260feb63ca#timings

### Expected behavior

Dropping a held compass with `item.compass.holding-shows-bossbar` enabled hides the bossbar, just like when switching to a different item. Swapping hands to place the compass in your offhand should either keep the bossbar visible or hide it correctly.

### Observed/Actual behavior

The bossbar remains visible after dropping the compass:
![image](https://user-images.githubusercontent.com/4615316/134818052-7c950411-dc50-4f18-8cc1-216aca3b3048.png)

Swapping hands causes the bossbar to become visible whenever the first hotbar slot is active:
![image](https://user-images.githubusercontent.com/4615316/134818157-ee803854-6d63-4864-9e3b-ed4542dea3fa.png)
![image](https://user-images.githubusercontent.com/4615316/134818334-408ac910-2098-490b-994a-9ecb00f74141.png)

(To be clear `/compass` wasn't used at any point)

### Steps/models to reproduce

- Enable  `item.compass.holding-shows-bossbar` 
- Get and hold a compass
- Drop it in any of the usual ways
- Observe how the bossbar remains visible
- Pickup the compass again and then swap it to your offhand
- Observe how the bossbar will become visible whenever the first hotbar slot is selected

### Purpur version

    [18:43:23 INFO]: This server is running Purpur version git-Purpur-1394 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1- 
    SNAPSHOT) (Git: acb8a26 on ver/1.17.1)
    [18:43:23 INFO]: You are running the latest version
    [18:43:23 INFO]: Previous version: git-Purpur-1166 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Tested and able to reproduce without plugins

**Comment by BillyGalbreath** [comment]
Confirmed.

This happens because I don't listen to any events (those are plugin API only). Instead, the compass itself is ticking when in hand. Dropping it needs to fire 1 extra tick for my logic to run, which isn't possible so I'll have to find somewhere to check for dropping the compass and remove the bossbar.

As for the offhand thing, I'm not sure what's up with that. It should be ticking just the same. I'll have to look deeper into that one.
