### ISSUE TITLE
Enderman Melon farm

### ISSUE THREAD

**Issue by ghost** [pl3xgaming/Purpur#690]
### Expected behavior

Enderman Can carry watermelons

### Observed/Actual behavior

My player has built Enderman Melon farm
But Enderman will not move Melon
Is it a bug?

### Steps/models to reproduce

https://user-images.githubusercontent.com/75075197/134820911-992386ed-e504-4303-aef1-066fdf936120.mp4

### Purpur version

![擷取](https://user-images.githubusercontent.com/75075197/134820927-8243fdd5-8c0a-47c5-a19b-fe8ef3ed55d8.PNG)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Purpur doesn't change anything about what an enderman can and cannot pickup. That is 100% controlled by datapacks using the `enderman_holdable` block tag.

https://minecraft.fandom.com/wiki/Tag#blocks_enderman_holdable
