### ISSUE TITLE
Purpur seed change not working

### ISSUE THREAD

**Issue by Pantera07** [pl3xgaming/Purpur#691]
### Expected behavior

> https://purpur.pl3x.net/docs/Configuration/#seed
> The default value is -1 for "use the world seed". anything not -1 will be a custom seed. it can accept any Integer value (-2147483648 to 2147483647)

> https://discord.com/channels/685683385313919172/685683773953540160/883039657435217960
> We have kept our structure seed patch, so you will still keep the buried_treasure, mineshaft, and stronghold options under the settings.seed.structure section of purpur.yml

I changed the buried_treasure, mineshaft, stronghold seeds.

### Observed/Actual behavior

Same as the structure location of buried_treasure, mineshaft, stronghold from https://www.chunkbase.com/apps/seed-map. The seed has not changed.

### Steps/models to reproduce

Change the Purpur seed and reset the world.
And look at the location at https://www.chunkbase.com/apps/seed-map and try tp.
This is very easy to reproduce.

I reported this on Discord, but it was ignored.
I do not misreport or lie. Trust me and just try it.

### Purpur version

This server is running Purpur version git-Purpur-1394 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: acb8a26 on ver/1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by IceWaffles** [comment]
I had this issue too a while ago, never checked up on it. Dunno if it's already fixed or something.

**Comment by emielderckx** [comment]
Paper now has almost all seed features. I recommend checking there docs. 👍

**Comment by IceWaffles** [comment]
We're referring to structure seeds; the feature seeds from Purpur before and Paper now have always worked fine

**Comment by IceWaffles** [comment]
Hey, I forgot this issue existed. I just made another issue about this... I forgot this was for structure seeds too-

**Comment by katekerllenevich** [comment]
We are using the same method as spigot for this, try and reproduce on spigots seeds?

**Comment by IceWaffles** [comment]
> We are using the same method as spigot for this, try and reproduce on spigots seeds?

Well, spigot seeds work perfectly fine. I tested them out-I distinctly remember testing ocean monuments and villages. They not only spawn in a completely different area, but the way they're generated often look different as well.
