### ISSUE TITLE
RAM clogging

### ISSUE THREAD

**Issue by ghtg** [pl3xgaming/Purpur#699]
### Timings link

https://timings.pl3x.net/?id=dca17cebf71d42849eec3549852f13b8

### Description of issue

RAM clogging
When server is running, the RAM is periodically clearing (
![image](https://user-images.githubusercontent.com/21358664/135796368-db41193f-7f28-4a7b-83bf-41c275734ae4.png)
), but over time, more and more memory is used with each cleanup by a small amount. Because of this, server can't running all day! While I had all the RAM clogged, I made a heapdump, and here are the results of a memory leak: more than 90% is occupied by this class.
![image](https://user-images.githubusercontent.com/21358664/135796894-2778f023-8d5f-40ad-ba28-b596c1732612.png)

### Purpur version

[08:46:31 INFO]: Checking version, please wait...
[08:46:32 INFO]: This server is running Purpur version git-Purpur-1400 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 144a08e on ver/1.17.1)
[08:46:32 INFO]: You are running the latest version
[08:46:32 INFO]: Previous version: git-Paper-"81d89f6" (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I think you can add special parameter in purpur, that cleans memory, occupied by this class. Thank you.

**Comment by encode42** [comment]
We don't support offline mode servers. Additionally, it does not appear as though this issue is caused by Purpur.
