### ISSUE TITLE
Persistent tile entity names don't always persist.

### ISSUE THREAD

**Issue by Xevolu** [pl3xgaming/Purpur#704]
### Timings link

https://timings.pl3x.net/?id=a356c665c9f842bea96bcc970cd582c5

### Expected behavior

I expected that player heads always keep their display names (and lore tags) when `persistent-tileentity-display-names-and-lore` (in purpur.yml) is set to `true`, even if they are destroyed by flowing water or something similar.

### Observed/Actual behavior

Player heads keep their display names and lore tags when destroyed by a player. However, the name and lore are lost when the head is destroyed by flowing water. This happens when the head is renamed using an anvil or by a plugin.

### Steps/models to reproduce

1. Set `persistent-tileentity-display-names-and-lore` to `true` in purpur.yml.
2. Give yourself a player head and rename it with an anvil or with commands.
3. If you place it down on a solid block (like a grass block) the name will stay.
4. However, if you place it down and break it with flowing water, the name will be gone.

https://user-images.githubusercontent.com/82513800/136690446-ae33faa2-ead4-4aff-9c1e-39b2f890f0c5.mp4

### Purpur version

```
> version
[11:03:35 INFO]: This server is running Purpur version git-Purpur-1404 (MC: 1.17.1)
  (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: ad6f2f5 on ver/1.17.1)
[11:03:35 INFO]: You are running the latest version
```

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Confirmed.

Sounds like we've missed a few spots where items can be broken. I'll take a deeper look and see why this is happening.
