### ISSUE TITLE
Players on my server can't pillar jump (but I can)

### ISSUE THREAD

**Issue by luciobortoletto** [pl3xgaming/Purpur#725]
### Expected behavior

I expected to see the other players on my server pillar jumping.

### Observed/Actual behavior

The players that try to pillar jump take damage and fall. But that doesn't happen to me (the server owner).

### Steps/models to reproduce

1. Host a server on the pc where you play.
2. Ask the players on the server to pillar jump.
3. The players take damage and fall.

### Purpur version

> version
[21:22:39 INFO]: Checking version, please wait...
[21:22:40 INFO]: This server is running Purpur version git-Purpur-1415 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2df73e0 on ver/1.17.1)
[21:22:40 INFO]: You are running the latest version
[21:22:40 INFO]: Previous version: git-Purpur-1414 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Sorry for the bad english...

**Comment by encode42** [comment]
Not sure what pillar jumping is, could you provide a link?

Also a timings link would be useful to sus out any problematic plugins.

**Comment by Zeronic76** [comment]
https://minecraft.fandom.com/wiki/Tutorials/Pillar_jumping

**Comment by luciobortoletto** [comment]
What is a timings link?

**Comment by encode42** [comment]
Run the command `/timings paste` and return with the link it provides, it lets us see your plugins and server configuration to ensure they're not the issue.

I don't believe its an issue with Purpur, since pillaring (or pillar jumping, a term I learned today) is such a common action, and I haven't seen anyone else with the issue.

**Comment by luciobortoletto** [comment]
I never had this problem before, but I found out it's AntiCheat Reloaded's fault. Thanks for the help!
