### ISSUE TITLE
Client spams warnings for bat not having attribute minecraft:generic.flying_speed

### ISSUE THREAD

**Issue by mibby** [pl3xgaming/Purpur#728]
### Timings link

https://timings.pl3x.net/?id=7f2d96d1f84049a2a9bad8bd74e7a196

### Expected behavior

Client log to not spam errors for a bat entity not having a specific attribute.

### Observed/Actual behavior

The client seems to spam warnings for the bat entity not having the flying_speed attribute.

```
[23:02:59] [Render thread/WARN]: Entity bdt['Bat'/3378, l='ClientLevel', x=3607.50, y=30.00, z=504.50] does not have attribute minecraft:generic.flying_speed
```

This occurs hundreds of times for me in a short time period just by flying around my overworld.

### Steps/models to reproduce

* Fly around an older pre-generated overworld ``world`` for a minute.
* Open client latest.log and see the warning has occurred hundreds of times.

### Purpur version

Purpur version git-Purpur-1417 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

purpur.yml mobs section:
```
      bat:
        takes-damage-from-water: false
        ridable: false
        ridable-in-water: false
        ridable-max-y: 256.0
        attributes:
          max_health: 6.0
```

Related?
https://github.com/pl3xgaming/Purpur/issues/13#issuecomment-605427930

Seeing as how Tuinity is now merged into Paper, is this issue catchable so bats that don't have the necessary flying attribute can be set with it? Or any workaround to prevent the client from just spamming errors?

Bat flying speed is set in the configurable entity base attributes patch but there's no config option generated for it by default.
https://github.com/pl3xgaming/Purpur/blob/69c7c31f9a5c115693adf3b09088d17c2be18118/patches/server/0008-Configurable-entity-base-attributes.patch#L1445

It's also all over the ridables patch in a few places for generic flying speed, but I don't have ridables enabled.
https://github.com/pl3xgaming/Purpur/blob/69c7c31f9a5c115693adf3b09088d17c2be18118/patches/server/0007-Ridables.patch#L4037

**Comment by BillyGalbreath** [comment]
It's just a generic warning that can safely be ignored. If it does bother you enough (like it does me) you can patch it out in the client the way I do in [PurpurClient](https://github.com/pl3xgaming/PurpurClient/blob/master/src/main/java/net/pl3x/fabric/purpurclient/mixin/MixinClientPlayNetworkHandler.java#L53-L54). There is nothing I can do server side to stop it, other than rip out the Ridables patch.

**Comment by mibby** [comment]
Is it not possible to unregister all changes in the Ridables patch if it is toggled off / not used? Or just not load the patch with a config toggle? I'd really like to avoid maintaining my own fork just to rip out the patch and not everyone is going to resort to using your PurpurClient.

Spamming the client hundreds of times a minute with warnings can't be great. :(
