### ISSUE TITLE
Thread Netty Epoll Server IO #0 failed main thread check: Chunk getEntities call

### ISSUE THREAD

**Issue by ActuallyVieja** [pl3xgaming/Purpur#736]
### Timings link

https://timings.pl3x.net/?id=7dc258ee8dd943b495b06a5de85380e1

### Expected behavior

Not to see the Console being spammed by the error showed on this Pastebin 

### Observed/Actual behavior

I´ll Just leave the Pastebin:
(https://pastebin.com/VXuDEAkn)

### Steps/models to reproduce

It just paste it in the console with any action, either with the server empty or full. 

### Purpur version

[18:49:06 INFO]: Checking version, please wait...
[18:49:06 INFO]: This server is running Purpur version git-Purpur-1421 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 983ed96 on ver/1.17.1)
[18:49:06 INFO]: You are running the latest version
[18:49:06 INFO]: Previous version: git-Purpur-1415 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

This issue has no impact on Gameplay (as far as i can see), it just makes it extremely hard to work with console.

**Comment by BillyGalbreath** [comment]
This is caused from a plugin doing something it shouldn't be doing asynchronously. Spigot added the async catchers, and we have no plans of removing them.

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/CraftBukkit-Patches/0006-Async-Operation-Catching.patch

**Comment by ActuallyVieja** [comment]
Thanks Billy! Sorry for the Issue thread.
