### ISSUE TITLE
[Bug] Able to edit/break signs in protected areas/blocks

### ISSUE THREAD

**Issue by AZFire1** [pl3xgaming/Purpur#75]
**Describe the bug**
If you are using the sign editing feature and have some plugin protecting signs (such as lockette, chestshop, worldguard etc..) you will notice that if you have the correct permissions for editing signs (and are not Operator and are in a protected area or block) you can edit signs that you aren't supposed to (and effectively break locked blocks from lockette or change prices on chestshop shops)

**To Reproduce**
Turn on the sign editing feature in purpur.yml
Give yourself correct permissions to use it.
Make sure you have some sort of a protected area/block and signs there.
Remove operator from yourself.
Attempt editing a sign inside the protected area.
Notice you can edit signs. (Or break lockette signs and chestshop signs)

**Screenshots or Videos**
None.

**Plugins**
https://paste.helpch.at/zemahihawo.css

**Version**
25.09 22:09:19 [Server] INFO This server is running Purpur version git-Purpur-768 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
As far as I know the feature for sign editing only exists in Purpur.

**Additional context**
None.

**Comment by BillyGalbreath** [comment]
Are you sure the signs are actually being edited, or is this just a client desync? Try relogging after you think you've edited a sign you have no access to. Editing the sign calls the same events as originally placing a sign, so any protection plugins should be able to pick up on this and prevent editing protected signs (works on my own server, last I tested)

**Comment by AZFire1** [comment]
Hmm, well (after some testing) this seems to only be an issue with the plugin called "LockettePro". I tested with other (sign) protection plugins and the result of "editing" the signs ended up being what you said, it was only client side. It looks like LockettePro seems to actually edit/change it's "protected" signs. I suppose I'll go ahead and report this over at LockettePro then. Thanks for the info & help.
