### ISSUE TITLE
GC problem when going throught netherportal

### ISSUE THREAD

**Issue by MrEDok** [pl3xgaming/Purpur#753]
### Timings link

-

### Description of issue

When going throught netherportal multiple time like in the video it seem like there memory problem like in the chat using /spark gcmonitor

i will do more testing locally and on server to see if i can reproduce it 100% all the time or not.
https://streamable.com/jrum29

Spark heapsum: https://spark.lucko.me/lWNfyuBXzJ

have try with paper/purpur
java 16/17

### Purpur version

[00:45:15 INFO]: This server is running Purpur version git-Purpur-1427 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8bb5a93 on ver/1.17.1)
[00:45:15 INFO]: You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by katekerllenevich** [comment]
Issue opened upstream PaperMC/Paper#7098
