### ISSUE TITLE
Huge Ram Consumption ! Here is Suspectes Report:

### ISSUE THREAD

**Issue by el211** [pl3xgaming/Purpur#755]
### Timings link

https://timings.aikar.co/?id=88e11d9391a14012ae5c8cbaa3a4e8ba

### Description of issue

My server RAM Is Going UP TO 32 GB my maximum amount then server crashes , this server is meant to take a maximum of 3 gb 
its actually going up to 32 
i tried some tweaks that can find issue of that leak and here the results (images attached):
![result1](https://user-images.githubusercontent.com/86126606/142768473-81312376-1057-45c8-b59b-7ecb40038568.png)
![result2](https://user-images.githubusercontent.com/86126606/142768499-9531c8eb-19d0-4aa9-9961-c011528e7c6b.png)

i hope i can get a fix for those

RUNNING 1.17.1

### Purpur version

[16:36:58 INFO]: This server is running Purpur version git-Purpur-1427 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8bb5a93 on ver/1.17.1)
[16:36:58 INFO]: You are running the latest version
[16:36:58 INFO]: Previous version: git-Paper-384 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by encode42** [comment]
What's your launch arguments?

**Comment by el211** [comment]
> What's your launch arguments?

java -Xms128M -Xmx32768M -Dterminal.jline=false -Dterminal.ansi=true -jar purpur.jar

**Comment by encode42** [comment]
Well there's the issue, you're giving the server 32gb of ram to use. Java will naturally use all of the ram you give it, so reduce your xmx value.

**Comment by el211** [comment]
> Well there's the issue, you're giving the server 32gb of ram to use. Java will naturally use all of the ram you give it, so reduce your xmx value.

how much i will reduce it to ?

**Comment by encode42** [comment]
As much as you want your server to consume. 3gb of ram is ~3000M

**Comment by el211** [comment]
cz usually my preivous server i gave 16 gb on pterodactyl , it was only using 3

> As much as you want your server to consume. 3gb of ram is ~3000M

**Comment by el211** [comment]
but now its going more then 3 so i made the test to see memory leaks and i found those ^^

**Comment by encode42** [comment]
That's for you to figure out as we're not sure what your setup is. Either way, the issue isn't with Purpur, rather the amount of ram you're giving Java.
