### ISSUE TITLE
False inscription about the old version

### ISSUE THREAD

**Issue by VladimirIAlexandrov** [pl3xgaming/Purpur#766]
### Timings link

https://drive.google.com/file/d/1X977oMJGax_iyfOaSddj1Mpgxe1GtAkq/view?usp=sharing

### Expected behavior

This message should not be when entering from 1.18

### Observed/Actual behavior

False label about the old version when viewed in the server list

### Steps/models to reproduce

https://drive.google.com/file/d/1X977oMJGax_iyfOaSddj1Mpgxe1GtAkq/view?usp=sharing

### Purpur version

[13:05:59 INFO]: This server is running Purpur version git-Purpur-1430 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 5cbd2c7 on HEAD)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by encode42** [comment]
This could be caused by a plugin such as ViaVersion, but you haven't provided a timings link for us to look over.
