### ISSUE TITLE
Lectern bugs the player out

### ISSUE THREAD

**Issue by Ingemaru** [pl3xgaming/Purpur#767]
### Timings link

https://timings.aikar.co/?id=705e86b90bf6460086fe7850408aa721

### Expected behavior

You should be able to walk over Lectern.

### Observed/Actual behavior

Getting stuck unable to move.

### Steps/models to reproduce

If you walk over or by a Lectern with ur character you get stuck or start to lag.

### Purpur version

git-Paper-25

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by encode42** [comment]
> git-Paper-25

Looks like this is meant for [Paper's issue tracker](https://github.com/PaperMC/Paper/issues/new/choose).

In fact, it's [already been reported to them](https://github.com/PaperMC/Paper/issues/7043).
