### ISSUE TITLE
Strange characters in log file

### ISSUE THREAD

**Issue by x1p** [pl3xgaming/Purpur#77]
**Describe the bug**
Since purpur 764, I have these strange characters in the log on a everything a couple plugins do.
I think commit https://github.com/pl3xgaming/Purpur/commit/4895a88416867441128121a3c4d1157e4415850e is responsible for this.
I have the following flags added a year ago to prevent other strange characters.
`-Dterminal.jline=false -Dterminal.ansi=true`
Most plugins don't have it, some do.

**To Reproduce**
1. Default test server with purpur > 764
2. Start with e.g. LuckPerms
3. Read log
4. Check for something like:
```
[14:22:18] [Server thread/INFO]:         __    [0m
[14:22:18] [Server thread/INFO]:   |    |__)   LuckPerms v5.1.93[0m
[14:22:18] [Server thread/INFO]:   |___ |      Running on Bukkit - Purpur[0m
[14:22:18] [Server thread/INFO]: [0m
```

**Screenshots or Videos**
![Screenshot_20201008_143737](https://user-images.githubusercontent.com/28690790/95459356-d424c280-0973-11eb-88c1-d1cfef73e04c.png)

**Plugins**
Examples of affected plugins: Luckperms, Chatcontrol, CMI

**Version**
Purpur 1.16.3 build 786

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
Paper doesn have this issue. Tested build 220 (1.16.3)

**Comment by jpenilla** [comment]
those are ANSI escape characters which are showing because you set the ``terminal.ansi=true`` property on a terminal which does not support ANSI. edit: didn't realize it was showing up in log files

**Comment by BillyGalbreath** [comment]
The commit responsible is https://github.com/pl3xgaming/Purpur/commit/0743d383bdaffe39fce5260010301d8addf0b017

It's a PR in Paper that hasn't been pulled yet. https://github.com/PaperMC/Paper/pull/4221

Please report it to the PR so the devs can know and find a fix.

Fwiw, it also effects the DiscordSRV plugin.

**Comment by x1p** [comment]
Funny, to report something in a PR I technically know nothing about.

**Comment by jpenilla** [comment]
To instead strip all RGB and other colors codes from console output (and also logs), use the flag ``-Dterminal.ansi=false`` This will disable console colors but will also fix these characters appearing in logs. When proper support for RGB is eventually included upstream this patch will be dropped.

**Comment by x1p** [comment]
Now I see `[m` on the log.
Due to the slow hosting response, the ansi flag is still present so at the moment, I can't test without.

**Comment by BillyGalbreath** [comment]
> Now I see `�[m` on the log.

Let the linked PR know. I just pulled in their changes, is all.

> Due to the slow hosting response, the ansi flag is still present so at the moment, I can't test without.

The flag will fix your logs, yes, but you will also sacrifice all colors showing in your console as well. It's not a fix, but a temporary workaround with a cost.

I'll reopen this ticket until I can put this hex stuff behind a purpur.yml config option later today.

**Comment by x1p** [comment]
The `-Dterminal.ansi=true` flag in the startup flags have been removed.
This solves the strange characters for me.
(so maybe this issue can be closed?)
