### ISSUE TITLE
A important Bug about log4j

### ISSUE THREAD

**Issue by g2nnyS** [pl3xgaming/Purpur#775]
### Purpur version

 latest version 

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by RealCamar** [comment]
Known issue. I suggest removing the steps on how to reproduce it since any people with malicious intent could use it.

**Comment by granny** [comment]
already fixed on latest version

**Comment by TheFrenchGhosty** [comment]
@granny Just FYI, the "download" button on the homepage that download the latest version isn't downloading the hotfix, this is dangerous and should be fixed in my opinion.

**Comment by encode42** [comment]
known
