### ISSUE TITLE
Almost every stair, trapdoor and fence is waterlogged and faced randomly.

### ISSUE THREAD

**Issue by 5oC8** [pl3xgaming/Purpur#777]
### Timings link

https://timings.aikar.co/?id=09dc29b0282b4e3b9ec6add7698d1920

### Expected behavior

Normally generated and placed Stairs, trapdoors and fences.

### Observed/Actual behavior

Really wierd faced and waterlogged trapdoors, stairs, glow linchen, etc....

### Steps/models to reproduce

![2021-12-10_20 34 02](https://user-images.githubusercontent.com/76214226/145631396-d5b6249e-1132-464a-aa39-05bf9cd33a11.png)
![2021-12-10_20 34 47](https://user-images.githubusercontent.com/76214226/145631440-7763444a-3615-4a5f-a1d2-619ed8b97b65.png)
![2021-12-10_20 35 12](https://user-images.githubusercontent.com/76214226/145631487-630c346f-2bd2-427f-a7bc-66e20cddce67.png)
![2021-12-10_20 35 31](https://user-images.githubusercontent.com/76214226/145631524-df9ab486-3541-494e-b36e-e0a1709a901c.png)
![2021-12-10_20 36 47](https://user-images.githubusercontent.com/76214226/145631709-d2ea3d44-88a5-444e-bb15-ac4849e91612.png)
![2021-12-10_20 37 03](https://user-images.githubusercontent.com/76214226/145631717-48513498-dfc0-4890-8dad-00c5bd62fd5e.png)

### Purpur version

This server is running Purpur version git-Purpur-1434 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 1fd37bd on HEAD)
You are running the latest version
Previous version: git-Purpur-1433 (MC: 1.18)

### Agreements

- [x] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I have generated a world in singleplayer with the same seed and It was NOT like on the server. It was fine as it normally has to work.

**Comment by encode42** [comment]
Resolved in Discord

> OK sorry it was somehow an issue with my performance mods that i was running
> \- NickWilde1994
