### ISSUE TITLE
Hordes Lessrain legacy

### ISSUE THREAD

**Issue by x1p** [pl3xgaming/Purpur#78]
**Describe the bug**
I like using Hordes and Lessrain. They only they appear as legacy
`Hordes*, ..., LessRain*`

**Suggestion**
Is it possible to update them to native > 1.16.x or something like that?

**Plugins**
Show the output of `/plugins` here.
`Hordes*, ..., LessRain*`

**Version**
Purpur 1.16.3 build 795

**Comment by granny** [comment]
has nothing to do with Purpur.
