### ISSUE TITLE
NetherPortal Memory problem

### ISSUE THREAD

**Issue by MrEDok** [pl3xgaming/Purpur#784]
### Timings link

https://timings.pl3x.net/?id=9d1d50ee247742f8bca45f40414e24c0

### Description of issue

When entering a netherportal memory usage increase by ALOT 1-1.5 GB and this have cause some of the lag from GC and sometime Oldgen on the server.

in video: https://streamable.com/uw1k2n

when i spam /spark healthreport you can see that 
before entering the portal memory is at 3GB and 0.5-1 seond before entering memory shot up to 4GB which seem very strange and when player running this type of "farm" obsidian farm which entering the portal over and over again it cause the server to lag and sometime OOM.

i have only test this on 1.17.1 and 1.18.1

### Purpur version

Purpur version git-Purpur-"9a7a4dc" (MC: 1.17.1)
Purpur version git-Purpur-1434 (MC: 1.18.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
superseded by https://github.com/PaperMC/Paper/issues/7098
