### ISSUE TITLE
15 tps On almost empty world

### ISSUE THREAD

**Issue by jokbon** [pl3xgaming/Purpur#786]
### Timings link

https://timings.aikar.co/?id=cc111b6aef7749a3a625d205fd537fa2

### Description of issue

Consistent 15 tps hapening prety randomly. Without plugins hapens too.

Purpur-1434:
https://timings.aikar.co/?id=630b440a61f84748aa4f1daf9544f778

Purpur-1436:
https://timings.aikar.co/?id=cc111b6aef7749a3a625d205fd537fa2

![2021-12-14_18 31 20](https://user-images.githubusercontent.com/29400409/146039525-5f077fde-eafe-4552-84d3-b66eef57296e.png)

### Purpur version

This server is running Purpur version git-Purpur-1436 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 45ae426 on HEAD)
You are running the latest version
Previous version: git-Purpur-1434 (MC: 1.18.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by jokbon** [comment]
And even world was recreated.

**Comment by cfitz25** [comment]
Im having performance issues aswell. Purpur seems to be running slower than paper at this time.
Purpur: https://timin.gs/?id=8bc434875b6f410d94601e287c960efa
Paper: https://timin.gs/?id=7c85fe92b8484d1297ffafd6b07c52ad

**Comment by BillyGalbreath** [comment]
> Purpur-1434: https://timings.aikar.co/?id=630b440a61f84748aa4f1daf9544f778
> Purpur-1436: https://timings.aikar.co/?id=cc111b6aef7749a3a625d205fd537fa2

These reports don't make any sense, tbh. Looking at the mspt rates (0.4ms) during the 15tps ranges, it _should_ be reading 20tps. The graphs don't even show any signs of tps loss at all (0%). Are you _actually_ experiencing any lag, or is this a fault in the tps readout/calculation?


> Purpur: https://timin.gs/?id=8bc434875b6f410d94601e287c960efa
> Paper: https://timin.gs/?id=7c85fe92b8484d1297ffafd6b07c52ad

I'm not sure where you think Purpur is being slower than Paper in these reports @cfitz25. Both reports show the server running at a perfect 20tps. Paper's report is 22.8mspt and Purpur's is 15.7mspt, making Purpur's _faster_ but both are running in perfect condition with no lag..

**Comment by cfitz25** [comment]
Sorry, i was looking at the ms values below that, seems i gotta understand how timings reports work better. Thanks for pointing this out

**Comment by jokbon** [comment]
Probalyt tps are calculated wrong. I thought it was intended reading and just tps lag spikes moving that down. 
Maybe iam wrong and this is probaly tps calculation isusue.

**Comment by jokbon** [comment]
I set 5000000 random tick rate and server wasnt lagging too bad. So this must be tps calculation isusue.
