### ISSUE TITLE
if set max-growth-age, plants may not grow

### ISSUE THREAD

**Issue by KioProject123** [pl3xgaming/Purpur#788]
### Expected behavior

Cave vines and kelp can grow normally

### Observed/Actual behavior

Cave vines and kelp cannot grow after repeated destroy

### Steps/models to reproduce

1、set cave vines (or kelp) max-growth-age to 10
2、place some
3、/gamerule randomTickSpeed 1000
4、when cave vines grows up, destroy its newly grown parts, until all cave vines stops growing

### Purpur version

[19:22:47 INFO]: This server is running Purpur version git-Purpur-1434 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 1fd37bd on HEAD)

### Agreements

- [ ] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Placed and destroyed cave vines will have a random age(0-25), It will not change according to the max-growth-age.
This leads to the age of cave vines after multiple destruction is greater than max-growth-age.

**Comment by BillyGalbreath** [comment]
Confirmed.

~~Looks like there have been a lot of changes to the `GrowingPlantHeadBlock` class. To fix this we will need to move the `max-growth-age` world settings to the global config since most of the new methods only expose the `BlockState` and not the `ServerLevel`~~

Was easier to fix than I thought.

**Comment by hexadecimal233** [comment]
any update rn? @BillyGalbreath

**Comment by BillyGalbreath** [comment]
> any update rn? @BillyGalbreath

Looks like its still an open issue to me.
