### ISSUE TITLE
fire spread bug

### ISSUE THREAD

**Issue by rodrigoveglo** [pl3xgaming/Purpur#794]
### Timings link

https://timings.pl3x.net/?id=a3c3ed5eca5a4d5b9b7b598b2bbf5603

### Expected behavior

the fire spreads and at the end of the fire is eliminated

### Observed/Actual behavior

the fire expands but is never eliminated

### Steps/models to reproduce

quemar un bosque o cualquier bloque que se queme

### Purpur version

![image](https://user-images.githubusercontent.com/44950448/146508047-dc771417-0028-40aa-adc6-978f795e6507.png)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

![image](https://user-images.githubusercontent.com/44950448/146508077-7308b92b-4bd5-4961-a9a5-422af14112a5.png)
![image](https://user-images.githubusercontent.com/44950448/146508084-8f67facf-23be-440b-a1f0-41432ac599ca.png)

**Comment by encode42** [comment]
1.16.5 is no longer supported.
