### ISSUE TITLE
Player clicking on inventory too fast throws NPE for Packet 20

### ISSUE THREAD

**Issue by luizsusin** [pl3xgaming/Purpur#797]
### Expected behavior

Players not being kicked.

### Observed/Actual behavior

Players are being kicked.

### Steps/models to reproduce

Clicking too fast on inventory, changing inventories, etc, usually triggers this.
I'm not really sure how to reproduce it perfectly because it seems to be random.

### Purpur version

Purpur version git-Purpur-1446 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: a1c3bf0 on HEAD).

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Stacktrace thrown:
https://pastebin.com/AAa3zSat
        
It's also worth mentioning that, besides tradesystem plugin show's up in there, it doesn't seem to be the issue.
If this is a ProtocolLib problem, I'm sorry for posting it here.

Edit: Posted a Pastebin link for better visualization of the stacktrace.

**Comment by ghost** [comment]
See https://github.com/PaperMC/Paper/issues/7130#issuecomment-995621532
