### ISSUE TITLE
curl download API not working?

### ISSUE THREAD

**Issue by Apprisco** [pl3xgaming/Purpur#798]
### Timings link

N/A

### Expected behavior

curl -o purpur.jar https://api.pl3x.net/v2/purpur/1.18.1/latest/download
Should download the latest into purpur.jar

### Observed/Actual behavior

Downloads a corrupt 0kb file.

### Steps/models to reproduce

curl -o purpur.jar https://api.pl3x.net/v2/purpur/1.18.1/latest/download in unix command line.

### Purpur version

N/A

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by notjoshmiles** [comment]
Try `curl -o purpur.jar https://api.purpurmc.org/v2/purpur/1.18.1/latest/download` instead

**Comment by BillyGalbreath** [comment]
When using curl you need to specify the [`-L` flag (short for `--location`)](https://curl.se/docs/manpage.html#-L) so it will follow any redirects. In this case, the `api.pl3x.net` url has a [permanent redirect (301)](https://en.wikipedia.org/wiki/HTTP_301) to the new `api.purpurmc.org` url.

Example:
```sh
curl -OJL https://api.pl3x.net/v2/purpur/1.18.1/latest/download
```

`-O` uses the remote filename
`-J` sets `-O` to use the content disposition to get the remote filename
`-L` will follow any redirects like a normal browser

**Comment by Apprisco** [comment]
Understood, it now has a redirect huh!

**Comment by granny** [comment]
Well yes, but no. The url for the api has been moved to `https://api.purpurmc.org`, and the old url was turned into a redirect.
