### ISSUE TITLE
Items start jumping on beds too high

### ISSUE THREAD

**Issue by StKillReal** [pl3xgaming/Purpur#801]
### Timings link

Not needed

### Expected behavior

Items just lay on the bed, only with vanilla rotation

### Observed/Actual behavior

After 5-10 second items start to jump higher and higer. If u wait for a couple minutes, they will be jumping 30+ blocks height 

### Steps/models to reproduce

1. Drop any items on the bed
2. Wait 5-10 seconds
3. U can see how items start to jump higher and higher

### Purpur version

This server is running Purpur version git-Purpur-1454 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 35bf26e on HEAD)
You are 2 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous version: git-Purpur-1449 (MC: 1.18.1)

### Agreements

- [ ] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

It works without any plugins

**Comment by BillyGalbreath** [comment]
Closing due to no timings report linked.
