### ISSUE TITLE
Items start jumping on beds too high

### ISSUE THREAD

**Issue by StKillReal** [pl3xgaming/Purpur#802]
### Timings link

https://timings.aikar.co/?id=86f86eb8538f48d78e559eb9856b5d65

### Expected behavior

Items just lay on the bed, only with vanilla rotation

### Observed/Actual behavior

After 5-10 second items start to jump higher and higer. If u wait for a couple minutes, they will be jumping 30+ blocks heigh
![2021-12-26_20 31 06](https://user-images.githubusercontent.com/60330193/147406802-05620af4-23d5-4d09-bcba-99e62dfda3eb.png)
![2021-12-26_20 31 24](https://user-images.githubusercontent.com/60330193/147406813-92642d40-8514-4acc-b491-c04b0cec2b99.png)

### Steps/models to reproduce

1.Drop any items on the bed
2.Wait 5-10 seconds
3, U can see how items start to jump higher and higher

### Purpur version

This server is running Purpur version git-Purpur-1454 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 35bf26e on HEAD)
You are 2 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous version: git-Purpur-1449 (MC: 1.18.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

It works without any plugins

**Comment by BillyGalbreath** [comment]
Unable to reproduce on latest release.

[![Purpur #802 - Unable to reproduce](https://i9.ytimg.com/vi/tlSo4v0hG9I/mq3.jpg?sqp=COCAo44G&rs=AOn4CLAQnPdQTl1ivN2RdapC87hAHAGbxg)](https://youtu.be/tlSo4v0hG9I)
