### ISSUE TITLE
disable-note-block-updates does not work correctly

### ISSUE THREAD

**Issue by nykonhrytsyshyn** [pl3xgaming/Purpur#803]
### Expected behavior

Note block simply does not need to be updated in any way

### Observed/Actual behavior

Note block is updated sometimes :
https://www.youtube.com/watch?v=0fE41MBQcZE

### Steps/models to reproduce

1. place note block
2. click on it and you will see how it updated the note
3. break/place any block under noteblock and it will change to default parameters

### Purpur version

 This server is running Purpur version git-Purpur-1456 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 7551c72 on HEAD)
You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [x] My version of Minecraft is supported by Purpur.

### Other

In addition, this parameter also interferes with the plugin, note blocks simply do not save their block data after the actions described in "Steps/models to reproduce".
This parameter makes it very easy to work as visual defects are observed when closing BlockPhysicsEvent.

**Comment by IllagerCaptain** [comment]
Still an issue in latest version..
