### ISSUE TITLE
Map error in console

### ISSUE THREAD

**Issue by MrDisastrous** [pl3xgaming/Purpur#805]
### Timings link

https://timings.aikar.co/?id=78bda22460884c3ea7798d2ea5c2f6f1

### Expected behavior

No errors in console?

### Observed/Actual behavior

I haven't seen any issues in the game but it is causing lag.

Error: https://pastebin.com/JzxVqbqM

### Steps/models to reproduce

Just moving around my map. I don't have any special map plugins except a schematic plugin (CustomStructures) that places schematics on new chunk loads but the map is pre-generated. 

### Purpur version

This server is running Purpur version git-Purpur-1456 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 7551c72 on HEAD)\nYou are running the latest version\nPrevious version: git-Purpur-1427 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I've googled this issue and have not found a fix; only information that tells me it is likely a Mojang bug and has been around since 1.16. I have not seen this issue before updating to 1.18.

**Comment by BillyGalbreath** [comment]
This is a [vanilla bug](https://bugs.mojang.com/browse/MC-227945) in [DFU](https://github.com/Mojang/DataFixerUpper). You'll see these errors when loading old chunks for the first time that contain structures/features that were removed from the game (or renamed). Once the chunks have been loaded at least once and upgrade to the new format they will stop spamming like this. It is best to use a plugin like [Chunky](https://www.spigotmc.org/resources/chunky.81534/) to force load all chunks again (almost like pregenerating you world again).

The community census is this is [just harmless spam](https://github.com/PaperMC/Paper/issues/7066) (albeit annoying and sometimes laggy) and can be ignored.
