### ISSUE TITLE
adding Github actions

### ISSUE THREAD

**Issue by Titaniumtown** [pl3xgaming/Purpur#81]
Could someone add github actions integration with this repo so it can test if PRs build or not?

**Comment by granny** [comment]
Billy was looking into setting up Github actions with Purpur but decided against it once he saw that artifacts are only stored for 90 days.

**Comment by Titaniumtown** [comment]
I mean for when people submit PRs and new commits are pushed, not really for storing artifacts.

**Comment by BillyGalbreath** [comment]
PR builds would be considered dev builds and should be reserved for devs (or at least people smart enough to know how to compile the project). Yes, this is a form of gatekeeping because I dont need normies downloading PR jars ;)
