### ISSUE TITLE
Stronghold seed issue locating strongholds

### ISSUE THREAD

**Issue by Decme** [pl3xgaming/Purpur#813]
### Expected behavior

After changing stronghold seed in purpur.yml, expecting ender eyes & the /locate stronghold command to find strongholds as normal.

### Observed/Actual behavior

Ender eyes & the /locate stronghold command no longer work, even after reverting the stronghold seed back to the original stronghold seed.

### Steps/models to reproduce

Changed stronghold seed post world generation (no pregen but a fair amount of chunks were loaded by players)

### Purpur version

This server is running Purpur version git-Purpur-1467 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 288d42c on HEAD)
You are running the latest version
Previous version: git-Purpur-1447 (MC: 1.18.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

If this is intended behavior, please could a warning label at least be added next to the stronghold seed option in purpur.yml that it can break ender eye & /locate stronghold command?

**Comment by BillyGalbreath** [comment]
What version were you running when the world was generated? Those seed settings were fixed in build 1453, so if the world was generated before that the strongholds are at their vanilla positions for old chunks (which would throw the /locate command ender eye of enders off course)

**Comment by BillyGalbreath** [comment]
Ok, after substantial testing I can confirm my original suspicions were correct.

If you generated your world before build 1453, then using anything other than `-1` for the seed settings will break things like this. The 3 seed settings in purpur.yml simply weren't used before that build, so it's like they were -1 even if you did change them.

There is nothing further I can do to fix this. It's just one of those unfortunate things that happens. Just leave these settings at -1 until you can reset your worlds.
