### ISSUE TITLE
Hoe settings - Replant Crops | No durability usage

### ISSUE THREAD

**Issue by ElFrod0** [pl3xgaming/Purpur#817]
### Timings link

No need for timings

### Expected behavior

I expected to make my hoe lose durability when harvesting fully grown crop.

### Observed/Actual behavior

My hoe didn't lose any durability when I harvested fully grown crop.

### Steps/models to reproduce

1) Enable: `world-settings.default.tools.hoe.replant-crops: true`
2) Plant a crop of your choice.
3) Wait (or use bone meal) to make it fully grown.
4) Use hoe and left click the fully grown crop. It will replant automatically and drop items on the ground.
5) Voilá no damage to hoe.

### Purpur version

[03:00:18 INFO]: This server is running Purpur version git-Purpur-1474 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 1c9c6b9 on HEAD)
[03:00:18 INFO]: You are running the latest version
[03:00:18 INFO]: Previous version: git-Purpur-1453 (MC: 1.18.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I'm honestly not sure if this is working as intended. Maybe it was meant to work that way. What about making it an option in config to actually damage the hoe when harvesting crops that way?

**Comment by BillyGalbreath** [comment]
Crops have a strength of 0, so they do not damage durability. This is a vanilla thing (try it on single player if you don't believe me).

I originally had the same thought about it, and was honestly surprised to find out about this.

**Comment by fahlur** [comment]
Can you add the durability as a config thing? Plugins such as sickle effect durability as a added thing. Any way of treating it with a configurable dmg value?
