### ISSUE TITLE
Patch(es) request: Axe combat patches

### ISSUE THREAD

**Issue by Titaniumtown** [pl3xgaming/Purpur#82]
Since Purpur has a patch for mending and infinity on the bow along with some infinity configs. I was wondering if you could add patch{es) that add config options for the following:
1. Allow for sword-only enchantments to be added on an Axe (ex. fire aspect, Looting III, etc).
2. Disable 2 durability being used when using an axe to attack a mob, in favor of only 1 durability (like an sword). Afaik, this is caused by the axe not being considered a weapon, and using a tool/weapon "improperly" uses more durability.

**Comment by katekerllenevich** [comment]
I will be submitting a pull request within the next week (hopefully), to add both of these items.

**Comment by Titaniumtown** [comment]
Yay! Thanks @notOM3GA I'll be looking forward to it!

**Comment by Titaniumtown** [comment]
@notOM3GA any progress?

**Comment by katekerllenevich** [comment]
I meant to tell you this but kind of forgot. I did some deep diving into the enchantment system and found something interesting. Axes extend the Tool class, and sharpness and other enchantments will not apply when it is a tool. This could be fixed by delving further into the Tool class and changing that. Changing the tool class would allow sharpness to go on shovels and pickaxes, etc. as well.

Don't quote me on anything as I am not looking at the code rn but that is the idea.

I haven't looked at durability yet.

**Comment by BillyGalbreath** [comment]
Has anyone tried using a plugin to test if adding these enchantments even do anything on an axe? I mean, is it as simple as allowing the enchantments to be applied, or will there be more work required to actually make them function correctly once applied?

You can use Essentials to add "illegal" and "unsafe" enchantments to items to test, etc.

**Comment by granny** [comment]
Only Sharpness will work since it's just an increase to damage. The other enchantments do not work (Basing this on what Nessie said in the discord server a while ago). Not sure about the extra work needed to make them functional or if it's even possible without client side changes.

**Comment by katekerllenevich** [comment]
It is most likely possible client side, but the major flaw is that the sharpness enchantment cannot be applied to anything that extends `ItemTool`. This would allow sharpness to go on *any* tool.

**Comment by BillyGalbreath** [comment]
Closing this because its just not possible without rewriting all the tools. I was hoping it would "just work" by brute forcing the enchantment on the axe, but that is simply not the case. Sorry
