### ISSUE TITLE
Datapack does not generate custom biomes in end dimension

### ISSUE THREAD

**Issue by mibby** [pl3xgaming/Purpur#835]
### Expected behavior

Datapack loaded to generate custom biomes in the end dimension.

### Observed/Actual behavior

End dimension datapack does not generate custom biomes.

### Steps/models to reproduce

* Put custom end datapack in the ``world/datpacks`` folder.
https://www.planetminecraft.com/data-pack/fokastudio-s-ender-expansion/
* Delete ``world_the_end`` if it exists.
* Start server.
* Enter the end dimension.
* Notice only modified vanilla biomes from the datapack exist and generate in the end dimension.

### Purpur version

``Purpur version git-Purpur-1493 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 695f09c on HEAD)``

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Using the datapack in singleplayer in a new world _does_ generate the custom biomes fine.

**Comment by mibby** [comment]
This seems to affect Paper dev 134 (1.18.1) as well, so not entirely sure who or what is at fault. Likewise using a datapack that generate custom biomes in the overworld (Terralith) _does_ work fine with Purpur. So it's only end datapack generation that is broken?

If this could be fixed or patched until Spigot/Paper fixes the issue, would be much appreciated!

**Comment by mibby** [comment]
Related? https://github.com/PaperMC/Paper/issues/6880

**Comment by BillyGalbreath** [comment]
Definitely seems related. Read over jmp's comments, he mentions he got it to work with 2 world resets (one to apply the pack, then another for it to go into effect, or something)

**Comment by Athesiel** [comment]
It's end **and** nether biome generation that are effected; interestingly enough, custom worldgen features still exist in pre-existing biomes, too. So if you were to, say, add red wool piles to the nether wastes biome: it would show up. It's just custom biomes in dimensions other than the overworld that aren't generating.

**Comment by BillyGalbreath** [comment]
Going to go ahead and close this since its upstream (probably to do with the way spigot handles datapacks)
