### ISSUE TITLE
Feature Request: Alpha Farmland

### ISSUE THREAD

**Issue by CorvieSonder** [pl3xgaming/Purpur#84]
From Alpha v1.0.17 until Beta 1.9 Prerelease 6, fences (and presumably stone walls, if they existed), could be placed under farmland to prevent it from decaying when a player jumped on it. The reason for this was that either the fence hitbox was slightly higher than it is now, or the farmland hitbox was slightly lower than it is now. That way, the player never technically touched the farmland when jumping on it. Is this something you could add/would be willing to add to Purpur?

![image](https://user-images.githubusercontent.com/38408292/97092154-5eb52500-15f6-11eb-8755-412b16a73c61.png)

**Comment by jpenilla** [comment]
I feel like this could be done very easily with a plugin...
edit: Sent a simple plugin to do this in the Purpur Discord `#off-topic` channel
https://cdn.discordapp.com/attachments/720375089123688488/770809126699532298/OldFarmland-1.0-SNAPSHOT.jar

**Comment by CorvieSonder** [comment]
Totally willing to have this closed now if devs don't want to add it :)

**Comment by BillyGalbreath** [comment]
https://github.com/pl3xgaming/Purpur/commit/686640fb79be93608f593727a8a8231c9f67f839
