### ISSUE TITLE
Comments Duplicating

### ISSUE THREAD

**Issue by SkeletonAce** [pl3xgaming/Purpur#847]
### Expected behavior

Nothing

### Observed/Actual behavior

Plugin comments are duplicating.
(everything with a # before it)

e.g.

#example

becomes

#example
#example

### Steps/models to reproduce

Update to latest 1.18.1 build.

Whenever server is restarted, comments get duplicated.
Notably, vulcan seems to be the most effected by this. Even on vulcan-2.4.3 comments are still being duplicated.
I have noticed that anther plugin I use DeluxeSellWands is also duplicating comments.

One of these upstream updates from paper may have fucked something up.

After downgrading to purpur-1495 it appears to have stopped the duplication from happening.

### Purpur version

purpur-1504

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Unable to reproduce. I use Vulcan and am not seeing duplicate comments on build 1506.

**Comment by SkeletonAce** [comment]
Interesting, it must be an issue with my plugins then.
Thankyou for testing
