### ISSUE TITLE
Zombified piglins stop pathfinding towards turtle eggs

### ISSUE THREAD

**Issue by ALFR3D343** [pl3xgaming/Purpur#852]
### Expected behavior

Using my gold farm, zombified piglins should spawn in their corresponding platforms, pathfind towards turtle eggs and fall to the killing chamber where I'm afk.

### Observed/Actual behavior

When standing in the afk spot everything starts working as normal, however, as time goes on some of the zombified piglins spawned in the two nearest platforms to the player just stop pathfinding and remain static, in those same platforms there are some zombified piglins that pathfind towards turtle eggs, they even collide with some of the static zombified piglins but they refuse to move and stay static, as time continues to go on, these platforms get full of static zombified piglins and the efficiency of the farm drops dramatically.

Screenshot of the static piglins in the first platforms:
![2022-01-17_11 02 00](https://user-images.githubusercontent.com/76851628/149819856-3c3c1faf-e121-4008-9917-a87203a4334a.png)
 

### Steps/models to reproduce

- Build a gold farm based on turtle eggs on top of the bedrock ceiling in a nether wastes biome (I used: 
[Gnembon Gold Farm.zip](https://github.com/PurpurMC/Purpur/files/7883905/Gnembon.Gold.Farm.zip))
- Stay in any of the afk places [next to the killing chamber (this one needs spawnproofing below the bedrock) or at y=256 (this one doesn't need any spawn proof)]
- Wait a few seconds
- If you are next to the killing chamber use freecam to see the first two platforms and notice the problem, if you are at y=256 just observe the zobified piglins at the top platform from the afk spot

### Purpur version

This server is running Purpur version git-Purpur-1508 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: af068b4 on HEAD)
You are running the latest version
Previous version: git-Purpur-1503 (MC: 1.18.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

- The static zombified piglins are only in the nearest platforms to the player, all other platforms work as normal.
- The bugged zombified piglins fix themselves as the player moves closer to them, however the issure occurs again as the player return to the afk spot, as this problem happens in fully afk farms, moving the player is not a valid solution.
- I temporarily switched my server jar to the latest verision of paper and it works normally using it, the problem comes with purpur.
- The purpur.yml is the default one

**Comment by TweekerX** [comment]
This is on other gold farm desings as I build the square kind. Same holds true for mobs in a wither skeleton farm they just stand there

**Comment by BillyGalbreath** [comment]
This sounds like DAB (dynamic activation of brain) setting in pufferfish.yml - It is known to cause issues with vanilla farms like these. Try disabling that setting (or finding a tuning that works for you).

**Comment by ALFR3D343** [comment]
> This sounds like DAB (dynamic activation of brain) setting in pufferfish.yml - It is known to cause issues with vanilla farms like these. Try disabling that setting (or finding a tuning that works for you).

Yes, I tried that and it worked, thanks for helping.
