### ISSUE TITLE
Player#teleportOffline and #teleportOfflineAsync throw a StackOverflowError

### ISSUE THREAD

**Issue by motz0815** [pl3xgaming/Purpur#855]
### Expected behavior

I expect online players to get teleported using the normal teleport method.
I expect the location of offline players to be set to the desired location.

### Observed/Actual behavior

Every time either the #teleportOffline or #teleportOfflineAsync methods are called, I get a StackOverflowError.
The player does not get teleported.

![grafik](https://user-images.githubusercontent.com/49114741/150632919-ff332ec0-0a27-43b1-8a81-e2a23a071576.png)

### Steps/models to reproduce

1. Be either offline or online, doesn't matter.
2. Call the teleportOffline or teleportOfflineAsync method: `p.teleportOffline(p.getWorld().getSpawnLocation());`

### Purpur version

This server is running Purpur version git-Purpur-1522 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 762fcdd on HEAD)
You are running the latest version
Previous version: git-Paper-169 (MC: 1.18.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I am calling the method inside of a (synchronous) task timer scheduled using Bukkit#getScheduler#runTaskTimer, but the error also occurs when calling it just normally, like through a command

**Comment by YouHaveTrouble** [comment]
Reproduced, will look at this later today
