### ISSUE TITLE
Entity N

### ISSUE THREAD

**Issue by Frietzak1** [pl3xgaming/Purpur#858]
### Expected behavior

the name of the entity (abcdefgh-abcd-abcd-abcd-abcdefghijkl) showing up in the chat list when you do a command like /kill ... or /data get entity ... while looking at an entity.

### Observed/Actual behavior

The list only said "@a @e @p @r @s <username>"

### Steps/models to reproduce

a config option
make it like paper/singleplayer (it works fine there)

### Purpur version

This server is running Purpur version git-Purpur-1525 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: e9fb694 on HEAD)
You are running the latest version
Previous version: git-Purpur-1452 (MC: 1.18.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I've tried disabling all plugins.
![image](https://user-images.githubusercontent.com/98241015/150659271-10e26c8f-22e4-4b99-8e9c-2dbc03fc7d23.png)

**Comment by BillyGalbreath** [comment]
You have to be rather close to the entity from what I've seen. This works exactly the same on Purpur as it does Paper.

**Comment by Frietzak1** [comment]
Is there a way to change the distance
