### ISSUE TITLE
1.18.1 features bugs, but works on 1.16.5

### ISSUE THREAD

**Issue by cardanawandra** [pl3xgaming/Purpur#868]
### Expected behavior

1. able to strip custom block
2. enderman ai able to go to water
3. phantom not burning on daylight
4. glow squid is swimming on air without damage

it's all works in 1.16.5, but no in 1.18

### Observed/Actual behavior

1. Invalid block for `tools.axe.strippables`: minecraft:striped_warped_hyphae on custom strippables
2. Enderman still avoid water, in older version Enderman AI is able to go on water if damage by water is off
3. Phantom is burning on daylight
4. Glow Squid is death on air (flying active)

### Steps/models to reproduce

1.        axe:
        strippables:
          minecraft:striped_warped_hyphae:
            drops: {}
            into: minecraft:warped_hyphae
          minecraft:striped_crimson_stem:
            drops: {}
            into: minecraft:crimson_stem
          minecraft:striped_warped_stem:
            drops: {}
            into: minecraft:warped_stem
          minecraft:striped_spruce_log:
            drops: {}
            into: minecraft:spruce_log
          minecraft:striped_oak_log:
            drops: {}
            into: minecraft:oak_log
          minecraft:striped_jungle_log:
            drops: {}
            into: minecraft:jungle_log
          minecraft:striped_dark_oak_wood:
            drops: {}
            into: minecraft:dark_oak_wood
          minecraft:striped_acacia_log:
            drops: {}
            into: minecraft:acacia_log
          minecraft:striped_birch_wood:
            drops: {}
            into: minecraft:birch_wood
          minecraft:striped_birch_log:
            drops: {}
            into: minecraft:birch_log
          minecraft:striped_jungle_wood:
            drops: {}
            into: minecraft:jungle_wood
          minecraft:striped_acacia_wood:
            drops: {}
            into: minecraft:acacia_wood
          minecraft:striped_dark_oak_log:
            drops: {}
            into: minecraft:dark_oak_log
          minecraft:striped_oak_wood:
            drops: {}
            into: minecraft:oak_wood
          minecraft:striped_spruce_wood:
            drops: {}
            into: minecraft:spruce_wood
          minecraft:striped_crimson_hyphae:
            drops: {}
            into: minecraft:crimson_hyphae
          minecraft:warped_hyphae:
            drops: {}
            into: minecraft:stripped_warped_hyphae
          minecraft:crimson_stem:
            drops: {}
            into: minecraft:stripped_crimson_stem
          minecraft:warped_stem:
            drops: {}
            into: minecraft:stripped_warped_stem
          minecraft:spruce_log:
            drops: {}
            into: minecraft:stripped_spruce_log
          minecraft:oak_log:
            drops: {}
            into: minecraft:stripped_oak_log
          minecraft:jungle_log:
            drops: {}
            into: minecraft:stripped_jungle_log
          minecraft:dark_oak_wood:
            drops: {}
            into: minecraft:stripped_dark_oak_wood
          minecraft:acacia_log:
            drops: {}
            into: minecraft:stripped_acacia_log
          minecraft:birch_wood:
            drops: {}
            into: minecraft:stripped_birch_wood
          minecraft:birch_log:
            drops: {}
            into: minecraft:stripped_birch_log
          minecraft:jungle_wood:
            drops: {}
            into: minecraft:stripped_jungle_wood
          minecraft:acacia_wood:
            drops: {}
            into: minecraft:stripped_acacia_wood
          minecraft:dark_oak_log:
            drops: {}
            into: minecraft:stripped_dark_oak_log
          minecraft:oak_wood:
            drops: {}
            into: minecraft:stripped_oak_wood
          minecraft:spruce_wood:
            drops: {}
            into: minecraft:stripped_spruce_wood
        waxables:
          minecraft:waxed_exposed_cut_copper_stairs:
            drops: {}
            into: minecraft:exposed_cut_copper_stairs
          minecraft:waxed_oxidized_cut_copper_slab:
            drops: {}
            into: minecraft:oxidized_cut_copper_slab
          minecraft:waxed_weathered_cut_copper_slab:
            drops: {}
            into: minecraft:weathered_cut_copper_slab
          minecraft:waxed_exposed_copper:
            drops: {}
            into: minecraft:exposed_copper
          minecraft:waxed_cut_copper_stairs:
            drops: {}
            into: minecraft:cut_copper_stairs
          minecraft:waxed_cut_copper:
            drops: {}
            into: minecraft:cut_copper
          minecraft:waxed_exposed_cut_copper:
            drops: {}
            into: minecraft:exposed_cut_copper
          minecraft:waxed_oxidized_cut_copper_stairs:
            drops: {}
            into: minecraft:oxidized_cut_copper_stairs
          minecraft:waxed_weathered_cut_copper_stairs:
            drops: {}
            into: minecraft:weathered_cut_copper_stairs
          minecraft:waxed_exposed_cut_copper_slab:
            drops: {}
            into: minecraft:exposed_cut_copper_slab
          minecraft:waxed_cut_copper_slab:
            drops: {}
            into: minecraft:cut_copper_slab
          minecraft:waxed_copper_block:
            drops: {}
            into: minecraft:copper_block
          minecraft:waxed_oxidized_copper:
            drops: {}
            into: minecraft:oxidized_copper
          minecraft:waxed_weathered_copper:
            drops: {}
            into: minecraft:weathered_copper
          minecraft:waxed_oxidized_cut_copper:
            drops: {}
            into: minecraft:oxidized_cut_copper
          minecraft:waxed_weathered_cut_copper:
            drops: {}
            into: minecraft:weathered_cut_copper
        weatherables:
          minecraft:oxidized_cut_copper_stairs:
            drops: {}
            into: minecraft:weathered_cut_copper_stairs
          minecraft:exposed_cut_copper_slab:
            drops: {}
            into: minecraft:cut_copper_slab
          minecraft:weathered_cut_copper:
            drops: {}
            into: minecraft:exposed_cut_copper
          minecraft:oxidized_cut_copper_slab:
            drops: {}
            into: minecraft:weathered_cut_copper_slab
          minecraft:weathered_cut_copper_slab:
            drops: {}
            into: minecraft:exposed_cut_copper_slab
          minecraft:weathered_cut_copper_stairs:
            drops: {}
            into: minecraft:exposed_cut_copper_stairs
          minecraft:exposed_copper:
            drops: {}
            into: minecraft:copper_block
          minecraft:oxidized_cut_copper:
            drops: {}
            into: minecraft:weathered_cut_copper
          minecraft:exposed_cut_copper:
            drops: {}
            into: minecraft:cut_copper
          minecraft:weathered_copper:
            drops: {}
            into: minecraft:exposed_copper
          minecraft:exposed_cut_copper_stairs:
            drops: {}
            into: minecraft:cut_copper_stairs
          minecraft:oxidized_copper:
            drops: {}
            into: minecraft:weathered_copper
2.       enderman:
        ridable: true
        ridable-in-water: true
        controllable: true
        attributes:
          max_health: 40.0
        allow-griefing: true
        can-despawn-with-held-block: false
        bypass-mob-griefing: false
        takes-damage-from-water: false
        aggressive-towards-endermites: true
        aggressive-towards-endermites-only-spawned-by-player-thrown-ender-pearls: true
        ignore-players-wearing-dragon-head: false
        disable-player-stare-aggression: true
        ignore-projectiles: true
        always-drop-exp: true
3.        phantom:
        ridable: true
        ridable-in-water: true
        controllable: true
        ridable-max-y: 320.0
        flames:
          damage: 1.0
          fire-time: 8
        allow-griefing: false
        attributes:
          max_health: '20.0'
          attack_damage: 6 + size
        attacked-by-crystal-range: 0.0
        attacked-by-crystal-damage: 1.0
        orbit-crystal-radius: 0.0
        spawn:
          delay:
            min: 1200
            max: 2400
          min-sky-darkness: 5
          only-above-sea-level: true
          only-with-visible-sky: true
          local-difficulty-chance: 3.0
          min-time-since-slept: 72000
          overhead:
            min: 20
            max: 35
            radius: 10
          per-attempt:
            min: 1
            max: -1
        burn-in-light: 0
        burn-in-daylight: false
        ignore-players-with-torch: true
        flames-on-swoop: true
        takes-damage-from-water: true
        always-drop-exp: true
        size:
          min: 32
          max: 32
4. 

### Purpur version

purpur-1519

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Can I get you to separate these into their own issues so we can track them better as we look into and fix them?

**Comment by cardanawandra** [comment]
okay

**Comment by BillyGalbreath** [comment]
Also, I got around to testing all these. 1 and 4 work fine, but 2 and 3 I can confirm are bugged. For 1, you misspelled `stripped` (it's got two `p`'s). For 4, it just works.

**Comment by BillyGalbreath** [comment]
Fixed 2 and 3

**Comment by cardanawandra** [comment]
you works so fast, good job man
