### ISSUE TITLE
about items from the augmented Ender Chest

### ISSUE THREAD

**Issue by triesharder** [pl3xgaming/Purpur#870]
### Expected behavior

Can we make the additional slots be dropped on ground when player loses the permission for more ender chest slots?

### Observed/Actual behavior

When players lose permission to have a larger ender chest, items that were in the additional slots are deleted.

### Steps/models to reproduce

1 Have more space on ender chest

2 Use the additional slots

3 Remove your permission to have it

4 You lost the items that were in the additional space

### Purpur version

Checking version, please wait...
This server is running Purpur version git-Purpur-1521 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 4365741 on HEAD)
You are 11 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous version: git-Purpur-1519 (MC: 1.18.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I'm not using the latest version of Purpur, but my issue has nothing to do with it

**Comment by BillyGalbreath** [comment]
With the way containers are implemented, this isn't really possible. It's the same problem if you decided to switch to another fork instead of Purpur. All the extra rows simply will not exist in order to drop the contents to the ground.

**Comment by triesharder** [comment]
What do you can suggest for me then? maybe there is a plugin that can handle this?
