### ISSUE TITLE
teleport-if-outside-border breaks with latency

### ISSUE THREAD

**Issue by MWHunter** [pl3xgaming/Purpur#878]
### Expected behavior

The player teleporting once when going outside border

### Observed/Actual behavior

The player teleporting in a loop when going outside border, if the player has high latency

### Steps/models to reproduce

1. Use clumsy to get high ping
2. Go outside border, such as setting the border close to spawn and using an ender pearl to escape the worldborder
3. Teleport spam

### Purpur version

Current: git-Purpur-1538 (MC: 1.18.1)*
Previous: git-Paper-175 (MC: 1.18.1)
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

The fix could be if there's a pending teleport don't teleport the player again.

**Comment by BillyGalbreath** [comment]
I'm honestly not sure of a way to fix this. Teleporting the player to spawn when they are outside the border is really just a convenience. They shouldn't be outside it to begin with, so I personally feel if someone intentionally gets themself outside of it and is forcing high latency then they deserve to get stuck in a broken state.

 I feel Purpur should continue to teleport the player each tick they are reporting themselves to be outside the border. Not being persistent would open possibilities for abuse.

If this is unacceptable for you, PRs are welcome. Or you could disable the feature and implement your own way in a plugin.
