### ISSUE TITLE
TNT break block 36 will not drop items

### ISSUE THREAD

**Issue by nikissXI** [pl3xgaming/Purpur#881]
### Expected behavior

when TNT break the block 36, it will drop correctly.

### Observed/Actual behavior

I made a stone maker machine, but tnt break the block 36 (cobble stone) will not drop cobble stone.
![image](https://user-images.githubusercontent.com/31379266/151700884-9247002e-1d80-42b3-9d28-cad746741099.png)

### Steps/models to reproduce

none

### Purpur version

git-Purpur-1541 (MC: 1.18.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Can you test this upstream on Pufferfish and Paper? I don't think this is a bug caused by Purpur.

**Comment by nikissXI** [comment]
> Can you test this upstream on Pufferfish and Paper? I don't think this is a bug caused by Purpur.

oh, I test in Ppaer and it still like that. You are right, thank you.
