### ISSUE TITLE
Lobotomized villagers do not acquire or lose poi.

### ISSUE THREAD

**Issue by Pantera07** [pl3xgaming/Purpur#883]
### Expected behavior

Villager lobotomize is for trading halls so it should be possible to acquire and lose poi.

### Observed/Actual behavior

Lobotomized villagers do not acquire or lose poi.

### Steps/models to reproduce

Turn on Lobotomize and create a trading hall.
![2022-01-31_00 58 05](https://user-images.githubusercontent.com/89838384/151741564-c281b728-3503-4664-bf15-6c3a607fbe36.png)

### Purpur version

[14:00:30] [Thread-25/INFO]: Current: git-Purpur-1541 (MC: 1.18.1)*
[14:00:30] [Thread-25/INFO]: Previous: git-Purpur-1538 (MC: 1.18.1)
[14:00:30] [Thread-25/INFO]: * You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Working as intended..

A lobotomized villager will not perform any brain functions. If you want them to use their brain then you need to get them out of the 1x1 hole temporarily. Example: https://youtu.be/A2Xp8GASrBE

**Comment by Pantera07** [comment]
> Working as intended..
> 
> A lobotomized villager will not perform any brain functions. If you want them to use their brain then you need to get them out of the 1x1 hole temporarily. Example: https://youtu.be/A2Xp8GASrBE

If the admin doesn't force players to 1x1 trading hole, all players will just create 1x2 trading hole. If that happens, this patch will be meaningless. :D
