### ISSUE TITLE
purpur.debug.f3n works as bad as f3nperm plugin

### ISSUE THREAD

**Issue by masmc05** [pl3xgaming/Purpur#886]
### Expected behavior

to work

### Observed/Actual behavior

it doesn't work when joining, but works when i change the world, just like f3nperm, and i helped some people in f3nperm's discord and seems like they have similar issues with that plugin, so it's not my client's problem

### Steps/models to reproduce

just join a server, and don't switch the world

### Purpur version

[Wed, 2. Feb 2022 15:59:54 MSK INFO] Checking version, please wait...
[Wed, 2. Feb 2022 15:59:54 MSK INFO] Current: git-Purpur-1544 (MC: 1.18.1)*
[Wed, 2. Feb 2022 15:59:54 MSK INFO] Previous: git-Purpur-1537 (MC: 1.18.1)
[Wed, 2. Feb 2022 15:59:54 MSK INFO] * You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by masmc05** [comment]
maybe because when the player is joining, some plugins may block his permission untill success login? 
may you add an alternative, not trough permission?

**Comment by BillyGalbreath** [comment]
You probably do have some plugin or client mod interfering. This feature works as intended.

https://youtu.be/4zmZcxpY4jE
