### ISSUE TITLE
Add natural bee spawning options

### ISSUE THREAD

**Issue by mibby** [pl3xgaming/Purpur#9]
RE: https://github.com/pl3xgaming/Purpur/commit/acfe38067bad9884b487fefc657da50f218eed31#comments

Would it make sense to add an option for natural spawning bees since they only spawn in newly generated 1.15 chunks? If you have an older world (1.14) that is already too large to expand further and too new to reset, people won't be able to see and use bees.

**Comment by BillyGalbreath** [comment]
I've been thinking a lot about this, and I can't think of a way to make this a possibility without lagging the server. Bees have heavy pathfinding logic attached to them for finding their nest, so just spawning bees in randomly without nests is going to cause them to endlessly search for a nest which isn't there and lag the server to hell.

I'm going to put this on hold and think about it more, so don't think I'm ignoring it. I was actually talking with my wife about it a week ago and it's something we want as well. I just cant think of a valid way to implement it yet.

**Comment by BillyGalbreath** [comment]
Ok, I've thought of a way to do this, but its not really natural spawning. I am going to add an option to purpur.yml that lets you set the percent chance beehives will spawn on trees when a tree grows from a sapling. This way they will have a chance to spawn in on older worlds. ^_^

**Comment by lukeeexd** [comment]
Tis already a plugin https://www.spigotmc.org/resources/beehivestrees-grow-trees-from-saplings-with-bees.73394/ so if you can just import it or add the same way it functions or better that be great

**Comment by BillyGalbreath** [comment]
Resolved with https://github.com/pl3xgaming/Purpur/commit/154be2caaf41bf87c54935f9bc91c5372a5a0a98

**Comment by mibby** [comment]
Good solution! It was originally something in the pre-release build for 1.15 but they removed it.
