### ISSUE TITLE
Stacking Raidfarms aren't working

### ISSUE THREAD

**Issue by BossDaily** [pl3xgaming/Purpur#917]
### Timings link

https://timings.aikar.co/?id=3ab90888013d4a7a880db12a0c84d624

### Expected behavior

Raids should be obtained every swing, but bad omen isn't acquired in every swing (of your sword)

### Observed/Actual behavior

Bad Omen is only obtained once per Raid when it should be obtained every swing

### Steps/models to reproduce

Download this world, and use the stacking raid farm.

Give yourself bad omen, and put yourself in survival mode, go and hit the minecart

Youtube video if your confused on how to use it: https://youtu.be/KjH2NA1eqIc?t=1707
World: https://www.mediafire.com/file/adhk7m1742ecksc/New_World.zip/file

### Purpur version

We have zero plugins and zero datapacks

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Here is our stacking raid farm design.
https://www.youtube.com/watch?v=d4z7YzgIIB0 (1.18 version)

Some stacking raid farm designs work, but others don't. The ones that send the raids up work, but the ones that send the raids down don't so chronos, and css stacking raid farm. The ones that send the raids down are more efficient and get better rates. 

(By send the raids down I mean the villagers are below the player, the ones that send the raids up the villagers are above the player)

**Comment by BillyGalbreath** [comment]
This is something upstream would have to fix.

I see you reported it to Paper here <https://github.com/PaperMC/Paper/issues/7281> but you also mentioned in that ticket that it happens on Spigot. But I cannot find any tickets on Spigot's Jira about it.

Your best chances of having this fixed are to go as far upstream as possible where the bug occurs. We don't really go out of our way here at Purpur to fix upstream bugs, especially for things like this where it seems the feature you are _wanting_ is a vanilla bug in itself.

**Comment by wlm3201** [comment]
https://www.youtube.com/watch?v=11aueQMiEmA

**Comment by wlm3201** [comment]
https://www.youtube.com/watch?v=11aueQMiEmA
This one works well on paper but has issues with purpur. A potential configuration ` raid-cooldown-seconds` seems to make no difference.

**Comment by wlm3201** [comment]
![image](https://user-images.githubusercontent.com/77601125/160181466-44f5eabf-6820-473b-89bd-056bacaf120b.png)
configure this
