### ISSUE TITLE
chunk load problem

### ISSUE THREAD

**Issue by ttt0** [pl3xgaming/Purpur#919]
### Timings link

https://timings.aikar.co/?id=a24ec0729ead41e8acb1f2e1b3c9a75f

### Description of issue

https://www.youtube.com/watch?v=CimfTkVZyN0

### Purpur version

![image](https://user-images.githubusercontent.com/66686400/154804083-185bae28-306f-471a-9787-7d10448fd8eb.png)

### Agreements

- [x] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I have 1.18.1 latest version server. I'm having a problem with the Chunk not loading. Do you have any suggestions?

**Comment by katekerllenevich** [comment]
> I am running the latest version of Purpur available from https://purpurmc.org/downloads.

> I have 1.18.1 latest version server.

> You are 5 versions behind

**Comment by ttt0** [comment]
I have installed the latest version now but my problem still persists.

**Comment by ttt0** [comment]
can you help me

**Comment by ttt0** [comment]
You muted your discord server because I have a cracked server, I can't get help from anyone
