### ISSUE TITLE
ignore-players-wearing-dragon-head isnt working

### ISSUE THREAD

**Issue by fahlur** [pl3xgaming/Purpur#921]
### Expected behavior

When set to true endermen should ignore players wearing a dragon head.

### Observed/Actual behavior

This is not occurring, endermen still aggro.

### Steps/models to reproduce

set
ignore-players-wearing-dragon-head: true

wear dragon head, look at endermen.

### Purpur version

[07:40:01 INFO]: Checking version, please wait...
[07:40:02 INFO]: Current: git-Purpur-1566 (MC: 1.18.1)*
[07:40:02 INFO]: Previous: git-Purpur-1563 (MC: 1.18.1)
[07:40:02 INFO]: * You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by katekerllenevich** [comment]
Timings links aren't optional.

**Comment by katekerllenevich** [comment]
Also, unable to reproduce on latest 1.18.2. Try without plugins.
