### ISSUE TITLE
Anvil will remove all enchant.

### ISSUE THREAD

**Issue by DreamVoid** [pl3xgaming/Purpur#924]
### Expected behavior

Put some item and enchantment book to anvil, returns same item with **none** enchant. (even item has enchant before)

### Observed/Actual behavior

![a](https://user-images.githubusercontent.com/45266046/156890042-2bae52de-afa3-40b3-9ffd-95af6ac8cde4.png)
Before (Mending)

![b](https://user-images.githubusercontent.com/45266046/156890043-531d4f19-6da0-4569-bdb3-d6bd80aba51e.png)
Book (Efficiency V)

![c](https://user-images.githubusercontent.com/45266046/156890045-896fb3e7-c4c5-487c-b7f4-0360436f5309.png)
After (Nothing)

### Steps/models to reproduce

1. Place an anvil.
2. Put item on 1st slot.
3. Put enchant book on 2nd slot.
4. All enchantment will be removed.

### Purpur version

```
> ver
[23:39:34 INFO]: Current: git-Purpur-1575 (MC: 1.18.2)*
[23:39:34 INFO]: Previous: git-Purpur-1566 (MC: 1.18.1)
[23:39:34 INFO]: * You are 1 version(s) behind
[23:39:34 INFO]: Download the new version at: https://purpurmc.org/downloads
```

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Sorry for my bad grammar, I am from China and I am not using translator.

**Comment by katekerllenevich** [comment]
:wave: Please send a timings link, the form template isn't exactly optional.

This smells like a plugin to me, if you can reproduce without any, let me know. If not, feel free to come into our discord and we can help you debug the issue!

**Comment by BillyGalbreath** [comment]
Unable to reproduce

![image](https://user-images.githubusercontent.com/332527/156890327-6e2dc83a-3da6-4675-99f1-0d55f9c25c7b.png)

![image](https://user-images.githubusercontent.com/332527/156890333-77f0e94b-b490-46de-965f-d6b4d8b54338.png)

![image](https://user-images.githubusercontent.com/332527/156890342-e328d04e-131e-45dd-9956-28d8a435c634.png)

![image](https://user-images.githubusercontent.com/332527/156890354-98ae88a8-e018-41c9-bf47-0a8031966b28.png)

**Comment by DreamVoid** [comment]
![a](https://user-images.githubusercontent.com/45266046/156890585-e6f45914-1f87-4b2a-8e93-8003a1b25570.png)
![b](https://user-images.githubusercontent.com/45266046/156890586-2d84f0fa-bd0b-4b5c-9ecb-976d86b3da8c.png)

I have tested in a plugin-free environment without this problem.

After investigation, it has been confirmed that it is a problem with a plugin named "deenchatment". Already reported it to author.
