### ISSUE TITLE
Feature Request: Actual Kraken

### ISSUE THREAD

**Issue by KoxSosen** [pl3xgaming/Purpur#93]
Hello!

We have Flying Squids. Why not add an oversied Squid, witch would have a really small spawn %-and it would be hard to kill? It would work & act as a normal Squid, but really Oversied, and rare, and only can be found in deep Ocans.

Imagine riding a Giant size squid while flying on it 0_0

**Comment by BillyGalbreath** [comment]
Impossible without a client mod.
