### ISSUE TITLE
Stronghold seed is incorrect after server update

### ISSUE THREAD

**Issue by Krakenied** [pl3xgaming/Purpur#930]
### Timings link

http://localhost

### Expected behavior

Correct seed

### Observed/Actual behavior

Incorrect seed

### Steps/models to reproduce

Generate custom stronghold feature seed world using Purpur older than https://github.com/PurpurMC/Purpur/commit/cb7bcb9686027dcaacd296ec552b3fb7a6ef38e1 and update to any newer build

### Purpur version

https://github.com/PurpurMC/Purpur/commit/cb7bcb9686027dcaacd296ec552b3fb7a6ef38e1 and newer

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

https://github.com/PurpurMC/Purpur/blob/291955ea75062358d7adc4c0458b561eace3bae1/patches/server/0204-Structure-seed-options.patch#L55

`stronghold` in this line should be changed to `stronghold` + main world seed because
https://github.com/PurpurMC/Purpur/blob/db6920e35e8380e8ad6fb3fc0f3942d517cbc349/patches/server/0204-Structure-seed-options.patch#L16-L19

**Comment by YouHaveTrouble** [comment]
Latest is not a version, do it right.

**Comment by katekerllenevich** [comment]
Localhost is not a timings link. You have to follow the format.

**Comment by Krakenied** [comment]
> Localhost is not a timings link. You have to follow the format.

I do not have timings. Just wanted to report missing `worldSeed +` in your config migration code ¯\\_(ツ)_/¯
That's not my problem now because I calculated the Paper seed properly myself.

**Comment by katekerllenevich** [comment]
Reporting an issue is useless without giving us information to fix it. If you want to report a bug, you have to do it right. Have a nice day.

**Comment by Krakenied** [comment]
I told you what's wrong in the code, going to submit PR

**Comment by katekerllenevich** [comment]
That doesn't matter, you can't not chose to put items in issues.
