### ISSUE TITLE
White and black console

### ISSUE THREAD

**Issue by moda84** [pl3xgaming/Purpur#934]
### Timings link

 Please enable timings by typing /timings on

### Expected behavior

Color console

### Observed/Actual behavior

White and black console

### Steps/models to reproduce

The console became black and white, and when I tried to find out what was wrong, I was banned in the discord. ._.
![image](https://user-images.githubusercontent.com/44532692/159163516-28866ae6-7213-4c9c-b648-81c085150cec.png)

### Purpur version

Current: git-Purpur-1597 (MC: 1.18.2)*
Previous: git-Purpur-1586 (MC: 1.18.2)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [x] My version of Minecraft is supported by Purpur.

**Comment by katekerllenevich** [comment]
You're using offline mode, we've already been over this. Also you didn't fill out the form properly.
