### ISSUE TITLE
Grindstones "ignored-enchants:" automatically repopulated if left blank in Purpur.yml

### ISSUE THREAD

**Issue by I0u0I** [pl3xgaming/Purpur#938]
### Timings link

https://timings.aikar.co/?id=ee20d037186d488f83b01ba0abf1dde6

### Expected behavior

When removing all entries from "ignored-enchants:" in purpur.yml expected behaviour is to be able to use grindstone to remove all enchantments and curses from items added to grindstone.

### Observed/Actual behavior

Curses remaining on items put into grindstone. Purpur.yml file changed automagically to include both curses again.

### Steps/models to reproduce

Edit purpur.yml file at "ignored-enchants:" and remove both curse enchantments leaving the entry blank.
Save file and restart the server and both will be re-populated when purpur.yml is reloaded.

This is not the case when removing just one of the values, or removing both and placing a dummy enchantment such as "- minecraft:null" in the field instead.

### Purpur version

Current: git-Purpur-1597 (MC: 1.18.2)*
Previous: git-Purpur-1596 (MC: 1.18.2)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by katekerllenevich** [comment]
Instead of making it blank, try making the line say `ignored-enchants: []`. That makes it an empty list.

**Comment by I0u0I** [comment]
> Instead of making it blank, try making the line say `ignored-enchants: []`. That makes it an empty list.

This works thanks, was a brain fart on my end for not trying this originally.
