### ISSUE TITLE
White and black console

### ISSUE THREAD

**Issue by Akiranya** [pl3xgaming/Purpur#946]
### Timings link

https://timings.aikar.co/?id=9c50ff0b4f954ada892eb697c56b54d7

### Expected behavior

Color codes should correctly be displayed on the console.

### Observed/Actual behavior

Color codes are not correctly displayed on the console.

### Steps/models to reproduce

Start the server and print something colorful on the console, for example:

Running command `/version essentials`
![image](https://user-images.githubusercontent.com/14846342/160468527-962e17d0-e6b8-413c-84c2-9f4f6aa86d44.png)
The colorful text are all shown in gray.

### Purpur version

Current: git-Purpur-1602 (MC: 1.18.2)*
Previous: git-Purpur-1566 (MC: 1.18.1)
* You are running the latest version

### Agreements

- [x] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I checked the update log and found:

![image](https://user-images.githubusercontent.com/14846342/160468840-4a0aaa85-6123-4533-a88e-d7872267ce5a.png)

Seems this issue already got fixed, but for now seems it's not really fixed ...

**Comment by BillyGalbreath** [comment]
Unable to reproduce.


![image](https://user-images.githubusercontent.com/332527/160471118-da1ae59e-b908-4531-97f9-5a699453a9d9.png)

**Comment by Akiranya** [comment]
![image](https://user-images.githubusercontent.com/14846342/160527846-15b608cb-b76e-44a0-91e6-b31495494686.png)

I confirmed again this is build 1602 ... did it have something to do with the java version I used? or the OS?

I'm using [Dragonwell Java 17](https://github.com/alibaba/dragonwell17)

OS information:
```
> uname --all 
Linux minecraft 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Akiranya** [comment]
![image](https://user-images.githubusercontent.com/14846342/160559658-7a343ff6-2ab6-448e-b313-25a3f1b865af.png)
I'm adding more information. Some colorful text are shown properly but some are not.

The gray text should be colorful.

**Comment by Akiranya** [comment]
I tried oracle java 17 and there was still the issue ...

**Comment by Akiranya** [comment]
Searching in the Paper discord, finally I figured it out. I need to turn off `settings.loggers.use-rgb-for-named-text-colors` in paper.yml so that the legacy color can be displayed properly on the console.

But now seems the RGB colors are messing around (they used to be like non color and be able to be seen clearly):

![image](https://user-images.githubusercontent.com/14846342/161136002-546731b8-59a2-477f-bef6-ae943b22a27a.png)

**Comment by ghost** [comment]
Your terminal may not be showing colors correctly, try using a different one or consider taking a peek to your configs.

**Comment by encode42** [comment]
As stated above, this is an issue with the terminal emulator being used. As such, I am also unable to reproduce using Xfce's terminal.
