### ISSUE TITLE
purpur api download latest not recent

### ISSUE THREAD

**Issue by EdDeNtEr** [pl3xgaming/Purpur#949]
### Timings link

timings not needed

### Expected behavior

expect to get the latest build number download

### Observed/Actual behavior

using version 1.18.2 actually get build 1573

### Steps/models to reproduce

check json output of https://api.purpurmc.org/v2/purpur/1.18.2/latest

### Purpur version

[14:28:44 INFO]: Checking version, please wait...
[14:28:44 INFO]: Current: git-Purpur-1602 (MC: 1.18.2)*
Previous: git-Purpur-1573 (MC: 1.18.2)
* You are 1 version(s) behind
* Download the new version at: https://purpurmc.org/downloads

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by katekerllenevich** [comment]
This is an issue with caching, as it works perfectly fine for most people.
