### ISSUE TITLE
Why sand fix-duping doesm't work?

### ISSUE THREAD

**Issue by z0z0r4** [pl3xgaming/Purpur#951]
### Timings link

.

### Expected behavior

.

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/78744121/161176562-88afe534-fa10-4b5f-b99d-7ae23480ea9d.png)
![image](https://user-images.githubusercontent.com/78744121/161176502-34e87fad-94b3-4213-900c-c2ab542bc3af.png)
![image](https://user-images.githubusercontent.com/78744121/161176507-27f66d3f-cced-4852-bcda-c1f71b8869e4.png)
tthere aren't any sand....

### Steps/models to reproduce

.

### Purpur version

![image](https://user-images.githubusercontent.com/78744121/161176471-5351a939-ea4e-4b68-bc93-02551859f48d.png)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

already restarted

**Comment by katekerllenevich** [comment]
https://github.com/PurpurMC/Purpur/issues/834#issuecomment-1006559843

**Comment by Alexlau2023** [comment]
me too

**Comment by Alexlau2023** [comment]
my server can't work

**Comment by granny** [comment]
@Alexlau2023 Look at the comment linked by theomega and read carefully what it says.
