### ISSUE TITLE
reducedDebugInfo don't work in Nether (mb End)

### ISSUE THREAD

**Issue by h45hc47** [pl3xgaming/Purpur#952]
### Timings link

https://timings.aikar.co/?id=79f05c31786847ba87c483c7304d5618

### Expected behavior

I expected not to see the coordinates and another info in nether

### Observed/Actual behavior

I see it

### Steps/models to reproduce

/gamerule reducedDebugInfo true

Go to Nether

### Purpur version

Current: git-Purpur-1609 (MC: 1.18.2)*
Previous: git-Purpur-1551 (MC: 1.18.1)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

On previous version all was OK

And screens of problem on current version
![2022-04-12_16 45 09](https://user-images.githubusercontent.com/87547709/162978450-428a99f7-2540-4e00-bf00-cd70921abdbe.png)
![2022-04-12_16 45 21](https://user-images.githubusercontent.com/87547709/162978457-71208127-a236-4756-905d-043ea1da2003.png)

**Comment by Krakenied** [comment]
Gamerules are per world, so you have to execute the gamerule command while being in Nether

**Comment by Krakenied** [comment]
Btw, you are running offline mode so no more support will be given 👍

**Comment by h45hc47** [comment]
> Gamerules are per world, so you have to execute the gamerule command while being in Nether

I will know, thanks.

> Btw, you are running offline mode so no more support will be given 👍

Why?

**Comment by RealTriassic** [comment]
> > Gamerules are per world, so you have to execute the gamerule command while being in Nether
> 
> I will know, thanks.
> 
> > Btw, you are running offline mode so no more support will be given 👍
> 
> Why?

Piracy is illegal.

**Comment by h45hc47** [comment]
> > > Gamerules are per world, so you have to execute the gamerule command while being in Nether
> > 
> > 
> > I will know, thanks.
> > > Btw, you are running offline mode so no more support will be given 👍
> > 
> > 
> > Why?
> 
> Piracy is illegal.

Personally, I have a license. But given that Minecraft costs one fifth of the average salary in my country, and the gaming blockade that it is currently under, there is simply no other way out.

**Comment by craftish37** [comment]
> > **What does no support mean?**
> 
> Well, quite simply it means you will receive no help from us. Period. You are free to use the server as you please, but offline mode means you'll be doing so on your own.
> 
> > **But I live in _XYZ_ country and no one can afford the game**
> 
> Piracy is piracy, no matter where the crime is committed.
