### ISSUE TITLE
Kick when talking to villager - Packet Proccesing Error

### ISSUE THREAD

**Issue by GhostIsBeHere** [pl3xgaming/Purpur#954]
### Timings link

https://timings.aikar.co/?id=3b0b44b8cc7949f489e4f2f1547c02d7

### Expected behavior

Open villager trading GUI

### Observed/Actual behavior

Kick with `Packet processing error` on client and `Error whilst processing packet net.minecraft.network.protocol.game.PacketPlayInUseEntity@4ddb5de3 for <username>` in server console

### Steps/models to reproduce
IGNORE THIS PLEASE
1. Create a pupur server
2. Use this purpur.yml [https://pastebin.com/L4GunCpJ](https://pastebin.com/L4GunCpJ) 
3. Spawn a villager
4. Talk to villager
5. Be kicked

### Purpur version

`[04/13/2022 01:24:47 pm] [INFO]: Checking version, please wait...`
`[04/13/2022 01:24:47 pm] [INFO]: Current: git-Purpur-1610 (MC: 1.18.2)*`
`[04/13/2022 01:24:47 pm]: Previous: git-Paper-286 (MC: 1.18.2)`
`[04/13/2022 01:24:47 pm]: * You are running the latest version`

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

- Kick on Vanilla Client: Yes
- Kick on Fabric Client: Yes
- Kick with plugins: Yes
- Kick without plugins: Yes
- Kick on MacOS Client: Yes
- Kick on Windows Client: Yes
Only tested on Linux-Based server

**Comment by 12emin34** [comment]
Unable to reproduce on a clean Purpur-1610 server

**Comment by GhostIsBeHere** [comment]
Odd, I'll do a bit more testing and then add more info

**Comment by GhostIsBeHere** [comment]
OK, it has something to do with my purpur.yml file. I've linked that here [https://pastebin.com/L4GunCpJ](https://pastebin.com/L4GunCpJ)

**Comment by Camotoy** [comment]
For what it's worth, we had someone on the Geyser Discord come on and claim the error only happens with Bedrock players. I have not investigated the issue further. Here's their stack trace: https://paste.gg/p/anonymous/b7ec93004f2f4f28b122700ae114a7b2

**Comment by GhostIsBeHere** [comment]
I did manage to fix this by deleting and regenerating my purpur.yml

**Comment by encode42** [comment]
In @GhostIsBeHere's case, this is caused by outdated color codes (`§`) in the `cannot-ride-mob` configuration key, while modern versions of Purpur only support [Adventure components](https://docs.adventure.kyori.net/) (`<color>`). Regenerating `purpur.yml`, and therefore the `cannot-ride-mob` key, meant that `§` was no longer used.

I can't tell if the same is happening regarding @Camotoy's comment, as the paste seems to lead to a 404 now. Will re-open this issue if it turns out unrelated.
