### ISSUE TITLE
missing food properties... with fresh install

### ISSUE THREAD

**Issue by ghost** [pl3xgaming/Purpur#960]
### Timings link

(not necessary) https://timings.aikar.co/?id=f4b3915a360345618b6c8cb59ced3444

### Expected behavior

No error message upon starting a fresh install

### Observed/Actual behavior

error message '[11:58:15 ERROR]: missing food properties...' shows up in console

complete log:
https://bin.bloom.host/kejoxedepo

### Steps/models to reproduce

Download build 1612 (https://purpurmc.org/)
Start server

### Purpur version

[12:01:53 INFO]: Current: git-Purpur-1612 (MC: 1.18.2)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Though it's not a huge issue, I've seen it mentioned in the Discord, it may be worth removing the error message ^-^

**Comment by encode42** [comment]
This is normal behavior and nothing to worry about. It's just part of the first-time configuration generation, and not necessarily an error.
