### ISSUE TITLE
projectile-despawn-rates doesn't work

### ISSUE THREAD

**Issue by YouHaveTrouble** [pl3xgaming/Purpur#978]
### Timings link

https://timings.aikar.co/?id=a5c19294e1324d45a38f63924ac38ed2

### Expected behavior

Entities like snowballs or eggs to disappear after set amount of ticks

### Observed/Actual behavior

Entities not disappearing after set amount of ticks

### Steps/models to reproduce

1. Set any small positive value to a snowball or egg in projectile-despawn-rates.
2. reload or restart purpur
3. throw egg/snowball up and wait for it to land on your head, still very much existing

### Purpur version

```
> version
[23:18:01 INFO]: Checking version, please wait...
[23:18:02 INFO]: Current: git-Purpur-1623 (MC: 1.18.2)*
Previous: git-Purpur-1616 (MC: 1.18.2)
* You are running the latest version
```

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by Pantera07** [comment]
https://youtu.be/1Q2JNynhtOU
Can reproduce on build 1623

**Comment by Incluuu** [comment]
> https://youtu.be/1Q2JNynhtOU Can reproduce on build 1623

I had this problem too, I checked on build 1623

I checked right away: git-Purpur-1625 (MC: 1.18.2) *

**Comment by encode42** [comment]
It is indeed confirmed

**Comment by mattnicee7** [comment]
Awaiting fix.
