### ISSUE TITLE
Players cannot join the game

### ISSUE THREAD

**Issue by ifloppy** [pl3xgaming/Purpur#979]
### Timings link

https://timings.aikar.co/?id=2f0fcb9028ec43a3bd3b6d2fa800aaf7

### Expected behavior

Players enter the game normally

### Observed/Actual behavior

Displays loading terrain for a long time

### Steps/models to reproduce

This problem occurs after a normal exit from the game. During this time the server was shut down with stop and started normally once here. No error information for this event was found in the log.

### Purpur version

[15:18:36 INFO]: Checking version, please wait...
[15:18:39 INFO]: Current: git-Purpur-1623 (MC: 1.18.2)*
Previous: git-Purpur-1616 (MC: 1.18.2)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I found a post with the same problem as me here: https://www.mcbbs.net/forum.php?mod=viewthread&tid=1324809
He appears to be using PaperMC. The same point as the problem I encountered is that only this account cannot be entered, and it can be entered normally after changing to another account. I don't know how to edit and view this NBT file he said.

**Comment by SageSphinx63920** [comment]
Purpur doesn’t support Servers in offline mode!
