### ISSUE TITLE
TNT copy 

### ISSUE THREAD

**Issue by WeiYang0112** [pl3xgaming/Purpur#985]
### Timings link

https://timings.aikar.co/?id=0706a76f78934f6c9e9a4d1d149ee16b

### Expected behavior

Fix related replication bugs, thanks

### Observed/Actual behavior

![tntcopy](https://user-images.githubusercontent.com/105790128/169030175-4f717ffb-d60a-45af-b774-a5effb3a8ff3.png)

### Steps/models to reproduce

tnt copy
https://www.youtube.com/watch?v=YITt6HUxju0

### Purpur version

Current: git-Purpur-1623 (MC: 1.18.2)*
Previous: git-Paper-335 (MC: 1.18.2)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

np

**Comment by encode42** [comment]
Dupes and their respective options are entirely unsupported and will not be fixed if issues occur.
